import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiChevronRight,
  HiPaperAirplane,
  HiOutlineChartPie,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiReact,
  SiFigma,
  SiSupabase,
  SiPython,
  SiPandas,
  SiStreamlit,
  SiVercel,
  SiGoogleads,
  SiGoogleanalytics,
  SiHubspot,
  SiPagespeedinsights,
  SiVuedotjs,
  SiSass,
  SiShopify,
} from "react-icons/si";

import { FaMagnifyingGlass, FaMeta } from "react-icons/fa6";
import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaInstagram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  external: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  react: SiReact,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  python: SiPython,
  pandas: SiPandas,
  streamlit: SiStreamlit,
  vercel: SiVercel,
  chart: HiOutlineChartPie,
  seo: FaMagnifyingGlass,
  meta: FaMeta,
  ads: SiGoogleads,
  ga: SiGoogleanalytics,
  crm: SiHubspot,
  performance: SiPagespeedinsights,
  vue: SiVuedotjs,
  sass: SiSass,
  shopify: SiShopify,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  chevronRight: HiChevronRight,
  send: HiPaperAirplane,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
