import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { BreadcrumbJsonLd } from "@/components/seo/BreadcrumbJsonLd";
import { ReadingAuthors,ReadingCover,ReadingEditionInfo,ReadingOffers,ReadingRelations } from "@/components/reading";
import { isComicWork } from "@/content/reading/readingDomain";
import { getPublishedComics,getReadingEditionsForWork,getReadingInstallmentsForWork,getReadingOffersForEdition,getReadingVolumesForWork,getReadingWorkBySlug,getReadingWorks } from "@/data/reading";
import { baseURL } from "@/resources";
import styles from "../../livros/reading.module.scss";

export const dynamicParams=false;

export async function generateStaticParams(){return(await getPublishedComics()).map((work)=>({slug:work.slug}));}
async function findPublishedComic(slug:string){const work=await getReadingWorkBySlug(slug);return work&&work.status==="published"&&isComicWork(work)?work:undefined;}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const work=await findPublishedComic((await params).slug);if(!work)return{};const title=work.titleBr??work.originalTitle;return{title,description:work.shortDescription,alternates:{canonical:`${baseURL}/quadrinhos/${work.slug}`},openGraph:{title,description:work.shortDescription,url:`${baseURL}/quadrinhos/${work.slug}`,type:"book",images:work.image?[{url:work.image.src,alt:work.image.alt}]:undefined}};}
export default async function ComicPage({params}:{params:Promise<{slug:string}>}){const work=await findPublishedComic((await params).slug);if(!work)notFound();const[volumes,installments,editions,works]=await Promise.all([getReadingVolumesForWork(work.id),getReadingInstallmentsForWork(work.id),getReadingEditionsForWork(work.id),getReadingWorks()]);const offers=(await Promise.all(editions.map((edition)=>getReadingOffersForEdition(edition.id)))).flat();const title=work.titleBr??work.originalTitle;const jsonLd={"@context":"https://schema.org","@type":"Book",name:title,alternateName:[work.originalTitle,work.romanizedTitle].filter(Boolean),description:work.shortDescription,bookFormat:work.comicFormat,inLanguage:work.originalLanguages,url:`${baseURL}/quadrinhos/${work.slug}`};return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><BreadcrumbJsonLd items={[{name:"Início",url:baseURL},{name:"Quadrinhos",url:`${baseURL}/quadrinhos`},{name:title,url:`${baseURL}/quadrinhos/${work.slug}`}]}/><header className={styles.hero}><span>{work.comicTradition} · {work.comicFormat}</span><h1>{title}</h1>{title!==work.originalTitle&&<p>{work.originalTitle}</p>}<p>{work.shortDescription}</p></header><section><h2>Informações essenciais</h2><ReadingCover work={work}/><ReadingAuthors credits={work.credits}/><p>{work.originCountries.join(" · ")} · {work.originalLanguages.join(" · ")} · leitura {work.readingDirection}</p>{work.confirmedVolumeCount&&<p>{work.confirmedVolumeCount} volumes confirmados · verificado em {work.volumeCountCheckedAt}</p>}</section>{work.audienceProfile&&<section><h2>Sobre a obra</h2><p>{work.audienceProfile}</p></section>}{(volumes.length>0||installments.length>0)&&<section><h2>Série e volumes</h2>{volumes.map((volume)=><article key={volume.id}><strong>{volume.label}</strong>{volume.summary&&<p>{volume.summary}</p>}</article>)}{installments.map((item)=><article key={item.id}><strong>{item.label}</strong>{item.summary&&<p>{item.summary}</p>}</article>)}</section>}{editions.length>0&&<section><h2>Publicação no Brasil e outras edições</h2>{editions.map((edition)=><ReadingEditionInfo key={edition.id} edition={edition}/>)}</section>}<ReadingOffers offers={offers}/><ReadingRelations work={work} works={[...works]}/><section><h2>Fontes e créditos</h2><ul>{work.sources.map((source)=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a></li>)}</ul>{work.image&&<p>{work.image.credit} · direitos: {work.image.rights}</p>}</section></main>}
