import {z} from "zod";
const Schema=z.object({id:z.string(),slug:z.string(),title:z.string(),year:z.number(),format:z.enum(["feature","short","series"]),status:z.enum(["released","upcoming"]),directors:z.array(z.string()),relationships:z.array(z.object({organizationId:z.string(),role:z.enum(["primary-production","co-production","animation-service","development"])})),groupIds:z.array(z.string()),summary:z.string(),officialUrl:z.string().url()});
const make=(value:z.input<typeof Schema>)=>Schema.parse(value);
export const animationWorks=[
make({id:"anim_secret_of_kells_2009",slug:"the-secret-of-kells",title:"The Secret of Kells",year:2009,format:"feature",status:"released",directors:["Tomm Moore","Nora Twomey"],relationships:[{organizationId:"org_cartoon_saloon",role:"primary-production"}],groupIds:["group_irish_folklore_trilogy"],summary:"A estreia em longa transforma manuscrito, história e imaginação numa aventura desenhada.",officialUrl:"https://www.cartoonsaloon.ie/irish-animation-studio/feature-films/the-secret-of-kells/"}),
make({id:"anim_song_of_the_sea_2014",slug:"song-of-the-sea",title:"Song of the Sea",year:2014,format:"feature",status:"released",directors:["Tomm Moore"],relationships:[{organizationId:"org_cartoon_saloon",role:"co-production"}],groupIds:["group_irish_folklore_trilogy"],summary:"Uma história familiar em que luto, oralidade e paisagem costeira ocupam o mesmo desenho.",officialUrl:"https://www.cartoonsaloon.ie/irish-animation-studio/feature-films/song-of-the-sea/"}),
make({id:"anim_breadwinner_2017",slug:"the-breadwinner",title:"The Breadwinner",year:2017,format:"feature",status:"released",directors:["Nora Twomey"],relationships:[{organizationId:"org_cartoon_saloon",role:"co-production"}],groupIds:[],summary:"Adaptação literária ambientada no Afeganistão que amplia o alcance cultural do estúdio.",officialUrl:"https://www.cartoonsaloon.ie/irish-animation-studio/feature-films/the-breadwinner/"}),
make({id:"anim_wolfwalkers_2020",slug:"wolfwalkers",title:"WolfWalkers",year:2020,format:"feature",status:"released",directors:["Tomm Moore","Ross Stewart"],relationships:[{organizationId:"org_cartoon_saloon",role:"co-production"}],groupIds:["group_irish_folklore_trilogy"],summary:"O encerramento do conjunto folclórico confronta cidade murada, floresta e colonização.",officialUrl:"https://www.cartoonsaloon.ie/irish-animation-studio/feature-films/wolfwalkers/"}),
make({id:"anim_my_fathers_dragon_2022",slug:"my-fathers-dragon",title:"My Father’s Dragon",year:2022,format:"feature",status:"released",directors:["Nora Twomey"],relationships:[{organizationId:"org_cartoon_saloon",role:"primary-production"}],groupIds:[],summary:"Uma adaptação infantil sobre fuga, responsabilidade e amizade, com outra organização visual.",officialUrl:"https://www.cartoonsaloon.ie/irish-animation-studio/feature-films/my-fathers-dragon/"}),
make({id:"anim_puffin_rock_new_friends_2023",slug:"puffin-rock-and-the-new-friends",title:"Puffin Rock and the New Friends",year:2023,format:"feature",status:"released",directors:["Jeremy Purcell"],relationships:[{organizationId:"org_cartoon_saloon",role:"co-production"}],groupIds:[],summary:"O universo pré-escolar da série chega ao longa com atenção a comunidade e natureza.",officialUrl:"https://www.cartoonsaloon.ie/feature-films/"}),
make({id:"anim_late_afternoon_2017",slug:"late-afternoon",title:"Late Afternoon",year:2017,format:"short",status:"released",directors:["Louise Bagnall"],relationships:[{organizationId:"org_cartoon_saloon",role:"primary-production"}],groupIds:[],summary:"Um curta sobre memória e envelhecimento que condensa tempo por cor e associação.",officialUrl:"https://www.cartoonsaloon.ie/irish-animation-studio/short-films/"}),
make({id:"anim_puffin_rock_2015",slug:"puffin-rock",title:"Puffin Rock",year:2015,format:"series",status:"released",directors:[],relationships:[{organizationId:"org_cartoon_saloon",role:"co-production"}],groupIds:[],summary:"Série pré-escolar que observa vida animal, família e descoberta numa escala delicada.",officialUrl:"https://www.cartoonsaloon.ie/irish-animation-studio/tv-series/"}),
];
export const irishFolkloreGrouping={id:"group_irish_folklore_trilogy",kind:"editorial-group",label:"Trilogia do folclore irlandês",workIds:animationWorks.filter(w=>w.groupIds.includes("group_irish_folklore_trilogy")).map(w=>w.id)};
