import type {Metadata} from "next";
import {PersonLibrary} from "@/components/entities/PersonLibrary";
import {BreadcrumbJsonLd} from "@/components/seo/BreadcrumbJsonLd";
import {getPublishedPersonalities} from "@/data/personalities";
import {baseURL} from "@/resources";
import styles from "../filmes/movies.module.scss";
const path="/personalidades",title="Acervo de personalidades",description="Escritores, filósofos, cineastas, artistas e outros criadores relacionados às obras do acervo.";
export const metadata:Metadata={title,description,alternates:{canonical:`${baseURL}${path}`},openGraph:{title,description,url:`${baseURL}${path}`,type:"website"}};
export default function PersonalitiesPage(){const people=getPublishedPersonalities();const jsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:title,url:`${baseURL}${path}`,mainEntity:{"@type":"ItemList",numberOfItems:people.length,itemListElement:people.map((person,index)=>({"@type":"ListItem",position:index+1,item:{"@type":"Person",name:person.name,url:`${baseURL}${person.profilePath}`}}))}};return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><BreadcrumbJsonLd items={[{name:"Início",url:baseURL},{name:"Personalidades",url:`${baseURL}${path}`}]}/><header className={styles.hero}><div className={styles.heroMain}><span className={styles.kicker}>Biblioteca cultural · pessoas</span><h1>Ideias e obras começam em trajetórias humanas.</h1><p>Perfis verificáveis de pessoas relacionadas ao acervo, sem separar artificialmente quem exerce mais de uma função.</p></div><div className={styles.heroAside}><span>Perfis públicos</span><strong>{people.length}</strong><p>personalidades com biografia e fontes suficientes para uma página própria.</p></div></header><section className={styles.library}><div className={styles.sectionHeader}><h2>Personalidades</h2><p>Busque pelo nome ou combine ocupação, origem e período de vida.</p></div><PersonLibrary people={people}/></section></main>}
