import type {Metadata} from "next";
import {notFound} from "next/navigation";
import {BreadcrumbJsonLd} from "@/components/seo/BreadcrumbJsonLd";
import {OrganizationRelatedWorks} from "@/components/organizations/OrganizationRelatedWorks";
import {getPublishedStudios,getStudioBySlug,getWorksForOrganization} from "@/data/organizations";
import {baseURL} from "@/resources";
import styles from "../../filmes/movies.module.scss";
const specialized=new Set(["studio-ghibli","laika","aardman","science-saru","kyoto-animation","team-cherry","cartoon-saloon"]);
export const dynamicParams=false;
export function generateStaticParams(){return getPublishedStudios().filter((studio)=>!specialized.has(studio.slug)).map((studio)=>({slug:studio.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const studio=getStudioBySlug((await params).slug);if(!studio||specialized.has(studio.slug))return{robots:{index:false,follow:false}};const title=`${studio.name}: perfil, obras e processo`;const url=`${baseURL}/estudios/${studio.slug}`;return{title,description:studio.summary,alternates:{canonical:url},openGraph:{title,description:studio.summary,url,type:"profile",images:studio.image?[{url:`${baseURL}${studio.image.src}`,alt:studio.image.alt}]:undefined}}}
export default async function StudioPage({params}:{params:Promise<{slug:string}>}){const studio=getStudioBySlug((await params).slug);if(!studio||specialized.has(studio.slug))notFound();const works=await getWorksForOrganization(studio.id);const path=`/estudios/${studio.slug}`;const jsonLd={"@context":"https://schema.org","@type":"Organization",name:studio.name,url:`${baseURL}${path}`,description:studio.summary,foundingDate:studio.founded,location:studio.location?{"@type":"Place",name:[studio.location.city,studio.location.region,studio.location.country].filter(Boolean).join(", ")}:undefined,image:studio.image?`${baseURL}${studio.image.src}`:undefined,sameAs:studio.website};return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><BreadcrumbJsonLd items={[{name:"Início",url:baseURL},{name:"Estúdios",url:`${baseURL}/estudios`},{name:studio.name,url:`${baseURL}${path}`}]}/><header className={styles.hero}><div className={styles.heroMain}><span className={styles.kicker}>{studio.kind}</span><h1>{studio.name}</h1><p>{studio.summary}</p></div><div className={styles.heroAside}><span>Atividade</span><strong>{studio.founded??"—"}</strong><p>{studio.location?.country??"Origem não cadastrada"}{studio.activeUntil?` · até ${studio.activeUntil}`:""}</p></div></header><OrganizationRelatedWorks works={works}/><footer><h2>Fontes e imagem</h2><ul>{studio.sources.map((source)=><li key={source.url}><a href={source.url}>{source.title}</a></li>)}</ul>{studio.image?<p>Imagem: <a href={studio.image.sourceUrl}>{studio.image.credit}</a>. Licença: {studio.image.license}.</p>:<p>Nenhuma imagem institucional com licença registrada.</p>}</footer></main>}
