import { CreatorSchema, type Creator } from "./creatorSchema";

export const shingoTamagawa: Creator = CreatorSchema.parse({
  id: "person_shingo_tamagawa",
  slug: "shingo-tamagawa",
  name: "Shingo Tamagawa",
  kind: "person",
  status: "published",
  birthYear: 1987,
  birthPlace: "Nara, Japão",
  summary: "Animador e realizador japonês, autor do curta independente Puparia.",
  workIds: ["work_puparia_2020", "work_archipel_making_puparia_2021"],
  sources: [
    { title: "PUPARIA", url: "https://www.youtube.com/watch?v=CWnqX41JHuM", kind: "primary" },
    { title: "Three Minutes, Three Years: Making Puparia", url: "https://www.youtube.com/watch?v=VKsG3E7TLl4", kind: "primary" },
    { title: "PUPARIA — FilmFreeway", url: "https://filmfreeway.com/PUPARIA831", kind: "primary" },
  ],
  createdAt: "2026-08-12",
  updatedAt: "2026-08-12",
});

export const upamanyuBhattacharyya: Creator = CreatorSchema.parse({
  id: "person_upamanyu_bhattacharyya", slug: "upamanyu-bhattacharyya", name: "Upamanyu Bhattacharyya", kind: "person", status: "draft",
  summary: "Animador e codiretor indiano de Wade.", workIds: ["work_wade_2019"],
  sources: [{ title: "Wade — Annecy 2020", url: "https://www.annecyfestival.com/about/archives/2020/award-winners/film-index%3Afilm-20200770", kind: "primary" }],
  createdAt: "2026-08-12", updatedAt: "2026-08-12",
});

export const kalpSanghvi: Creator = CreatorSchema.parse({
  id: "person_kalp_sanghvi", slug: "kalp-sanghvi", name: "Kalp Sanghvi", kind: "person", status: "draft",
  summary: "Animador e codiretor indiano de Wade.", workIds: ["work_wade_2019"],
  sources: [{ title: "Wade — Annecy 2020", url: "https://www.annecyfestival.com/about/archives/2020/award-winners/film-index%3Afilm-20200770", kind: "primary" }],
  createdAt: "2026-08-12", updatedAt: "2026-08-12",
});

const teamCherryPeople:Creator[]=[
  {id:"person_ari_gibson",slug:"ari-gibson",name:"Ari Gibson",kind:"person",status:"draft",summary:"Cofundador, artista, animador e designer da Team Cherry.",workIds:[],sources:[{title:"Team Cherry",url:"https://www.teamcherry.com.au/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
  {id:"person_william_pellen",slug:"william-pellen",name:"William Pellen",kind:"person",status:"draft",summary:"Cofundador, designer e programador da Team Cherry.",workIds:[],sources:[{title:"Team Cherry",url:"https://www.teamcherry.com.au/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
  {id:"person_jasmine_vine",slug:"jasmine-vine",name:"Jasmine Vine",kind:"person",status:"draft",summary:"Programadora de Hollow Knight: Silksong.",workIds:[],sources:[{title:"Hollow Knight: Silksong",url:"https://hollowknightsilksong.com/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
  {id:"person_christopher_larkin",slug:"christopher-larkin",name:"Christopher Larkin",kind:"person",status:"draft",summary:"Compositor de Hollow Knight e Hollow Knight: Silksong.",workIds:[],sources:[{title:"Hollow Knight: Silksong",url:"https://hollowknightsilksong.com/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
].map(item=>CreatorSchema.parse(item));
const cartoonSaloonPeople:Creator[]=["Tomm Moore","Nora Twomey","Paul Young","Ross Stewart","Louise Bagnall"].map(name=>CreatorSchema.parse({id:`person_${name.toLowerCase().replaceAll(" ","_")}`,slug:name.toLowerCase().replaceAll(" ","-"),name,kind:"person",status:"draft",summary:`Profissional relacionado ao Cartoon Saloon.`,workIds:[],sources:[{title:"Cartoon Saloon — About",url:"https://www.cartoonsaloon.ie/irish-animation-studio/about/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"}));
const ghibliPeople:Creator[] = [
  { id:"person_hayao_miyazaki", slug:"hayao-miyazaki", name:"Hayao Miyazaki", summary:"Diretor, roteirista, animador e participante da fundação do Studio Ghibli." },
  { id:"person_isao_takahata", slug:"isao-takahata", name:"Isao Takahata", summary:"Diretor, produtor e participante da fundação do Studio Ghibli." },
  { id:"person_toshio_suzuki", slug:"toshio-suzuki", name:"Toshio Suzuki", summary:"Produtor e articulador editorial que participou da fundação e continuidade do Studio Ghibli." },
].map(person=>CreatorSchema.parse({
  ...person, kind:"person", status:"draft", workIds:[],
  sources:[{title:"História oficial — Studio Ghibli",url:"https://www.ghibli.jp/history/",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
}));
const laikaPeople:Creator[] = [CreatorSchema.parse({
  id:"person_travis_knight",slug:"travis-knight",name:"Travis Knight",kind:"person",status:"draft",
  summary:"Presidente e CEO da LAIKA, diretor de Kubo e as Cordas Mágicas e Wildwood.",workIds:[],
  sources:[{title:"Wildwood — anúncio de distribuição",url:"https://www.fathomentertainment.com/news/laika-debuts-teaser-trailer-press-release-fathom/",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
})];
const aardmanPeople:Creator[] = [
  {id:"person_peter_lord",slug:"peter-lord",name:"Peter Lord",summary:"Cofundador da Aardman, diretor, animador e produtor."},
  {id:"person_david_sproxton",slug:"david-sproxton",name:"David Sproxton",summary:"Cofundador da Aardman e produtor ligado à consolidação do estúdio."},
  {id:"person_nick_park",slug:"nick-park",name:"Nick Park",summary:"Diretor e animador que criou Wallace & Gromit e desenvolveu obras centrais da Aardman."},
].map(person=>CreatorSchema.parse({
  ...person,kind:"person",status:"draft",workIds:[],
  sources:[{title:"People — Aardman",url:"https://www.aardman.com/about/people/",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
}));
const scienceSaruPeople:Creator[] = [
  {id:"person_masaaki_yuasa",slug:"masaaki-yuasa",name:"Masaaki Yuasa",summary:"Diretor e cofundador histórico da Science SARU; deixou a presidência em 2020."},
  {id:"person_eunyoung_choi",slug:"eunyoung-choi",name:"Eunyoung Choi",summary:"Animadora, produtora e cofundadora histórica da Science SARU."},
  {id:"person_masanori_fujita",slug:"masanori-fujita",name:"Masanori Fujita",summary:"Representante e CEO da Science SARU no cadastro institucional de 2026."},
].map(person=>CreatorSchema.parse({
  ...person,kind:"person",status:"draft",workIds:[],
  sources:[{title:"About — Science SARU",url:"https://sciencesaru.com/en/about",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
}));
const kyotoAnimationPeople:Creator[] = [
  {id:"person_yoko_hatta",slug:"yoko-hatta",name:"Yoko Hatta",summary:"Animadora e cofundadora da Kyoto Animation."},
  {id:"person_hideaki_hatta",slug:"hideaki-hatta",name:"Hideaki Hatta",summary:"Cofundador e presidente histórico da Kyoto Animation, morto em fevereiro de 2026."},
  {id:"person_shinichiro_hatta",slug:"shinichiro-hatta",name:"Shinichiro Hatta",summary:"Presidente e CEO da Kyoto Animation desde fevereiro de 2026."},
].map(person=>CreatorSchema.parse({
  ...person,kind:"person",status:"draft",workIds:[],
  sources:[{title:"Corporate Profile — Kyoto Animation",url:"https://www.kyotoanimation.co.jp/en/company/profile/",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
}));
const vampireBookAuthors: Creator[] = [
  ["person_john_polidori","john-polidori","John Polidori","Autor britânico de O Vampiro."],
  ["person_sheridan_le_fanu","sheridan-le-fanu","Sheridan Le Fanu","Escritor irlandês e autor de Carmilla."],
  ["person_bram_stoker","bram-stoker","Bram Stoker","Escritor irlandês e autor de Drácula."],
  ["person_richard_matheson","richard-matheson","Richard Matheson","Escritor norte-americano de terror e ficção científica."],
  ["person_stephen_king","stephen-king","Stephen King","Escritor norte-americano de terror, suspense e fantasia."],
  ["person_anne_rice","anne-rice","Anne Rice","Escritora norte-americana e autora das Crônicas Vampirescas."],
  ["person_suzy_mckee_charnas","suzy-mckee-charnas","Suzy McKee Charnas","Escritora norte-americana de fantasia e ficção científica."],
  ["person_george_r_r_martin","george-r-r-martin","George R. R. Martin","Escritor norte-americano de fantasia, terror e ficção científica."],
  ["person_s_p_somtow","s-p-somtow","S. P. Somtow","Escritor e compositor tailandês-americano."],
  ["person_elizabeth_engstrom","elizabeth-engstrom","Elizabeth Engstrom","Escritora norte-americana de horror."],
  ["person_jewelle_gomez","jewelle-gomez","Jewelle Gomez","Escritora e dramaturga norte-americana."],
  ["person_robin_mckinley","robin-mckinley","Robin McKinley","Escritora norte-americana de fantasia."],
  ["person_john_ajvide_lindqvist","john-ajvide-lindqvist","John Ajvide Lindqvist","Escritor sueco de terror."],
  ["person_octavia_e_butler","octavia-e-butler","Octavia E. Butler","Escritora norte-americana de ficção científica."],
  ["person_elizabeth_kostova","elizabeth-kostova","Elizabeth Kostova","Escritora norte-americana e autora de A Historiadora."],
  ["person_justin_cronin","justin-cronin","Justin Cronin","Escritor norte-americano e autor da trilogia A Passagem."],
  ["person_holly_black","holly-black","Holly Black","Escritora norte-americana de fantasia contemporânea."],
  ["person_christopher_buehlman","christopher-buehlman","Christopher Buehlman","Escritor norte-americano de horror e fantasia."],
  ["person_silvia_moreno_garcia","silvia-moreno-garcia","Silvia Moreno-Garcia","Escritora mexicana-canadense de fantasia e horror."],
  ["person_jose_luis_zarate","jose-luis-zarate","José Luis Zárate","Escritor mexicano de ficção especulativa."],
  ["person_grady_hendrix","grady-hendrix","Grady Hendrix","Escritor norte-americano de horror."],
  ["person_s_t_gibson","s-t-gibson","S. T. Gibson","Escritora norte-americana de fantasia gótica."],
  ["person_claire_kohda","claire-kohda","Claire Kohda","Escritora e crítica musical britânica."],
  ["person_alexis_henderson","alexis-henderson","Alexis Henderson","Escritora norte-americana de fantasia sombria."],
  ["person_isabel_canas","isabel-canas","Isabel Cañas","Escritora mexicano-americana de ficção gótica."],
  ["person_mary_shelley","mary-shelley","Mary Shelley","Escritora inglesa de ficção gótica e especulativa."],
  ["person_henry_james","henry-james","Henry James","Escritor norte-americano-britânico de ficção psicológica."],
  ["person_shirley_jackson","shirley-jackson","Shirley Jackson","Escritora norte-americana de terror e ficção psicológica."],
  ["person_ira_levin","ira-levin","Ira Levin","Escritor e dramaturgo norte-americano."],
  ["person_toni_morrison","toni-morrison","Toni Morrison","Escritora norte-americana e autora de Amada."],
  ["person_koji_suzuki","koji-suzuki","Koji Suzuki","Escritor japonês de terror e ficção científica."],
  ["person_jeff_vandermeer","jeff-vandermeer","Jeff VanderMeer","Escritor norte-americano de ficção especulativa e New Weird."],
  ["person_john_langan","john-langan","John Langan","Escritor norte-americano de horror."],
  ["person_agustina_bazterrica","agustina-bazterrica","Agustina Bazterrica","Escritora argentina de ficção especulativa."],
  ["person_mariana_enriquez","mariana-enriquez","Mariana Enriquez","Escritora e jornalista argentina."],
  ["person_stephen_graham_jones","stephen-graham-jones","Stephen Graham Jones","Escritor norte-americano de origem Blackfeet."],
  ["person_tananarive_due","tananarive-due","Tananarive Due","Escritora norte-americana de horror e ficção especulativa."],
  ["person_p_djeli_clark","p-djeli-clark","P. Djèlí Clark","Escritor norte-americano de fantasia e horror."],
  ["person_bora_chung","bora-chung","Bora Chung","Escritora e tradutora sul-coreana."],
  ["person_raphael_montes","raphael-montes","Raphael Montes","Escritor e roteirista brasileiro de suspense e horror."],
  ["person_dan_simmons","dan-simmons","Dan Simmons","Escritor norte-americano de terror, ficção científica e fantasia."],
  ["person_robert_mccammon","robert-mccammon","Robert McCammon","Escritor norte-americano de terror e ficção histórica."],
  ["person_ray_bradbury","ray-bradbury","Ray Bradbury","Escritor norte-americano de ficção especulativa, fantasia e horror."],
  ["person_stephen_chbosky","stephen-chbosky","Stephen Chbosky","Escritor, roteirista e diretor norte-americano."],
  ["person_c_j_tudor","c-j-tudor","C. J. Tudor","Escritora britânica de suspense e terror."],
  ["person_paul_tremblay","paul-tremblay","Paul Tremblay","Escritor norte-americano de terror e suspense."],
  ["person_ronald_malfi","ronald-malfi","Ronald Malfi","Escritor norte-americano de terror."],
  ["person_craig_davidson","craig-davidson","Craig Davidson","Escritor canadense de ficção literária e horror."],
  ["person_jessica_johns","jessica-johns","Jessica Johns","Escritora canadense nehiyaw de ficção contemporânea e horror."],
  ["person_adam_cesare","adam-cesare","Adam Cesare","Escritor norte-americano de terror."],
  ["person_marv_wolfman","marv-wolfman","Marv Wolfman","Roteirista norte-americano de quadrinhos."],
  ["person_gene_colan","gene-colan","Gene Colan","Desenhista norte-americano de quadrinhos."],
  ["person_moto_hagio","moto-hagio","Moto Hagio","Mangaká japonesa associada ao Grupo do Ano 24."],
  ["person_joann_sfar","joann-sfar","Joann Sfar","Quadrinista e cineasta francês."],
  ["person_matsuri_hino","matsuri-hino","Matsuri Hino","Mangaká japonesa."],
  ["person_kouta_hirano","kohta-hirano","Kohta Hirano","Mangaká japonês e criador de Hellsing."],
  ["person_steve_niles","steve-niles","Steve Niles","Roteirista norte-americano de quadrinhos de terror."],
  ["person_ben_templesmith","ben-templesmith","Ben Templesmith","Artista australiano de quadrinhos."],
  ["person_scott_snyder","scott-snyder","Scott Snyder","Roteirista norte-americano de quadrinhos."],
  ["person_rafael_albuquerque","rafael-albuquerque","Rafael Albuquerque","Quadrinista brasileiro."],
  ["person_mike_mignola","mike-mignola","Mike Mignola","Quadrinista norte-americano e criador de Hellboy e Baltimore."],
  ["person_christopher_golden","christopher-golden","Christopher Golden","Escritor e roteirista norte-americano."],
  ["person_fabio_moon","fabio-moon","Fábio Moon","Quadrinista brasileiro."],
  ["person_jessica_abel","jessica-abel","Jessica Abel","Quadrinista e escritora norte-americana."],
  ["person_gabriel_soria","gabriel-soria","Gabriel Soria","Roteirista norte-americano de quadrinhos."],
  ["person_warren_pleece","warren-pleece","Warren Pleece","Quadrinista britânico."],
  ["person_sarah_andersen","sarah-andersen","Sarah Andersen","Quadrinista norte-americana."],
  ["person_alex_de_campi","alex-de-campi","Alex de Campi","Roteirista britânica-americana de quadrinhos."],
  ["person_erica_henderson","erica-henderson","Erica Henderson","Desenhista e colorista norte-americana."],
  ["person_ram_v","ram-v","Ram V","Roteirista indiano de quadrinhos."],
  ["person_sumit_kumar","sumit-kumar","Sumit Kumar","Artista indiano de quadrinhos."],
  ["person_rodney_barnes","rodney-barnes","Rodney Barnes","Roteirista e produtor norte-americano."],
  ["person_jason_shawn_alexander","jason-shawn-alexander","Jason Shawn Alexander","Artista norte-americano de quadrinhos."],
  ["person_shuzo_oshimi","shuzo-oshimi","Shuzo Oshimi","Mangaká japonês."],
  ["person_jun_mochizuki","jun-mochizuki","Jun Mochizuki","Mangaká japonesa."],
  ["person_kotoyama","kotoyama","Kotoyama","Mangaká japonês."],
  ["person_akili","akili","Akili","Mangaká japonês, também conhecido como Shou Higashiyama."],
  ["person_lina_im","lina-im","Lina Im","Quadrinista sul-coreana e criadora de Unholy Blood."],
  ["person_junji_ito","junji-ito","Junji Ito","Mangaká japonês de horror."],
  ["person_kazuo_umezz","kazuo-umezz","Kazuo Umezz","Mangaká japonês de horror e ficção científica."],
  ["person_masaaki_nakayama","masaaki-nakayama","Masaaki Nakayama","Mangaká japonês de horror."],
  ["person_hitoshi_iwaaki","hitoshi-iwaaki","Hitoshi Iwaaki","Mangaká japonês."],
  ["person_hideo_yamamoto","hideo-yamamoto","Hideo Yamamoto","Mangaká japonês."],
  ["person_mokumokuren","mokumokuren","Mokumokuren","Mangaká japonês."],
  ["person_carnby_kim","carnby-kim","Carnby Kim","Roteirista sul-coreano de webtoons."],
  ["person_youngchan_hwang","youngchan-hwang","Youngchan Hwang","Artista sul-coreano de webtoons."],
  ["person_alan_moore","alan-moore","Alan Moore","Roteirista britânico de quadrinhos."],
  ["person_eddie_campbell","eddie-campbell","Eddie Campbell","Quadrinista escocês-australiano."],
  ["person_charles_burns","charles-burns","Charles Burns","Quadrinista norte-americano."],
  ["person_joe_hill","joe-hill","Joe Hill","Escritor e roteirista norte-americano."],
  ["person_gabriel_rodriguez","gabriel-rodriguez","Gabriel Rodríguez","Quadrinista chileno."],
  ["person_pornsak_pichetshote","pornsak-pichetshote","Pornsak Pichetshote","Roteirista e editor de quadrinhos."],
  ["person_aaron_campbell","aaron-campbell","Aaron Campbell","Desenhista norte-americano de quadrinhos."],
  ["person_james_tynion_iv","james-tynion-iv","James Tynion IV","Roteirista norte-americano de quadrinhos."],
  ["person_alvaro_martinez_bueno","alvaro-martinez-bueno","Álvaro Martínez Bueno","Desenhista espanhol de quadrinhos."],
  ["person_jeff_lemire","jeff-lemire","Jeff Lemire","Quadrinista e roteirista canadense."],
  ["person_andrea_sorrentino","andrea-sorrentino","Andrea Sorrentino","Desenhista italiano de quadrinhos."],
  ["person_shiko","shiko","Shiko","Quadrinista paraibano."],
  ["person_alex_magnos","alex-magnos","Alex Magnos","Roteirista brasileiro de quadrinhos."],
  ["person_gean_bandeira","gean-bandeira","Gean Bandeira","Quadrinista brasileiro."],
  ["person_ian_sbf","ian-sbf","Ian SBF","Roteirista e cineasta brasileiro."],
  ["person_marcela_godoy","marcela-godoy","Marcela Godoy","Roteirista brasileira de quadrinhos e horror."],
  ["person_leonel_caldela","leonel-caldela","Leonel Caldela","Escritor e roteirista brasileiro."],
  ["person_kouji_miura","kouji-miura","Kouji Miura","Mangaká japonesa e autora de Blue Box."],
  ["person_aka_akasaka","aka-akasaka","Aka Akasaka","Mangaká japonês."],
  ["person_fujita","fujita","Fujita","Mangaká japonesa e autora de Wotakoi."],
  ["person_ai_yazawa","ai-yazawa","Ai Yazawa","Mangaká japonesa."],
  ["person_natsuki_takaya","natsuki-takaya","Natsuki Takaya","Mangaká japonesa."],
  ["person_hero","hero-mangaka","HERO","Mangaká japonesa e criadora de Horimiya."],
  ["person_daisuke_hagiwara","daisuke-hagiwara","Daisuke Hagiwara","Mangaká japonesa e artista de Horimiya."],
  ["person_shinichi_fukuda","shinichi-fukuda","Shinichi Fukuda","Mangaká japonesa."],
  ["person_makoto_ojiro","makoto-ojiro","Makoto Ojiro","Mangaká japonesa."],
  ["person_misaki_takamatsu","misaki-takamatsu","Misaki Takamatsu","Mangaká japonesa."],
  ["person_suu_morishita","suu-morishita","Suu Morishita","Dupla japonesa de mangakás."],
  ["person_kintetsu_yamada","kintetsu-yamada","Kintetsu Yamada","Mangaká japonesa."],
  ["person_rumiko_takahashi","rumiko-takahashi","Rumiko Takahashi","Mangaká japonesa."],
  ["person_inio_asano","inio-asano","Inio Asano","Mangaká japonês."],
  ["person_kazune_kawahara","kazune-kawahara","Kazune Kawahara","Mangaká japonesa."],
  ["person_aruco","aruko","Aruko","Mangaká japonesa."],
  ["person_natsuki_kizu","natsuki-kizu","Natsuki Kizu","Mangaká japonesa."],
  ["person_nio_nakatani","nio-nakatani","Nio Nakatani","Mangaká japonesa."],
  ["person_tomoko_ninomiya","tomoko-ninomiya","Tomoko Ninomiya","Mangaká japonesa."],
].map(([id,slug,name,summary])=>CreatorSchema.parse({id,slug,name,summary,kind:"person",status:"draft",workIds:[],sources:[{title:`Página oficial ou bibliográfica — ${name}`,url:`https://openlibrary.org/search/authors?q=${encodeURIComponent(name)}`,kind:"secondary"}],createdAt:"2026-08-13",updatedAt:"2026-08-13"}));
export const creators = [shingoTamagawa, upamanyuBhattacharyya, kalpSanghvi,...teamCherryPeople,...cartoonSaloonPeople,...ghibliPeople,...laikaPeople,...aardmanPeople,...scienceSaruPeople,...kyotoAnimationPeople,...vampireBookAuthors];
