import { CreatorSchema, type Creator } from "./creatorSchema";

export const shingoTamagawa: Creator = CreatorSchema.parse({
  id: "person_shingo_tamagawa",
  slug: "shingo-tamagawa",
  name: "Shingo Tamagawa",
  kind: "person",
  status: "published",
  profilePath: "/criadores/shingo-tamagawa",
  birthYear: 1987,
  birthPlace: "Nara, Japão",
  summary: "Animador e realizador japonês, autor do curta independente Puparia.",
  workIds: ["work_puparia_2020", "work_archipel_making_puparia_2021"],
  sources: [
    { title: "PUPARIA", url: "https://www.youtube.com/watch?v=CWnqX41JHuM", kind: "primary" },
    { title: "Three Minutes, Three Years: Making Puparia", url: "https://www.youtube.com/watch?v=VKsG3E7TLl4", kind: "primary" },
    { title: "PUPARIA — FilmFreeway", url: "https://filmfreeway.com/PUPARIA831", kind: "primary" },
  ],
  createdAt: "2026-08-12",
  updatedAt: "2026-08-12",
});

export const upamanyuBhattacharyya: Creator = CreatorSchema.parse({
  id: "person_upamanyu_bhattacharyya", slug: "upamanyu-bhattacharyya", name: "Upamanyu Bhattacharyya", kind: "person", status: "draft",
  summary: "Animador e codiretor indiano de Wade.", workIds: ["work_wade_2019"],
  sources: [{ title: "Wade — Annecy 2020", url: "https://www.annecyfestival.com/about/archives/2020/award-winners/film-index%3Afilm-20200770", kind: "primary" }],
  createdAt: "2026-08-12", updatedAt: "2026-08-12",
});

export const kalpSanghvi: Creator = CreatorSchema.parse({
  id: "person_kalp_sanghvi", slug: "kalp-sanghvi", name: "Kalp Sanghvi", kind: "person", status: "draft",
  summary: "Animador e codiretor indiano de Wade.", workIds: ["work_wade_2019"],
  sources: [{ title: "Wade — Annecy 2020", url: "https://www.annecyfestival.com/about/archives/2020/award-winners/film-index%3Afilm-20200770", kind: "primary" }],
  createdAt: "2026-08-12", updatedAt: "2026-08-12",
});

const teamCherryPeople:Creator[]=[
  {id:"person_ari_gibson",slug:"ari-gibson",name:"Ari Gibson",kind:"person",status:"draft",summary:"Cofundador, artista, animador e designer da Team Cherry.",workIds:[],sources:[{title:"Team Cherry",url:"https://www.teamcherry.com.au/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
  {id:"person_william_pellen",slug:"william-pellen",name:"William Pellen",kind:"person",status:"draft",summary:"Cofundador, designer e programador da Team Cherry.",workIds:[],sources:[{title:"Team Cherry",url:"https://www.teamcherry.com.au/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
  {id:"person_jasmine_vine",slug:"jasmine-vine",name:"Jasmine Vine",kind:"person",status:"draft",summary:"Programadora de Hollow Knight: Silksong.",workIds:[],sources:[{title:"Hollow Knight: Silksong",url:"https://hollowknightsilksong.com/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
  {id:"person_christopher_larkin",slug:"christopher-larkin",name:"Christopher Larkin",kind:"person",status:"draft",summary:"Compositor de Hollow Knight e Hollow Knight: Silksong.",workIds:[],sources:[{title:"Hollow Knight: Silksong",url:"https://hollowknightsilksong.com/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"},
].map(item=>CreatorSchema.parse(item));
const cartoonSaloonPeople:Creator[]=["Tomm Moore","Nora Twomey","Paul Young","Ross Stewart","Louise Bagnall"].map(name=>CreatorSchema.parse({id:`person_${name.toLowerCase().replaceAll(" ","_")}`,slug:name.toLowerCase().replaceAll(" ","-"),name,kind:"person",status:"draft",summary:`Profissional relacionado ao Cartoon Saloon.`,workIds:[],sources:[{title:"Cartoon Saloon — About",url:"https://www.cartoonsaloon.ie/irish-animation-studio/about/",kind:"primary"}],createdAt:"2026-08-12",updatedAt:"2026-08-12"}));
const ghibliPeople:Creator[] = [
  { id:"person_hayao_miyazaki", slug:"hayao-miyazaki", name:"Hayao Miyazaki", summary:"Diretor, roteirista, animador e participante da fundação do Studio Ghibli." },
  { id:"person_isao_takahata", slug:"isao-takahata", name:"Isao Takahata", summary:"Diretor, produtor e participante da fundação do Studio Ghibli." },
  { id:"person_toshio_suzuki", slug:"toshio-suzuki", name:"Toshio Suzuki", summary:"Produtor e articulador editorial que participou da fundação e continuidade do Studio Ghibli." },
].map(person=>CreatorSchema.parse({
  ...person, kind:"person", status:person.id === "person_hayao_miyazaki" ? "published" : "draft", workIds:[],
  ...(person.id === "person_hayao_miyazaki" ? {
    profilePath:"/personalidades/hayao-miyazaki",
    originalName:"宮崎 駿",
    image:{
      src:"/images/personalities/hayao-miyazaki.webp",
      alt:"Hayao Miyazaki no Festival de Cinema de Veneza de 2008",
      credit:"Thomas Schulz",
      sourceUrl:"https://commons.wikimedia.org/wiki/File:Hayao_Miyazaki.jpg",
      license:"CC BY-SA 2.0",
      licenseUrl:"https://creativecommons.org/licenses/by-sa/2.0/",
    },
    birthDate:"1941-01-05",
    birthPlace:"Tóquio, Japão",
    countryOrRegion:"Japão",
    occupations:["Diretor", "Animador", "Roteirista", "Mangaká"],
    biography:[
      "Hayao Miyazaki nasceu em Tóquio, em 1941. Depois de se formar em Ciência Política e Economia na Universidade Gakushuin, entrou na Toei Animation em 1963 e desenvolveu parte importante de sua formação profissional ao lado de Isao Takahata.",
      "Sua estreia na direção de longas ocorreu com O Castelo de Cagliostro, em 1979. Após escrever e dirigir Nausicaä do Vale do Vento, participou da fundação do Studio Ghibli em 1985 e consolidou uma obra em que aventura, cotidiano, trabalho manual, guerra e natureza raramente oferecem respostas simples.",
      "No Studio Ghibli, Miyazaki alternou projetos voltados à infância, aventuras de grande escala e dramas históricos. Mesmo quando outras pessoas assumiram a direção, ele também trabalhou em roteiro e desenvolvimento de obras do estúdio; por isso, a filmografia abaixo separa direção de colaboração, em vez de atribuir todos os filmes a uma única função.",
    ],
    themes:["Natureza e tecnologia", "Infância e autonomia", "Trabalho e criação", "Aviação", "Guerra e responsabilidade"],
    ideas:[
      {title:"Natureza sem pureza fácil",description:"Florestas, mares e criaturas possuem agência, mas seus filmes evitam reduzir conflitos ambientais a uma oposição simples entre natureza inocente e humanidade maligna."},
      {title:"Trabalho como formação",description:"Oficinas, cozinhas, entregas e tarefas cotidianas organizam relações. Aprender a fazer algo costuma ser também uma maneira de conquistar autonomia e participar de uma comunidade."},
      {title:"Voo, técnica e ambivalência",description:"A aviação aparece como fascínio visual e conquista técnica, mas permanece ligada à guerra, à indústria e às consequências do que se constrói."},
      {title:"Infância com capacidade de agir",description:"Crianças não funcionam apenas como símbolos de inocência: observam, trabalham, erram e tomam decisões diante de mundos que os adultos não controlam por completo."},
    ],
    startingPoints:[
      {workId:"mov_ghb_2001_chihiro",note:"A entrada mais abrangente: fantasia, trabalho, consumo e amadurecimento organizados numa aventura acessível a diferentes idades."},
      {workId:"mov_ghb_1988_totoro",note:"Para conhecer seu interesse pelo cotidiano infantil, pela espera e por uma natureza fantástica que não existe apenas para ameaçar."},
      {workId:"mov_ghb_1997_mononoke",note:"A escolha para quem prefere conflito político, violência concreta e uma relação entre indústria e natureza sem lados inteiramente puros."},
    ],
    relatedLinks:[
      {label:"Perfil permanente do Studio Ghibli",href:"/estudios/studio-ghibli",kind:"studio"},
      {label:"Studio Ghibli: história, filmes e por onde começar",href:"/blog/studio-ghibli",kind:"article"},
    ],
    sources:[
      {title:"Hayao Miyazaki — Academy of Motion Picture Arts and Sciences",url:"https://www.oscars.org/governors-awards/2014/hayao-miyazaki",kind:"secondary"},
      {title:"História oficial — Studio Ghibli",url:"https://www.ghibli.jp/history/",kind:"primary"},
      {title:"Hayao Miyazaki no Festival de Veneza — Wikimedia Commons",url:"https://commons.wikimedia.org/wiki/File:Hayao_Miyazaki.jpg",kind:"secondary"},
    ],
    updatedAt:"2026-08-14",
  } : {
    sources:[{title:"História oficial — Studio Ghibli",url:"https://www.ghibli.jp/history/",kind:"primary"}],
    updatedAt:"2026-08-13",
  }),
  createdAt:"2026-08-13",
}));
const laikaPeople:Creator[] = [CreatorSchema.parse({
  id:"person_travis_knight",slug:"travis-knight",name:"Travis Knight",kind:"person",status:"draft",
  summary:"Presidente e CEO da LAIKA, diretor de Kubo e as Cordas Mágicas e Wildwood.",workIds:[],
  sources:[{title:"Wildwood — anúncio de distribuição",url:"https://www.fathomentertainment.com/news/laika-debuts-teaser-trailer-press-release-fathom/",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
})];
const aardmanPeople:Creator[] = [
  {id:"person_peter_lord",slug:"peter-lord",name:"Peter Lord",summary:"Cofundador da Aardman, diretor, animador e produtor."},
  {id:"person_david_sproxton",slug:"david-sproxton",name:"David Sproxton",summary:"Cofundador da Aardman e produtor ligado à consolidação do estúdio."},
  {id:"person_nick_park",slug:"nick-park",name:"Nick Park",summary:"Diretor e animador que criou Wallace & Gromit e desenvolveu obras centrais da Aardman."},
].map(person=>CreatorSchema.parse({
  ...person,kind:"person",status:"draft",workIds:[],
  sources:[{title:"People — Aardman",url:"https://www.aardman.com/about/people/",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
}));
const scienceSaruPeople:Creator[] = [
  {id:"person_masaaki_yuasa",slug:"masaaki-yuasa",name:"Masaaki Yuasa",summary:"Diretor e cofundador histórico da Science SARU; deixou a presidência em 2020."},
  {id:"person_eunyoung_choi",slug:"eunyoung-choi",name:"Eunyoung Choi",summary:"Animadora, produtora e cofundadora histórica da Science SARU."},
  {id:"person_masanori_fujita",slug:"masanori-fujita",name:"Masanori Fujita",summary:"Representante e CEO da Science SARU no cadastro institucional de 2026."},
].map(person=>CreatorSchema.parse({
  ...person,kind:"person",status:"draft",workIds:[],
  sources:[{title:"About — Science SARU",url:"https://sciencesaru.com/en/about",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
}));
const kyotoAnimationPeople:Creator[] = [
  {id:"person_yoko_hatta",slug:"yoko-hatta",name:"Yoko Hatta",summary:"Animadora e cofundadora da Kyoto Animation."},
  {id:"person_hideaki_hatta",slug:"hideaki-hatta",name:"Hideaki Hatta",summary:"Cofundador e presidente histórico da Kyoto Animation, morto em fevereiro de 2026."},
  {id:"person_shinichiro_hatta",slug:"shinichiro-hatta",name:"Shinichiro Hatta",summary:"Presidente e CEO da Kyoto Animation desde fevereiro de 2026."},
].map(person=>CreatorSchema.parse({
  ...person,kind:"person",status:"draft",workIds:[],
  sources:[{title:"Corporate Profile — Kyoto Animation",url:"https://www.kyotoanimation.co.jp/en/company/profile/",kind:"primary"}],
  createdAt:"2026-08-13",updatedAt:"2026-08-13",
}));
const creatorVisuals: Partial<Record<string, Pick<Creator, "image" | "countryOrRegion" | "occupations" | "birthDate" | "birthYear" | "deathDate">>> = {
  person_byung_chul_han: {
    image: {
      src: "/images/personalities/byung-chul-han.jpg",
      alt: "Retrato de Byung-Chul Han durante o Prix Bristol des Lumières de 2015",
      credit: "ActuaLitté; recorte de MRCLD, Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Byung-Chul_Han.jpg",
      license: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    },
    countryOrRegion: "Coreia do Sul / Alemanha",
    occupations: ["Filósofo", "Ensaísta", "Professor"],
    birthYear: 1959,
  },
  person_hannah_arendt: {
    image: {
      src: "/images/personalities/hannah-arendt.jpg",
      alt: "Retrato de Hannah Arendt em 1924",
      credit: "Autor desconhecido; reprodução preservada no Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Hannah_Arendt_1924.jpg",
      license: "Domínio público nos Estados Unidos; situação territorial descrita na fonte",
      licenseUrl: "https://commons.wikimedia.org/wiki/File:Hannah_Arendt_1924.jpg#Licensing",
    },
    countryOrRegion: "Alemanha / Estados Unidos",
    occupations: ["Filósofa", "Teórica política", "Escritora"],
    birthDate: "1906-10-14",
    deathDate: "1975-12-04",
  },
  person_agostinho_hipona: {
    image: {
      src: "/images/personalities/agostinho-de-hipona.jpg",
      alt: "Retrato histórico de Agostinho de Hipona na Basílica de São João de Latrão, em Roma",
      credit: "Mosaico do século VI; reprodução no Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:AugustineLateran.jpg",
      license: "Domínio público",
      licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Public_domain",
    },
    countryOrRegion: "Norte da África romana",
    occupations: ["Filósofo", "Teólogo", "Bispo de Hipona"],
    birthDate: "0354-11-13",
    deathDate: "0430-08-28",
  },
};

const vampireBookAuthors: Creator[] = [
  ["person_john_polidori","john-polidori","John Polidori","Autor britânico de O Vampiro."],
  ["person_sheridan_le_fanu","sheridan-le-fanu","Sheridan Le Fanu","Escritor irlandês e autor de Carmilla."],
  ["person_bram_stoker","bram-stoker","Bram Stoker","Escritor irlandês e autor de Drácula."],
  ["person_richard_matheson","richard-matheson","Richard Matheson","Escritor norte-americano de terror e ficção científica."],
  ["person_stephen_king","stephen-king","Stephen King","Escritor norte-americano de terror, suspense e fantasia."],
  ["person_anne_rice","anne-rice","Anne Rice","Escritora norte-americana e autora das Crônicas Vampirescas."],
  ["person_suzy_mckee_charnas","suzy-mckee-charnas","Suzy McKee Charnas","Escritora norte-americana de fantasia e ficção científica."],
  ["person_george_r_r_martin","george-r-r-martin","George R. R. Martin","Escritor norte-americano de fantasia, terror e ficção científica."],
  ["person_s_p_somtow","s-p-somtow","S. P. Somtow","Escritor e compositor tailandês-americano."],
  ["person_elizabeth_engstrom","elizabeth-engstrom","Elizabeth Engstrom","Escritora norte-americana de horror."],
  ["person_jewelle_gomez","jewelle-gomez","Jewelle Gomez","Escritora e dramaturga norte-americana."],
  ["person_robin_mckinley","robin-mckinley","Robin McKinley","Escritora norte-americana de fantasia."],
  ["person_john_ajvide_lindqvist","john-ajvide-lindqvist","John Ajvide Lindqvist","Escritor sueco de terror."],
  ["person_octavia_e_butler","octavia-e-butler","Octavia E. Butler","Escritora norte-americana de ficção científica."],
  ["person_elizabeth_kostova","elizabeth-kostova","Elizabeth Kostova","Escritora norte-americana e autora de A Historiadora."],
  ["person_justin_cronin","justin-cronin","Justin Cronin","Escritor norte-americano e autor da trilogia A Passagem."],
  ["person_holly_black","holly-black","Holly Black","Escritora norte-americana de fantasia contemporânea."],
  ["person_christopher_buehlman","christopher-buehlman","Christopher Buehlman","Escritor norte-americano de horror e fantasia."],
  ["person_silvia_moreno_garcia","silvia-moreno-garcia","Silvia Moreno-Garcia","Escritora mexicana-canadense de fantasia e horror."],
  ["person_jose_luis_zarate","jose-luis-zarate","José Luis Zárate","Escritor mexicano de ficção especulativa."],
  ["person_grady_hendrix","grady-hendrix","Grady Hendrix","Escritor norte-americano de horror."],
  ["person_s_t_gibson","s-t-gibson","S. T. Gibson","Escritora norte-americana de fantasia gótica."],
  ["person_claire_kohda","claire-kohda","Claire Kohda","Escritora e crítica musical britânica."],
  ["person_alexis_henderson","alexis-henderson","Alexis Henderson","Escritora norte-americana de fantasia sombria."],
  ["person_isabel_canas","isabel-canas","Isabel Cañas","Escritora mexicano-americana de ficção gótica."],
  ["person_mary_shelley","mary-shelley","Mary Shelley","Escritora inglesa de ficção gótica e especulativa."],
  ["person_henry_james","henry-james","Henry James","Escritor norte-americano-britânico de ficção psicológica."],
  ["person_shirley_jackson","shirley-jackson","Shirley Jackson","Escritora norte-americana de terror e ficção psicológica."],
  ["person_ira_levin","ira-levin","Ira Levin","Escritor e dramaturgo norte-americano."],
  ["person_toni_morrison","toni-morrison","Toni Morrison","Escritora norte-americana e autora de Amada."],
  ["person_koji_suzuki","koji-suzuki","Koji Suzuki","Escritor japonês de terror e ficção científica."],
  ["person_jeff_vandermeer","jeff-vandermeer","Jeff VanderMeer","Escritor norte-americano de ficção especulativa e New Weird."],
  ["person_john_langan","john-langan","John Langan","Escritor norte-americano de horror."],
  ["person_agustina_bazterrica","agustina-bazterrica","Agustina Bazterrica","Escritora argentina de ficção especulativa."],
  ["person_mariana_enriquez","mariana-enriquez","Mariana Enriquez","Escritora e jornalista argentina."],
  ["person_stephen_graham_jones","stephen-graham-jones","Stephen Graham Jones","Escritor norte-americano de origem Blackfeet."],
  ["person_tananarive_due","tananarive-due","Tananarive Due","Escritora norte-americana de horror e ficção especulativa."],
  ["person_p_djeli_clark","p-djeli-clark","P. Djèlí Clark","Escritor norte-americano de fantasia e horror."],
  ["person_bora_chung","bora-chung","Bora Chung","Escritora e tradutora sul-coreana."],
  ["person_raphael_montes","raphael-montes","Raphael Montes","Escritor e roteirista brasileiro de suspense e horror."],
  ["person_dan_simmons","dan-simmons","Dan Simmons","Escritor norte-americano de terror, ficção científica e fantasia."],
  ["person_robert_mccammon","robert-mccammon","Robert McCammon","Escritor norte-americano de terror e ficção histórica."],
  ["person_ray_bradbury","ray-bradbury","Ray Bradbury","Escritor norte-americano de ficção especulativa, fantasia e horror."],
  ["person_stephen_chbosky","stephen-chbosky","Stephen Chbosky","Escritor, roteirista e diretor norte-americano."],
  ["person_c_j_tudor","c-j-tudor","C. J. Tudor","Escritora britânica de suspense e terror."],
  ["person_paul_tremblay","paul-tremblay","Paul Tremblay","Escritor norte-americano de terror e suspense."],
  ["person_ronald_malfi","ronald-malfi","Ronald Malfi","Escritor norte-americano de terror."],
  ["person_craig_davidson","craig-davidson","Craig Davidson","Escritor canadense de ficção literária e horror."],
  ["person_jessica_johns","jessica-johns","Jessica Johns","Escritora canadense nehiyaw de ficção contemporânea e horror."],
  ["person_adam_cesare","adam-cesare","Adam Cesare","Escritor norte-americano de terror."],
  ["person_marv_wolfman","marv-wolfman","Marv Wolfman","Roteirista norte-americano de quadrinhos."],
  ["person_gene_colan","gene-colan","Gene Colan","Desenhista norte-americano de quadrinhos."],
  ["person_moto_hagio","moto-hagio","Moto Hagio","Mangaká japonesa associada ao Grupo do Ano 24."],
  ["person_joann_sfar","joann-sfar","Joann Sfar","Quadrinista e cineasta francês."],
  ["person_matsuri_hino","matsuri-hino","Matsuri Hino","Mangaká japonesa."],
  ["person_kouta_hirano","kohta-hirano","Kohta Hirano","Mangaká japonês e criador de Hellsing."],
  ["person_steve_niles","steve-niles","Steve Niles","Roteirista norte-americano de quadrinhos de terror."],
  ["person_ben_templesmith","ben-templesmith","Ben Templesmith","Artista australiano de quadrinhos."],
  ["person_scott_snyder","scott-snyder","Scott Snyder","Roteirista norte-americano de quadrinhos."],
  ["person_nick_dragotta","nick-dragotta","Nick Dragotta","Desenhista e cocriador norte-americano de quadrinhos."],
  ["person_neil_gaiman","neil-gaiman","Neil Gaiman","Escritor e roteirista britânico de romances, contos e quadrinhos."],
  ["person_rafael_albuquerque","rafael-albuquerque","Rafael Albuquerque","Quadrinista brasileiro."],
  ["person_mike_mignola","mike-mignola","Mike Mignola","Quadrinista norte-americano e criador de Hellboy e Baltimore."],
  ["person_christopher_golden","christopher-golden","Christopher Golden","Escritor e roteirista norte-americano."],
  ["person_fabio_moon","fabio-moon","Fábio Moon","Quadrinista brasileiro."],
  ["person_jessica_abel","jessica-abel","Jessica Abel","Quadrinista e escritora norte-americana."],
  ["person_gabriel_soria","gabriel-soria","Gabriel Soria","Roteirista norte-americano de quadrinhos."],
  ["person_warren_pleece","warren-pleece","Warren Pleece","Quadrinista britânico."],
  ["person_sarah_andersen","sarah-andersen","Sarah Andersen","Quadrinista norte-americana."],
  ["person_alex_de_campi","alex-de-campi","Alex de Campi","Roteirista britânica-americana de quadrinhos."],
  ["person_erica_henderson","erica-henderson","Erica Henderson","Desenhista e colorista norte-americana."],
  ["person_ram_v","ram-v","Ram V","Roteirista indiano de quadrinhos."],
  ["person_sumit_kumar","sumit-kumar","Sumit Kumar","Artista indiano de quadrinhos."],
  ["person_rodney_barnes","rodney-barnes","Rodney Barnes","Roteirista e produtor norte-americano."],
  ["person_jason_shawn_alexander","jason-shawn-alexander","Jason Shawn Alexander","Artista norte-americano de quadrinhos."],
  ["person_shuzo_oshimi","shuzo-oshimi","Shuzo Oshimi","Mangaká japonês."],
  ["person_jun_mochizuki","jun-mochizuki","Jun Mochizuki","Mangaká japonesa."],
  ["person_kotoyama","kotoyama","Kotoyama","Mangaká japonês."],
  ["person_akili","akili","Akili","Mangaká japonês, também conhecido como Shou Higashiyama."],
  ["person_lina_im","lina-im","Lina Im","Quadrinista sul-coreana e criadora de Unholy Blood."],
  ["person_junji_ito","junji-ito","Junji Ito","Mangaká japonês de horror."],
  ["person_kazuo_umezz","kazuo-umezz","Kazuo Umezz","Mangaká japonês de horror e ficção científica."],
  ["person_masaaki_nakayama","masaaki-nakayama","Masaaki Nakayama","Mangaká japonês de horror."],
  ["person_hitoshi_iwaaki","hitoshi-iwaaki","Hitoshi Iwaaki","Mangaká japonês."],
  ["person_hideo_yamamoto","hideo-yamamoto","Hideo Yamamoto","Mangaká japonês."],
  ["person_mokumokuren","mokumokuren","Mokumokuren","Mangaká japonês."],
  ["person_carnby_kim","carnby-kim","Carnby Kim","Roteirista sul-coreano de webtoons."],
  ["person_youngchan_hwang","youngchan-hwang","Youngchan Hwang","Artista sul-coreano de webtoons."],
  ["person_alan_moore","alan-moore","Alan Moore","Roteirista britânico de quadrinhos."],
  ["person_eddie_campbell","eddie-campbell","Eddie Campbell","Quadrinista escocês-australiano."],
  ["person_charles_burns","charles-burns","Charles Burns","Quadrinista norte-americano."],
  ["person_joe_hill","joe-hill","Joe Hill","Escritor e roteirista norte-americano."],
  ["person_gabriel_rodriguez","gabriel-rodriguez","Gabriel Rodríguez","Quadrinista chileno."],
  ["person_pornsak_pichetshote","pornsak-pichetshote","Pornsak Pichetshote","Roteirista e editor de quadrinhos."],
  ["person_aaron_campbell","aaron-campbell","Aaron Campbell","Desenhista norte-americano de quadrinhos."],
  ["person_james_tynion_iv","james-tynion-iv","James Tynion IV","Roteirista norte-americano de quadrinhos."],
  ["person_alvaro_martinez_bueno","alvaro-martinez-bueno","Álvaro Martínez Bueno","Desenhista espanhol de quadrinhos."],
  ["person_jeff_lemire","jeff-lemire","Jeff Lemire","Quadrinista e roteirista canadense."],
  ["person_andrea_sorrentino","andrea-sorrentino","Andrea Sorrentino","Desenhista italiano de quadrinhos."],
  ["person_shiko","shiko","Shiko","Quadrinista paraibano."],
  ["person_alex_magnos","alex-magnos","Alex Magnos","Roteirista brasileiro de quadrinhos."],
  ["person_gean_bandeira","gean-bandeira","Gean Bandeira","Quadrinista brasileiro."],
  ["person_ian_sbf","ian-sbf","Ian SBF","Roteirista e cineasta brasileiro."],
  ["person_marcela_godoy","marcela-godoy","Marcela Godoy","Roteirista brasileira de quadrinhos e horror."],
  ["person_leonel_caldela","leonel-caldela","Leonel Caldela","Escritor e roteirista brasileiro."],
  ["person_kouji_miura","kouji-miura","Kouji Miura","Mangaká japonesa e autora de Blue Box."],
  ["person_aka_akasaka","aka-akasaka","Aka Akasaka","Mangaká japonês."],
  ["person_fujita","fujita","Fujita","Mangaká japonesa e autora de Wotakoi."],
  ["person_ai_yazawa","ai-yazawa","Ai Yazawa","Mangaká japonesa."],
  ["person_natsuki_takaya","natsuki-takaya","Natsuki Takaya","Mangaká japonesa."],
  ["person_hero","hero-mangaka","HERO","Mangaká japonesa e criadora de Horimiya."],
  ["person_daisuke_hagiwara","daisuke-hagiwara","Daisuke Hagiwara","Mangaká japonesa e artista de Horimiya."],
  ["person_shinichi_fukuda","shinichi-fukuda","Shinichi Fukuda","Mangaká japonesa."],
  ["person_makoto_ojiro","makoto-ojiro","Makoto Ojiro","Mangaká japonesa."],
  ["person_misaki_takamatsu","misaki-takamatsu","Misaki Takamatsu","Mangaká japonesa."],
  ["person_suu_morishita","suu-morishita","Suu Morishita","Dupla japonesa de mangakás."],
  ["person_kintetsu_yamada","kintetsu-yamada","Kintetsu Yamada","Mangaká japonesa."],
  ["person_rumiko_takahashi","rumiko-takahashi","Rumiko Takahashi","Mangaká japonesa."],
  ["person_inio_asano","inio-asano","Inio Asano","Mangaká japonês."],
  ["person_kazune_kawahara","kazune-kawahara","Kazune Kawahara","Mangaká japonesa."],
  ["person_aruco","aruko","Aruko","Mangaká japonesa."],
  ["person_natsuki_kizu","natsuki-kizu","Natsuki Kizu","Mangaká japonesa."],
  ["person_nio_nakatani","nio-nakatani","Nio Nakatani","Mangaká japonesa."],
  ["person_tomoko_ninomiya","tomoko-ninomiya","Tomoko Ninomiya","Mangaká japonesa."],
].map(([id,slug,name,summary])=>CreatorSchema.parse({
  id, slug, name, summary, kind:"person", workIds:[],
  ...creatorVisuals[id],
  status:id === "person_stephen_king" ? "published" : "draft",
  ...(id === "person_stephen_king" ? {
    profilePath:"/personalidades/stephen-king",
    fullName:"Stephen Edwin King",
    image:{
      src:"/images/personalities/stephen-king.webp",
      alt:"Stephen King durante o Festival Internacional de Cinema de Toronto de 2024",
      credit:"Kevin Payravi, Wikimedia Commons",
      sourceUrl:"https://commons.wikimedia.org/wiki/File:Stephen_King_at_the_2024_Toronto_International_Film_Festival_2.jpg",
      license:"CC BY-SA 4.0",
      licenseUrl:"https://creativecommons.org/licenses/by-sa/4.0/",
    },
    birthDate:"1947-09-21",
    birthPlace:"Portland, Maine, Estados Unidos",
    countryOrRegion:"Estados Unidos",
    occupations:["Escritor", "Roteirista"],
    biography:[
      "Stephen King nasceu em Portland, no estado do Maine, e começou a publicar profissionalmente ainda nos anos 1960. Depois de estudar inglês e trabalhar como professor, passou a escrever em tempo integral após a publicação de Carrie.",
      "Sua importância não se limita à frequência com que foi adaptado. King aproximou o terror de famílias, cidades pequenas, trabalho, infância e instituições reconhecíveis, fazendo o sobrenatural conviver com violências que já estavam presentes nas comunidades.",
    ],
    themes:["Terror cotidiano", "Cidades pequenas", "Infância e amadurecimento", "Memória", "Violência comunitária"],
    startingPoints:[
      {workId:"read_work_it",note:"A porta de entrada mais ampla para seus temas recorrentes: infância, memória, amizade e uma cidade que aprende a ignorar o horror."},
      {workId:"read_work_shining",note:"Uma escolha mais concentrada, indicada para conhecer como isolamento, dependência e violência familiar atravessam o sobrenatural."},
      {workId:"read_work_salem_lot",note:"Para observar a cidade pequena como organismo social antes e durante a chegada de uma ameaça vampírica."},
    ],
    relatedLinks:[
      {label:"Melhores livros de terror para diferentes leitores",href:"/blog/melhores-livros-de-terror",kind:"list"},
      {label:"Livros para quem gostou de It: Bem-Vindos a Derry",href:"/blog/livros-para-quem-gostou-de-it-bem-vindos-a-derry",kind:"list"},
    ],
    sources:[
      {title:"Stephen King — biografia oficial",url:"https://stephenking.com/the-author/",kind:"primary"},
      {title:"Stephen King no TIFF 2024 — Wikimedia Commons",url:"https://commons.wikimedia.org/wiki/File:Stephen_King_at_the_2024_Toronto_International_Film_Festival_2.jpg",kind:"secondary"},
    ],
    updatedAt:"2026-08-14",
  } : {
    sources:[{title:`Página oficial ou bibliográfica — ${name}`,url:`https://openlibrary.org/search/authors?q=${encodeURIComponent(name)}`,kind:"secondary"}],
    updatedAt:"2026-08-13",
  }),
  createdAt:"2026-08-13",
}));
const nietzschePeople: Creator[] = [
  CreatorSchema.parse({
    id:"person_friedrich_nietzsche",slug:"friedrich-nietzsche",name:"Friedrich Nietzsche",fullName:"Friedrich Wilhelm Nietzsche",kind:"person",status:"published",
    profilePath:"/personalidades/friedrich-nietzsche",
    image:{
      src:"/images/personalities/friedrich-nietzsche.webp",
      alt:"Retrato de perfil de Friedrich Nietzsche fotografado em 1882",
      credit:"Gustav-Adolf Schultze; digitalização tratada por Anton (2005)",
      sourceUrl:"https://commons.wikimedia.org/wiki/File:Nietzsche1882.jpg",
      license:"Domínio público",
      licenseUrl:"https://commons.wikimedia.org/wiki/Commons:Public_domain",
    },
    birthDate:"1844-10-15",deathDate:"1900-08-25",birthPlace:"Röcken, Prússia (atual Alemanha)",countryOrRegion:"Alemanha",
    occupations:["Filósofo", "Filólogo clássico", "Escritor", "Crítico cultural"],
    summary:"Filósofo e filólogo alemão que investigou como valores são criados, herdados e transformados diante da crise da moral e da religião europeias.",
    biography:[
      "Nietzsche nasceu em Röcken e se formou em filologia clássica. Em 1869, ainda jovem, assumiu uma cátedra na Universidade da Basileia; o estudo rigoroso dos textos antigos continuaria presente mesmo quando sua escrita se afastou do formato acadêmico.",
      "Depois de deixar a universidade por problemas de saúde em 1879, viveu de forma itinerante e escreveu livros que alternam aforismo, ensaio, genealogia e narrativa filosófica. Sua crítica à moral, à religião e aos valores tradicionais pergunta de onde eles vêm, a que formas de vida servem e o que acontece quando perdem autoridade.",
      "Após seu colapso em 1889, a irmã Elisabeth Förster-Nietzsche controlou o arquivo e interferiu na organização póstuma dos fragmentos, especialmente na compilação conhecida como A Vontade de Poder. Sua promoção nacionalista e antissemita favoreceu uma associação posterior e indevida da obra ao nazismo. Nietzsche morreu em 1900, antes do regime, e havia se manifestado contra o antissemitismo e o nacionalismo alemão; isso não elimina os aspectos elitistas e controversos que ainda exigem leitura crítica.",
    ],
    themes:["Crítica da moral", "Religião e crise dos valores", "Genealogia", "Arte e cultura", "Afirmação da vida"],
    ideas:[
      {title:"Niilismo",description:"É o diagnóstico da perda de força dos valores considerados superiores e da crise de sentido que se segue. Nietzsche não propõe simplesmente o vazio: boa parte de seu trabalho procura atravessar o niilismo e perguntar como criar avaliações afirmadoras da vida."},
      {title:"Além-do-homem",description:"Apresentado sobretudo em Assim Falou Zaratustra, é uma figura de autossuperação e criação de valores, não uma raça biologicamente superior. O conceito funciona como horizonte exigente, e sua interpretação permanece debatida."},
      {title:"Eterno retorno",description:"A ideia pergunta como viveríamos diante da possibilidade de cada instante retornar incontáveis vezes. Pode ser lida como desafio de afirmação radical da vida; leituras cosmológicas e existenciais continuam em disputa."},
      {title:"Vontade de poder",description:"Nomeia, em diferentes contextos, relações de força, interpretação, crescimento e superação. Não deve ser reduzida a desejo de domínio político nem tratada como um sistema fechado a partir da compilação póstuma organizada por seus editores."},
      {title:"Perspectivismo",description:"Conhecemos a partir de posições, interesses e capacidades situadas. Isso não significa que qualquer opinião valha tanto quanto outra: perspectivas podem ser comparadas pelo alcance, pela coerência e pelo que conseguem tornar visível."},
      {title:"Moral de senhores e moral de escravos",description:"Na Genealogia da Moral, são categorias para investigar como valores se formam. A primeira parte da autoafirmação; a segunda surge reativamente, marcada pelo ressentimento. É uma análise genealógica controversa, não uma instrução política literal."},
    ],
    workIds:[],
    startingPoints:[
      {workId:"read_work_twilight_idols",note:"Introdução mais curta e direta à crítica dos ídolos filosóficos e culturais — uma boa forma de conhecer o tom sem começar pela obra mais simbólica."},
      {workId:"read_work_gay_science",note:"Reúne aforismos sobre conhecimento, moral, arte, morte de Deus e eterno retorno, oferecendo contato com vários temas centrais."},
      {workId:"read_work_beyond_good_evil",note:"Aprofunda a crítica à filosofia dogmática, à moral e às pretensões de neutralidade; funciona melhor depois de uma primeira familiaridade com seu vocabulário."},
      {workId:"read_work_genealogy_morality",note:"Investiga a formação histórica e psicológica dos valores, do ressentimento, da culpa e do ideal ascético em três ensaios conectados."},
      {workId:"read_work_thus_spoke_zarathustra",note:"A entrada mais literária, simbólica e exigente desta trilha. Vale chegar a ela sem esperar um manual nem uma explicação definitiva dos conceitos."},
    ],
    relatedPersonIds:["person_arthur_schopenhauer","person_richard_wagner","person_elisabeth_forster_nietzsche"],
    relatedLinks:[
      {label:"Friedrich Nietzsche: vida, ideias, obras e por onde começar",href:"/blog/friedrich-nietzsche",kind:"article"},
      {label:"O que é niilismo? De Nietzsche ao uso atual",href:"/blog/o-que-e-niilismo",kind:"article"},
      {label:"Amor fati: o que Nietzsche queria dizer",href:"/blog/amor-fati-significado-nietzsche",kind:"article"},
      {label:"Arthur Schopenhauer: vida, filosofia, obras e por onde começar",href:"/blog/arthur-schopenhauer",kind:"article"},
    ],
    sources:[
      {title:"Nietzsche’s Life and Works — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/nietzsche-life-works/",kind:"secondary"},
      {title:"Nietzsche’s Moral and Political Philosophy — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/nietzsche-moral-political/",kind:"secondary"},
      {title:"Friedrich Nietzsche — Internet Encyclopedia of Philosophy",url:"https://iep.utm.edu/nietzsch/",kind:"secondary"},
      {title:"Digital Critical Edition of Nietzsche’s Works and Letters",url:"https://doc.nietzschesource.org/en/ekgwb",kind:"primary"},
      {title:"Nietzsche's political misappropriation — Cambridge University Press",url:"https://www.cambridge.org/core/books/cambridge-companion-to-nietzsche/nietzsches-political-misappropriation/1B8D0FFB378250F08C950775F98261CE",kind:"secondary"},
      {title:"Retrato de Friedrich Nietzsche, 1882 — Wikimedia Commons",url:"https://commons.wikimedia.org/wiki/File:Nietzsche1882.jpg",kind:"secondary"},
    ],
    createdAt:"2026-08-14",updatedAt:"2026-08-14",
  }),
  ...[
    {id:"person_arthur_schopenhauer",slug:"arthur-schopenhauer",name:"Arthur Schopenhauer",summary:"Filósofo alemão cuja reflexão sobre vontade, sofrimento e arte influenciou o jovem Nietzsche."},
    {id:"person_richard_wagner",slug:"richard-wagner",name:"Richard Wagner",summary:"Compositor alemão, primeiro aliado e depois alvo importante da crítica cultural de Nietzsche."},
    {id:"person_elisabeth_forster_nietzsche",slug:"elisabeth-forster-nietzsche",name:"Elisabeth Förster-Nietzsche",summary:"Irmã de Nietzsche e dirigente do arquivo que moldou a edição e a recepção pública póstuma de seus escritos."},
  ].map((person)=>CreatorSchema.parse({...person,kind:"person",status:"draft",workIds:[],sources:[{title:"Nietzsche’s Life and Works — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/nietzsche-life-works/",kind:"secondary"}],createdAt:"2026-08-14",updatedAt:"2026-08-14"})),
];

const jungPeople: Creator[] = [
  CreatorSchema.parse({
    id:"person_carl_jung",slug:"carl-jung",name:"Carl Jung",fullName:"Carl Gustav Jung",kind:"person",status:"published",profilePath:"/personalidades/carl-jung",
    image:{
      src:"/images/personalities/carl-jung.jpg",
      alt:"Retrato de corpo inteiro de Carl Gustav Jung no Burghölzli, por volta de 1909",
      credit:"Autor desconhecido; Library of Congress / Wikimedia Commons",
      sourceUrl:"https://commons.wikimedia.org/wiki/File:Jung_1910.jpg",
      license:"Domínio público nos Estados Unidos; situação territorial descrita na fonte",
      licenseUrl:"https://commons.wikimedia.org/wiki/File:Jung_1910.jpg#Licensing",
    },
    birthDate:"1875-07-26",deathDate:"1961-06-06",birthPlace:"Kesswil, Suíça",countryOrRegion:"Suíça",
    occupations:["Psiquiatra", "Psicoterapeuta", "Ensaísta"],
    summary:"Psiquiatra suíço que fundou a psicologia analítica e desenvolveu conceitos como inconsciente coletivo, arquétipos, individuação e tipos psicológicos.",
    biography:[
      "Jung formou-se em medicina e trabalhou no hospital Burghölzli, em Zurique, sob Eugen Bleuler. Seus experimentos de associação de palavras contribuíram para a investigação dos complexos e aproximaram-no da psicanálise.",
      "A colaboração com Sigmund Freud tornou Jung uma figura central do movimento psicanalítico internacional. Divergências sobre libido, religião, mito e a extensão do inconsciente levaram ao rompimento entre 1912 e 1914.",
      "Nas décadas seguintes, Jung chamou seu projeto de psicologia analítica. Sua obra circulou pela psicoterapia, estudos da religião, literatura e artes, mas conceitos centrais continuam sujeitos a disputas interpretativas e críticas científicas.",
    ],
    themes:["Psicologia analítica", "Inconsciente", "Arquétipos", "Individuação", "Sonhos e símbolos"],
    ideas:[
      {title:"Inconsciente coletivo",description:"Camada hipotética da psique que não deriva apenas da experiência pessoal e cujas disposições estruturais Jung chamou de arquétipos."},
      {title:"Individuação",description:"Processo de diferenciação e integração pelo qual a pessoa se relaciona com aspectos conscientes e inconscientes sem reduzir o Self ao ego."},
      {title:"Tipos psicológicos",description:"Modelo de atitudes e funções psíquicas que influenciou tipologias posteriores, embora estas não sejam equivalentes à teoria original."},
    ],
    workIds:[],startingPoints:[],relatedPersonIds:[],
    relatedLinks:[
      {label:"Carl Jung: quem foi, principais ideias e sua influência",href:"/blog/carl-jung",kind:"article"},
      {label:"O que é arquétipo? De Carl Jung ao uso popular",href:"/blog/o-que-e-arquetipo",kind:"article"},
    ],
    sources:[
      {title:"Jungian Psychology Lectures — IAAP",url:"https://www.iaap.org/wp-content/uploads/2021/10/Jungian-Psychotherapy-origin-history-and-contemporary-forms-part-I-2.pdf",kind:"secondary"},
      {title:"Retrato de Carl Jung, c. 1909 — Library of Congress",url:"https://www.loc.gov/pictures/item/98514811/",kind:"primary"},
    ],
    createdAt:"2026-08-20",updatedAt:"2026-08-20",
  }),
];

const philosophyPeople: Creator[] = [
  CreatorSchema.parse({
    id:"person_byung_chul_han",slug:"byung-chul-han",name:"Byung-Chul Han",kind:"person",status:"published",profilePath:"/personalidades/byung-chul-han",
    image:creatorVisuals.person_byung_chul_han!.image,birthYear:1959,countryOrRegion:"Coreia do Sul / Alemanha",occupations:["Filósofo", "Ensaísta", "Professor"],
    summary:"Filósofo e ensaísta sul-coreano radicado na Alemanha que investiga desempenho, tecnologia, atenção, transparência e formas contemporâneas de poder.",
    biography:[
      "Nascido em Seul, Byung-Chul Han estudou metalurgia antes de mudar-se para a Alemanha, onde estudou filosofia, literatura alemã e teologia católica. Doutorou-se em Freiburg com uma pesquisa sobre Martin Heidegger.",
      "Sua circulação pública está ligada a ensaios breves que descrevem autoexploração, excesso de positividade, transparência, psicopolítica e perda da contemplação. A concisão torna os problemas acessíveis, mas também exige distinguir diagnóstico filosófico, metáfora e evidência empírica.",
    ],
    themes:["Sociedade do desempenho", "Tecnologia e poder", "Atenção", "Cansaço", "Contemplação"],
    ideas:[
      {title:"Sociedade do desempenho",description:"Forma social em que a exigência aparece como iniciativa, otimização e projeto pessoal, favorecendo autoexploração."},
      {title:"Excesso de positividade",description:"Acúmulo de estímulos, comunicação e possibilidades que reduz espaço para limite, pausa e alteridade."},
      {title:"Psicopolítica",description:"Poder que mobiliza liberdade, desejo, dados e participação em vez de depender apenas de proibição externa."},
      {title:"Atenção e contemplação",description:"Práticas de demora e receptividade que resistem à fragmentação produtiva do tempo."},
    ],
    workIds:[],startingPoints:[{workId:"read_work_burnout_society",note:"Entrada curta para compreender desempenho, autoexploração e cansaço, acompanhada de leitura crítica das generalizações."}],relatedPersonIds:["person_hannah_arendt"],
    relatedLinks:[{label:"Byung-Chul Han: conceitos, obras, críticas e por onde começar",href:"/blog/byung-chul-han",kind:"article"},{label:"Sociedade do Cansaço: resumo, ideias e críticas",href:"/blog/sociedade-do-cansaco-resumo",kind:"article"}],
    sources:[{title:"Byung-Chul Han — University of the Arts Berlin",url:"https://www.udk-berlin.de/person/byung-chul-han/",kind:"primary"},{title:"The Burnout Society — Stanford University Press",url:"https://www.sup.org/books/theory-and-philosophy/burnout-society",kind:"secondary"},{title:"Retrato de Byung-Chul Han — Wikimedia Commons",url:"https://commons.wikimedia.org/wiki/File:Byung-Chul_Han.jpg",kind:"secondary"}],createdAt:"2026-08-20",updatedAt:"2026-08-20",
  }),
  CreatorSchema.parse({
    id:"person_hannah_arendt",slug:"hannah-arendt",name:"Hannah Arendt",fullName:"Johanna Arendt",kind:"person",status:"published",profilePath:"/personalidades/hannah-arendt",
    image:creatorVisuals.person_hannah_arendt!.image,birthDate:"1906-10-14",deathDate:"1975-12-04",birthPlace:"Linden, Hanôver, Império Alemão",countryOrRegion:"Alemanha / Estados Unidos",occupations:["Teórica política", "Filósofa", "Escritora"],
    summary:"Pensadora política germano-americana que investigou totalitarismo, ação, liberdade, responsabilidade e as condições de um mundo comum.",
    biography:["Nascida numa família judaica alemã, Arendt estudou com Martin Heidegger e Karl Jaspers e escreveu sua tese sobre o amor em Agostinho. Fugiu da Alemanha em 1933, viveu em Paris e chegou aos Estados Unidos em 1941.","Sua obra examina experiências políticas do século XX sem formar um sistema fechado. Totalitarismo, ação, pluralidade, julgamento e responsabilidade conectam história, filosofia e atenção às instituições."],
    themes:["Totalitarismo", "Ação e pluralidade", "Liberdade política", "Julgamento", "Mundo comum"],
    ideas:[{title:"Ação",description:"Atividade política pela qual pessoas iniciam algo e aparecem umas diante das outras em condição de pluralidade."},{title:"Banalidade do mal",description:"Formulação ligada ao julgamento de Eichmann sobre irreflexão, responsabilidade e funcionamento burocrático; não significa que o mal seja pequeno."},{title:"Poder e violência",description:"Poder nasce da ação conjunta e não é idêntico à violência, embora ambos possam se combinar historicamente."},{title:"Pluralidade",description:"Condição de igualdade e diferença que torna possível falar, agir e compartilhar um mundo."}],
    workIds:[],startingPoints:[],relatedPersonIds:["person_agostinho_hipona"],
    relatedLinks:[{label:"Hannah Arendt: ideias, obras e controvérsias",href:"/blog/hannah-arendt",kind:"article"},{label:"Os principais filósofos da história",href:"/blog/principais-filosofos-da-historia",kind:"article"}],
    sources:[{title:"Hannah Arendt — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/arendt/",kind:"secondary"},{title:"Hannah Arendt Papers — Library of Congress",url:"https://www.loc.gov/collections/hannah-arendt-papers/",kind:"primary"},{title:"Retrato de Hannah Arendt — Wikimedia Commons",url:"https://commons.wikimedia.org/wiki/File:Hannah_Arendt_1924.jpg",kind:"secondary"}],createdAt:"2026-08-20",updatedAt:"2026-08-20",
  }),
  CreatorSchema.parse({
    id:"person_agostinho_hipona",slug:"agostinho-de-hipona",name:"Agostinho de Hipona",fullName:"Aurélio Agostinho",originalName:"Aurelius Augustinus",kind:"person",status:"published",profilePath:"/personalidades/agostinho-de-hipona",
    image:creatorVisuals.person_agostinho_hipona!.image,birthDate:"0354-11-13",deathDate:"0430-08-28",birthPlace:"Tagaste, África romana",countryOrRegion:"Norte da África romana",occupations:["Filósofo", "Teólogo", "Bispo de Hipona"],
    summary:"Filósofo e teólogo da Antiguidade tardia que articulou cristianismo, platonismo e investigação da vontade, do mal, da memória, do tempo e da história.",
    biography:["Agostinho nasceu em Tagaste, no Norte da África romana, estudou e ensinou retórica. Após passagens pelo maniqueísmo e pelo ceticismo acadêmico, aproximou-se de leituras platônicas e converteu-se ao cristianismo em Milão.","De volta à África, tornou-se presbítero e bispo de Hipona. Seus escritos unem controvérsia teológica, interpretação bíblica e investigação filosófica; separá-los completamente segundo disciplinas modernas distorce o projeto."],
    themes:["Vontade e liberdade", "Problema do mal", "Memória e interioridade", "Tempo", "Filosofia da história"],
    ideas:[{title:"Mal como privação",description:"O mal não é uma substância rival do bem; descreve corrupção ou falta numa realidade criada."},{title:"Livre-arbítrio e graça",description:"A responsabilidade da vontade e a dependência da graça formam uma tensão central, desenvolvida de maneiras diferentes ao longo da obra."},{title:"Tempo",description:"A experiência temporal conecta memória do passado, atenção ao presente e expectativa do futuro."},{title:"Interioridade",description:"O retorno à mente não é isolamento: procura verdade, memória, vontade e relação com Deus."}],
    workIds:[],startingPoints:[],relatedPersonIds:["person_hannah_arendt"],relatedLinks:[{label:"Agostinho de Hipona: vida, ideias e influência",href:"/blog/agostinho-de-hipona",kind:"article"},{label:"Os principais filósofos da história",href:"/blog/principais-filosofos-da-historia",kind:"article"}],
    sources:[{title:"Augustine of Hippo — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/augustine/",kind:"secondary"},{title:"Obras de Agostinho — Augustinus.it",url:"https://www.augustinus.it/",kind:"primary"},{title:"Representação de Agostinho no Latrão — Wikimedia Commons",url:"https://commons.wikimedia.org/wiki/File:AugustineLateran.jpg",kind:"secondary"}],createdAt:"2026-08-20",updatedAt:"2026-08-20",
  }),
  CreatorSchema.parse({
    id:"person_thomas_hobbes",slug:"thomas-hobbes",name:"Thomas Hobbes",kind:"person",status:"published",profilePath:"/personalidades/thomas-hobbes",
    image:{src:"/images/personalities/thomas-hobbes.jpg",alt:"Retrato de Thomas Hobbes pintado por John Michael Wright por volta de 1669–1670",credit:"John Michael Wright; National Portrait Gallery / Wikimedia Commons",sourceUrl:"https://commons.wikimedia.org/wiki/File:Thomas_Hobbes_by_John_Michael_Wright.jpg",license:"Domínio público",licenseUrl:"https://creativecommons.org/publicdomain/mark/1.0/"},
    birthDate:"1588-04-05",deathDate:"1679-12-04",birthPlace:"Westport, Wiltshire, Inglaterra",countryOrRegion:"Inglaterra",occupations:["Filósofo", "Historiador", "Tradutor"],
    summary:"Filósofo inglês que investigou linguagem, matéria, liberdade e a autoridade política necessária para escapar da insegurança do estado de natureza.",
    biography:["Hobbes estudou em Oxford e trabalhou por décadas com a família Cavendish, relação que lhe deu acesso a bibliotecas e redes intelectuais europeias. Traduziu Tucídides e participou de debates sobre ciência, religião e política.","Escreveu durante conflitos que culminaram nas guerras civis inglesas. Leviatã organiza uma teoria materialista da pessoa, do pacto e da soberania; reduzir Hobbes à defesa de um governante cruel apaga o problema da paz civil que orienta o argumento."],
    themes:["Contrato social", "Soberania", "Medo e autopreservação", "Liberdade e necessidade", "Materialismo"],
    ideas:[{title:"Estado de natureza",description:"Situação teórica sem poder comum capaz de garantir pactos, marcada por insegurança mesmo quando não há combate contínuo."},{title:"Contrato e soberania",description:"Pessoas autorizam um poder comum para tornar possível a paz; a extensão e os limites dessa autorização permanecem debatidos."},{title:"Liberdade",description:"Ausência de impedimentos externos, compatível em sua teoria com causas necessárias e obrigações civis."},{title:"Representação",description:"O soberano age em nome da pessoa artificial do Estado criada pela autorização dos indivíduos."}],
    workIds:[],startingPoints:[],relatedPersonIds:[],relatedLinks:[{label:"Os principais filósofos da história",href:"/blog/principais-filosofos-da-historia",kind:"article"}],
    sources:[{title:"Thomas Hobbes — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/hobbes/",kind:"secondary"},{title:"Hobbes’s Moral and Political Philosophy — Stanford Encyclopedia of Philosophy",url:"https://plato.stanford.edu/entries/hobbes-moral/",kind:"secondary"},{title:"Retrato de Thomas Hobbes — Wikimedia Commons",url:"https://commons.wikimedia.org/wiki/File:Thomas_Hobbes_by_John_Michael_Wright.jpg",kind:"secondary"}],createdAt:"2026-08-20",updatedAt:"2026-08-20",
  }),
];

export const creators = [shingoTamagawa, upamanyuBhattacharyya, kalpSanghvi,...teamCherryPeople,...cartoonSaloonPeople,...ghibliPeople,...laikaPeople,...aardmanPeople,...scienceSaruPeople,...kyotoAnimationPeople,...vampireBookAuthors,...nietzschePeople,...jungPeople,...philosophyPeople];
