import type { ReadingWork } from "./readingSchema";

const checked = "2026-08-24";
type Entry = { id:string; slug:string; originalTitle:string; title:string; romanized?:string; country:"Coreia do Sul"|"China"; start:string; end?:string; status?:ReadingWork["publicationStatus"]; credits:ReadingWork["credits"]; genres:string[]; themes:string[]; description:string; sourceUrl:string; image:string; width:number; height:number; credit:string };
const comic = (e:Entry):ReadingWork => ({
  id:`read_work_${e.id}`,contentType:"reading-work",schemaVersion:1,slug:e.slug,aliases:[],originalTitle:e.originalTitle,titleBr:e.title,romanizedTitle:e.romanized,
  format:e.country==="Coreia do Sul"?"manhwa":"manhua",originCountries:[e.country],originalLanguages:[e.country==="Coreia do Sul"?"Coreano":"Chinês"],
  comicTradition:e.country==="Coreia do Sul"?"manhwa":"manhua",comicFormat:"webtoon",readingDirection:"vertical",credits:e.credits,organizationRelationships:[],
  publicationStart:e.start,publicationEnd:e.end,publicationStatus:e.status??(e.end?"completed":"ongoing"),categories:["comics"],genres:e.genres,themes:e.themes,demographics:["young-adult","adult"],
  shortDescription:e.description,seriesMemberships:[],relatedWorks:[],adaptations:[],image:{src:`/images/reading/action-romance/${e.image}`,alt:`Capa ou arte promocional oficial de ${e.title}`,sourceUrl:e.sourceUrl,credit:e.credit,rights:"licensed",width:e.width,height:e.height},
  sources:[{title:`${e.title} — publicação oficial`,url:e.sourceUrl}],status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked,
});

export const actionRomanceComicWorks:ReadingWork[]=[
  comic({id:"doom_breaker",slug:"doom-breaker",originalTitle:"투신전생기",title:"Doom Breaker",romanized:"Tusinjeonsaenggi",country:"Coreia do Sul",start:"2021",status:"hiatus",credits:[{personId:"person_blue_deep",roles:["writer","artist"]}],genres:["Ação","Fantasia","Regressão"],themes:["Vingança","Segunda chance","Romance"],description:"O último guerreiro da humanidade retorna dez anos no tempo para enfrentar o deus que destruiu o mundo e impedir a morte da mulher que ama.",sourceUrl:"https://www.webtoons.com/en/action/doom-breaker/list?title_no=3197",image:"doom-breaker-cover.jpg",width:480,height:540,credit:"WEBTOON / Blue-Deep"}),
  comic({id:"ending_maker",slug:"ending-maker",originalTitle:"엔딩메이커",title:"Ending Maker",romanized:"Ending Maker",country:"Coreia do Sul",start:"2022",status:"hiatus",credits:[{personId:"person_chwiryong",roles:["original-creator","writer"]},{personId:"person_does",roles:["artist","adapter"]}],genres:["Ação","Fantasia","Romance","Isekai"],themes:["Sistema de jogo","Parceria","Apocalipse"],description:"Dois rivais do ranking de um RPG acordam como personagens prometidos em casamento e combinam conhecimento do jogo para impedir o final apocalíptico.",sourceUrl:"https://tapas.io/series/ending-maker/info",image:"ending-maker-cover.jpg",width:400,height:600,credit:"Tapas / CARROTOON"}),
  comic({id:"infinite_mage",slug:"the-infinite-mage",originalTitle:"무한의 마법사",title:"The Infinite Mage",romanized:"Muhan-ui Mabeopsa",country:"Coreia do Sul",start:"2022",status:"hiatus",credits:[{personId:"person_kim_chi_woo",roles:["original-creator","writer"]},{personId:"person_themis",roles:["adapter"]},{personId:"person_kiraz",roles:["artist"]}],genres:["Ação","Fantasia","Academia"],themes:["Magia","Mobilidade social","Amadurecimento"],description:"Um órfão criado por caçadores transforma curiosidade científica e domínio da zona espiritual em caminho para entrar no mundo aristocrático da magia.",sourceUrl:"https://tapas.io/series/the-infinite-mage/info",image:"infinite-mage-cover.jpg",width:400,height:600,credit:"Tapas / REDICE STUDIO"}),
  comic({id:"lazy_lord_sword",slug:"the-lazy-lord-masters-the-sword",originalTitle:"나태 공자, 노력 천재 되다",title:"The Lazy Lord Masters the Sword",romanized:"Natae Gongja, Noryeok Cheonjae Doeda",country:"Coreia do Sul",start:"2021",status:"hiatus",credits:[{personId:"person_second_star",roles:["original-creator"]},{personId:"person_dodomoon",roles:["writer","adapter"]},{personId:"person_doip",roles:["artist"]}],genres:["Ação","Fantasia","Drama"],themes:["Treinamento","Trauma","Companheirismo"],description:"Um jovem paralisado pelo luto encontra no sonho de um espadachim a disciplina para reconstruir corpo, identidade e vínculos com outros aprendizes.",sourceUrl:"https://www.tappytoon.com/en/book/367",image:"lazy-lord-cover.jpg",width:294,height:427,credit:"Tappytoon / Jakga Company"}),
  comic({id:"sss_class_revival_hunter",slug:"sss-class-revival-hunter",originalTitle:"SSS급 죽어야 사는 헌터",title:"SSS-Class Revival Hunter",romanized:"SSS-geup Jugeoya Saneun Hunter",country:"Coreia do Sul",start:"2020",status:"hiatus",credits:[{personId:"person_bill_k",roles:["original-creator"]},{personId:"person_sinnoa",roles:["writer","adapter"]},{personId:"person_neida",roles:["artist"]}],genres:["Ação","Fantasia","Sistema","Regressão"],themes:["Torre","Morte","Empatia"],description:"Um caçador copia habilidades e retorna um dia no tempo sempre que morre, usando a repetição para subir uma torre cujos andares mudam de gênero e lógica.",sourceUrl:"https://tapas.io/series/sss-class-revival-hunter/info",image:"sss-class-revival-hunter-cover.jpg",width:400,height:600,credit:"Tapas / Kakao Entertainment"}),
  comic({id:"jungle_juice",slug:"jungle-juice",originalTitle:"정글쥬스",title:"Jungle Juice",romanized:"Jeonggeuljyuseu",country:"Coreia do Sul",start:"2020",credits:[{personId:"person_hyeong_eun",roles:["writer"]},{personId:"person_juder",roles:["artist"]}],genres:["Ação","Fantasia urbana","Sobrevivência"],themes:["Insetos","Academia","Identidade"],description:"Um universitário com asas de libélula entra numa sociedade de humanos-inseto em que anatomia, cadeia alimentar e experimentos determinam poderes e conflitos.",sourceUrl:"https://www.webtoons.com/en/action/jungle-juice/list?title_no=2480",image:"jungle-juice-cover.jpg",width:480,height:540,credit:"WEBTOON / YLAB"}),
  comic({id:"legend_asura_poison_dragon",slug:"legend-of-an-asura-the-poison-dragon",originalTitle:"수라전설 독룡",title:"Legend of an Asura: The Poison Dragon",romanized:"Surajeonseol Dongnyong",country:"Coreia do Sul",start:"2021",status:"hiatus",credits:[{personId:"person_yk_sinier",roles:["original-creator","writer"]},{personId:"person_antstudio",roles:["artist","adapter"]}],genres:["Ação","Murim","Drama"],themes:["Veneno","Vingança","Sobrevivência"],description:"Único sobrevivente de uma facção medicinal exterminada, Jin Ja-kang converte o veneno usado para torturá-lo em método marcial e arma de vingança.",sourceUrl:"https://tapas.io/series/legend-of-an-asura-the-poison-dragon/info",image:"legend-asura-poison-dragon-cover.jpg",width:400,height:600,credit:"Tapas / Dreamtoon"}),
  comic({id:"tales_demons_gods",slug:"tales-of-demons-and-gods",originalTitle:"妖神记",title:"Tales of Demons and Gods",romanized:"Yao Shen Ji",country:"China",start:"2015",credits:[{personId:"person_mad_snail",roles:["original-creator","writer"]}],genres:["Ação","Cultivo","Fantasia","Regressão"],themes:["Espíritos demoníacos","Segunda chance","Proteção"],description:"Nie Li retorna à adolescência com séculos de conhecimento e usa cultivo, alquimia e espíritos demoníacos para salvar sua cidade e reencontrar seu amor.",sourceUrl:"https://comics.inkr.com/title/480-tales-of-demons-and-gods",image:"tales-demons-gods-cover.webp",width:462,height:693,credit:"INKR / Ruohong Culture / Taxue Comics"}),
  comic({id:"soul_land_ii",slug:"soul-land-ii-the-unrivaled-tang-sect",originalTitle:"斗罗大陆II绝世唐门",title:"Soul Land II: The Unrivaled Tang Sect",romanized:"Douluo Dalu II: Jueshi Tangmen",country:"China",start:"2012",credits:[{personId:"person_tang_jia_san_shao",roles:["original-creator","writer"]}],genres:["Ação","Cultivo","Fantasia","Academia"],themes:["Espíritos marciais","Equipe","Romance"],description:"Huo Yuhao ingressa na Academia Shrek e desenvolve espíritos, anéis e fusões marciais ao lado de Wang Dong, numa parceria que muda de significado com o tempo.",sourceUrl:"https://comics.inkr.com/title/766-soul-land-ii-the-unrivaled-tang-sect",image:"soul-land-ii-cover.webp",width:462,height:693,credit:"INKR / Changsha Angel Culture / Magic Comic"}),
  comic({id:"star_martial_god_technique",slug:"star-martial-god-technique",originalTitle:"星武神诀",title:"Star Martial God Technique",romanized:"Xing Wu Shen Jue",country:"China",start:"2016",credits:[{personId:"person_fa_shu_de_woniu",roles:["original-creator","writer"]}],genres:["Ação","Cultivo","Artes marciais","Fantasia"],themes:["Técnicas estelares","Clãs","Ascensão"],description:"Ye Xinghe desperta uma rara técnica marcial estelar e usa seu crescimento para desafiar hierarquias, proteger o clã e aproximar-se de duas figuras centrais.",sourceUrl:"https://comics.inkr.com/title/239-star-martial-god-technique",image:"star-martial-god-technique-cover.webp",width:462,height:693,credit:"INKR / Ruohong Culture / Taxue Comic"}),
];
