import { z } from "zod";
import type { ReadingWork } from "./readingSchema";

export const ReadingListSchema = z.object({
  id: z.string().regex(/^reading_list_[a-z0-9_]+$/), slug: z.string().min(1), title: z.string().min(1), href: z.string().startsWith("/blog/"),
  items: z.array(z.object({ workId: z.string().regex(/^read_work_[a-z0-9_]+$/), position: z.number().int().positive().optional(), comment: z.string().min(1).optional(), justification: z.string().min(1).optional(), recommendedFor: z.string().min(1).optional(), startingPointEditionId: z.string().regex(/^read_edition_[a-z0-9_]+$/).optional(), readingOrder: z.string().min(1).optional(), note: z.string().min(1).optional() })),
});
export type ReadingList = z.infer<typeof ReadingListSchema>;
export const readingCurations: ReadingList[] = [ReadingListSchema.parse({id:"reading_list_vampire_books",slug:"melhores-livros-de-vampiro",title:"Melhores livros de vampiro",href:"/blog/melhores-livros-de-vampiro",items:[
 ["read_work_dracula","O eixo histórico incontornável, escolhido pela forma epistolar e pela tensão entre arquivo moderno e ameaça antiga."],
 ["read_work_carmilla","Condensa desejo, intimidade e ameaça décadas antes de Drácula e continua aberta a leituras queer."],
 ["read_work_i_am_legend","Transforma vampirismo em epidemia e altera radicalmente a pergunta sobre quem é o monstro."],
 ["read_work_interview_vampire","Devolve voz ao vampiro e faz imortalidade carregar memória, culpa, desejo e conflito familiar."],
 ["read_work_salem_lot","Atualiza o gótico como contágio de cidade pequena, sem fingir que a comunidade era saudável antes dos vampiros."],
 ["read_work_let_right_one_in","Cruza infância, bullying e exploração social num romance brutal que não romantiza facilmente seus vínculos."],
 ["read_work_fledgling","Reinventa a espécie vampírica para discutir raça, consentimento, simbiose e família escolhida."],
 ["read_work_gilda_stories","Imagina uma imortalidade negra e queer baseada em comunidade, reciprocidade e travessia histórica."],
 ["read_work_vampire_tapestry","Uma investigação psicológica e biológica do predador que evita tanto o aristocrata quanto o herói romântico."],
 ["read_work_fevre_dream","Usa o Mississippi escravista para colocar hierarquias vampíricas e humanas no mesmo campo moral."],
 ["read_work_sunshine","Fantasia urbana calorosa e estranha, atenta a trabalho, comida, trauma e alianças que não apagam diferenças."],
 ["read_work_certain_dark_things","Cria linhagens vampíricas locais e um noir mexicano atravessado por colonialidade e violência contemporânea."],
 ["read_work_route_ice_salt","Uma expansão mexicana, marítima e queer de poucas páginas do Drácula, formalmente concentrada e sensorial."],
 ["read_work_woman_eating","Traz o vampiro para a precariedade contemporânea e faz fome significar corpo, arte e pertencimento cultural."],
 ["read_work_southern_book_club","Sátira social em que o vampiro prospera porque machismo e racismo já organizam quem merece ser ouvido."],
 ["read_work_lesser_dead","Narrador não confiável, metrô de Nova York e crianças vampiras desmontam a autoconfiança do predador."],
 ["read_work_passage","Dá escala épica à epidemia sem perder o interesse por memória, comunidade e passagem do tempo."],
 ["read_work_historian","Faz bibliotecas, cartas e pesquisa histórica sustentarem um encontro lento e erudito com Drácula."],
 ["read_work_coldest_girl","A melhor entrada juvenil do recorte para pensar celebridade, transmissão e sedução como espetáculo público."],
 ["read_work_dowry_blood","Reescreve as companheiras de Drácula pelo ponto de vista de quem reconhece o romance como sistema de controle."],
 ["read_work_house_hunger","Fome aristocrática e trabalho corporal estruturam um gótico queer sobre classe e exploração."],
 ["read_work_vampires_norte","Une romance e horror histórico para materializar a violência colonial na fronteira entre México e Estados Unidos."],
 ["read_work_black_ambrosia","Uma road novel feroz que acompanha transformação feminina sem oferecer uma emancipação limpa."],
 ["read_work_vampire_junction","Sátira pop precoce sobre celebridade adolescente, consumo e um vampiro que virou mercadoria."],
 ["read_work_the_vampyre","Curto e historicamente decisivo: fixa o vampiro aristocrático na prosa inglesa antes dos romances mais conhecidos."],
 ["read_work_education_malice","Uma releitura acadêmica e queer de Carmilla que mostra a permanência do texto em novas disputas de desejo e autoria."],
].map(([workId,justification],index)=>({workId,position:index+1,justification}))})];
readingCurations.push(ReadingListSchema.parse({id:"reading_list_horror_by_reader",slug:"melhores-livros-de-terror",title:"Melhores livros de terror para diferentes tipos de leitor",href:"/blog/melhores-livros-de-terror",items:[
 ["read_work_shining","Para quem quer uma entrada narrativa e intensa: assombração, isolamento e violência familiar avançam juntos."],
 ["read_work_hill_house","Para descobrir como uma casa assombrada pode agir por arquitetura, linguagem e desejo de pertencimento."],
 ["read_work_rosemary_baby","Para leitores de paranoia cotidiana: o horror nasce quando instituições íntimas retiram de uma mulher o controle sobre o próprio corpo."],
 ["read_work_salem_lot","Para quem gosta de cidade pequena e contágio, com um mal sobrenatural apoiado por problemas comunitários preexistentes."],
 ["read_work_always_castle","Para quem prefere veneno psicológico, humor macabro e uma narradora cuja lógica protege e distorce o mundo."],
 ["read_work_turn_screw","Para leitores confortáveis com ambiguidade, repressão e fantasmas que talvez não aceitem uma explicação única."],
 ["read_work_frankenstein","Para chegar à raiz comum do gótico, da ficção científica e do horror corporal por responsabilidade, não apenas aparência monstruosa."],
 ["read_work_dracula","Para quem quer o grande arquivo do gótico vampírico, montado por cartas, diários, notícias e vozes em conflito."],
 ["read_work_carmilla","Para uma experiência gótica curta, íntima e atravessada por desejo queer sem eliminar ameaça ou ambivalência."],
 ["read_work_beloved","Para entender assombração como memória histórica: o sobrenatural torna presente aquilo que a escravidão tentou transformar em passado."],
 ["read_work_annihilation","Para quem busca horror cósmico ecológico e aceita que investigar também significa ser transformado pelo objeto da investigação."],
 ["read_work_fisherman","Para leitores pacientes de narrativas dentro de narrativas, luto e uma cosmologia que se abre lentamente sob a água."],
 ["read_work_ring","Para quem gosta de maldições com mecanismo claro, investigação e tecnologia funcionando como meio de contágio."],
 ["read_work_good_house","Para uma saga sobrenatural centrada em família negra, luto, comunidade e uma casa que guarda história demais."],
 ["read_work_only_good_indians","Para folk horror contemporâneo interessado em culpa, identidade Blackfeet e tradição viva, não em exotismo."],
 ["read_work_our_share_night","Para uma leitura longa em que ocultismo, ditadura argentina, poder econômico e herança familiar são inseparáveis."],
 ["read_work_mexican_gothic","Para quem quer mansão, fungos e horror corporal ligados a colonialismo, eugenia e linhagem."],
 ["read_work_tender_flesh","Para uma distopia corporal direta sobre consumo e desumanização; a violência exige estômago e leitura crítica."],
 ["read_work_cursed_bunny","Para experimentar contos sul-coreanos que misturam fábula, grotesco, humor e crítica ao patriarcado e ao capitalismo."],
 ["read_work_secret_dinner","Para conhecer horror corporal brasileiro de ritmo rápido, com canibalismo ligado a ambição, classe e mercado de luxo."],
 ["read_work_southern_book_club","Para uma sátira doméstica em que o vampiro depende de machismo e racismo para desacreditar quem reconhece o perigo."],
 ["read_work_reformatory","Para terror histórico em que fantasmas convivem com a violência institucional de um reformatório segregado."],
 ["read_work_ring_shout","Para uma novela veloz de horror cósmico e resistência negra que transforma a Klan em monstro sem reduzir racismo a metáfora."],
 ["read_work_i_am_legend","Para ficção científica pós-apocalíptica que usa o vampiro para inverter normalidade, ciência e definição de monstruosidade."],
 ["read_work_let_right_one_in","Para um terror social frio sobre infância, bullying, exploração e um vínculo que resiste a ser chamado apenas de amizade ou romance."],
].map(([workId,justification])=>({workId,justification}))}));
readingCurations.push(ReadingListSchema.parse({id:"reading_list_after_welcome_to_derry",slug:"livros-para-quem-gostou-de-it-bem-vindos-a-derry",title:"Melhores livros para quem gostou de It: Bem-Vindos a Derry",href:"/blog/livros-para-quem-gostou-de-it-bem-vindos-a-derry",items:[
 ["read_work_it","A matriz da curadoria: infância em grupo, retorno adulto, memória seletiva e uma cidade que colabora com o mal por hábito e silêncio."],
 ["read_work_salem_lot","Distribui a ameaça por uma cidade inteira e mostra que o monstro encontra relações comunitárias já fragilizadas."],
 ["read_work_institute","Concentra o olhar nas crianças e numa instituição adulta que chama violência de proteção e pesquisa."],
 ["read_work_summer_night","Leva um grupo de amigos por um verão de mal antigo e pequenas descobertas que tornam crescer uma forma de sobrevivência."],
 ["read_work_boys_life","Troca o horror frontal pela memória de infância, pelo crime e pela percepção de que uma cidade nunca é tão inocente quanto parecia."],
 ["read_work_something_wicked","Une dois meninos, uma pequena cidade e uma força itinerante capaz de explorar os desejos secretos de adultos e crianças."],
 ["read_work_imaginary_friend","Aproxima-se por desaparecimento infantil, bosque, cidade isolada e escala épica, embora siga uma cosmologia mais explícita."],
 ["read_work_chalk_man","Usa duas linhas temporais para perguntar como amigos adultos reorganizam um trauma de infância e suas responsabilidades."],
 ["read_work_chalk_pits","Parte de uma irmã desaparecida e de um retorno ao vilarejo onde a comunidade aprendeu a conviver com o inexplicável."],
 ["read_work_disappearance_devils_rock","Transforma o desaparecimento de um adolescente em investigação fragmentada sobre amizade, segredo e luto familiar."],
 ["read_work_black_mouth","Reúne amigos adultos marcados por um verão sobrenatural e interessados tanto no trauma quanto no confronto tardio."],
 ["read_work_saturday_night_ghost_club","Uma alternativa menor e mais melancólica sobre lendas locais, amadurecimento e o modo como trauma vira história de família."],
 ["read_work_clown_cornfield","Para quem quer o conflito geracional e a iconografia do palhaço convertidos num slasher veloz de cidade pequena."],
 ["read_work_good_house","Faz casa, família negra, luto e história comunitária sustentarem uma saga sobrenatural de grande escala."],
 ["read_work_reformatory","Mostra uma comunidade e uma instituição protegendo violência real enquanto crianças percebem também os mortos apagados."],
 ["read_work_only_good_indians","Relaciona uma transgressão de juventude ao retorno de uma força vingativa, sem usar comunidade indígena como cenário genérico."],
 ["read_work_bad_cree","Oferece uma resposta coletiva ao trauma: voltar para casa e reconstruir vínculos é parte do enfrentamento do sobrenatural."],
 ["read_work_let_right_one_in","Combina infância, bullying, abandono e violência comunitária num subúrbio em que o monstro nunca é o único perigo."],
 ["read_work_our_share_night","Amplia mal antigo e herança para décadas de história argentina, com poder familiar, político e ocultista no mesmo sistema."],
 ["read_work_hill_house","Troca a cidade pela casa, mas preserva a dúvida sobre memória, pertencimento e a colaboração entre lugar e vulnerabilidade."],
].map(([workId,justification])=>({workId,justification}))}));
readingCurations.push(ReadingListSchema.parse({id:"reading_list_vampire_comics",slug:"melhores-quadrinhos-mangas-de-vampiro",title:"Melhores quadrinhos e mangás de vampiro",href:"/blog/melhores-quadrinhos-mangas-de-vampiro",items:[
 ["read_work_tomb_dracula","A ponte histórica entre o Drácula literário, o terror seriado da Marvel e a criação de Blade."],
 ["read_work_poe_clan","Um marco do mangá shōjo que trata imortalidade como memória, perda e deslocamento através do tempo."],
 ["read_work_hellsing","Ação gótica maximalista cuja energia visual, humor ácido e violência transformam Alucard em arma institucional."],
 ["read_work_30_days_night","Uma premissa espacial perfeita e a arte abrasiva de Ben Templesmith devolvem ao vampiro sua função de predador."],
 ["read_work_american_vampire","Usa novas linhagens para atravessar a história dos Estados Unidos e suas formas mutáveis de poder."],
 ["read_work_baltimore","Aventura gótica de guerra e peste, construída como perseguição obsessiva por uma Europa alternativa."],
 ["read_work_happiness_manga","Horror corporal e adolescência vistos pela sensibilidade psicológica e pelo desenho inquieto de Shuzo Oshimi."],
 ["read_work_vanitas","Mistério gótico, ação e relações ambíguas numa Paris steampunk de composição visual muito própria."],
 ["read_work_call_night","Romance e comédia noturna que encontram liberdade, desejo e melancolia na vontade de virar vampiro."],
 ["read_work_vampire_knight","O melodrama shōjo de maior alcance do recorte, importante para romance, hierarquias e fantasia escolar vampírica."],
 ["read_work_vampeerz","Romance sáfico e humor sustentam uma leitura contemporânea sobre intimidade, amadurecimento e imortalidade."],
 ["read_work_unholy_blood","A entrada do webtoon coreano: ação vertical legível, heroína poderosa e romance dentro de uma guerra vampírica."],
 ["read_work_savage_shores","Desloca o vampiro europeu para a Índia colonial e recusa que ele seja a força mais antiga ou importante do território."],
 ["read_work_killadelphia","Terror social e investigação policial conectam vampiros às feridas raciais e políticas da história americana."],
 ["read_work_dracula_motherfucker","Uma graphic novel curta em que cor, ritmo e composição importam mais que reverência ao cânone de Drácula."],
 ["read_work_life_sucks","Comédia romântica de trabalho precário que troca castelos por turnos noturnos numa loja de conveniência."],
 ["read_work_fangs","Tiras mínimas e afetuosas sobre a rotina amorosa de uma vampira e um lobisomem."],
 ["read_work_little_vampire","Uma rota infantil inteligente e calorosa em que monstros, escola e amizade convivem sem cinismo."],
].map(([workId,justification],index)=>({workId,position:index+1,justification}))}));
readingCurations.push(ReadingListSchema.parse({id:"reading_list_horror_comics",slug:"melhores-quadrinhos-mangas-de-terror",title:"Melhores quadrinhos e mangás de terror",href:"/blog/melhores-quadrinhos-mangas-de-terror",items:[
 ["read_work_uzumaki","A porta de entrada mais clara para Junji Ito: uma ideia visual simples contamina corpos, arquitetura e uma cidade inteira."],
 ["read_work_locke_key","Terror sobrenatural narrativamente acessível, com família, luto e regras visuais que recompensam leitura longa."],
 ["read_work_infidel","Assombração e preconceito se alimentam dentro de um edifício, sem transformar islamofobia em mera metáfora."],
 ["read_work_hikaru_summer","Luto, desejo queer e presença sobrenatural sustentam um horror íntimo de interior rural."],
 ["read_work_black_hole","Horror corporal e adolescência encontram uma linguagem gráfica precisa para doença, sexo e exclusão."],
 ["read_work_happiness_manga","A transformação vampírica interessa principalmente como ruptura de corpo, desejo e identidade."],
 ["read_work_parasyte","Ficção científica corporal que combina ação, convivência impossível e uma pergunta ecológica ainda atual."],
 ["read_work_sweet_home_webtoon","O formato vertical serve ao confinamento e às criaturas moldadas pelos desejos dos moradores."],
 ["read_work_tomie","Repetição, violência de gênero e desejo formam um ciclo grotesco que resiste a explicações simples."],
 ["read_work_drifting_classroom","Uma escola deslocada vira laboratório cruel de sobrevivência, infância e colapso das instituições adultas."],
 ["read_work_from_hell","Terror histórico monumental sobre cidade, poder e fabricação do mito em torno de mulheres assassinadas."],
 ["read_work_carnica_blindagem","Um terror brasileiro inseparável do cangaço, da violência patriarcal e da paisagem sertaneja."],
 ["read_work_lua_negra","Gótico rural brasileiro em preto e branco, compacto e ligado à licantropia no Nordeste."],
 ["read_work_propria_carne","Antologia brasileira de horror histórico que liga Guerra do Paraguai, corpo e mal ancestral."],
 ["read_work_tres_buracos","Uma experiência brasileira fragmentada em que montagem, silêncio e memória produzem desconforto."],
 ["read_work_nice_house_lake","Horror cósmico contemporâneo construído pelo contraste entre apocalipse, amizade e conforto controlado."],
 ["read_work_gideon_falls","Montagem radical e arquitetura impossível conectam obsessão, religião e múltiplas realidades."],
 ["read_work_ptsd_radio","Fragmentos mínimos e imagens abruptas criam uma frequência assombrada sem explicação estabilizadora."],
 ["read_work_dracula_motherfucker","Uma experiência curta em que cor psicodélica e composição têm mais importância que fidelidade a Drácula."],
 ["read_work_savage_shores","Terror histórico anticolonial que desloca o vampiro europeu do centro do mundo."],
 ["read_work_30_days_night","Cerco vampírico direto cuja arte abrasiva torna predadores e noite polar quase materiais."],
 ["read_work_hellsing","Ação gótica extrema escolhida pela invenção gráfica e pelo humor ácido, não apenas pelo grau de violência."],
 ["read_work_homunculus","Terror psicológico desconfortável sobre percepção e identidade, com temas que exigem leitura crítica."],
 ["read_work_american_vampire","Terror histórico serializado que usa linhagens monstruosas para atravessar mudanças de poder nos Estados Unidos."],
].map(([workId,justification])=>({workId,justification}))}));
readingCurations.push(ReadingListSchema.parse({id:"reading_list_romance_manga_men",slug:"melhores-mangas-de-romance-para-homens",title:"Melhores mangás de romance para homens que querem começar",href:"/blog/melhores-mangas-de-romance-para-homens",items:[
 ["read_work_blue_box","Para quem vem de mangás esportivos: treino, ambição e romance avançam com a mesma disciplina narrativa."],
 ["read_work_kaguya_sama","Para começar pelo humor estratégico e descobrir gradualmente vulnerabilidade, comunicação e amadurecimento."],
 ["read_work_horimiya","Um namoro que começa relativamente cedo permite acompanhar intimidade, amigos e inseguranças além da conquista."],
 ["read_work_insomniacs","Romance calmo e realista construído por noites compartilhadas, saúde e confiança, sem jogos artificiais."],
 ["read_work_wotakoi","Adultos trabalhando e namorando sem abandonar videogames, mangás ou dificuldades de comunicação."],
 ["read_work_sweat_soap","Uma premissa excêntrica evolui para relação adulta atenta a limites, corpo e decisões cotidianas."],
 ["read_work_solanin","Para leitores de ficção adulta sobre trabalho, música, luto e o que um casal faz com futuros incertos."],
 ["read_work_nodame","Comédia e parceria entre músicos em que carreira e vocação nunca viram simples obstáculos românticos."],
 ["read_work_skip_loafer","Amizades e amadurecimento importam tanto quanto romance, com personagens tratados sem cinismo."],
 ["read_work_sign_affection","Uma história universitária sobre comunicação e curiosidade que não reduz a protagonista surda a lição."],
 ["read_work_nana","Drama adulto sobre amizade, desejo e dependência; indicado a quem aceita relações falhas e ausência de conclusão."],
 ["read_work_fruits_basket","Fantasia e romance usados para enfrentar trauma familiar e ciclos de abuso, não para escapar deles."],
 ["read_work_my_love_story","Comédia shōjo com protagonista masculino que questiona autoimagem sem ridicularizar gentileza ou afeto."],
 ["read_work_given","Música, luto e romance entre rapazes para quem busca drama emocional sem separar criação de intimidade."],
 ["read_work_bloom_into_you","Romance sáfico reflexivo sobre expectativas e formas diferentes de reconhecer o amor."],
 ["read_work_dress_up_darling","Trabalho criativo compartilhado aproxima dois adolescentes; o fanservice exige tolerância, mas não define toda a relação."],
 ["read_work_maison_ikkoku","Um clássico longo sobre luto e amadurecimento, com humor de época e evolução afetiva gradual."],
 ["read_work_call_night","Fantasia noturna e comédia para quem prefere chegar ao romance por atmosfera, liberdade e sobrenatural."],
 ["read_work_vampeerz","Romance sáfico com vampiros que combina humor, desejo e aventura sem esconder sua proposta afetiva."],
].map(([workId,justification])=>({workId,justification}))}));
export function resolveReadingList(list: ReadingList, works: readonly ReadingWork[]) { const byId = new Map(works.map((work) => [work.id, work])); return list.items.map((item) => byId.get(item.workId)).filter((work): work is ReadingWork => Boolean(work)); }
