import type { ReadingEdition, ReadingSeries, ReadingWork } from "./readingSchema";

const checked="2026-08-24";
const sources=(title:string,url:string)=>[{title,url}];
const series=(id:string,title:string,summary:string,url:string,status:ReadingSeries["publicationStatus"]="completed"):ReadingSeries=>({id:`read_series_${id}`,slug:id.replaceAll("_","-"),aliases:[],title,summary,kind:"narrative",publicationStatus:status,status:"published",sources:sources(`${title} — editora`,url),createdAt:checked,updatedAt:checked});
const work=(id:string,slug:string,title:string,year:string,country:string,personId:string,genres:string[],themes:string[],description:string,url:string,seriesId?:string,position?:number):ReadingWork=>({id:`read_work_${id}`,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle:title,format:"book",originCountries:[country],originalLanguages:["Inglês"],credits:[{personId,roles:["author"]}],organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["fiction"],genres,themes,demographics:["adult"],shortDescription:description,seriesMemberships:seriesId?[{seriesId:`read_series_${seriesId}`,position}]:[],relatedWorks:[],adaptations:[],sources:sources(`${title} — editora`,url),status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked});
const edition=(id:string,workId:string,title:string,publisherId:string,date:string,isbn13:string,pages:number,url:string):ReadingEdition=>({id:`read_edition_${id}`,workId:`read_work_${workId}`,title,publisherId,country:"Estados Unidos",language:"Inglês",medium:"paperback",publicationDate:date,isbn13,pageCount:pages,availabilityStatus:"unknown",status:"published",sources:sources(`${title} — edição verificada`,url),translationCredits:[],createdAt:checked,updatedAt:checked});

export const darkFantasySeries:ReadingSeries[]=[
  series("first_law_trilogy","The First Law Trilogy","Trilogia grimdark sobre guerra, poder e personagens que raramente correspondem aos papéis heroicos que imaginam ocupar.","https://www.hachettebookgroup.com/titles/joe-abercrombie/the-first-law-trilogy/9780316361194/"),
  series("broken_empire","The Broken Empire","Trilogia de fantasia sombria e pós-apocalíptica acompanhando a ascensão violenta de Jorg Ancrath.","https://www.penguinrandomhouse.com/books/308315/prince-of-thorns-by-mark-lawrence/paperback/"),
  series("black_company","Chronicles of the Black Company","Série de fantasia militar narrada pelos cronistas de uma companhia mercenária que serve poderes moralmente indefensáveis.","https://us.macmillan.com/series/chroniclesoftheblackcompany","ongoing"),
];

export const darkFantasyWorks:ReadingWork[]=[
  work("blade_itself","the-blade-itself","The Blade Itself","2006","Reino Unido","person_joe_abercrombie",["Fantasia sombria","Grimdark","Fantasia épica"],["Guerra","Tortura","Ambiguidade moral","Política"],"Um bárbaro cansado, um nobre vaidoso e um inquisidor mutilado convergem enquanto guerras e planos de um antigo mago reorganizam a União.","https://www.hachettebookgroup.com/titles/joe-abercrombie/the-blade-itself/9780316609821/","first_law_trilogy",1),
  work("before_hanged","before-they-are-hanged","Before They Are Hanged","2007","Reino Unido","person_joe_abercrombie",["Fantasia sombria","Grimdark","Fantasia militar"],["Cerco","Guerra","Ruínas","Traição"],"A guerra divide o elenco entre um cerco, uma campanha desastrosa e uma expedição às ruínas do passado.","https://www.hachettebookgroup.com/titles/joe-abercrombie/before-they-are-hanged/9780316610032/","first_law_trilogy",2),
  work("last_argument_kings","last-argument-of-kings","Last Argument of Kings","2008","Reino Unido","person_joe_abercrombie",["Fantasia sombria","Grimdark","Fantasia épica"],["Guerra","Poder","Revolta","Consequências"],"Guerras externas e disputas pela sucessão obrigam os personagens a pagar pelo poder que perseguiram.","https://www.hachettebookgroup.com/titles/joe-abercrombie/last-argument-of-kings/9780316610070/","first_law_trilogy",3),
  work("prince_thorns","prince-of-thorns","Prince of Thorns","2011","Reino Unido","person_mark_lawrence",["Fantasia sombria","Grimdark","Fantasia pós-apocalíptica"],["Vingança","Crueldade","Magia","Ruínas"],"Um príncipe adolescente lidera saqueadores e retorna ao castelo do pai decidido a conquistar pela violência aquilo que considera seu.","https://www.penguinrandomhouse.com/books/308315/prince-of-thorns-by-mark-lawrence/paperback/","broken_empire",1),
  work("king_thorns","king-of-thorns","King of Thorns","2012","Reino Unido","person_mark_lawrence",["Fantasia sombria","Grimdark","Fantasia pós-apocalíptica"],["Cerco","Estratégia","Trauma","Tecnologia antiga"],"Já no trono, Jorg precisa defender um reino pequeno usando memória, manipulação e artefatos que parecem mágicos.","https://www.penguinrandomhouse.com/books/308316/king-of-thorns-by-mark-lawrence/paperback/","broken_empire",2),
  work("emperor_thorns","emperor-of-thorns","Emperor of Thorns","2013","Reino Unido","person_mark_lawrence",["Fantasia sombria","Grimdark","Fantasia pós-apocalíptica"],["Império","Política","Mortos","Ambição"],"Jorg procura tornar-se imperador enquanto forças sobrenaturais e vestígios do passado ameaçam consumir o mundo que deseja governar.","https://www.penguinrandomhouse.com/books/308317/emperor-of-thorns-by-mark-lawrence/paperback/","broken_empire",3),
  work("black_company_book","the-black-company","The Black Company","1984","Estados Unidos","person_glen_cook",["Fantasia sombria","Grimdark","Fantasia militar"],["Mercenários","Guerra","Necromancia","Lealdade"],"Os registros de um médico acompanham uma companhia mercenária contratada por uma soberana e seus servos sobrenaturais.","https://us.macmillan.com/books/9781250781208/theblackcompany/","black_company",1),
  work("shadows_linger","shadows-linger","Shadows Linger","1984","Estados Unidos","person_glen_cook",["Fantasia sombria","Fantasia militar","Horror fantástico"],["Corrupção","Cerco","Mercenários","Monstros"],"A Companhia descobre que a figura capaz de desafiar sua empregadora pode estar sob sua própria proteção.","https://us.macmillan.com/books/9781466831100/shadowslinger/","black_company",2),
  work("white_rose","the-white-rose-glen-cook","The White Rose","1985","Estados Unidos","person_glen_cook",["Fantasia sombria","Fantasia militar","Horror fantástico"],["Rebelião","Magia","Tiranos","Lealdade"],"A Companhia precisa escolher entre contratos, sobrevivência e uma rebelião contra poderes que tratavam como inevitáveis.","https://us.macmillan.com/series/chroniclesoftheblackcompany","black_company",3),
  work("between_two_fires","between-two-fires-christopher-buehlman","Between Two Fires","2012","Estados Unidos","person_christopher_buehlman",["Fantasia sombria","Horror histórico","Horror religioso"],["Peste Negra","Demônios","Redenção","Monstros"],"Durante a Peste Negra, um cavaleiro desacreditado escolta uma menina por uma França onde a epidemia acompanha uma guerra sobrenatural.","https://us.macmillan.com/books/9781250439208/betweentwofires/"),
  work("perdido_street_station","perdido-street-station","Perdido Street Station","2000","Reino Unido","person_china_mieville",["Fantasia sombria","New Weird","Horror fantástico"],["Cidade industrial","Monstros","Corrupção","Ciência e magia"],"Uma pesquisa clandestina liberta predadores capazes de devastar a cidade industrial e autoritária de New Crobuzon.","https://www.penguinrandomhouse.com/books/114262/perdido-street-station-by-china-mieville/"),
  work("library_mount_char","the-library-at-mount-char","The Library at Mount Char","2015","Estados Unidos","person_scott_hawkins",["Fantasia sombria","Horror fantástico","Fantasia contemporânea"],["Família abusiva","Conhecimento","Divindade","Violência"],"Após o desaparecimento do homem que os criou como discípulos, filhos adotivos com conhecimentos impossíveis disputam acesso à biblioteca dele.","https://www.penguinrandomhouse.com/books/240942/the-library-at-mount-char-by-scott-hawkins/"),
];

export const darkFantasyEditions:ReadingEdition[]=[
  edition("blade_itself_orbit","blade_itself","The Blade Itself","org_little_brown","2015-09-08","9780316387316",542,"https://openlibrary.org/isbn/9780316387316"),
  edition("before_hanged_orbit","before_hanged","Before They Are Hanged","org_little_brown","2015-09-15","9780316387354",560,"https://openlibrary.org/isbn/9780316387354"),
  edition("last_argument_pyr","last_argument_kings","Last Argument of Kings","org_prometheus_books","2008-09-01","9781591026907",639,"https://openlibrary.org/books/OL24981613M"),
  edition("prince_thorns_ace","prince_thorns","Prince of Thorns","org_penguin_publishing_group","2012-07-31","9781937007683",336,"https://www.penguinrandomhouse.com/books/308315/prince-of-thorns-by-mark-lawrence/paperback/"),
  edition("king_thorns_ace","king_thorns","King of Thorns","org_penguin_publishing_group","2013-07-30","9780425256237",432,"https://www.penguinrandomhouse.com/books/308316/king-of-thorns-by-mark-lawrence/paperback/"),
  edition("emperor_thorns_ace","emperor_thorns","Emperor of Thorns","org_penguin_publishing_group","2014-05-27","9780425256541",416,"https://www.penguinrandomhouse.com/books/308317/emperor-of-thorns-by-mark-lawrence/paperback/"),
  edition("black_company_tor","black_company_book","The Black Company","org_macmillan","1992-03-01","9780812521399",320,"https://openlibrary.org/isbn/9780812521399"),
  edition("shadows_linger_tor","shadows_linger","Shadows Linger","org_macmillan","1990-04-01","9780812508420",319,"https://openlibrary.org/books/OL24931266M"),
  edition("white_rose_tor","white_rose","The White Rose","org_macmillan","1992-08-15","9780812521412",304,"https://openlibrary.org/isbn/9780812521412"),
  edition("between_fires_ace","between_two_fires","Between Two Fires","org_penguin_publishing_group","2013-09-03","9780425256909",464,"https://openlibrary.org/books/OL26788197M"),
  edition("perdido_del_rey","perdido_street_station","Perdido Street Station","org_penguin_publishing_group","2001-02-27","9780345443021",752,"https://www.penguinrandomhouse.com/books/114262/perdido-street-station-by-china-mieville/"),
  edition("library_mount_crown","library_mount_char","The Library at Mount Char","org_penguin_publishing_group","2016-03-15","9780553418620",400,"https://www.penguinrandomhouse.com/books/240942/the-library-at-mount-char-by-scott-hawkins/"),
];
