import type { ReadingWork } from "./readingSchema";

const checked="2026-09-02";
const src=(title:string,author:string)=>({title:`${title} — registro bibliográfico`,url:`https://openlibrary.org/search?q=${encodeURIComponent(title)}&author=${encodeURIComponent(author)}`});
const work=(id:string,slug:string,title:string,titleBr:string|undefined,year:string,credits:ReadingWork["credits"],difficulty:ReadingWork["readingDifficulty"],concepts:string[],description:string,extra:Partial<ReadingWork>={}):ReadingWork=>({id:`read_work_${id}`,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle:title,titleBr,workType:"book",format:"book",originCountries:["Estados Unidos"],originalLanguages:["Inglês"],credits,organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["non-fiction"],genres:["Economia"],themes:concepts,concepts,readingDifficulty:difficulty,demographics:["adult"],audienceProfile:"Leitores sem formação em economia que procuram compreender conceitos, evidências e controvérsias sem aderir antecipadamente a uma escola.",shortDescription:description,seriesMemberships:[],relatedWorks:[],adaptations:[],sources:[src(title,credits[0].personId.replace("person_","").replaceAll("_"," "))],status:"draft",createdAt:checked,updatedAt:checked,...extra});

export const economicsWorks:ReadingWork[]=[
  work("economy_core","a-economia-core","The Economy: Economics for a Changing World","A Economia","2017",[{personId:"person_samuel_bowles",roles:["author"]},{personId:"person_wendy_carlin",roles:["author"]},{personId:"person_margaret_stevens",roles:["author"]}],"introductory",["Escassez","Incentivos","Mercados","Trabalho","Políticas públicas"],"Manual aberto organiza economia por problemas reais, modelos, dados e instituições, combinando decisões individuais com desigualdade, ambiente e poder."),
  work("economics_user_guide","economia-modo-de-usar","Economics: The User's Guide","Economia: Modo de Usar","2014",[{personId:"person_ha_joon_chang",roles:["author"]}],"introductory",["Escolas econômicas","Produção","Trabalho","Desenvolvimento"],"Chang apresenta diferentes tradições econômicas e mostra como cada uma ilumina e omite aspectos distintos da produção e da vida social."),
  work("undercover_economist","o-economista-clandestino","The Undercover Economist","O Economista Clandestino","2005",[{personId:"person_tim_harford",roles:["author"]}],"introductory",["Preços","Escassez","Incentivos","Informação","Externalidades"],"Situações cotidianas introduzem preços, poder de mercado, informação imperfeita, externalidades e comércio com linguagem acessível."),
  work("money_goldstein","money-true-story-made-up-thing","Money: The True Story of a Made-Up Thing",undefined,"2020",[{personId:"person_jacob_goldstein",roles:["author"]}],"introductory",["Moeda","Bancos","Crédito","Padrão-ouro","Criptomoedas"],"Goldstein acompanha formas históricas de dinheiro para explicar confiança, crédito, bancos e por que moeda é uma instituição, não apenas um objeto."),
  work("return_depression_economics","a-crise-de-2008-e-a-economia-da-depressao","The Return of Depression Economics and the Crisis of 2008","A Crise de 2008 e a Economia da Depressão","2008",[{personId:"person_paul_krugman",roles:["author"]}],"intermediate",["Recessão","Demanda agregada","Crises cambiais","Liquidez"],"Krugman conecta crises financeiras, insuficiência de demanda e respostas macroeconômicas, com foco no caminho até 2008."),
  work("why_nations_fail","por-que-as-nacoes-fracassam","Why Nations Fail","Por Que as Nações Fracassam","2012",[{personId:"person_daron_acemoglu",roles:["author"]},{personId:"person_james_a_robinson",roles:["author"]}],"introductory",["Instituições","Poder","Desenvolvimento","Estado"],"Acemoglu e Robinson atribuem trajetórias de desenvolvimento à disputa entre instituições inclusivas e extrativas e à distribuição de poder."),
  work("great_transformation","a-grande-transformacao","The Great Transformation","A Grande Transformação","1944",[{personId:"person_karl_polanyi",roles:["author"]}],"advanced",["Mercados","Estado","Trabalho","Terra","Proteção social"],"Polanyi interpreta a expansão dos mercados autorregulados e as reações sociais e políticas que tentaram limitar seus efeitos destrutivos."),
  work("formacao_economica_brasil","formacao-economica-do-brasil","Formação Econômica do Brasil","Formação Econômica do Brasil","1959",[{personId:"person_celso_furtado",roles:["author"]}],"intermediate",["Colonização","Exportação","Industrialização","Desigualdade regional"],"Furtado interpreta a formação econômica brasileira por ciclos produtivos, trabalho escravizado, mercado interno, industrialização e desigualdades regionais.",{originCountries:["Brasil"],originalLanguages:["Português"]}),
  work("poor_economics","a-economia-dos-pobres","Poor Economics","A Economia dos Pobres","2011",[{personId:"person_abhijit_banerjee",roles:["author"]},{personId:"person_esther_duflo",roles:["author"]}],"introductory",["Pobreza","Saúde","Educação","Crédito","Experimentos"],"Banerjee e Duflo usam estudos de campo para examinar decisões e políticas ligadas a saúde, educação, crédito e pobreza."),
  work("capital_21_century","o-capital-no-seculo-xxi","Capital in the Twenty-First Century","O Capital no Século XXI","2013",[{personId:"person_thomas_piketty",roles:["author"]}],"advanced",["Renda","Patrimônio","Desigualdade","Tributação"],"Piketty reúne séries históricas para investigar concentração de renda e patrimônio e discutir mecanismos políticos de redistribuição."),
  work("globalization_discontents","a-globalizacao-e-seus-maleficios","Globalization and Its Discontents","A Globalização e Seus Malefícios","2002",[{personId:"person_joseph_stiglitz",roles:["author"]}],"intermediate",["Comércio","FMI","Crises","Desenvolvimento"],"Stiglitz critica a condução institucional da globalização e programas padronizados de liberalização aplicados a economias em condições distintas."),
  work("manias_panics_crashes","manias-panicos-e-crises","Manias, Panics, and Crashes","Manias, Pânicos e Crises","1978",[{personId:"person_charles_kindleberger",roles:["author"]},{personId:"person_robert_aliber",roles:["author"]}],"intermediate",["Bolhas","Crédito","Pânico","Contágio","Emprestador de última instância"],"Uma história comparada de euforia, expansão de crédito, reversão de expectativas, pânico e contágio em crises financeiras."),
  work("this_time_different","desta-vez-e-diferente","This Time Is Different","Desta Vez É Diferente","2009",[{personId:"person_carmen_reinhart",roles:["author"]},{personId:"person_kenneth_rogoff",roles:["author"]}],"advanced",["Dívida","Crises bancárias","Inflação","Calotes"],"Reinhart e Rogoff compilam episódios históricos de crises bancárias, dívida soberana, inflação e calotes para identificar recorrências e diferenças."),
  work("good_economics_hard_times","boa-economia-para-tempos-dificeis","Good Economics for Hard Times","Boa Economia para Tempos Difíceis","2019",[{personId:"person_abhijit_banerjee",roles:["author"]},{personId:"person_esther_duflo",roles:["author"]}],"introductory",["Migração","Comércio","Crescimento","Clima","Políticas públicas"],"Os autores revisam evidências sobre debates econômicos contemporâneos e mostram onde resultados são mais incertos do que slogans sugerem."),
  work("deficit_myth","o-mito-do-deficit","The Deficit Myth","O Mito do Déficit","2020",[{personId:"person_stephanie_kelton",roles:["author"]}],"intermediate",["Moeda soberana","Déficit público","Inflação","Emprego"],"Kelton apresenta a Teoria Monetária Moderna e argumenta que, para emissores soberanos de moeda, inflação e recursos são limites mais relevantes que analogias domésticas."),
];
