import type { ReadingEdition, ReadingSeries, ReadingWork } from "./readingSchema";

const checked="2026-08-24";
const source=(title:string,url:string)=>[{title,url}];
const book=(id:string,slug:string,title:string,titleBr:string|undefined,year:string,country:string,personId:string,genres:string[],themes:string[],description:string,url:string,seriesMemberships:ReadingWork["seriesMemberships"]=[]):ReadingWork=>({id:`read_work_${id}`,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle:title,titleBr,format:"book",originCountries:[country],originalLanguages:["Inglês"],credits:[{personId,roles:["author"]}],organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["fiction"],genres,themes,demographics:["adult"],shortDescription:description,seriesMemberships,relatedWorks:[],adaptations:[],sources:source(`${title} — editora`,url),status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked});
const series=(id:string,title:string,summary:string,url:string,publicationStatus:ReadingSeries["publicationStatus"]="completed"):ReadingSeries=>({id:`read_series_${id}`,slug:id.replaceAll("_","-"),aliases:[],title,summary,kind:"narrative",publicationStatus,status:"published",sources:source(`${title} — editora`,url),createdAt:checked,updatedAt:checked});
const edition=(id:string,workId:string,title:string,publisherId:string,medium:ReadingEdition["medium"],date:string,isbn13:string,pages:number,url:string):ReadingEdition=>({id:`read_edition_${id}`,workId:`read_work_${workId}`,title,publisherId,country:"Estados Unidos",language:"Inglês",medium,publicationDate:date,isbn13,pageCount:pages,availabilityStatus:"unknown",status:"published",sources:source(`${title} — edição verificada`,url),translationCredits:[],createdAt:checked,updatedAt:checked});

export const fantasyRomanceSeries:ReadingSeries[]=[
  series("kushiels_legacy","Kushiel's Legacy","Saga de fantasia política em Terre d'Ange, acompanhando espionagem, religião, desejo e relações que atravessam conflitos de Estado.","https://us.macmillan.com/books/9781250213068/kushielsdart/"),
  series("sevenwaters","Sevenwaters","Saga de fantasia histórica inspirada em mitos celtas, organizada em torno de família, magia feérica, sacrifício e vínculos amorosos.","https://us.macmillan.com/books/9781250238665/daughteroftheforest/"),
  series("burning_kingdoms","The Burning Kingdoms","Trilogia épica inspirada na história e nos épicos da Índia, com império, magia vegetal, rebelião e romance sáfico.","https://www.hachettebookgroup.com/titles/tasha-suri/the-jasmine-throne/9780316538510/"),
  series("empyrean","The Empyrean","Série de romantasy militar sobre cavaleiros de dragão, guerra, segredos de Estado e relações formadas sob competição letal.","https://www.entangledpublishing.com/books/fourth-wing","ongoing"),
];

export const fantasyRomanceWorks:ReadingWork[]=[
  book("kushiels_dart","kushiels-dart","Kushiel's Dart",undefined,"2001","Estados Unidos","person_jacqueline_carey",["Fantasia épica","Fantasia política","Romance"],["Espionagem","Religião","BDSM","Guerra"],"Uma cortesã treinada como espiã descobre uma conspiração contra Terre d'Ange e constrói uma relação difícil com o guerreiro celibatário encarregado de protegê-la.","https://us.macmillan.com/books/9781250213068/kushielsdart/",[{seriesId:"read_series_kushiels_legacy",position:1}]),
  book("daughter_forest","daughter-of-the-forest","Daughter of the Forest","A Filha da Floresta","1999","Austrália","person_juliet_marillier",["Fantasia histórica","Conto de fadas","Romance"],["Mitologia celta","Família","Maldição","Slow burn"],"Sorcha precisa permanecer em silêncio e cumprir uma tarefa dolorosa para libertar seis irmãos enfeitiçados, mesmo quando é levada para a terra dos inimigos e se apaixona.","https://us.macmillan.com/books/9781250238665/daughteroftheforest/",[{seriesId:"read_series_sevenwaters",position:1}]),
  book("tress_emerald_sea","tress-of-the-emerald-sea","Tress of the Emerald Sea","Tress, a Garota do Mar Esmeralda","2023","Estados Unidos","person_brandon_sanderson",["Fantasia","Aventura","Romance"],["Piratas","Cosmere","Magia de esporos","Resgate"],"Tress abandona uma ilha segura e atravessa oceanos de esporos mortais para resgatar Charlie, aprendendo navegação, liderança e magia durante a viagem.","https://us.macmillan.com/books/9781250899651/tressoftheemeraldsea/"),
  book("uprooted","uprooted-naomi-novik","Uprooted","Enraizados","2015","Estados Unidos","person_naomi_novik",["Fantasia sombria","Conto de fadas","Romance"],["Floresta corrompida","Magia","Mestre e aprendiz","Guerra"],"Agnieszka é escolhida por um mago recluso para servi-lo por dez anos e descobre uma magia incompatível com a dele enquanto uma floresta corrompida avança.","https://www.penguinrandomhouse.com/books/236925/uprooted-by-naomi-novik/9780804179041/"),
  book("jasmine_throne","the-jasmine-throne","The Jasmine Throne","O Trono de Jasmim","2021","Reino Unido","person_tasha_suri",["Fantasia épica","Fantasia política","Romance sáfico"],["Império","Rebelião","Magia vegetal","Identidade"],"Uma princesa aprisionada e uma criada com magia proibida tornam-se aliadas, amantes e forças políticas com projetos nem sempre compatíveis para o império.","https://www.hachettebookgroup.com/titles/tasha-suri/the-jasmine-throne/9780316538510/",[{seriesId:"read_series_burning_kingdoms",position:1}]),
  book("night_circus","the-night-circus","The Night Circus","O Circo da Noite","2011","Estados Unidos","person_erin_morgenstern",["Fantasia histórica","Romance","Realismo mágico"],["Circo","Duelo mágico","Atmosfera","Amor proibido"],"Dois magos treinados desde a infância para um duelo prolongado se apaixonam dentro de um circo noturno construído como campo de competição.","https://www.penguinrandomhouse.com/books/211964/the-night-circus-by-erin-morgenstern/"),
  book("fourth_wing","fourth-wing","Fourth Wing","Quarta Asa","2023","Estados Unidos","person_rebecca_yarros",["Romantasy","Fantasia militar","Romance"],["Dragões","Academia militar","Rivais","Guerra"],"Violet entra à força numa academia letal de cavaleiros de dragão e se aproxima de Xaden enquanto treinamento, conspiração militar e vínculo dracônico redefinem sua sobrevivência.","https://www.entangledpublishing.com/books/fourth-wing",[{seriesId:"read_series_empyrean",position:1}]),
];

export const fantasyRomanceEditions:ReadingEdition[]=[
  edition("kushiels_dart_tor","kushiels_dart","Kushiel's Dart","org_macmillan","hardcover","2001-06-15","9780312872380",704,"https://openlibrary.org/isbn/9780312872380"),
  edition("daughter_forest_tor","daughter_forest","Daughter of the Forest","org_macmillan","paperback","2020-04-21","9781250238665",416,"https://us.macmillan.com/books/9781250238665/daughteroftheforest/"),
  edition("tress_emerald_tor","tress_emerald_sea","Tress of the Emerald Sea","org_macmillan","hardcover","2023-04-04","9781250899651",384,"https://us.macmillan.com/books/9781250899651/tressoftheemeraldsea/"),
  edition("uprooted_del_rey","uprooted","Uprooted","org_penguin_publishing_group","paperback","2016-03-01","9780804179058",480,"https://www.penguinrandomhouse.com/books/236925/uprooted-by-naomi-novik/9780804179041/"),
  edition("jasmine_throne_orbit","jasmine_throne","The Jasmine Throne","org_little_brown","paperback","2021-06-08","9780316538510",576,"https://www.hachettebookgroup.com/titles/tasha-suri/the-jasmine-throne/9780316538510/"),
  edition("night_circus_vintage","night_circus","The Night Circus","org_penguin_publishing_group","paperback","2012-07-03","9780307744432",528,"https://www.penguinrandomhouse.com/books/211964/the-night-circus-by-erin-morgenstern/"),
  edition("fourth_wing_red_tower","fourth_wing","Fourth Wing","org_entangled_publishing","hardcover","2023-05-02","9781649374042",512,"https://www.entangledpublishing.com/books/fourth-wing"),
];
