import type { ReadingWork } from "./readingSchema";

const checked = "2026-09-02";
const source = (title:string, author:string) => ({title:`${title} — registro bibliográfico`,url:`https://openlibrary.org/search?q=${encodeURIComponent(title)}&author=${encodeURIComponent(author)}`});
const work = (id:string,slug:string,title:string,titleBr:string|undefined,year:string,credits:ReadingWork["credits"],concepts:string[],description:string):ReadingWork => ({
  id:`read_work_${id}`,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle:title,titleBr,workType:"book",format:"book",originCountries:["Estados Unidos"],originalLanguages:["Inglês"],credits,organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["non-fiction"],genres:["Divulgação científica","Formação intelectual"],themes:concepts,concepts,readingDifficulty:"introductory",demographics:["adult"],audienceProfile:"Leitores iniciantes que procuram desenvolver uma capacidade intelectual específica com contexto e exercícios de interpretação.",shortDescription:description,seriesMemberships:[],relatedWorks:[],adaptations:[],sources:[source(title,credits[0].personId.replace("person_","").replaceAll("_"," "))],status:"draft",createdAt:checked,updatedAt:checked,
});

export const intellectualFormationWorks:ReadingWork[] = [
  work("how_not_wrong","how-not-to-be-wrong","How Not to Be Wrong: The Power of Mathematical Thinking","O Poder do Pensamento Matemático","2014",[{personId:"person_jordan_ellenberg",roles:["author"]}],["Modelagem","Proporção","Probabilidade","Raciocínio quantitativo"],"Ellenberg mostra como ideias matemáticas ajudam a modelar situações, comparar grandezas e reconhecer conclusões quantitativas enganosas."),
  work("art_statistics","a-arte-da-estatistica","The Art of Statistics: Learning from Data","A Arte da Estatística","2019",[{personId:"person_david_spiegelhalter",roles:["author"]}],["Incerteza","Distribuições","Correlação","Causalidade","Risco"],"Spiegelhalter introduz o raciocínio com dados por perguntas concretas, distinguindo descrição, inferência, incerteza e comunicação de risco."),
  work("demon_haunted_world","o-mundo-assombrado-pelos-demonios","The Demon-Haunted World: Science as a Candle in the Dark","O Mundo Assombrado pelos Demônios","1995",[{personId:"person_carl_sagan",roles:["author"]}],["Método científico","Evidência","Ceticismo","Pseudociência"],"Sagan discute como avaliar alegações extraordinárias, comparar explicações e preservar abertura intelectual sem abandonar padrões de evidência."),
  work("landscape_history","a-paisagem-da-historia","The Landscape of History: How Historians Map the Past","Paisagens da História","2002",[{personId:"person_john_lewis_gaddis",roles:["author"]}],["Causalidade histórica","Escala","Evidência","Interpretação"],"Gaddis explica como historiadores relacionam evidências, causalidade, escalas temporais e narrativas sem tratar o passado como experimento repetível."),
  work("how_read_literature","como-ler-literatura","How to Read Literature","Como Ler Literatura","2013",[{personId:"person_terry_eagleton",roles:["author"]}],["Forma literária","Narrador","Ambiguidade","Interpretação"],"Eagleton apresenta ferramentas para observar tom, narrativa, personagem, abertura e valor literário sem reduzir leitura a uma mensagem escondida."),
  work("style_clarity_grace","style-lesson-clarity-grace","Style: Lessons in Clarity and Grace",undefined,"1981",[{personId:"person_joseph_m_williams",roles:["author"]},{personId:"person_joseph_bizup",roles:["author"]}],["Clareza","Coesão","Ênfase","Revisão"],"Um guia de revisão que relaciona estrutura das frases, continuidade entre ideias, escolha de sujeitos e ênfase ao efeito produzido no leitor."),
];
