import type { ReadingWork } from "./readingSchema";

const checked="2026-08-24";
type Entry={id:string;slug:string;originalTitle:string;title:string;start:string;end?:string;status?:ReadingWork["publicationStatus"];credits:ReadingWork["credits"];genres:string[];themes:string[];description:string;sourceUrl:string;image:string;credit:string;portrait?:boolean};
const work=(e:Entry):ReadingWork=>({id:`read_work_${e.id}`,contentType:"reading-work",schemaVersion:1,slug:e.slug,aliases:[],originalTitle:e.originalTitle,titleBr:e.title,format:"manhwa",originCountries:["Coreia do Sul"],originalLanguages:["Coreano"],comicTradition:"manhwa",comicFormat:"webtoon",readingDirection:"vertical",credits:e.credits,organizationRelationships:[],publicationStart:e.start,publicationEnd:e.end,publicationStatus:e.status??(e.end?"completed":"ongoing"),categories:["comics"],genres:e.genres,themes:e.themes,demographics:["young-adult","adult"],shortDescription:e.description,seriesMemberships:[],relatedWorks:[],adaptations:[],image:{src:`/images/reading/overpower/${e.image}`,alt:`Capa ou arte promocional oficial de ${e.title}`,sourceUrl:e.sourceUrl,credit:e.credit,rights:"licensed",width:e.portrait?400:540,height:e.portrait?600:540},sources:[{title:`${e.title} — publicação oficial`,url:e.sourceUrl}],status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked});

export const overpowerManhwaWorks:ReadingWork[]=[
  work({id:"advanced_player_tutorial_tower",slug:"the-advanced-player-of-the-tutorial-tower",originalTitle:"튜토리얼 탑의 고인물",title:"The Advanced Player of the Tutorial Tower",start:"2020",end:"2023",credits:[{personId:"person_bangguseok_gimssi",roles:["original-creator"]},{personId:"person_juyeong_hwang",roles:["writer","adapter"]},{personId:"person_topp",roles:["artist"]}],genres:["Ação","Fantasia urbana","Sistema"],themes:["Torre","Overpower","Vingança","Humor"],description:"Após doze anos preso numa torre de monstros regenerativos, Hyeonu retorna tão acima da escala humana que vencer lutas deixa de ser seu principal problema.",sourceUrl:"https://www.webtoons.com/en/action/the-advanced-player-of-the-tutorial-tower/list?title_no=2409",image:"advanced-player-tutorial-tower-cover.jpg",credit:"WEBTOON / Bangguseok Gimssi / Topp"}),
  work({id:"max_level_hero_strikes_back",slug:"the-max-level-hero-strikes-back",originalTitle:"만렙 영웅님께서 귀환하신다!",title:"The Max Level Hero Strikes Back",start:"2020",status:"hiatus",credits:[{personId:"person_devils_tail",roles:["original-creator"]},{personId:"person_yudo",roles:["artist","adapter"]}],genres:["Ação","Fantasia","Reencarnação"],themes:["Overpower","Política","Treinamento","Reino"],description:"A alma de um príncipe impotente treina por mil anos no Salão dos Heróis e retorna ao próprio corpo com técnicas de mestres de várias áreas.",sourceUrl:"https://tapas.io/series/the-max-level-hero-strikes-back/info",image:"max-level-hero-cover.jpg",credit:"Tapas / Golem Factory / Yudo / Devil's tail",portrait:true}),
  work({id:"academys_undercover_professor",slug:"the-academys-undercover-professor",originalTitle:"아카데미에 위장취업당했다",title:"The Academy's Undercover Professor",start:"2022",end:"2026",credits:[{personId:"person_sayren",roles:["original-creator"]},{personId:"person_tana_undercover",roles:["writer","adapter"]},{personId:"person_wag",roles:["artist"]}],genres:["Ação","Fantasia","Academia","Mistério"],themes:["Identidade secreta","Magia","Overpower","Conspiração"],description:"Um mago de muitas identidades assume por acidente o nome de um professor e precisa ocultar força, passado e objetivos entre academia e sociedade secreta.",sourceUrl:"https://www.webtoons.com/en/fantasy/the-academys-undercover-professor/list?title_no=4636",image:"academys-undercover-professor-cover.jpg",credit:"WEBTOON / sayren / Tana / WAG"}),
  work({id:"return_blossoming_blade",slug:"return-of-the-blossoming-blade",originalTitle:"화산귀환",title:"Return of the Blossoming Blade",start:"2021",credits:[{personId:"person_biga",roles:["original-creator"]},{personId:"person_lico",roles:["artist","adapter"]},{personId:"person_arche",roles:["artist"]}],genres:["Ação","Murim","Reencarnação","Comédia"],themes:["Mestre renascido","Seita","Overpower","Reconstrução"],description:"O mestre Cheongmyeong desperta um século após sua morte e usa memória marcial, disciplina brutal e astúcia para reconstruir a decadente seita Mount Hua.",sourceUrl:"https://www.webtoons.com/en/action/return-of-the-blossoming-blade/list?title_no=2849",image:"return-blossoming-blade-cover.jpg",credit:"WEBTOON / LICO / ARCHE"}),
];
