import type { ReadingEdition, ReadingWork } from "./readingSchema";

const checked = "2026-08-27";
type Extra = Partial<ReadingWork>;
const librarySource = (title: string, author: string) => ({ title:`${title} — catálogo bibliográfico`, url:`https://openlibrary.org/search?q=${encodeURIComponent(title)}&author=${encodeURIComponent(author)}` });
const philosophySource = (slug: string) => ({ title:"Contexto filosófico — Stanford Encyclopedia of Philosophy", url:`https://plato.stanford.edu/entries/${slug}/` });
const work = (id:string, slug:string, originalTitle:string, titleBr:string, year:string|undefined, country:string, language:string, personId:string, author:string, workType:ReadingWork["workType"], concepts:string[], description:string, extra:Extra={}):ReadingWork => ({
  id,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle,titleBr,workType,format:"book",originCountries:[country],originalLanguages:[language],credits:[{personId,roles:["author"]}],organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["philosophy"],genres:["Filosofia"],themes:concepts,concepts,demographics:["adult"],shortDescription:description,seriesMemberships:[],relatedWorks:[],relatedArticlePaths:[],relatedPeople:[],adaptations:[],sources:[librarySource(originalTitle,author)],status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked,...extra,
});

export const modernPhilosophyWorks:ReadingWork[] = [
  work("read_work_origins_totalitarianism","origens-do-totalitarismo","The Origins of Totalitarianism","Origens do Totalitarismo","1951","Estados Unidos","Inglês","person_hannah_arendt","Hannah Arendt","book",["Antissemitismo","Imperialismo","Totalitarismo","Massas"],"Arendt investiga elementos históricos e políticos que convergiram nas formas totalitárias de dominação do século XX.",{readingDifficulty:"advanced",featuredEditionId:"read_edition_origins_totalitarianism_companhia",relatedArticlePaths:["/blog/hannah-arendt"],sources:[librarySource("The Origins of Totalitarianism","Hannah Arendt"),philosophySource("arendt"),{title:"Origens do Totalitarismo — Companhia das Letras",url:"https://www.companhiadasletras.com.br/livro/9788535922042/origens-do-totalitarismo"}]}),
  work("read_work_human_condition","a-condicao-humana","The Human Condition","A Condição Humana","1958","Estados Unidos","Inglês","person_hannah_arendt","Hannah Arendt","book",["Trabalho","Obra","Ação","Pluralidade","Mundo comum"],"A distinção entre trabalho, obra e ação organiza uma investigação das atividades humanas e das condições da vida política.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/hannah-arendt"],sources:[librarySource("The Human Condition","Hannah Arendt"),philosophySource("arendt")]}),
  work("read_work_eichmann_jerusalem","eichmann-em-jerusalem","Eichmann in Jerusalem: A Report on the Banality of Evil","Eichmann em Jerusalém","1963","Estados Unidos","Inglês","person_hannah_arendt","Hannah Arendt","book",["Responsabilidade","Julgamento","Banalidade do mal","Burocracia"],"A reportagem sobre o julgamento de Adolf Eichmann examina responsabilidade, linguagem burocrática e incapacidade de julgar.",{readingDifficulty:"intermediate",featuredEditionId:"read_edition_eichmann_companhia",relatedArticlePaths:["/blog/hannah-arendt"],sources:[librarySource("Eichmann in Jerusalem","Hannah Arendt"),philosophySource("arendt"),{title:"Eichmann em Jerusalém — Companhia das Letras",url:"https://www.companhiadasletras.com.br/livro/9788571649620/eichmann-em-jerusalem"}]}),
  work("read_work_between_past_future","entre-o-passado-e-o-futuro","Between Past and Future","Entre o Passado e o Futuro","1961","Estados Unidos","Inglês","person_hannah_arendt","Hannah Arendt","collection",["Tradição","Autoridade","Liberdade","Educação","Cultura"],"Ensaios analisam rupturas da tradição e problemas de autoridade, liberdade, educação, cultura e verdade na modernidade.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/hannah-arendt"],sources:[librarySource("Between Past and Future","Hannah Arendt"),philosophySource("arendt")]}),

  work("read_work_discipline_punish","vigiar-e-punir","Surveiller et punir: Naissance de la prison","Vigiar e Punir","1975","França","Francês","person_michel_foucault","Michel Foucault","book",["Disciplina","Panoptismo","Poder disciplinar","Prisão","Corpos dóceis"],"Foucault reconstrói transformações das práticas penais e mostra como vigilância, exame e disciplina fabricam corpos úteis e indivíduos documentados.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/michel-foucault"],sources:[librarySource("Surveiller et punir","Michel Foucault"),philosophySource("foucault")]}),
  work("read_work_history_sexuality_1","historia-da-sexualidade-1-a-vontade-de-saber","Histoire de la sexualité I: La volonté de savoir","História da Sexualidade I: A Vontade de Saber","1976","França","Francês","person_michel_foucault","Michel Foucault","book",["Sexualidade","Biopoder","Dispositivo","Confissão","Hipótese repressiva"],"O primeiro volume questiona a ideia de simples repressão sexual e investiga como discursos, saberes e técnicas de poder produziram a sexualidade como objeto.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/michel-foucault"],sources:[librarySource("Histoire de la sexualité La volonté de savoir","Michel Foucault"),philosophySource("foucault")]}),
  work("read_work_order_things","as-palavras-e-as-coisas","Les Mots et les choses: Une archéologie des sciences humaines","As Palavras e as Coisas","1966","França","Francês","person_michel_foucault","Michel Foucault","book",["Arqueologia","Episteme","Representação","Ciências humanas","Historicidade"],"Uma arqueologia compara configurações históricas do saber para investigar como linguagem, vida, trabalho e a figura moderna do homem se tornaram pensáveis.",{readingDifficulty:"advanced",featuredEditionId:"read_edition_order_things_martins",relatedArticlePaths:["/blog/michel-foucault"],sources:[librarySource("Les Mots et les choses","Michel Foucault"),philosophySource("foucault"),{title:"As Palavras e as Coisas — Martins Fontes Paulista",url:"https://www.martinsfontespaulista.com.br/as-palavras-e-as-coisas-784690/p"}]}),
  work("read_work_history_madness","historia-da-loucura","Folie et Déraison: Histoire de la folie à l'âge classique","História da Loucura","1961","França","Francês","person_michel_foucault","Michel Foucault","book",["Loucura","Razão","Internamento","Psiquiatria","Exclusão"],"Foucault acompanha práticas, instituições e saberes que separaram razão e loucura; versões abreviadas e reedições posteriores não devem ser confundidas com a tese integral de 1961.",{readingDifficulty:"advanced",relatedArticlePaths:["/blog/michel-foucault"],sources:[librarySource("Folie et Déraison Histoire de la folie","Michel Foucault"),philosophySource("foucault")]}),

  work("read_work_second_sex","o-segundo-sexo","Le Deuxième Sexe","O Segundo Sexo","1949","França","Francês","person_simone_de_beauvoir","Simone de Beauvoir","treatise",["Alteridade","Situação","Corpo","Opressão","Liberdade"],"Em duas partes publicadas como uma única obra intelectual, Beauvoir articula história, filosofia e experiência para analisar como a mulher é produzida como Outro.",{publicationEnd:"1949",readingDifficulty:"advanced",relatedArticlePaths:["/blog/simone-de-beauvoir"],sources:[librarySource("Le Deuxième Sexe","Simone de Beauvoir"),philosophySource("beauvoir")]}),
  work("read_work_ethics_ambiguity","por-uma-moral-da-ambiguidade","Pour une morale de l'ambiguïté","Por uma Moral da Ambiguidade","1947","França","Francês","person_simone_de_beauvoir","Simone de Beauvoir","essay",["Ambiguidade","Liberdade","Situação","Responsabilidade","Opressão"],"Beauvoir parte da condição simultaneamente situada e aberta da existência para pensar uma ética em que a própria liberdade depende do reconhecimento de outras liberdades.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/simone-de-beauvoir"],sources:[librarySource("Pour une morale de l'ambiguïté","Simone de Beauvoir"),philosophySource("beauvoir")]}),
  work("read_work_memoirs_dutiful_daughter","memorias-de-uma-moca-bem-comportada","Mémoires d'une jeune fille rangée","Memórias de uma Moça Bem-Comportada","1958","França","Francês","person_simone_de_beauvoir","Simone de Beauvoir","memoir",["Formação","Família","Educação","Autonomia","Escrita"],"No primeiro volume de suas memórias, Beauvoir reconstrói infância, formação intelectual, ruptura religiosa e escolha da escrita sem converter autobiografia em tratado.",{categories:["biography"],genres:["Memória","Autobiografia"],readingDifficulty:"introductory",featuredEditionId:"read_edition_memoirs_dutiful_daughter_nova_fronteira",relatedArticlePaths:["/blog/simone-de-beauvoir"],sources:[librarySource("Mémoires d'une jeune fille rangée","Simone de Beauvoir"),{title:"Memórias de uma Moça Bem-Comportada — Nova Fronteira",url:"https://www.novafronteira.com.br/memorias-de-uma-moca-bem-comportada-2025"}]}),

  work("read_work_black_skin_white_masks","pele-negra-mascaras-brancas","Peau noire, masques blancs","Pele Negra, Máscaras Brancas","1952","França","Francês","person_frantz_fanon","Frantz Fanon","book",["Racialização","Sociogenia","Linguagem","Reconhecimento","Alienação"],"Fanon combina clínica, filosofia e crítica cultural para investigar como o colonialismo organiza linguagem, desejo, corpo e sofrimento racializado.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/frantz-fanon"],sources:[librarySource("Peau noire masques blancs","Frantz Fanon"),philosophySource("frantz-fanon")]}),
  work("read_work_wretched_earth","os-condenados-da-terra","Les Damnés de la Terre","Os Condenados da Terra","1961","França","Francês","person_frantz_fanon","Frantz Fanon","book",["Colonialismo","Violência","Descolonização","Cultura nacional","Consciência"],"Escrito no contexto da luta argelina, o livro analisa violência colonial, descolonização, formação nacional e riscos políticos posteriores à independência.",{readingDifficulty:"advanced",relatedArticlePaths:["/blog/frantz-fanon"],sources:[librarySource("Les Damnés de la Terre","Frantz Fanon"),philosophySource("frantz-fanon")]}),

  work("read_work_gender_trouble","problemas-de-genero","Gender Trouble: Feminism and the Subversion of Identity","Problemas de Gênero","1990","Estados Unidos","Inglês","person_judith_butler","Judith Butler","book",["Performatividade","Gênero","Identidade","Linguagem","Subversão"],"Butler questiona identidades tomadas como fundamento estável do feminismo e investiga como normas reiteradas produzem efeitos de gênero.",{readingDifficulty:"advanced",relatedArticlePaths:["/blog/judith-butler"],sources:[librarySource("Gender Trouble","Judith Butler"),philosophySource("feminism-gender")]}),
  work("read_work_bodies_matter","corpos-que-importam","Bodies That Matter: On the Discursive Limits of Sex","Corpos que Importam","1993","Estados Unidos","Inglês","person_judith_butler","Judith Butler","book",["Materialização","Corpo","Sexo","Norma","Performatividade"],"Butler desenvolve a performatividade para explicar como normas materializam corpos e produzem limites entre vidas reconhecíveis e excluídas.",{readingDifficulty:"advanced",relatedArticlePaths:["/blog/judith-butler"],sources:[librarySource("Bodies That Matter","Judith Butler"),philosophySource("feminism-gender")]}),
  work("read_work_precarious_life","vida-precaria","Precarious Life: The Powers of Mourning and Violence","Vida Precária","2004","Estados Unidos","Inglês","person_judith_butler","Judith Butler","collection",["Precariedade","Luto","Violência","Reconhecimento","Vulnerabilidade"],"Ensaios escritos após o 11 de Setembro relacionam luto, vulnerabilidade compartilhada, enquadramentos políticos e distribuição desigual do reconhecimento.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/judith-butler"],sources:[librarySource("Precarious Life","Judith Butler"),philosophySource("feminism-gender")]}),

  work("read_work_world_will_representation","o-mundo-como-vontade-e-representacao","Die Welt als Wille und Vorstellung","O Mundo como Vontade e Representação","1818","Alemanha","Alemão","person_arthur_schopenhauer","Arthur Schopenhauer","treatise",["Representação","Vontade","Corpo","Sofrimento","Arte"],"Schopenhauer organiza seu sistema em torno do mundo conhecido como representação e da vontade que se manifesta no corpo, no desejo e na natureza.",{publicationEnd:"1844",readingDifficulty:"advanced",relatedArticlePaths:["/blog/arthur-schopenhauer"],sources:[librarySource("Die Welt als Wille und Vorstellung","Arthur Schopenhauer"),philosophySource("schopenhauer")]}),
  work("read_work_aphorisms_wisdom","aforismos-para-a-sabedoria-de-vida","Aphorismen zur Lebensweisheit","Aforismos para a Sabedoria de Vida","1851","Alemanha","Alemão","person_arthur_schopenhauer","Arthur Schopenhauer","essay",["Prudência","Caráter","Fortuna","Sofrimento","Vida prática"],"Parte de Parerga e Paralipomena, o ensaio pergunta como conduzir a vida com prudência dentro dos limites de uma filosofia pessimista.",{readingDifficulty:"introductory",relatedArticlePaths:["/blog/arthur-schopenhauer"],sources:[librarySource("Aphorismen zur Lebensweisheit","Arthur Schopenhauer"),philosophySource("schopenhauer")]}),
  work("read_work_freedom_will_schopenhauer","sobre-a-liberdade-da-vontade","Über die Freiheit des menschlichen Willens","Sobre a Liberdade da Vontade","1839","Alemanha","Alemão","person_arthur_schopenhauer","Arthur Schopenhauer","essay",["Vontade","Liberdade","Necessidade","Caráter","Responsabilidade"],"O ensaio premiado distingue liberdade física, intelectual e moral para defender que ações seguem motivos e caráter, embora a vontade em si pertença a outro nível do sistema.",{readingDifficulty:"intermediate",relatedArticlePaths:["/blog/arthur-schopenhauer"],sources:[librarySource("Über die Freiheit des menschlichen Willens","Arthur Schopenhauer"),philosophySource("schopenhauer")]}),
];

export const historicalPhilosophyWorks:ReadingWork[] = [
  work("read_work_republic_plato","a-republica-platao","Πολιτεία","A República",undefined,"Grécia antiga","Grego antigo","person_platao","Platão","dialogue",["Justiça","Educação","Política","Alma","Formas"],"Sócrates e seus interlocutores investigam por que ser justo, como educar a alma e que cidade torna visível a relação entre conhecimento, desejo e poder.",{publicationDisplay:"c. século IV a.C.",readingDifficulty:"advanced",relatedArticlePaths:["/blog/platao"],relatedPeople:[{personId:"person_socrates",relationship:"character",note:"Interlocutor central do diálogo; não é o autor do texto."}],sources:[librarySource("Politeia Plato","Plato"),philosophySource("plato-ethics-politics")]}),
  work("read_work_symposium_plato","o-banquete-platao","Συμπόσιον","O Banquete",undefined,"Grécia antiga","Grego antigo","person_platao","Platão","dialogue",["Amor","Desejo","Beleza","Discurso","Filosofia"],"Discursos pronunciados num banquete oferecem concepções rivais de eros, culminando na narrativa socrática do ensinamento de Diotima.",{publicationDisplay:"c. século IV a.C.",readingDifficulty:"intermediate",relatedArticlePaths:["/blog/platao"],relatedPeople:[{personId:"person_socrates",relationship:"character"}],sources:[librarySource("Symposium Plato","Plato"),philosophySource("plato")]}),
  work("read_work_phaedo_plato","fedon-platao","Φαίδων","Fédon",undefined,"Grécia antiga","Grego antigo","person_platao","Platão","dialogue",["Alma","Morte","Formas","Filosofia","Argumentação"],"A cena das últimas horas de Sócrates articula argumentos sobre alma, morte e Formas, acompanhados de objeções e revisões internas.",{publicationDisplay:"c. século IV a.C.",readingDifficulty:"intermediate",relatedArticlePaths:["/blog/platao"],relatedPeople:[{personId:"person_socrates",relationship:"character"}],sources:[librarySource("Phaedo Plato","Plato"),philosophySource("plato")]}),
  work("read_work_apology_socrates_plato","apologia-de-socrates-platao","Ἀπολογία Σωκράτους","Apologia de Sócrates",undefined,"Grécia antiga","Grego antigo","person_platao","Platão","dialogue",["Defesa","Virtude","Conhecimento","Morte","Vida examinada"],"Platão compõe a defesa de Sócrates diante do tribunal ateniense; o texto é uma fonte filosófica e literária, não uma transcrição judicial nem obra escrita por Sócrates.",{publicationDisplay:"c. século IV a.C.",readingDifficulty:"introductory",relatedArticlePaths:["/blog/platao","/blog/principais-filosofos-da-historia"],relatedPeople:[{personId:"person_socrates",relationship:"subject",note:"Figura central e personagem da defesa; Platão é o autor."}],sources:[librarySource("Apology Plato","Plato"),philosophySource("socrates")]}),

  work("read_work_confessions_augustine","confissoes-agostinho","Confessiones","Confissões","0397","Norte da África romana","Latim","person_agostinho_hipona","Augustine of Hippo","book",["Memória","Tempo","Vontade","Conversão","Interioridade"],"Agostinho combina narrativa de formação, oração e investigação filosófica para pensar memória, desejo, linguagem, criação e experiência do tempo.",{publicationEnd:"0400",publicationDisplay:"c. 397–400",readingDifficulty:"intermediate",relatedArticlePaths:["/blog/agostinho-de-hipona"],sources:[librarySource("Confessiones Augustine","Augustine"),philosophySource("augustine")]}),
  work("read_work_city_god_augustine","a-cidade-de-deus","De civitate Dei contra paganos","A Cidade de Deus","0413","Norte da África romana","Latim","person_agostinho_hipona","Augustine of Hippo","treatise",["História","Política","Providência","Justiça","Comunidade"],"Em resposta às acusações contra o cristianismo após o saque de Roma, Agostinho contrapõe formas de amor, justiça e pertencimento para interpretar história e poder.",{publicationEnd:"0426",publicationDisplay:"413–426",readingDifficulty:"advanced",relatedArticlePaths:["/blog/agostinho-de-hipona"],sources:[librarySource("De civitate Dei contra paganos","Augustine"),philosophySource("augustine")]}),
  work("read_work_leviathan_hobbes","leviata","Leviathan, or The Matter, Forme and Power of a Commonwealth Ecclesiasticall and Civil","Leviatã","1651","Inglaterra","Inglês","person_thomas_hobbes","Thomas Hobbes","treatise",["Estado de natureza","Contrato","Soberania","Representação","Liberdade"],"Hobbes parte de uma teoria materialista da pessoa e das paixões para explicar pacto, representação e a autoridade necessária à paz civil.",{aliases:["leviata-hobbes"],readingDifficulty:"advanced",relatedArticlePaths:["/blog/principais-filosofos-da-historia"],sources:[librarySource("Leviathan Thomas Hobbes","Thomas Hobbes"),philosophySource("hobbes-moral")]}),
];

export const philosophyWorks:ReadingWork[] = [...modernPhilosophyWorks, ...historicalPhilosophyWorks];

const edition = (id:string,workId:string,title:string,publisherId:string,sourceUrl:string,extra:Partial<ReadingEdition>):ReadingEdition => ({id,workId,title,publisherId,country:"Brasil",language:"Português",medium:"paperback",availabilityStatus:"unknown",status:"published",sources:[{title:`${title} — edição brasileira`,url:sourceUrl}],createdAt:checked,updatedAt:checked,translationCredits:[],...extra});

export const philosophyEditions:ReadingEdition[] = [
  edition("read_edition_origins_totalitarianism_companhia","read_work_origins_totalitarianism","Origens do Totalitarismo","org_companhia_de_bolso","https://www.companhiadasletras.com.br/livro/9788535922042/origens-do-totalitarismo",{publicationDate:"2013-01-10",isbn13:"9788535922042",pageCount:832,translationCredits:[{personId:"person_roberto_raposo",roles:["translator"]}]}),
  edition("read_edition_eichmann_companhia","read_work_eichmann_jerusalem","Eichmann em Jerusalém","org_companhia_das_letras","https://www.companhiadasletras.com.br/livro/9788571649620/eichmann-em-jerusalem",{publicationDate:"1999-12-16",isbn13:"9788571649620",pageCount:344,translationCredits:[{personId:"person_jose_rubens_siqueira",roles:["translator"]}]}),
  edition("read_edition_order_things_martins","read_work_order_things","As Palavras e as Coisas","org_martins_fontes","https://www.martinsfontespaulista.com.br/as-palavras-e-as-coisas-784690/p",{publicationDate:"2016-01-01",isbn13:"9788580632644",pageCount:564}),
  edition("read_edition_memoirs_dutiful_daughter_nova_fronteira","read_work_memoirs_dutiful_daughter","Memórias de uma Moça Bem-Comportada","org_nova_fronteira","https://www.novafronteira.com.br/memorias-de-uma-moca-bem-comportada-2025",{publicationDate:"2025-03-01",isbn10:"6556406282",isbn13:"9786556406282",pageCount:326}),
];
