import type { ReadingWork } from "./readingSchema";

const checked="2026-09-02";
const src=(title:string,author:string)=>({title:`${title} — registro bibliográfico`,url:`https://openlibrary.org/search?q=${encodeURIComponent(title)}&author=${encodeURIComponent(author)}`});
const work=(id:string,slug:string,title:string,titleBr:string|undefined,year:string,credits:ReadingWork["credits"],difficulty:ReadingWork["readingDifficulty"],concepts:string[],description:string,extra:Partial<ReadingWork>={}):ReadingWork=>({id:`read_work_${id}`,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle:title,titleBr,workType:"book",format:"book",originCountries:["Estados Unidos"],originalLanguages:["Inglês"],credits,organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["science","non-fiction"],genres:["Psicologia"],themes:concepts,concepts,readingDifficulty:difficulty,demographics:["adult"],audienceProfile:"Leitores que procuram psicologia baseada em pesquisa e aceitam distinguir evidência, interpretação, controvérsia e aplicação.",shortDescription:description,seriesMemberships:[],relatedWorks:[],adaptations:[],sources:[src(title,credits[0].personId.replace("person_","").replaceAll("_"," "))],status:"draft",createdAt:checked,updatedAt:checked,...extra});

export const psychologyWorks:ReadingWork[]=[
  work("psychology_openstax","psychology-openstax","Psychology 2e",undefined,"2020",[{personId:"person_rose_spielman",roles:["author"]},{personId:"person_william_jenkins",roles:["author"]},{personId:"person_marilyn_lovett",roles:["author"]}],"introductory",["Métodos","Cognição","Desenvolvimento","Psicologia social","Saúde mental"],"Livro-texto aberto apresenta conceitos, métodos de pesquisa e principais áreas da psicologia com objetivos, exemplos e revisão por capítulo."),
  work("cognitive_psychology_goldstein","cognitive-psychology-goldstein","Cognitive Psychology: Connecting Mind, Research, and Everyday Experience",undefined,"2005",[{personId:"person_e_bruce_goldstein",roles:["author"]}],"advanced",["Percepção","Atenção","Memória","Linguagem","Decisão"],"Manual acadêmico relaciona experimentos e modelos de percepção, atenção, memória, conhecimento, linguagem e decisão a experiências cotidianas."),
  work("seven_sins_memory","os-sete-pecados-da-memoria","The Seven Sins of Memory","Os Sete Pecados da Memória","2001",[{personId:"person_daniel_schacter",roles:["author"]}],"introductory",["Esquecimento","Distorção","Sugestionabilidade","Persistência"],"Schacter organiza falhas de memória por mecanismos que também cumprem funções adaptativas, evitando tratar recordação como gravação literal."),
  work("man_mistook_wife_hat","o-homem-que-confundiu-sua-mulher-com-um-chapeu","The Man Who Mistook His Wife for a Hat","O Homem Que Confundiu Sua Mulher com um Chapéu","1985",[{personId:"person_oliver_sacks",roles:["author"]}],"introductory",["Neurologia","Percepção","Identidade","Casos clínicos"],"Narrativas clínicas mostram como alterações neurológicas podem reorganizar reconhecimento, memória, corpo e identidade sem reduzir pessoas ao diagnóstico."),
  work("thinking_fast_slow","rapido-e-devagar","Thinking, Fast and Slow","Rápido e Devagar","2011",[{personId:"person_daniel_kahneman",roles:["author"]}],"introductory",["Heurísticas","Vieses","Decisão","Risco"],"Kahneman sintetiza décadas de pesquisa sobre julgamento e decisão usando a distinção didática entre processos rápidos e deliberados."),
  work("influence_cialdini","influencia-psicologia-persuasao","Influence: The Psychology of Persuasion","As Armas da Persuasão","1984",[{personId:"person_robert_cialdini",roles:["author"]}],"introductory",["Persuasão","Reciprocidade","Autoridade","Prova social"],"Cialdini organiza princípios de influência social e exemplos de campo, úteis quando lidos como hipóteses contextuais e não como botões universais de comportamento."),
  work("person_situation","a-pessoa-e-a-situacao","The Person and the Situation",undefined,"1991",[{personId:"person_lee_ross",roles:["author"]},{personId:"person_richard_nisbett",roles:["author"]}],"intermediate",["Situação","Atribuição","Psicologia social","Contexto"],"Ross e Nisbett defendem que situações, interpretações e sistemas sociais explicam mais comportamento do que observadores costumam reconhecer."),
  work("personality_puzzle","the-personality-puzzle","The Personality Puzzle",undefined,"1997",[{personId:"person_david_funder",roles:["author"]}],"intermediate",["Traços","Pessoa","Situação","Avaliação de personalidade"],"Funder apresenta teorias, métodos e controvérsias da psicologia da personalidade, incluindo estabilidade de traços e variação entre situações."),
  work("development_lifespan_berk","development-through-lifespan","Development Through the Lifespan",undefined,"1998",[{personId:"person_laura_berk",roles:["author"]}],"advanced",["Infância","Adolescência","Vida adulta","Envelhecimento"],"Livro-texto acompanha desenvolvimento físico, cognitivo e socioemocional da infância ao envelhecimento e compara explicações e evidências."),
  work("emotional_brain","o-cerebro-emocional","The Emotional Brain","O Cérebro Emocional","1996",[{personId:"person_joseph_ledoux",roles:["author"]}],"intermediate",["Emoção","Medo","Amígdala","Aprendizagem"],"LeDoux explica circuitos de defesa e aprendizagem emocional, distinguindo respostas neurais de relatos conscientes de sentimento."),
  work("behave_sapolsky","comporte-se","Behave","Comporte-se","2017",[{personId:"person_robert_sapolsky",roles:["author"]}],"intermediate",["Neurociência","Hormônios","Desenvolvimento","Cultura","Agressão"],"Sapolsky organiza causas do comportamento por escalas temporais, de segundos anteriores a processos evolutivos e culturais de longa duração."),
  work("righteous_mind","a-mente-moralista","The Righteous Mind","A Mente Moralista","2012",[{personId:"person_jonathan_haidt",roles:["author"]}],"introductory",["Julgamento moral","Intuição","Grupos","Política"],"Haidt propõe que intuições precedem muitas justificativas morais e compara fundamentos morais usados por grupos políticos e culturais."),
  work("weirdest_people","os-mais-estranhos-do-mundo","The WEIRDest People in the World",undefined,"2020",[{personId:"person_joseph_henrich",roles:["author"]}],"intermediate",["Cultura","Instituições","Cognição","Comparação intercultural"],"Henrich argumenta que instituições históricas moldaram padrões psicológicos incomuns em populações ocidentais, escolarizadas, industrializadas, ricas e democráticas."),
  work("mistakes_were_made","erros-foram-cometidos-mas-nao-por-mim","Mistakes Were Made (But Not by Me)",undefined,"2007",[{personId:"person_carol_tavris",roles:["author"]},{personId:"person_elliot_aronson",roles:["author"]}],"introductory",["Dissonância cognitiva","Autojustificação","Memória","Conflito"],"Tavris e Aronson usam dissonância cognitiva para explicar como pessoas protegem decisões, identidades e lembranças diante de evidências contrárias."),
  work("social_animal_aronson","o-animal-social","The Social Animal","O Animal Social","1972",[{personId:"person_elliot_aronson",roles:["author"]}],"intermediate",["Conformidade","Preconceito","Atração","Persuasão","Grupos"],"Aronson apresenta problemas clássicos da psicologia social e conecta experimentos, relações entre grupos, persuasão e comportamento coletivo."),
];
