import type { ReadingWork } from "./readingSchema";

const checked = "2026-08-24";
type Entry = { id:string; slug:string; originalTitle:string; title:string; start:string; end?:string; status?:ReadingWork["publicationStatus"]; credits:ReadingWork["credits"]; genres:string[]; themes:string[]; description:string; sourceUrl:string; image:string; credit:string };
const work = (e: Entry): ReadingWork => ({
  id:`read_work_${e.id}`, contentType:"reading-work", schemaVersion:1, slug:e.slug, aliases:[], originalTitle:e.originalTitle, titleBr:e.title,
  format:"manhwa", originCountries:["Coreia do Sul"], originalLanguages:["Coreano"], comicTradition:"manhwa", comicFormat:"webtoon", readingDirection:"vertical",
  credits:e.credits, organizationRelationships:[], publicationStart:e.start, publicationEnd:e.end, publicationStatus:e.status ?? (e.end ? "completed" : "ongoing"),
  categories:["comics"], genres:e.genres, themes:e.themes, demographics:["young-adult","adult"], shortDescription:e.description,
  seriesMemberships:[], relatedWorks:[], adaptations:[], image:{src:`/images/reading/regression/${e.image}`,alt:`Capa ou arte promocional oficial de ${e.title}`,sourceUrl:e.sourceUrl,credit:e.credit,rights:"licensed",width:e.image.includes("returners")?400:540,height:e.image.includes("returners")?600:540},
  sources:[{title:`${e.title} — publicação oficial`,url:e.sourceUrl}], status:"published", publishedAt:checked, createdAt:checked, updatedAt:checked,
});

export const regressionManhwaWorks: ReadingWork[] = [
  work({id:"regressed_mercenary_plan",slug:"the-regressed-mercenary-has-a-plan",originalTitle:"회귀한 용병은 다 계획이 있다",title:"The Regressed Mercenary Has a Plan",start:"2024",credits:[{personId:"person_gold_haeng",roles:["original-creator"]},{personId:"person_jjjsss",roles:["artist"]}],genres:["Ação","Fantasia","Regressão"],themes:["Vingança","Estratégia","Gestão territorial"],description:"Um rei mercenário morto antes de vingar a família desperta como seu eu adolescente e usa experiência militar para impedir a ruína de sua casa.",sourceUrl:"https://www.webtoons.com/en/action/the-regressed-mercenary-has-a-plan/list?title_no=7261",image:"regressed-mercenary-cover.jpg",credit:"WEBTOON / Gold Haeng / JJJSSS"}),
  work({id:"returners_magic_special",slug:"a-returners-magic-should-be-special",originalTitle:"귀환자의 마법은 특별해야 합니다",title:"A Returner's Magic Should Be Special",start:"2018",end:"2024",credits:[{personId:"person_usonan",roles:["original-creator"]},{personId:"person_wookjakga",roles:["artist","adapter"]}],genres:["Ação","Fantasia","Regressão","Academia"],themes:["Magia","Estratégia","Apocalipse"],description:"Após dez anos no Labirinto das Sombras, Desir retorna treze anos à época da academia e prepara seus companheiros para a catástrofe que conhece.",sourceUrl:"https://tapas.io/series/a-returners-magic-should-be-special/info",image:"returners-magic-cover.jpg",credit:"Tapas / D&C MEDIA"}),
  work({id:"return_to_player",slug:"return-to-player",originalTitle:"리턴 투 플레이어",title:"Return to Player",start:"2020",end:"2026",credits:[{personId:"person_index_return_player",roles:["original-creator"]},{personId:"person_umky",roles:["writer","adapter"]},{personId:"person_sehon",roles:["artist"]}],genres:["Ação","Fantasia urbana","Regressão","Sistema"],themes:["Apocalipse","Deuses","Sobrevivência"],description:"Único sobrevivente de um jogo mortal imposto por deuses, Sehan volta ao início da partida para alterar a rota que exterminou a humanidade.",sourceUrl:"https://www.webtoons.com/en/action/return-to-player/list?title_no=2574",image:"return-to-player-cover.jpg",credit:"WEBTOON / INDEX / UMKY / SEHON"}),
  work({id:"absolute_regression",slug:"absolute-regression",originalTitle:"절대회귀",title:"Absolute Regression",start:"2024",credits:[{personId:"person_yh_jang",roles:["original-creator"]},{personId:"person_jp_absolute",roles:["writer"]},{personId:"person_park_jin_hwan",roles:["artist"]}],genres:["Ação","Murim","Regressão"],themes:["Redenção","Família","Artes marciais"],description:"O filho do Demônio Celestial usa um ritual proibido para voltar ao próprio passado, reunir aliados e preparar o Murim para um inimigo invencível.",sourceUrl:"https://www.webtoons.com/en/fantasy/absolute-regression/list?title_no=7004",image:"absolute-regression-cover.jpg",credit:"WEBTOON / Y.H.JANG / JP / PARK JIN HWAN"}),
  work({id:"knight_only_lives_today",slug:"the-knight-only-lives-today",originalTitle:"오늘만 사는 기사",title:"The Knight Only Lives Today",start:"2024",credits:[{personId:"person_soulpung",roles:["original-creator"]},{personId:"person_lee_hyun_min",roles:["writer","adapter"]},{personId:"person_kanara",roles:["adapter"]},{personId:"person_ian_knight",roles:["artist"]}],genres:["Ação","Fantasia","Regressão"],themes:["Loop temporal","Treinamento","Guerra"],description:"Um soldado que sonha ser cavaleiro retorna ao começo do mesmo dia sempre que morre e transforma repetição em treinamento deliberado.",sourceUrl:"https://www.webtoons.com/en/fantasy/the-knight-only-lives-today/list?title_no=6672",image:"knight-only-lives-today-cover.jpg",credit:"WEBTOON / SOULPUNG / IAN"}),
];
