import type { ReadingEdition, ReadingSeries, ReadingWork } from "./readingSchema";

const checked="2026-08-24";
const brazilianEdition=(id:string,workId:string,title:string,date:string,isbn13:string,pages:number,url:string,medium:ReadingEdition["medium"]="hardcover"):ReadingEdition=>({id:`read_edition_${id}`,workId:`read_work_${workId}`,title,publisherId:"org_editora_aleph",country:"Brasil",language:"Português",medium,publicationDate:date,isbn13,pageCount:pages,availabilityStatus:"available",availabilityCheckedAt:"2026-09-22",status:"published",sources:source(`${title} — Editora Aleph`,url),translationCredits:[],createdAt:"2026-09-22",updatedAt:"2026-09-22"});
const source=(title:string,url:string)=>[{title,url}];
const series=(id:string,title:string,summary:string,url:string,status:ReadingSeries["publicationStatus"]="completed"):ReadingSeries=>({id:`read_series_${id}`,slug:id.replaceAll("_","-"),aliases:[],title,summary,kind:"narrative",publicationStatus:status,status:"published",sources:source(`${title} — editora`,url),createdAt:checked,updatedAt:checked});
const work=(id:string,slug:string,title:string,titleBr:string|undefined,year:string,country:string,language:string,credits:ReadingWork["credits"],genres:string[],themes:string[],description:string,url:string,memberships:ReadingWork["seriesMemberships"]=[]):ReadingWork=>({id:`read_work_${id}`,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle:title,titleBr,format:"book",originCountries:[country],originalLanguages:[language],credits,organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["fiction"],genres,themes,demographics:["adult"],shortDescription:description,seriesMemberships:memberships,relatedWorks:[],adaptations:[],sources:source(`${title} — editora`,url),status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked});
const edition=(id:string,workId:string,title:string,publisherId:string,medium:ReadingEdition["medium"],date:string,isbn13:string,pages:number,url:string):ReadingEdition=>({id:`read_edition_${id}`,workId:`read_work_${workId}`,title,publisherId,country:"Estados Unidos",language:"Inglês",medium,publicationDate:date,isbn13,pageCount:pages,availabilityStatus:"unknown",status:"published",sources:source(`${title} — edição verificada`,url),translationCredits:[],createdAt:checked,updatedAt:checked});

export const scienceFictionSeries:ReadingSeries[]=[
  series("inhibitor_sequence","Inhibitor Sequence","Ciclo de space opera e arqueologia cósmica em que ruínas alienígenas e máquinas antigas condicionam o futuro humano.","https://www.hachettebookgroup.com/series/alastair-reynolds/revelation-space/"),
  series("the_expanse","The Expanse","Série de space opera sobre a expansão humana pelo Sistema Solar, conflitos políticos e uma tecnologia extraterrestre que altera sua escala.","https://www.hachettebookgroup.com/series/james-s-a-corey/the-expanse/"),
  series("children_time","Children of Time","Série sobre evolução dirigida, ecologias não humanas e encontros entre civilizações com modos incompatíveis de perceber o mundo.","https://www.hachettebookgroup.com/series/adrian-tchaikovsky/children-of-time/","ongoing"),
  series("firefall","Firefall","Dilogia de ficção científica pós-humana sobre inteligência, consciência e contato com algo que pode não pensar como nós.","https://us.macmillan.com/series/firefall"),
  series("imperial_radch","Imperial Radch","Trilogia de space opera sobre uma inteligência de nave confinada a um corpo, império, identidade e vingança.","https://www.hachettebookgroup.com/series/ann-leckie/imperial-radch/"),
  series("sprawl","Sprawl","Trilogia cyberpunk de William Gibson sobre inteligências artificiais, corporações e vidas conectadas ao ciberespaço.","https://www.penguinrandomhouse.com/series/ZSW/sprawl-trilogy/"),
  series("remembrance_earths_past","Remembrance of Earth's Past","Trilogia de primeiro contato que amplia um problema científico terrestre até escalas históricas e cosmológicas.","https://us.macmillan.com/series/thethreebodyproblemseries"),
];

export const scienceFictionWorks:ReadingWork[]=[
  work("revelation_space","revelation-space","Revelation Space",undefined,"2000","Reino Unido","Inglês",[{personId:"person_alastair_reynolds",roles:["author"]}],["Ficção científica","Space opera","Horror espacial"],["Arqueologia extraterrestre","Civilizações antigas","Pós-humanismo","Isolamento"],"Uma arqueóloga investiga a extinção de uma civilização alienígena enquanto uma nave interestelar procura a tecnologia capaz de salvar seu capitão.","https://www.hachettebookgroup.com/titles/alastair-reynolds/revelation-space/9780316462440/",[{seriesId:"read_series_inhibitor_sequence",position:1}]),
  work("leviathan_wakes","leviathan-wakes","Leviathan Wakes","O Despertar do Leviatã","2011","Estados Unidos","Inglês",[{personId:"person_james_s_a_corey",roles:["author"]}],["Ficção científica","Space opera","Thriller"],["Sistema Solar","Primeiro contato","Política","Horror corporal"],"O desaparecimento de uma jovem liga uma tripulação civil e um detetive a uma conspiração capaz de romper o equilíbrio entre Terra, Marte e o Cinturão.","https://www.hachettebookgroup.com/titles/james-s-a-corey/leviathan-wakes/9780316129084/",[{seriesId:"read_series_the_expanse",position:1}]),
  work("children_time","children-of-time","Children of Time","Filhos do Tempo","2015","Reino Unido","Inglês",[{personId:"person_adrian_tchaikovsky",roles:["author"]}],["Ficção científica","Space opera","Biotecnologia"],["Evolução dirigida","Aranhas","Terraformação","Civilização"],"Os últimos humanos encontram um planeta terraformado onde um experimento evolutivo criou uma civilização que não estava nos planos de seus criadores.","https://www.hachettebookgroup.com/titles/adrian-tchaikovsky/children-of-time/9780316452502/",[{seriesId:"read_series_children_time",position:1}]),
  work("blindsight","blindsight-peter-watts","Blindsight",undefined,"2006","Canadá","Inglês",[{personId:"person_peter_watts",roles:["author"]}],["Ficção científica","Primeiro contato","Horror espacial"],["Consciência","Pós-humanismo","Alienígenas","Isolamento"],"Uma equipe de humanos radicalmente modificados viaja até um objeto desconhecido para descobrir se inteligência e consciência são realmente a mesma coisa.","https://us.macmillan.com/books/9781250237484/blindsight/",[{seriesId:"read_series_firefall",position:1}]),
  work("mountain_sea","the-mountain-in-the-sea","The Mountain in the Sea",undefined,"2022","Estados Unidos","Inglês",[{personId:"person_ray_nayler",roles:["author"]}],["Ficção científica","Thriller","Biotecnologia"],["Inteligência não humana","Polvos","IA","Ecologia"],"Uma bióloga marinha investiga uma população de polvos com linguagem própria numa reserva controlada por uma corporação tecnológica.","https://us.macmillan.com/books/9780374605964/themountaininthesea/"),
  work("ancillary_justice","ancillary-justice","Ancillary Justice","Justiça Ancilar","2013","Estados Unidos","Inglês",[{personId:"person_ann_leckie",roles:["author"]}],["Ficção científica","Space opera","Ficção científica militar"],["Inteligência artificial","Império","Identidade","Vingança"],"A consciência que antes ocupava uma nave militar e milhares de corpos sobrevive agora em apenas um corpo humano e procura acertar contas com o império que serviu.","https://www.hachettebookgroup.com/titles/ann-leckie/ancillary-justice/9780316246637/",[{seriesId:"read_series_imperial_radch",position:1}]),
  work("neuromancer","neuromancer","Neuromancer","Neuromancer","1984","Estados Unidos","Inglês",[{personId:"person_william_gibson",roles:["author"]}],["Ficção científica","Cyberpunk","Distopia"],["Ciberespaço","Inteligência artificial","Corporações","Pós-humanismo"],"Um hacker impedido de acessar o ciberespaço aceita um último trabalho que o coloca entre mercenários, corporações e inteligências artificiais com objetivos próprios.","https://www.penguinrandomhouse.com/books/538861/neuromancer-by-william-gibson/",[{seriesId:"read_series_sprawl",position:1}]),
  work("kindred","kindred-octavia-butler","Kindred","Kindred: Laços de Sangue","1979","Estados Unidos","Inglês",[{personId:"person_octavia_e_butler",roles:["author"]}],["Ficção científica","Viagem no tempo","Ficção histórica"],["Escravidão","Ancestralidade","Poder","Sobrevivência"],"Uma escritora negra de 1976 é repetidamente transportada para uma plantação no século XIX e precisa sobreviver à relação perigosa com um antepassado branco.","https://www.beacon.org/Kindred-P2085.aspx"),
  work("three_body_problem","the-three-body-problem","三体","O Problema dos Três Corpos","2008","China","Chinês",[{personId:"person_cixin_liu",roles:["author"]}],["Ficção científica","Primeiro contato","Ficção científica filosófica"],["Astrofísica","Civilização extraterrestre","História","Escala cósmica"],"Uma investigação sobre mortes de cientistas revela conexões entre a Revolução Cultural, um estranho jogo e um contato capaz de redefinir o futuro humano.","https://us.macmillan.com/books/9780765382030/thethreebodyproblem/",[{seriesId:"read_series_remembrance_earths_past",position:1}]),
  work("roadside_picnic","roadside-picnic","Пикник на обочине","Piquenique na Estrada","1972","União Soviética","Russo",[{personId:"person_arkady_strugatsky",roles:["author"]},{personId:"person_boris_strugatsky",roles:["author"]}],["Ficção científica","Ficção científica filosófica","Distopia"],["Artefatos alienígenas","Zona interditada","Desconhecido","Desejo"],"Após uma visita extraterrestre incompreensível, um contrabandista entra numa Zona proibida para recuperar artefatos cujas funções ninguém entende.","https://www.chicagoreviewpress.com/roadside-picnic-products-9781613743416.php"),
];

scienceFictionWorks.push(
  work("time_machine","a-maquina-do-tempo","The Time Machine","A Máquina do Tempo","1895","Reino Unido","Inglês",[{personId:"person_h_g_wells",roles:["author"]}],["Ficção científica","Viagem no tempo","Distopia"],["Evolução","Classe social","Futuro distante","Progresso"],"Um cientista atravessa centenas de milhares de anos e encontra uma humanidade dividida em castas cuja aparente harmonia expõe uma história de desigualdade.","https://www.britannica.com/topic/The-Time-Machine"),
  work("foundation","fundacao","Foundation","Fundação","1951","Estados Unidos","Inglês",[{personId:"person_isaac_asimov",roles:["author"]}],["Ficção científica","Space opera","Ficção científica social"],["Psico-história","Império","Conhecimento","Planejamento"],"Diante da queda prevista de um império galáctico, uma comunidade tenta preservar conhecimento e reduzir um longo período de colapso civilizacional.","https://aleph.com.br/products/fundacao"),
  work("childhoods_end","o-fim-da-infancia","Childhood's End","O Fim da Infância","1953","Reino Unido","Inglês",[{personId:"person_arthur_c_clarke",roles:["author"]}],["Ficção científica","Primeiro contato","Ficção científica filosófica"],["Evolução humana","Utopia","Infância","Transcendência"],"A chegada de visitantes aparentemente benevolentes encerra guerras e escassez, mas cobra da humanidade uma transformação que também significa fim.","https://www.britannica.com/topic/Childhoods-End"),
  work("androids_electric_sheep","androides-sonham-com-ovelhas-eletricas","Do Androids Dream of Electric Sheep?","Androides Sonham com Ovelhas Elétricas?","1968","Estados Unidos","Inglês",[{personId:"person_philip_k_dick",roles:["author"]}],["Ficção científica","Cyberpunk","Distopia"],["Empatia","Androides","Realidade artificial","Colapso ambiental"],"Num mundo devastado, um caçador de recompensas persegue androides quase indistinguíveis de humanos e passa a duvidar do critério que separa os dois.","https://www.penguinrandomhouse.com/books/34262/do-androids-dream-of-electric-sheep-by-philip-k-dick/"),
  work("solaris","solaris","Solaris","Solaris","1961","Polônia","Polonês",[{personId:"person_stanislaw_lem",roles:["author"]}],["Ficção científica","Primeiro contato","Ficção científica filosófica"],["Consciência","Oceano vivo","Memória","Limites do conhecimento"],"Em uma estação sobre um planeta coberto por oceano possivelmente consciente, pesquisadores enfrentam manifestações de memórias que a ciência não consegue enquadrar.","https://aleph.com.br/products/solaris"),
  work("left_hand_darkness","a-mao-esquerda-da-escuridao","The Left Hand of Darkness","A Mão Esquerda da Escuridão","1969","Estados Unidos","Inglês",[{personId:"person_ursula_k_le_guin",roles:["author"]}],["Ficção científica","Ficção científica social","Ficção científica filosófica"],["Gênero","Diplomacia","Alteridade","Política"],"Um emissário tenta aproximar um planeta de pessoas ambissexuais de uma comunidade interestelar e descobre que seus próprios pressupostos impedem a negociação.","https://aleph.com.br/products/a-mao-esquerda-da-escuridao"),
  work("dune","duna","Dune","Duna","1965","Estados Unidos","Inglês",[{personId:"person_frank_herbert",roles:["author"]}],["Ficção científica","Space opera","Ecologia"],["Deserto","Colonialismo","Religião","Poder","Recursos naturais"],"Em Arrakis, uma família aristocrática é lançada a uma disputa pelo recurso que sustenta o império, enquanto ecologia, religião e messianismo reorganizam a política do planeta.","https://aleph.com.br/products/duna-1"),
  work("parable_sower","parabola-do-semeador","Parable of the Sower","Parábola do Semeador","1993","Estados Unidos","Inglês",[{personId:"person_octavia_e_butler",roles:["author"]}],["Ficção científica","Distopia","Afrofuturismo"],["Colapso climático","Comunidade","Violência","Religião"],"Em uma Califórnia desagregada por crise climática e desigualdade, uma jovem hipersensível formula uma crença orientada por mudança e procura construir comunidade.","https://www.hachettebookgroup.com/titles/octavia-e-butler/parable-of-the-sower/9781538732182/"),
  work("handmaids_tale","o-conto-da-aia","The Handmaid's Tale","O Conto da Aia","1985","Canadá","Inglês",[{personId:"person_margaret_atwood",roles:["author"]}],["Ficção científica","Distopia","Ficção científica social"],["Corpo","Teocracia","Reprodução","Memória"],"Sob um regime teocrático que transforma fertilidade em propriedade de Estado, uma mulher registra os limites e as brechas de uma vida submetida à vigilância.","https://www.penguinrandomhouse.com/books/61256/the-handmaids-tale-by-margaret-atwood/"),
  work("never_let_me_go","nao-me-abandone-jamais","Never Let Me Go","Não Me Abandone Jamais","2005","Reino Unido","Inglês",[{personId:"person_kazuo_ishiguro",roles:["author"]}],["Ficção científica","Distopia","Biotecnologia"],["Clonagem","Cuidado","Memória","Ética médica"],"Três ex-alunos revisitam uma infância protegida demais e compreendem gradualmente o sistema que definiu seus corpos, expectativas e futuro.","https://www.faber.co.uk/product/9780571258093-never-let-me-go/"),
  work("stories_your_life","historia-da-sua-vida-e-outros-contos","Stories of Your Life and Others","História da Sua Vida e Outros Contos","2002","Estados Unidos","Inglês",[{personId:"person_ted_chiang",roles:["author"]}],["Ficção científica","Contos","Ficção científica filosófica"],["Linguagem","Tempo","Livre-arbítrio","Matemática"],"O volume reúne narrativas que tratam descoberta científica e especulação filosófica como problemas humanos de linguagem, escolha e responsabilidade.","https://www.penguinrandomhouse.com/books/549738/stories-of-your-life-and-others-by-ted-chiang/"),
  work("nova_delany","nova","Nova","Nova","1968","Estados Unidos","Inglês",[{personId:"person_samuel_r_delany",roles:["author"]}],["Ficção científica","Space opera","Ficção científica social"],["Classe","Trabalho","Mito","Energia"],"Uma disputa por uma fonte de energia estelar aproxima tripulações, aristocracias e trabalhadores em uma space opera atravessada por linguagem, desejo e desigualdade.","https://aleph.com.br/products/nova"),
  work("native_tongue","lingua-nativa","Native Tongue","Língua Nativa","1984","Estados Unidos","Inglês",[{personId:"person_suzette_haden_elgin",roles:["author"]}],["Ficção científica","Distopia","Ficção científica feminista"],["Linguagem","Patriarcado","Resistência","Tradução"],"Em um futuro que retirou direitos civis das mulheres, linguistas constroem clandestinamente uma linguagem capaz de sustentar outra forma de pensar e resistir.","https://aleph.com.br/products/lingua-nativa"),
  work("metropolis_harbou","metropolis","Metropolis","Metrópolis","1925","Alemanha","Alemão",[{personId:"person_thea_von_harbou",roles:["author"]}],["Ficção científica","Distopia","Ficção científica social"],["Cidade","Classe social","Trabalho","Tecnologia"],"Uma cidade vertical organiza riqueza e trabalho em espaços radicalmente separados, enquanto a promessa de conciliação revela tensões entre ordem industrial e vida humana.","https://aleph.com.br/products/metropolis"),
  work("female_man","a-mulher-homem","The Female Man",undefined,"1975","Estados Unidos","Inglês",[{personId:"person_joanna_russ",roles:["author"]}],["Ficção científica","Ficção científica feminista","Ficção científica social"],["Gênero","Mundos paralelos","Patriarcado","Identidade"],"Quatro versões de mulheres atravessam mundos alternativos para confrontar as estruturas sociais que fazem parecer natural a desigualdade de gênero.","https://www.penguinrandomhouse.com/books/65717/the-female-man-by-joanna-russ/"),
);

export const scienceFictionEditions:ReadingEdition[]=[
  edition("revelation_space_orbit","revelation_space","Revelation Space","org_little_brown","paperback","2020-06-02","9780316462440",560,"https://www.hachettebookgroup.com/titles/alastair-reynolds/revelation-space/9780316462440/"),
  edition("leviathan_wakes_orbit","leviathan_wakes","Leviathan Wakes","org_little_brown","paperback","2011-06-15","9780316129084",592,"https://www.hachettebookgroup.com/titles/james-s-a-corey/leviathan-wakes/9780316129084/"),
  edition("children_time_orbit","children_time","Children of Time","org_little_brown","paperback","2018-12-11","9780316452502",416,"https://www.hachettebookgroup.com/titles/adrian-tchaikovsky/children-of-time/9780316452502/"),
  edition("blindsight_tor","blindsight","Blindsight","org_macmillan","paperback","2020-03-03","9781250237484",384,"https://us.macmillan.com/books/9781250237484/blindsight/"),
  edition("mountain_sea_mcd","mountain_sea","The Mountain in the Sea","org_macmillan","hardcover","2022-10-04","9780374605964",464,"https://us.macmillan.com/books/9780374605964/themountaininthesea/"),
  edition("ancillary_justice_orbit","ancillary_justice","Ancillary Justice","org_little_brown","paperback","2013-10-01","9780316246637",432,"https://www.hachettebookgroup.com/titles/ann-leckie/ancillary-justice/9780316246637/"),
  edition("neuromancer_penguin","neuromancer","Neuromancer — Penguin Galaxy","org_penguin_publishing_group","hardcover","2016-10-25","9780143111603",304,"https://www.penguinrandomhouse.com/books/538861/neuromancer-by-william-gibson/"),
  edition("kindred_beacon","kindred","Kindred","org_beacon_press","paperback","2004-02-01","9780807083697",288,"https://openlibrary.org/isbn/9780807083697"),
  edition("three_body_tor","three_body_problem","The Three-Body Problem","org_macmillan","paperback","2016-01-12","9780765382030",416,"https://us.macmillan.com/books/9780765382030/thethreebodyproblem/"),
  edition("roadside_picnic_chicago","roadside_picnic","Roadside Picnic","org_chicago_review_press","paperback","2012-05-01","9781613743416",224,"https://www.chicagoreviewpress.com/roadside-picnic-products-9781613743416.php"),
  brazilianEdition("foundation_aleph","foundation","Fundação","2020-09-04","9788576574835",320,"https://aleph.com.br/products/fundacao","paperback"),
  brazilianEdition("solaris_aleph","solaris","Solaris","2021-01-25","9786586064360",320,"https://aleph.com.br/products/solaris","paperback"),
  brazilianEdition("left_hand_darkness_aleph","left_hand_darkness","A Mão Esquerda da Escuridão","2019-08-10","9788576574484",304,"https://aleph.com.br/products/a-mao-esquerda-da-escuridao"),
  brazilianEdition("dune_aleph","dune","Duna","2017-04-28","9788576573135",680,"https://aleph.com.br/products/duna-1"),
  brazilianEdition("nova_aleph","nova_delany","Nova","2023-06-15","9788576575504",296,"https://aleph.com.br/products/nova"),
  brazilianEdition("native_tongue_aleph","native_tongue","Língua Nativa","2023-05-10","9788576575603",440,"https://aleph.com.br/products/lingua-nativa"),
  brazilianEdition("metropolis_aleph","metropolis_harbou","Metrópolis","2019-10-30","9788576574552",416,"https://aleph.com.br/products/metropolis"),
];
