import type { ReadingEdition, ReadingSeries, ReadingWork } from "./readingSchema";

const checked="2026-08-24";
const source=(title:string,url:string)=>[{title,url}];
const series=(id:string,title:string,summary:string,url:string,status:ReadingSeries["publicationStatus"]="completed"):ReadingSeries=>({id:`read_series_${id}`,slug:id.replaceAll("_","-"),aliases:[],title,summary,kind:"narrative",publicationStatus:status,status:"published",sources:source(`${title} — editora`,url),createdAt:checked,updatedAt:checked});
const work=(id:string,slug:string,title:string,titleBr:string|undefined,year:string,country:string,language:string,credits:ReadingWork["credits"],genres:string[],themes:string[],description:string,url:string,memberships:ReadingWork["seriesMemberships"]=[]):ReadingWork=>({id:`read_work_${id}`,contentType:"reading-work",schemaVersion:1,slug,aliases:[],originalTitle:title,titleBr,format:"book",originCountries:[country],originalLanguages:[language],credits,organizationRelationships:[],publicationStart:year,publicationEnd:year,publicationStatus:"completed",categories:["fiction"],genres,themes,demographics:["adult"],shortDescription:description,seriesMemberships:memberships,relatedWorks:[],adaptations:[],sources:source(`${title} — editora`,url),status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked});
const edition=(id:string,workId:string,title:string,publisherId:string,medium:ReadingEdition["medium"],date:string,isbn13:string,pages:number,url:string):ReadingEdition=>({id:`read_edition_${id}`,workId:`read_work_${workId}`,title,publisherId,country:"Estados Unidos",language:"Inglês",medium,publicationDate:date,isbn13,pageCount:pages,availabilityStatus:"unknown",status:"published",sources:source(`${title} — edição verificada`,url),translationCredits:[],createdAt:checked,updatedAt:checked});

export const scienceFictionSeries:ReadingSeries[]=[
  series("inhibitor_sequence","Inhibitor Sequence","Ciclo de space opera e arqueologia cósmica em que ruínas alienígenas e máquinas antigas condicionam o futuro humano.","https://www.hachettebookgroup.com/series/alastair-reynolds/revelation-space/"),
  series("the_expanse","The Expanse","Série de space opera sobre a expansão humana pelo Sistema Solar, conflitos políticos e uma tecnologia extraterrestre que altera sua escala.","https://www.hachettebookgroup.com/series/james-s-a-corey/the-expanse/"),
  series("children_time","Children of Time","Série sobre evolução dirigida, ecologias não humanas e encontros entre civilizações com modos incompatíveis de perceber o mundo.","https://www.hachettebookgroup.com/series/adrian-tchaikovsky/children-of-time/","ongoing"),
  series("firefall","Firefall","Dilogia de ficção científica pós-humana sobre inteligência, consciência e contato com algo que pode não pensar como nós.","https://us.macmillan.com/series/firefall"),
  series("imperial_radch","Imperial Radch","Trilogia de space opera sobre uma inteligência de nave confinada a um corpo, império, identidade e vingança.","https://www.hachettebookgroup.com/series/ann-leckie/imperial-radch/"),
  series("sprawl","Sprawl","Trilogia cyberpunk de William Gibson sobre inteligências artificiais, corporações e vidas conectadas ao ciberespaço.","https://www.penguinrandomhouse.com/series/ZSW/sprawl-trilogy/"),
  series("remembrance_earths_past","Remembrance of Earth's Past","Trilogia de primeiro contato que amplia um problema científico terrestre até escalas históricas e cosmológicas.","https://us.macmillan.com/series/thethreebodyproblemseries"),
];

export const scienceFictionWorks:ReadingWork[]=[
  work("revelation_space","revelation-space","Revelation Space",undefined,"2000","Reino Unido","Inglês",[{personId:"person_alastair_reynolds",roles:["author"]}],["Ficção científica","Space opera","Horror espacial"],["Arqueologia extraterrestre","Civilizações antigas","Pós-humanismo","Isolamento"],"Uma arqueóloga investiga a extinção de uma civilização alienígena enquanto uma nave interestelar procura a tecnologia capaz de salvar seu capitão.","https://www.hachettebookgroup.com/titles/alastair-reynolds/revelation-space/9780316462440/",[{seriesId:"read_series_inhibitor_sequence",position:1}]),
  work("leviathan_wakes","leviathan-wakes","Leviathan Wakes","O Despertar do Leviatã","2011","Estados Unidos","Inglês",[{personId:"person_james_s_a_corey",roles:["author"]}],["Ficção científica","Space opera","Thriller"],["Sistema Solar","Primeiro contato","Política","Horror corporal"],"O desaparecimento de uma jovem liga uma tripulação civil e um detetive a uma conspiração capaz de romper o equilíbrio entre Terra, Marte e o Cinturão.","https://www.hachettebookgroup.com/titles/james-s-a-corey/leviathan-wakes/9780316129084/",[{seriesId:"read_series_the_expanse",position:1}]),
  work("children_time","children-of-time","Children of Time","Filhos do Tempo","2015","Reino Unido","Inglês",[{personId:"person_adrian_tchaikovsky",roles:["author"]}],["Ficção científica","Space opera","Biotecnologia"],["Evolução dirigida","Aranhas","Terraformação","Civilização"],"Os últimos humanos encontram um planeta terraformado onde um experimento evolutivo criou uma civilização que não estava nos planos de seus criadores.","https://www.hachettebookgroup.com/titles/adrian-tchaikovsky/children-of-time/9780316452502/",[{seriesId:"read_series_children_time",position:1}]),
  work("blindsight","blindsight-peter-watts","Blindsight",undefined,"2006","Canadá","Inglês",[{personId:"person_peter_watts",roles:["author"]}],["Ficção científica","Primeiro contato","Horror espacial"],["Consciência","Pós-humanismo","Alienígenas","Isolamento"],"Uma equipe de humanos radicalmente modificados viaja até um objeto desconhecido para descobrir se inteligência e consciência são realmente a mesma coisa.","https://us.macmillan.com/books/9781250237484/blindsight/",[{seriesId:"read_series_firefall",position:1}]),
  work("mountain_sea","the-mountain-in-the-sea","The Mountain in the Sea",undefined,"2022","Estados Unidos","Inglês",[{personId:"person_ray_nayler",roles:["author"]}],["Ficção científica","Thriller","Biotecnologia"],["Inteligência não humana","Polvos","IA","Ecologia"],"Uma bióloga marinha investiga uma população de polvos com linguagem própria numa reserva controlada por uma corporação tecnológica.","https://us.macmillan.com/books/9780374605964/themountaininthesea/"),
  work("ancillary_justice","ancillary-justice","Ancillary Justice","Justiça Ancilar","2013","Estados Unidos","Inglês",[{personId:"person_ann_leckie",roles:["author"]}],["Ficção científica","Space opera","Ficção científica militar"],["Inteligência artificial","Império","Identidade","Vingança"],"A consciência que antes ocupava uma nave militar e milhares de corpos sobrevive agora em apenas um corpo humano e procura acertar contas com o império que serviu.","https://www.hachettebookgroup.com/titles/ann-leckie/ancillary-justice/9780316246637/",[{seriesId:"read_series_imperial_radch",position:1}]),
  work("neuromancer","neuromancer","Neuromancer","Neuromancer","1984","Estados Unidos","Inglês",[{personId:"person_william_gibson",roles:["author"]}],["Ficção científica","Cyberpunk","Distopia"],["Ciberespaço","Inteligência artificial","Corporações","Pós-humanismo"],"Um hacker impedido de acessar o ciberespaço aceita um último trabalho que o coloca entre mercenários, corporações e inteligências artificiais com objetivos próprios.","https://www.penguinrandomhouse.com/books/538861/neuromancer-by-william-gibson/",[{seriesId:"read_series_sprawl",position:1}]),
  work("kindred","kindred-octavia-butler","Kindred","Kindred: Laços de Sangue","1979","Estados Unidos","Inglês",[{personId:"person_octavia_e_butler",roles:["author"]}],["Ficção científica","Viagem no tempo","Ficção histórica"],["Escravidão","Ancestralidade","Poder","Sobrevivência"],"Uma escritora negra de 1976 é repetidamente transportada para uma plantação no século XIX e precisa sobreviver à relação perigosa com um antepassado branco.","https://www.beacon.org/Kindred-P2085.aspx"),
  work("three_body_problem","the-three-body-problem","三体","O Problema dos Três Corpos","2008","China","Chinês",[{personId:"person_cixin_liu",roles:["author"]}],["Ficção científica","Primeiro contato","Ficção científica filosófica"],["Astrofísica","Civilização extraterrestre","História","Escala cósmica"],"Uma investigação sobre mortes de cientistas revela conexões entre a Revolução Cultural, um estranho jogo e um contato capaz de redefinir o futuro humano.","https://us.macmillan.com/books/9780765382030/thethreebodyproblem/",[{seriesId:"read_series_remembrance_earths_past",position:1}]),
  work("roadside_picnic","roadside-picnic","Пикник на обочине","Piquenique na Estrada","1972","União Soviética","Russo",[{personId:"person_arkady_strugatsky",roles:["author"]},{personId:"person_boris_strugatsky",roles:["author"]}],["Ficção científica","Ficção científica filosófica","Distopia"],["Artefatos alienígenas","Zona interditada","Desconhecido","Desejo"],"Após uma visita extraterrestre incompreensível, um contrabandista entra numa Zona proibida para recuperar artefatos cujas funções ninguém entende.","https://www.chicagoreviewpress.com/roadside-picnic-products-9781613743416.php"),
];

export const scienceFictionEditions:ReadingEdition[]=[
  edition("revelation_space_orbit","revelation_space","Revelation Space","org_little_brown","paperback","2020-06-02","9780316462440",560,"https://www.hachettebookgroup.com/titles/alastair-reynolds/revelation-space/9780316462440/"),
  edition("leviathan_wakes_orbit","leviathan_wakes","Leviathan Wakes","org_little_brown","paperback","2011-06-15","9780316129084",592,"https://www.hachettebookgroup.com/titles/james-s-a-corey/leviathan-wakes/9780316129084/"),
  edition("children_time_orbit","children_time","Children of Time","org_little_brown","paperback","2018-12-11","9780316452502",416,"https://www.hachettebookgroup.com/titles/adrian-tchaikovsky/children-of-time/9780316452502/"),
  edition("blindsight_tor","blindsight","Blindsight","org_macmillan","paperback","2020-03-03","9781250237484",384,"https://us.macmillan.com/books/9781250237484/blindsight/"),
  edition("mountain_sea_mcd","mountain_sea","The Mountain in the Sea","org_macmillan","hardcover","2022-10-04","9780374605964",464,"https://us.macmillan.com/books/9780374605964/themountaininthesea/"),
  edition("ancillary_justice_orbit","ancillary_justice","Ancillary Justice","org_little_brown","paperback","2013-10-01","9780316246637",432,"https://www.hachettebookgroup.com/titles/ann-leckie/ancillary-justice/9780316246637/"),
  edition("neuromancer_penguin","neuromancer","Neuromancer — Penguin Galaxy","org_penguin_publishing_group","hardcover","2016-10-25","9780143111603",304,"https://www.penguinrandomhouse.com/books/538861/neuromancer-by-william-gibson/"),
  edition("kindred_beacon","kindred","Kindred","org_beacon_press","paperback","2004-02-01","9780807083697",288,"https://openlibrary.org/isbn/9780807083697"),
  edition("three_body_tor","three_body_problem","The Three-Body Problem","org_macmillan","paperback","2016-01-12","9780765382030",416,"https://us.macmillan.com/books/9780765382030/thethreebodyproblem/"),
  edition("roadside_picnic_chicago","roadside_picnic","Roadside Picnic","org_chicago_review_press","paperback","2012-05-01","9781613743416",224,"https://www.chicagoreviewpress.com/roadside-picnic-products-9781613743416.php"),
];
