import type { ReadingWork } from "./readingSchema";

const checked="2026-08-24";
type Entry={id:string;slug:string;originalTitle:string;title:string;start:string;end?:string;status?:ReadingWork["publicationStatus"];credits:ReadingWork["credits"];genres:string[];themes:string[];description:string;sourceUrl:string;image:string;credit:string;portrait?:boolean};
const work=(e:Entry):ReadingWork=>({id:`read_work_${e.id}`,contentType:"reading-work",schemaVersion:1,slug:e.slug,aliases:[],originalTitle:e.originalTitle,titleBr:e.title,format:"manhwa",originCountries:["Coreia do Sul"],originalLanguages:["Coreano"],comicTradition:"manhwa",comicFormat:"webtoon",readingDirection:"vertical",credits:e.credits,organizationRelationships:[],publicationStart:e.start,publicationEnd:e.end,publicationStatus:e.status??(e.end?"completed":"ongoing"),categories:["comics"],genres:e.genres,themes:e.themes,demographics:["young-adult","adult"],shortDescription:e.description,seriesMemberships:[],relatedWorks:[],adaptations:[],image:{src:`/images/reading/system/${e.image}`,alt:`Capa ou arte promocional oficial de ${e.title}`,sourceUrl:e.sourceUrl,credit:e.credit,rights:"licensed",width:e.portrait?400:540,height:e.portrait?600:540},sources:[{title:`${e.title} — publicação oficial`,url:e.sourceUrl}],status:"published",publishedAt:checked,createdAt:checked,updatedAt:checked});

export const systemManhwaWorks:ReadingWork[]=[
  work({id:"solo_leveling",slug:"solo-leveling",originalTitle:"나 혼자만 레벨업",title:"Solo Leveling",start:"2018",end:"2023",credits:[{personId:"person_chugong",roles:["original-creator"]},{personId:"person_h_goon",roles:["writer","adapter"]},{personId:"person_dubu",roles:["artist"]}],genres:["Ação","Fantasia urbana","Sistema","Dungeon"],themes:["Leveling","Hunters","Classes","Quests"],description:"Um caçador de rank E recebe acesso exclusivo a uma interface que permite cumprir missões, distribuir atributos, equipar itens e subir de nível.",sourceUrl:"https://tapas.io/series/solo-leveling-comic/info",image:"solo-leveling-cover.jpg",credit:"Tapas / D&C WEBTOON Biz / REDICE STUDIO",portrait:true}),
  work({id:"omniscient_reader",slug:"omniscient-reader",originalTitle:"전지적 독자 시점",title:"Omniscient Reader",start:"2020",status:"hiatus",credits:[{personId:"person_singsong",roles:["original-creator"]},{personId:"person_umi_orv",roles:["writer","adapter"]},{personId:"person_sleepy_c",roles:["artist"]}],genres:["Ação","Fantasia urbana","Sistema","Apocalipse"],themes:["Cenários","Constelações","Skills","Probabilidade"],description:"Quando uma web novel vira realidade, Kim Dokja usa conhecimento dos cenários, recompensas e personagens para sobreviver às missões impostas por seres que assistem ao apocalipse.",sourceUrl:"https://www.webtoons.com/en/action/omniscient-reader/list?title_no=2154",image:"omniscient-reader-cover.jpg",credit:"WEBTOON / singNsong / UMI / Sleepy-C"}),
  work({id:"log_in_murim",slug:"log-in-murim",originalTitle:"로그인 무림",title:"Log-in Murim",start:"2020",status:"hiatus",credits:[{personId:"person_zero_big",roles:["original-creator"]},{personId:"person_iron_wall",roles:["artist","adapter"]}],genres:["Ação","Murim","Sistema","Dungeon"],themes:["Leveling","Hunters","Quests","Realidade virtual"],description:"Um hunter de baixo rank entra num mundo de Murim por um console e descobre que níveis, quests e treino marcial atravessam a fronteira entre jogo e realidade.",sourceUrl:"https://tapas.io/series/log-in-murim/info",image:"log-in-murim-cover.jpg",credit:"Tapas / KENAZ / Iron wall / Zero-BIG",portrait:true}),
  work({id:"surviving_game_barbarian",slug:"surviving-the-game-as-a-barbarian",originalTitle:"게임 속 바바리안으로 살아남기",title:"Surviving the Game as a Barbarian",start:"2023",status:"hiatus",credits:[{personId:"person_jung_yoon_kang",roles:["original-creator"]},{personId:"person_team_the_jick",roles:["writer","adapter"]},{personId:"person_midnight_studio",roles:["artist"]}],genres:["Ação","Fantasia","Sistema","Sobrevivência"],themes:["Dungeon","RPG","Equipamentos","Build"],description:"Um veterano de um RPG difícil desperta como um bárbaro dentro do jogo e precisa transformar conhecimento de builds, monstros e recursos numa estratégia de sobrevivência.",sourceUrl:"https://www.webtoons.com/en/fantasy/surviving-the-game-as-a-barbarian/list?title_no=5515",image:"surviving-game-barbarian-cover.jpg",credit:"WEBTOON / Jung Yoon-kang / Team the JICK / MIDNIGHT STUDIO"}),
];
