import type { ServiceExample } from "./serviceExampleSchema";

export const serviceExamples: ServiceExample[] = [
  {
    id: "psychology-elisa-veral",
    slug: "psicologia",
    status: "published",
    order: 1,
    featured: true,
    updatedAt: "2026-09-09",
    title: "Elisa Veral",
    segment: "Psicologia",
    solutionType: "institutional",
    shortDescription: "Um site sereno para apresentar o atendimento e facilitar o primeiro contato.",
    tags: ["Modalidades", "FAQ", "Formulário"],
    decisions: [
      { title: "Informação antes do formulário", description: "Modalidades e etapas aparecem antes do contato para diminuir dúvidas práticas." },
      { title: "Ritmo de leitura calmo", description: "Texto curto, margens amplas e contraste suave sustentam uma leitura sem pressa." },
      { title: "Sequência contínua no celular", description: "A versão móvel preserva a hierarquia sem transformar o conteúdo em miniaturas." },
    ],
    visualStyle: {
      label: "Editorial serena em verde profundo, argila e papel claro",
      themeKey: "psychology-elisa-veral",
    },
    featureIds: ["whatsapp", "form", "faq", "social", "seo"],
    coverImage: {
      src: "/images/services/examples/psicologia-elisa-veral.webp",
      alt: "Prévia do site demonstrativo de Psicologia de Elisa Veral, identidade fictícia.",
      mobileSrc: "/images/services/examples/psicologia-elisa-veral-mobile.webp",
    },
    images: [
      { src: "/images/services/site-arquitetos/interiores.webp", alt: "Interior claro usado como imagem ambiental na demonstração de Psicologia." },
    ],
    rendererKey: "psychology-elisa-veral",
    seo: { index: false },
  },
  {
    id: "architecture-planobruto-17",
    slug: "arquitetura",
    status: "published",
    order: 2,
    featured: true,
    updatedAt: "2026-09-09",
    title: "Plano Bruto 17",
    segment: "Arquitetura",
    solutionType: "portfolio",
    shortDescription: "Um portfólio visual que deixa os projetos ocuparem o primeiro plano.",
    tags: ["Filtro de projetos", "Galerias", "Páginas internas"],
    decisions: [
      { title: "Projetos em primeiro plano", description: "As imagens chegam antes da apresentação do estúdio e conduzem a navegação." },
      { title: "Profundidade por projeto", description: "Cada estudo abre uma página própria com ficha, contexto e galeria visual." },
      { title: "Escala preservada no celular", description: "Títulos, filtros e fotografias se reorganizam sem imitar a grade do desktop." },
    ],
    visualStyle: {
      label: "Editorial arquitetônica em preto mineral, branco quente e acento ácido",
      themeKey: "architecture-planobruto-17",
    },
    featureIds: ["portfolio-gallery", "social", "seo"],
    coverImage: {
      src: "/images/services/examples/arquitetura-planobruto-17.webp",
      alt: "Prévia do portfólio demonstrativo de arquitetura Plano Bruto 17, estúdio fictício.",
      mobileSrc: "/images/services/examples/arquitetura-planobruto-17-mobile.webp",
    },
    images: [
      { src: "/images/services/site-arquitetos/residencial.webp", alt: "Residência usada no estudo demonstrativo Casa Pátio 06." },
      { src: "/images/services/site-arquitetos/interiores.webp", alt: "Interior usado no estudo demonstrativo Interior Linha 02." },
      { src: "/images/services/site-arquitetos/cultural.webp", alt: "Edifício cultural usado no estudo demonstrativo Centro Arco 11." },
    ],
    rendererKey: "architecture-planobruto-17",
    seo: { index: false },
  },
  {
    id: "barbershop-traco-84",
    slug: "barbearia",
    status: "published",
    order: 3,
    featured: true,
    updatedAt: "2026-09-09",
    title: "Traço 84",
    segment: "Negócio local",
    solutionType: "local-business",
    shortDescription: "Serviços, horários e localização organizados em um caminho direto.",
    tags: ["Preços", "Agendamento", "Localização"],
    decisions: [
      { title: "Escolha sem adivinhação", description: "Serviço, duração e valor permanecem juntos durante o agendamento demonstrativo." },
      { title: "Informação local visível", description: "Endereço e horários aparecem antes do contato final, onde são mais úteis." },
      { title: "Fluxo adequado ao toque", description: "No celular, serviço e horário viram uma sequência curta e fácil de conferir." },
    ],
    visualStyle: {
      label: "Lifestyle urbana em azul elétrico, coral e creme",
      themeKey: "barbershop-traco-84",
    },
    featureIds: ["whatsapp", "portfolio-gallery", "services-prices", "location-map", "hours", "scheduling", "seo"],
    coverImage: {
      src: "/images/services/examples/barbearia-traco-84.webp",
      alt: "Prévia do site demonstrativo de barbearia Traço 84, negócio fictício.",
      mobileSrc: "/images/services/examples/barbearia-traco-84-mobile.webp",
    },
    images: [
      { src: "/images/services/barbearia-demo/hero.webp", alt: "Profissional finalizando um corte na abertura da demonstração." },
      { src: "/images/services/barbearia-demo/ambiente.webp", alt: "Ambiente de barbearia usado na galeria demonstrativa." },
      { src: "/images/services/barbearia-demo/equipe.webp", alt: "Profissionais em barbearia usados na seção demonstrativa de equipe." },
    ],
    rendererKey: "barbershop-traco-84",
    seo: { index: false },
  },
];
