import type { ServiceExample } from "./serviceExampleSchema";

export const serviceExamples: ServiceExample[] = [
  {
    id: "psychology-elisa-veral",
    slug: "psicologia",
    status: "published",
    order: 1,
    featured: true,
    updatedAt: "2026-09-09",
    title: "Elisa Veral",
    segment: "Psicologia",
    solutionType: "institutional",
    shortDescription: "Site institucional para psicóloga, com modalidades de atendimento, etapas, FAQ e contato.",
    tags: ["Modalidades", "FAQ", "Formulário"],
    decisions: [
      { title: "Informação antes do formulário", description: "Modalidades e etapas aparecem antes do contato para diminuir dúvidas práticas." },
      { title: "Ritmo de leitura calmo", description: "Texto curto, margens amplas e contraste suave sustentam uma leitura sem pressa." },
      { title: "Sequência contínua no celular", description: "A versão móvel preserva a hierarquia sem transformar o conteúdo em miniaturas." },
    ],
    visualStyle: {
      label: "Editorial serena em verde profundo, argila e papel claro",
      themeKey: "psychology-elisa-veral",
    },
    featureIds: ["whatsapp", "form", "faq", "social", "seo"],
    coverImage: {
      src: "/images/services/examples/psicologia-elisa-veral.webp",
      alt: "Prévia do site demonstrativo de Psicologia de Elisa Veral, identidade fictícia.",
      mobileSrc: "/images/services/examples/psicologia-elisa-veral-mobile.webp",
    },
    images: [
      { src: "/images/services/site-arquitetos/interiores.webp", alt: "Interior claro usado como imagem ambiental na demonstração de Psicologia." },
    ],
    rendererKey: "psychology-elisa-veral",
    seo: { index: false },
  },
  {
    id: "nail-studio-tinta",
    slug: "estudio-unhas",
    status: "published",
    order: 2,
    featured: true,
    updatedAt: "2026-09-30",
    title: "Tinta",
    segment: "Estúdio de unhas",
    solutionType: "local-business",
    shortDescription: "Site para estúdio de unhas, com serviços, trabalhos, informações do atendimento e agendamento demonstrativo.",
    tags: ["Serviços e valores", "Galeria", "Agendamento"],
    decisions: [
      { title: "Marca reconhecível", description: "Nome, paleta, tipografia e fotografia formam uma identidade própria antes da lista de serviços." },
      { title: "Escolha com informação", description: "Serviço, duração e valor ilustrativo permanecem juntos para facilitar a comparação." },
      { title: "Fotografia em outra escala", description: "No celular, imagens e títulos ganham proporção própria sem comprimir a composição desktop." },
    ],
    visualStyle: {
      label: "Editorial tátil em osso, ameixa, ferrugem e tons naturais de pele",
      themeKey: "nail-studio-tinta",
    },
    featureIds: ["scheduling", "portfolio-gallery", "services-prices", "hours", "social", "seo"],
    coverImage: {
      src: "/images/services/examples/estudio-unhas-tinta.webp",
      alt: "Prévia do site demonstrativo Tinta, estúdio de unhas fictício com fotografia de manicure e identidade editorial.",
      mobileSrc: "/images/services/examples/estudio-unhas-tinta-mobile.webp",
    },
    images: [
      { src: "/images/services/nail-studio-demo/hero-manicure.webp", alt: "Manicure aplicando esmalte vinho em unhas curtas." },
      { src: "/images/services/nail-studio-demo/trabalho-ferrugem.webp", alt: "Unhas curtas em nude e ferrugem com francesinha fina." },
      { src: "/images/services/nail-studio-demo/trabalho-vinho.webp", alt: "Unhas curtas em vinho profundo com uma linha curva clara." },
      { src: "/images/services/nail-studio-demo/trabalho-cacau.webp", alt: "Duas mãos com esmaltação curta em tons de cacau." },
      { src: "/images/services/nail-studio-demo/estudio.webp", alt: "Bancada demonstrativa de um estúdio de unhas." },
    ],
    rendererKey: "nail-studio-tinta",
    seo: { index: false },
  },
  {
    id: "barbershop-traco-84",
    slug: "barbearia",
    status: "published",
    order: 3,
    featured: true,
    updatedAt: "2026-09-09",
    title: "Traço 84",
    segment: "Negócio local",
    solutionType: "local-business",
    shortDescription: "Site para barbearia, com serviços, preços, horários, localização e agendamento demonstrativo.",
    tags: ["Preços", "Agendamento", "Localização"],
    decisions: [
      { title: "Escolha sem adivinhação", description: "Serviço, duração e valor permanecem juntos durante o agendamento demonstrativo." },
      { title: "Informação local visível", description: "Endereço e horários aparecem antes do contato final, onde são mais úteis." },
      { title: "Fluxo adequado ao toque", description: "No celular, serviço e horário viram uma sequência curta e fácil de conferir." },
    ],
    visualStyle: {
      label: "Lifestyle urbana em azul elétrico, coral e creme",
      themeKey: "barbershop-traco-84",
    },
    featureIds: ["whatsapp", "portfolio-gallery", "services-prices", "location-map", "hours", "scheduling", "seo"],
    coverImage: {
      src: "/images/services/examples/barbearia-traco-84.webp",
      alt: "Prévia do site demonstrativo de barbearia Traço 84, negócio fictício.",
      mobileSrc: "/images/services/examples/barbearia-traco-84-mobile.webp",
    },
    images: [
      { src: "/images/services/barbearia-demo/hero.webp", alt: "Profissional finalizando um corte na abertura da demonstração." },
      { src: "/images/services/barbearia-demo/ambiente.webp", alt: "Ambiente de barbearia usado na galeria demonstrativa." },
      { src: "/images/services/barbearia-demo/equipe.webp", alt: "Profissionais em barbearia usados na seção demonstrativa de equipe." },
    ],
    rendererKey: "barbershop-traco-84",
    seo: { index: false },
  },
];
