import type { MovieSeed } from "./movies";

const checked="2026-08-27";
const source=(title:string,slug:string)=>[{title:`${title} — referência cinematográfica`,url:`https://en.wikipedia.org/wiki/${slug}`}];
const movie=(id:string,slug:string,titleBr:string,originalTitle:string,year:number,durationMinutes:number,countries:string[],directors:string[],genres:string[],themes:string[],description:string,extra:Partial<MovieSeed>={}):MovieSeed=>({id,slug,aliases:[],titleBr,originalTitle,year,durationMinutes,countries,directors,genres,subgenres:["Filme-catástrofe"],themes,shortDescription:description,audienceProfile:"Para quem procura uma abordagem diretamente ligada ao desastre e aceita o estilo do período e da produção.",experience:"Tenso e orientado pela catástrofe",contentWarnings:["Desastre","Mortes"],sources:source(originalTitle,encodeURIComponent(originalTitle.replaceAll(" ","_"))),...extra});

export const disasterClusterMovieSeeds:MovieSeed[]=[
  movie("mov_cluster_deep_impact_1998","impacto-profundo","Impacto Profundo","Deep Impact",1998,121,["Estados Unidos"],["Mimi Leder"],["Ficção científica","Drama"],["Cometa","Tsunami","Extinção"],"A descoberta de um cometa em rota de colisão leva a uma missão espacial, à construção de abrigos e à preparação pública para um impacto global."),
  movie("mov_cluster_2012_2009","2012-filme","2012","2012",2009,158,["Estados Unidos"],["Roland Emmerich"],["Ação","Ficção científica"],["Terremoto","Tsunami","Erupção vulcânica"],"Uma família tenta alcançar embarcações de sobrevivência enquanto uma sucessão fantasiosa de colapsos geológicos transforma o planeta."),
  movie("mov_cluster_hereafter_2010","alem-da-vida","Além da Vida","Hereafter",2010,129,["Estados Unidos"],["Clint Eastwood"],["Drama","Fantasia"],["Tsunami","Luto","Morte"],"Três histórias sobre morte e perda se cruzam depois que uma jornalista sobrevive ao tsunami do oceano Índico."),
  movie("mov_cluster_fukushima_50_2020","fukushima-50","Fukushima 50","Fukushima 50",2020,122,["Japão"],["Setsurō Wakamatsu"],["Drama"],["Terremoto","Tsunami","Acidente nuclear"],"Trabalhadores permanecem na usina de Fukushima Daiichi após o terremoto e o tsunami de 2011 interromperem sistemas essenciais."),
  movie("mov_cluster_earthquake_1974","terremoto-1974","Terremoto","Earthquake",1974,122,["Estados Unidos"],["Mark Robson"],["Ação","Drama"],["Terremoto","Los Angeles","Resgate"],"Um grande terremoto atinge Los Angeles e cruza conflitos pessoais com operações de resgate e destruição urbana."),
  movie("mov_cluster_aftershock_2010","terremoto-a-furia-da-natureza","Terremoto: A Fúria da Natureza","唐山大地震",2010,135,["China"],["Feng Xiaogang"],["Drama"],["Terremoto de Tangshan","Família","Trauma"],"Uma decisão impossível durante o terremoto de Tangshan separa uma família e produz consequências que atravessam décadas."),
  movie("mov_cluster_aftershock_2012","aftershock-2012","Aftershock","Aftershock",2012,89,["Estados Unidos","Chile"],["Nicolás López"],["Terror","Suspense"],["Terremoto","Colapso social","Sobrevivência"],"Turistas em Valparaíso sobrevivem a um terremoto e encontram uma cidade em que infraestrutura e ordem social entram em colapso."),
  movie("mov_cluster_volcano_1997","volcano-a-furia","Volcano: A Fúria","Volcano",1997,104,["Estados Unidos"],["Mick Jackson"],["Ação","Drama"],["Erupção vulcânica","Los Angeles","Lava"],"Uma abertura vulcânica surge sob Los Angeles e força equipes municipais a improvisar barreiras contra o fluxo de lava."),
  movie("mov_cluster_pompeii_2014","pompeia-2014","Pompeia","Pompeii",2014,105,["Canadá","Alemanha"],["Paul W. S. Anderson"],["Ação","Drama"],["Vesúvio","Pompeia","Erupção vulcânica"],"Um gladiador tenta alcançar a mulher que ama enquanto a erupção do Vesúvio destrói Pompeia."),
  movie("mov_cluster_skyfire_2019","skyfire","Skyfire","天·火",2019,97,["China"],["Simon West"],["Ação"],["Erupção vulcânica","Ilha","Resgate"],"Cientistas e turistas tentam escapar quando um resort construído numa ilha vulcânica é atingido por uma erupção explosiva."),
  movie("mov_cluster_when_time_ran_out_1980","when-time-ran-out","When Time Ran Out","When Time Ran Out...",1980,121,["Estados Unidos"],["James Goldstone"],["Ação","Drama"],["Erupção vulcânica","Resort","Evacuação"],"Hóspedes e trabalhadores de um resort precisam atravessar uma ilha depois que alertas sobre o vulcão são ignorados."),
  movie("mov_cluster_into_inferno_2016","dentro-do-inferno","Dentro do Inferno","Into the Inferno",2016,107,["Reino Unido","Alemanha"],["Werner Herzog"],["Documentário"],["Vulcões","Ciência","Cultura"],"Werner Herzog e o vulcanólogo Clive Oppenheimer visitam comunidades que vivem próximas a vulcões ativos."),
  movie("mov_cluster_whakaari_2022","o-vulcao-resgate-em-whakaari","O Vulcão: Resgate em Whakaari","The Volcano: Rescue from Whakaari",2022,98,["Estados Unidos"],["Rory Kennedy"],["Documentário"],["Whakaari","Erupção vulcânica","Resgate"],"Sobreviventes e socorristas reconstituem a erupção de Whakaari, na Nova Zelândia, em 2019."),
  movie("mov_cluster_into_storm_2014","no-olho-do-tornado","No Olho do Tornado","Into the Storm",2014,89,["Estados Unidos"],["Steven Quale"],["Ação","Suspense"],["Tornado","Found footage","Resgate"],"Moradores, estudantes e caçadores de tempestades registram uma sequência de tornados que atinge uma pequena cidade."),
  movie("mov_cluster_hurricane_heist_2018","furacao-categoria-5","Furacão: Categoria 5","The Hurricane Heist",2018,103,["Estados Unidos"],["Rob Cohen"],["Ação"],["Furacão","Roubo","Evacuação"],"Um roubo ao Tesouro acontece durante a evacuação de uma cidade ameaçada por um furacão de categoria máxima."),
  movie("mov_cluster_geostorm_2017","geostorm","Tempestade: Planeta em Fúria","Geostorm",2017,109,["Estados Unidos"],["Dean Devlin"],["Ação","Ficção científica"],["Supertempestade","Satélite","Conspiração"],"Uma rede de satélites criada para controlar o clima começa a produzir desastres enquanto uma conspiração ameaça o planeta."),
  movie("mov_cluster_13_minutes_2021","13-minutos","13 Minutos","13 Minutes",2021,108,["Estados Unidos"],["Lindsay Gossling"],["Drama","Suspense"],["Tornado","Comunidade","Abrigo"],"Quatro famílias têm poucos minutos para procurar abrigo antes de um tornado atravessar uma cidade de Oklahoma."),
  movie("mov_cluster_night_twisters_1996","a-noite-dos-tornados","A Noite dos Tornados","Night of the Twisters",1996,92,["Estados Unidos","Canadá"],["Timothy Bond"],["Drama"],["Tornado","Família","Telefilme"],"Uma família tenta se reunir quando uma sequência de tornados atinge a cidade de Grand Island durante a noite.",{releaseType:"television"}),
  movie("mov_cluster_finest_hours_2016","horas-decisivas","Horas Decisivas","The Finest Hours",2016,117,["Estados Unidos"],["Craig Gillespie"],["Drama","Ação"],["Tempestade marítima","Resgate","Guarda Costeira"],"Uma pequena equipe da Guarda Costeira enfrenta uma tempestade para alcançar tripulantes presos num petroleiro partido ao meio."),
  movie("mov_cluster_adrift_2018","a-deriva-2018","À Deriva","Adrift",2018,96,["Estados Unidos","Islândia"],["Baltasar Kormákur"],["Drama","Aventura"],["Furacão","Sobrevivência marítima","Relacionamento"],"Um casal atravessa o Pacífico e precisa sobreviver depois que um furacão destrói o veleiro."),
  movie("mov_cluster_armageddon_1998","armageddon","Armageddon","Armageddon",1998,151,["Estados Unidos"],["Michael Bay"],["Ação","Ficção científica"],["Asteroide","Missão espacial","Extinção"],"Perfuradores de petróleo são enviados ao espaço para implantar uma bomba num asteroide em rota de colisão com a Terra."),
  movie("mov_cluster_greenland_2020","greenland-o-ultimo-refugio","Greenland: O Último Refúgio","Greenland",2020,119,["Estados Unidos"],["Ric Roman Waugh"],["Suspense","Ação"],["Cometa","Abrigo","Família"],"Uma família tenta alcançar um abrigo governamental enquanto fragmentos de um cometa atingem cidades e desorganizam a sociedade."),
  movie("mov_cluster_dont_look_up_2021","nao-olhe-para-cima","Não Olhe para Cima","Don't Look Up",2021,138,["Estados Unidos"],["Adam McKay"],["Comédia","Drama"],["Cometa","Mídia","Negacionismo"],"Dois astrônomos tentam comunicar a descoberta de um cometa destruidor num ambiente político e midiático incapaz de responder."),
  movie("mov_cluster_meteor_1979","meteoro-1979","Meteoro","Meteor",1979,107,["Estados Unidos"],["Ronald Neame"],["Ficção científica","Ação"],["Asteroide","Guerra Fria","Cooperação"],"Estados Unidos e União Soviética precisam cooperar para desviar um grande asteroide em direção à Terra."),
  movie("mov_cluster_wandering_earth_2019","terra-a-deriva","Terra à Deriva","流浪地球",2019,125,["China"],["Frant Gwo"],["Ficção científica","Ação"],["Colisão planetária","Engenharia","Sobrevivência"],"Motores gigantes movem a Terra para longe do Sol, mas a aproximação de Júpiter ameaça destruir o planeta."),
  movie("mov_cluster_alive_1993","vivos-1993","Vivos","Alive",1993,126,["Estados Unidos"],["Frank Marshall"],["Drama","Aventura"],["Acidente aéreo","Andes","Sobrevivência"],"A adaptação de 1993 acompanha sobreviventes do voo 571 e enfatiza decisões práticas diante do isolamento nos Andes."),
  movie("mov_cluster_flight_2012","o-voo","O Voo","Flight",2012,138,["Estados Unidos"],["Robert Zemeckis"],["Drama"],["Acidente aéreo","Investigação","Dependência química"],"Um piloto realiza uma manobra extraordinária durante uma pane, mas a investigação expõe sua dependência de álcool e drogas."),
  movie("mov_cluster_cast_away_2000","naufrago","Náufrago","Cast Away",2000,143,["Estados Unidos"],["Robert Zemeckis"],["Drama","Aventura"],["Acidente aéreo","Ilha","Isolamento"],"Um funcionário sobrevive à queda de um avião cargueiro e passa anos sozinho numa ilha do Pacífico."),
  movie("mov_cluster_grey_2011","a-perseguicao","A Perseguição","The Grey",2011,117,["Estados Unidos"],["Joe Carnahan"],["Aventura","Drama"],["Acidente aéreo","Alasca","Sobrevivência"],"Trabalhadores sobrevivem a uma queda no Alasca e atravessam frio, ferimentos e território de lobos."),
  movie("mov_cluster_sully_2016","sully-o-heroi-do-rio-hudson","Sully: O Herói do Rio Hudson","Sully",2016,96,["Estados Unidos"],["Clint Eastwood"],["Drama","Biografia"],["Pouso de emergência","Investigação","Aviação"],"O pouso do voo 1549 no rio Hudson é reconstituído junto à investigação que examinou as decisões da tripulação."),
  movie("mov_cluster_united_93_2006","voo-united-93","Voo United 93","United 93",2006,111,["Estados Unidos","Reino Unido"],["Paul Greengrass"],["Drama","História"],["Voo 93","11 de Setembro","Reconstrução"],"O filme reconstrói o voo United 93 e as respostas civis e institucionais durante os ataques de 11 de setembro."),
  movie("mov_cluster_plane_2023","alerta-maximo","Alerta Máximo","Plane",2023,107,["Estados Unidos","Reino Unido"],["Jean-François Richet"],["Ação","Suspense"],["Pouso de emergência","Ilha","Resgate"],"Um piloto pousa numa ilha após uma tempestade e precisa proteger passageiros em uma região controlada por homens armados."),
  movie("mov_cluster_six_days_1998","seis-dias-sete-noites","Seis Dias, Sete Noites","Six Days, Seven Nights",1998,102,["Estados Unidos"],["Ivan Reitman"],["Aventura","Comédia"],["Queda de avião","Ilha","Sobrevivência"],"Uma editora e um piloto ficam presos numa ilha depois que uma tempestade força a queda do pequeno avião."),
  movie("mov_cluster_flight_phoenix_1965","o-voo-do-fenix-1965","O Voo do Fênix","The Flight of the Phoenix",1965,142,["Estados Unidos"],["Robert Aldrich"],["Aventura","Drama"],["Acidente aéreo","Deserto","Engenharia"],"Sobreviventes de uma queda no Saara tentam construir uma aeronave menor com os destroços do avião."),
  movie("mov_cluster_fearless_1993","sem-medo-de-viver","Sem Medo de Viver","Fearless",1993,122,["Estados Unidos"],["Peter Weir"],["Drama"],["Acidente aéreo","Trauma","Sobreviventes"],"Depois de sobreviver a uma queda, um arquiteto se sente invulnerável e se afasta da família enquanto outra passageira enfrenta o luto."),
];
