import { MovieBatchSchema, type Movie } from "./movieSchema";
import { ghibliMovieSeeds } from "./ghibliMovies";
import { laikaMovieSeeds } from "./laikaMovies";
import { posterCatalog } from "./posters";

export type MovieSeed = Pick<
  Movie,
  | "slug"
  | "titleBr"
  | "originalTitle"
  | "year"
  | "durationMinutes"
  | "countries"
  | "directors"
  | "genres"
  | "subgenres"
  | "themes"
  | "shortDescription"
  | "audienceProfile"
  | "experience"
  | "contentWarnings"
  | "sources"
> & Partial<Pick<Movie, "internationalTitle" | "releaseDate" | "screenwriters" | "credits" | "releaseType" | "productionStatus">> & {
  id?: string;
  aliases?: string[];
  poster?: Movie["poster"];
  organizationRelationships?: Movie["organizationRelationships"];
};

const movieIds: Record<string, string> = {
  "corra": "mov_7c1f3a", "hereditario": "mov_b40e92", "a-bruxa": "mov_2d815f",
  "o-lamento": "mov_ae39c4", "deixe-ela-entrar": "mov_91f72b", "rec": "mov_3c085e",
  "exterminio": "mov_d12a77", "a-substancia": "mov_68be30", "o-babadook": "mov_f51942",
  "corrente-do-mal": "mov_0b84dd", "o-hospedeiro": "mov_c71a05", "invasao-zumbi": "mov_46ed93",
  "kairo": "mov_823fa1", "medo": "mov_19c6be", "abismo-do-medo": "mov_e4507c",
  "martires": "mov_5a2d91", "grave": "mov_a38f04", "o-segredo-da-cabana": "mov_6d90ce",
  "o-homem-invisivel": "mov_14eb79", "fale-comigo": "mov_b731d8", "quando-o-mal-espreita": "mov_97a260",
  "pecadores": "mov_30cf85", "atividade-paranormal": "mov_dd418e", "host-2020": "mov_75b3ac",
  "x-a-marca-da-morte": "mov_08e6f1", "as-boas-maneiras": "mov_ca273d", "one-cut-of-the-dead": "mov_4f9b62",
  "o-que-ficou-para-tras": "mov_62d0a9", "jogos-mortais": "mov_eb8514", "sob-a-pele": "mov_1a74cf",
};

const bfiHorror = "https://www.bfi.org.uk/lists/great-horror-film-from-every-year-from-1922-now";
const bfiModern = "https://www.bfi.org.uk/lists/10-great-horror-films-2010s";
const cannesWailing = "https://www.festival-cannes.com/en/f/goksung/";
const cannesSubstance = "https://www.festival-cannes.com/f/the-substance/";
const sundanceHorror =
  "https://www.sundance.org/blogs/from-the-blair-witch-project-to-hereditary-how-the-sundance-film-festival-defined-modern-horror/";

const source = (title: string, url = bfiHorror) => [{ title, url }];

const seeds: MovieSeed[] = [
  { slug: "corra", titleBr: "Corra!", originalTitle: "Get Out", year: 2017, durationMinutes: 104, countries: ["Estados Unidos"], directors: ["Jordan Peele"], genres: ["Terror", "Suspense"], subgenres: ["Terror social", "Psicológico"], themes: ["Racismo", "Apropriação", "Identidade"], shortDescription: "Uma visita familiar transforma códigos sociais aparentemente cordiais em uma ameaça construída sobre controle e apropriação.", audienceProfile: "Boa entrada para quem prefere suspense, sátira e comentário social a violência constante.", experience: "Tensão crescente, humor desconfortável e mistério", contentWarnings: ["Racismo", "Violência", "Procedimentos médicos"], sources: source("Get Out — BFI", bfiModern) },
  { slug: "hereditario", titleBr: "Hereditário", originalTitle: "Hereditary", year: 2018, durationMinutes: 127, countries: ["Estados Unidos"], directors: ["Ari Aster"], genres: ["Terror", "Drama"], subgenres: ["Sobrenatural", "Psicológico"], themes: ["Luto", "Família", "Herança"], shortDescription: "O luto de uma família abre espaço para conflitos antigos e uma ameaça sobrenatural observada com rigor formal.", audienceProfile: "Para quem aceita uma construção lenta e emocionalmente pesada antes do horror mais explícito.", experience: "Opresso, gradual e perturbador", contentWarnings: ["Luto", "Morte de criança", "Automutilação"], sources: source("Hereditary — BFI", "https://www.bfi.org.uk/film/e397cbb2-d8e4-5138-9f5d-12d49deef199/hereditary") },
  { slug: "a-bruxa", titleBr: "A Bruxa", originalTitle: "The Witch: A New-England Folktale", year: 2015, durationMinutes: 92, countries: ["Estados Unidos", "Canadá"], directors: ["Robert Eggers"], genres: ["Terror"], subgenres: ["Folk horror", "Histórico"], themes: ["Religião", "Repressão", "Família"], shortDescription: "Uma família puritana isolada interpreta sua ruína material e afetiva por meio das crenças do século XVII.", audienceProfile: "Para quem gosta de atmosfera, linguagem de época e terror de combustão lenta.", experience: "Austero, lento e atmosférico", contentWarnings: ["Morte infantil", "Fanatismo religioso", "Violência contra animais"], sources: source("The Witch — BFI", "https://whatson.bfi.org.uk/imax/Online/default.asp?BOparam%3A%3AWScontent%3A%3AloadArticle%3A%3Apermalink=witch-imax") },
  { slug: "o-lamento", titleBr: "O Lamento", originalTitle: "Goksung", year: 2016, durationMinutes: 156, countries: ["Coreia do Sul", "Estados Unidos"], directors: ["Na Hong-jin"], genres: ["Terror", "Suspense"], subgenres: ["Folk horror", "Possessão"], themes: ["Rumor", "Fé", "Preconceito"], shortDescription: "Uma investigação rural mistura doença, ritual e suspeita enquanto cada explicação corrói a anterior.", audienceProfile: "Para espectadores pacientes que apreciam ambiguidade e mudanças de tom.", experience: "Longo, febril e desorientador", contentWarnings: ["Violência", "Doença", "Criança em sofrimento"], sources: source("Goksung — Festival de Cannes", cannesWailing) },
  { slug: "deixe-ela-entrar", titleBr: "Deixe Ela Entrar", originalTitle: "Låt den rätte komma in", year: 2008, durationMinutes: 114, countries: ["Suécia"], directors: ["Tomas Alfredson"], genres: ["Terror", "Drama"], subgenres: ["Vampiro"], themes: ["Solidão", "Dependência", "Infância"], shortDescription: "A aproximação entre duas crianças renova o mito do vampiro com afeto, violência e ambiguidade moral.", audienceProfile: "Para quem prefere atmosfera e relações complexas a ação constante.", experience: "Melancólico, frio e íntimo", contentWarnings: ["Bullying", "Violência envolvendo crianças", "Abuso"], sources: source("Let the Right One In — BFI", "https://www.bfi.org.uk/lists/10-great-horror-films-21st-century") },
  { slug: "rec", titleBr: "[REC]", originalTitle: "[REC]", year: 2007, durationMinutes: 78, countries: ["Espanha"], directors: ["Jaume Balagueró", "Paco Plaza"], genres: ["Terror"], subgenres: ["Found footage", "Possessão"], themes: ["Contaminação", "Confinamento"], shortDescription: "Uma equipe de reportagem fica presa em um edifício onde uma emergência sanitária muda rapidamente de natureza.", audienceProfile: "Para quem busca found footage curto, intenso e sem pausas longas.", experience: "Urgente, claustrofóbico e instável", contentWarnings: ["Câmera trêmula", "Violência", "Contaminação"], sources: source("[REC] — BFI") },
  { slug: "exterminio", titleBr: "Extermínio", originalTitle: "28 Days Later…", year: 2002, durationMinutes: 113, countries: ["Reino Unido"], directors: ["Danny Boyle"], genres: ["Terror", "Ficção científica"], subgenres: ["Infectados", "Apocalipse"], themes: ["Colapso social", "Sobrevivência"], shortDescription: "Uma epidemia esvazia Londres e força sobreviventes a enfrentar tanto infectados velozes quanto novas formas de violência organizada.", audienceProfile: "Para fãs de apocalipse que valorizam personagens e comentário social.", experience: "Áspero, urgente e melancólico", contentWarnings: ["Violência", "Ameaça sexual", "Epidemia"], sources: source("28 Days Later — BFI") },
  { slug: "a-substancia", titleBr: "A Substância", originalTitle: "The Substance", year: 2024, durationMinutes: 141, countries: ["Reino Unido", "Estados Unidos", "França"], directors: ["Coralie Fargeat"], genres: ["Terror", "Sátira"], subgenres: ["Body horror"], themes: ["Envelhecimento", "Imagem corporal", "Indústria do entretenimento"], shortDescription: "Uma promessa de juventude perfeita leva a cobrança sobre o corpo até uma escala grotesca e deliberadamente excessiva.", audienceProfile: "Para quem aprecia sátira frontal e efeitos corporais extremos.", experience: "Excessivo, tátil e cômico", contentWarnings: ["Gore extremo", "Nudez", "Distorção corporal"], sources: source("The Substance — Festival de Cannes", cannesSubstance) },
  { slug: "o-babadook", titleBr: "O Babadook", originalTitle: "The Babadook", year: 2014, durationMinutes: 94, countries: ["Austrália", "Canadá"], directors: ["Jennifer Kent"], genres: ["Terror", "Drama"], subgenres: ["Psicológico", "Sobrenatural"], themes: ["Luto", "Maternidade", "Exaustão"], shortDescription: "Um livro infantil perturbador materializa tensões de uma mãe exausta e de seu filho em luto.", audienceProfile: "Para quem gosta de monstros ligados a conflitos emocionais sem explicação redutora.", experience: "Claustrofóbico e emocional", contentWarnings: ["Luto", "Violência doméstica", "Ameaça a criança e animal"], sources: source("The Babadook — BFI", "https://www.bfi.org.uk/lists/10-great-supernatural-horror-films-21st-century") },
  { slug: "corrente-do-mal", titleBr: "Corrente do Mal", originalTitle: "It Follows", year: 2014, durationMinutes: 100, countries: ["Estados Unidos"], directors: ["David Robert Mitchell"], genres: ["Terror"], subgenres: ["Sobrenatural", "Perseguição"], themes: ["Sexualidade", "Ansiedade", "Responsabilidade"], shortDescription: "Uma ameaça transmitida sexualmente transforma figuras ao fundo do quadro em fontes permanentes de dúvida.", audienceProfile: "Para quem prefere ansiedade contínua e metáforas abertas a explicações fechadas.", experience: "Hipnótico, suburbano e inquieto", contentWarnings: ["Coerção sexual", "Nudez", "Imagens perturbadoras"], sources: source("It Follows — BFI") },
  { slug: "o-hospedeiro", titleBr: "O Hospedeiro", originalTitle: "Gwoemul", year: 2006, durationMinutes: 120, countries: ["Coreia do Sul"], directors: ["Bong Joon-ho"], genres: ["Terror", "Ação", "Comédia"], subgenres: ["Monstro", "Terror social"], themes: ["Família", "Desastre", "Instituições"], shortDescription: "Uma criatura no rio Han obriga uma família desajustada a agir em meio à incompetência institucional.", audienceProfile: "Para quem gosta de monstros, ação e sátira convivendo com melodrama familiar.", experience: "Dinâmico, estranho e emotivo", contentWarnings: ["Morte", "Violência contra crianças", "Doença"], sources: source("The Host — Korean Film Archive", "https://www.koreanfilm.or.kr/eng/films/index/filmsView.jsp?movieCd=20060151") },
  { slug: "invasao-zumbi", titleBr: "Invasão Zumbi", originalTitle: "Busanhaeng", year: 2016, durationMinutes: 118, countries: ["Coreia do Sul"], directors: ["Yeon Sang-ho"], genres: ["Terror", "Ação"], subgenres: ["Zumbi", "Sobrevivência"], themes: ["Família", "Solidariedade", "Classe"], shortDescription: "Uma epidemia dentro de um trem combina ação legível, infectados velozes e decisões coletivas com peso emocional.", audienceProfile: "Entrada acessível para quem quer tensão contínua e personagens claros.", experience: "Veloz, físico e emotivo", contentWarnings: ["Violência intensa", "Mortes", "Crianças em perigo"], sources: source("Train to Busan — Festival de Cannes", "https://www.festival-cannes.com/en/retrospective/2016/") },
  { slug: "kairo", titleBr: "Kairo", originalTitle: "Kairo", year: 2001, durationMinutes: 119, countries: ["Japão"], directors: ["Kiyoshi Kurosawa"], genres: ["Terror"], subgenres: ["J-horror", "Tecnológico"], themes: ["Solidão", "Internet", "Desaparecimento"], shortDescription: "Fantasmas e conexões digitais espalham uma solidão que parece contaminar gradualmente o mundo físico.", audienceProfile: "Para quem aceita ritmo lento, tecnologia datada e lógica de pesadelo.", experience: "Lento, vazio e profundamente melancólico", contentWarnings: ["Suicídio", "Depressão", "Desesperança"], sources: source("Pulse — BFI", "https://www.bfi.org.uk/lists/10-great-horror-films-21st-century") },
  { slug: "medo", titleBr: "Medo", originalTitle: "Janghwa, Hongryeon", year: 2003, durationMinutes: 115, countries: ["Coreia do Sul"], directors: ["Kim Jee-woon"], genres: ["Terror", "Drama"], subgenres: ["Gótico", "Psicológico"], themes: ["Família", "Memória", "Culpa"], shortDescription: "Duas irmãs retornam para casa e encontram relações familiares atravessadas por memória, hostilidade e assombração.", audienceProfile: "Para quem gosta de melodrama gótico, composição visual e narrativa fragmentada.", experience: "Elegante, triste e ambíguo", contentWarnings: ["Luto", "Violência familiar", "Saúde mental"], sources: source("A Tale of Two Sisters — Korean Film Archive", "https://www.koreanfilm.or.kr/eng/films/index/filmsView.jsp?movieCd=20030046") },
  { slug: "abismo-do-medo", titleBr: "Abismo do Medo", originalTitle: "The Descent", year: 2005, durationMinutes: 99, countries: ["Reino Unido"], directors: ["Neil Marshall"], genres: ["Terror", "Aventura"], subgenres: ["Sobrevivência", "Criatura"], themes: ["Luto", "Confinamento", "Amizade"], shortDescription: "Uma expedição subterrânea transforma geografia, escuridão e fraturas entre amigas em ameaça física.", audienceProfile: "Para fãs de sobrevivência, criaturas e claustrofobia intensa.", experience: "Claustrofóbico e brutal", contentWarnings: ["Violência gráfica", "Luto", "Confinamento extremo"], sources: source("The Descent — BFI", "https://player.bfi.org.uk/subscription/film/watch-the-descent-2005-online") },
  { slug: "martires", titleBr: "Mártires", originalTitle: "Martyrs", year: 2008, durationMinutes: 99, countries: ["França", "Canadá"], directors: ["Pascal Laugier"], genres: ["Terror"], subgenres: ["Extremo", "Body horror"], themes: ["Trauma", "Violência", "Transcendência"], shortDescription: "Uma busca por vingança conduz a um projeto de violência sistemática e a uma pergunta extrema sobre sofrimento.", audienceProfile: "Recomendação restrita a espectadores preparados para violência prolongada.", experience: "Implacável, gráfico e desesperador", contentWarnings: ["Tortura extrema", "Automutilação", "Abuso infantil"], sources: source("Martyrs — BFI", "https://www.bfi.org.uk/lists/10-great-horror-films-21st-century") },
  { slug: "grave", titleBr: "Grave", originalTitle: "Grave", year: 2016, durationMinutes: 99, countries: ["França", "Bélgica"], directors: ["Julia Ducournau"], genres: ["Terror", "Drama"], subgenres: ["Body horror"], themes: ["Desejo", "Identidade", "Amadurecimento"], shortDescription: "A entrada numa faculdade de veterinária desperta um apetite que aproxima corpo, desejo e transformação.", audienceProfile: "Boa porta para o body horror contemporâneo, desde que sangue não seja um limite.", experience: "Físico, sensual e desconfortável", contentWarnings: ["Canibalismo", "Ferimentos", "Trotes violentos"], sources: source("Raw — Festival de Cannes", "https://www.festival-cannes.com/en/f/grave/") },
  { slug: "o-segredo-da-cabana", titleBr: "O Segredo da Cabana", originalTitle: "The Cabin in the Woods", year: 2011, durationMinutes: 95, countries: ["Estados Unidos"], directors: ["Drew Goddard"], genres: ["Terror", "Comédia"], subgenres: ["Metalinguagem", "Slasher"], themes: ["Controle", "Rituais", "Convenções de gênero"], shortDescription: "Uma viagem de jovens a uma cabana desmonta, com humor e escala crescente, as engrenagens do terror comercial.", audienceProfile: "Funciona melhor para quem já conhece convenções e arquétipos do gênero.", experience: "Irônico, acelerado e expansivo", contentWarnings: ["Violência gráfica", "Drogas", "Mortes em massa"], sources: source("The Cabin in the Woods — BFI", "https://www.bfi.org.uk/film/5ef8954e-0988-5f4d-8d9b-7552cc913e40/the-cabin-in-the-woods") },
  { slug: "o-homem-invisivel", titleBr: "O Homem Invisível", originalTitle: "The Invisible Man", year: 2020, durationMinutes: 124, countries: ["Estados Unidos", "Austrália"], directors: ["Leigh Whannell"], genres: ["Terror", "Ficção científica"], subgenres: ["Perseguição", "Psicológico"], themes: ["Abuso", "Controle", "Descrédito"], shortDescription: "A invisibilidade transforma abuso e vigilância em ameaça espacial, explorando o que o quadro aparentemente vazio pode esconder.", audienceProfile: "Para quem busca suspense acessível com tensão sustentada e tema de abuso coercitivo.", experience: "Tenso, preciso e paranoico", contentWarnings: ["Abuso doméstico", "Suicídio", "Violência"], sources: source("The Invisible Man — Universal Pictures", "https://www.universalpictures.com/movies/the-invisible-man") },
  { slug: "fale-comigo", titleBr: "Fale Comigo", originalTitle: "Talk to Me", year: 2022, durationMinutes: 95, countries: ["Austrália"], directors: ["Danny Philippou", "Michael Philippou"], genres: ["Terror"], subgenres: ["Possessão", "Adolescente"], themes: ["Luto", "Pressão social", "Vício"], shortDescription: "Adolescentes transformam possessão em ritual social até que o jogo atravesse limites afetivos e físicos.", audienceProfile: "Para quem quer horror contemporâneo direto, com personagens jovens e consequências reais.", experience: "Enérgico, físico e emocional", contentWarnings: ["Automutilação", "Luto", "Violência envolvendo menores"], sources: source("Talk to Me — Screen Australia", "https://www.screenaustralia.gov.au/the-screen-guide/t/talk-to-me-2022/40332/") },
  { slug: "quando-o-mal-espreita", titleBr: "Quando o Mal Espreita", originalTitle: "Cuando acecha la maldad", year: 2023, durationMinutes: 99, countries: ["Argentina", "Estados Unidos"], directors: ["Demián Rugna"], genres: ["Terror"], subgenres: ["Possessão", "Horror rural"], themes: ["Contaminação", "Comunidade", "Regras"], shortDescription: "Uma forma de possessão se espalha por uma comunidade rural onde todos conhecem regras incompletas.", audienceProfile: "Para espectadores atrás de horror agressivo, cruel e imprevisível.", experience: "Brutal, rural e desesperado", contentWarnings: ["Violência extrema", "Animais", "Crianças em perigo"], sources: source("When Evil Lurks — Sitges", "https://sitgesfilmfestival.com/en/film/2023/cuando-acecha-la-maldad") },
  { slug: "pecadores", titleBr: "Pecadores", originalTitle: "Sinners", year: 2025, durationMinutes: 137, countries: ["Estados Unidos"], directors: ["Ryan Coogler"], genres: ["Terror", "Drama", "Musical"], subgenres: ["Vampiro", "Gótico sulista"], themes: ["Música", "Comunidade", "Apropriação cultural"], shortDescription: "Dois irmãos abrem um clube no Mississippi e encontram uma ameaça vampírica ligada à música, à comunidade e à história.", audienceProfile: "Para quem aceita mistura ampla de drama histórico, música, ação e horror.", experience: "Musical, expansivo e sangrento", contentWarnings: ["Violência gráfica", "Racismo", "Morte"], sources: source("Sinners — Warner Bros.", "https://www.warnerbros.com/movies/sinners") },
  { slug: "atividade-paranormal", titleBr: "Atividade Paranormal", originalTitle: "Paranormal Activity", year: 2007, durationMinutes: 86, countries: ["Estados Unidos"], directors: ["Oren Peli"], genres: ["Terror"], subgenres: ["Found footage", "Sobrenatural"], themes: ["Vigilância", "Casa", "Relacionamento"], shortDescription: "Câmeras domésticas registram pequenas alterações noturnas que transformam repetição e espera em ameaça.", audienceProfile: "Para quem aceita minimalismo, poucos efeitos e tensão baseada em antecipação.", experience: "Minimalista, repetitivo e crescente", contentWarnings: ["Possessão", "Violência doméstica", "Sustos repentinos"], sources: source("Paranormal Activity — Sundance Institute", sundanceHorror) },
  { slug: "host-2020", titleBr: "Host", originalTitle: "Host", year: 2020, durationMinutes: 57, countries: ["Reino Unido"], directors: ["Rob Savage"], genres: ["Terror"], subgenres: ["Screenlife", "Sobrenatural"], themes: ["Isolamento", "Tecnologia"], shortDescription: "Uma sessão espírita por chamada de vídeo usa os limites da tela como espaço de assombração.", audienceProfile: "Para quem procura uma sessão curta e sustos bem preparados.", experience: "Curto, direto e digital", contentWarnings: ["Sustos repentinos", "Ferimentos"], sources: source("Host — BFI", "https://www.bfi.org.uk/sight-and-sound/reviews/host-zoom-horror-lockdown") },
  { slug: "x-a-marca-da-morte", titleBr: "X: A Marca da Morte", originalTitle: "X", year: 2022, durationMinutes: 106, countries: ["Estados Unidos", "Canadá"], directors: ["Ti West"], genres: ["Terror"], subgenres: ["Slasher"], themes: ["Envelhecimento", "Desejo", "Imagem"], shortDescription: "Uma produção adulta numa fazenda recupera o slasher rural para confrontar juventude, desejo e envelhecimento.", audienceProfile: "Para fãs de slashers que aceitam uma primeira metade deliberada.", experience: "Paciente e depois sangrento", contentWarnings: ["Violência gráfica", "Sexo", "Envelhecimento"], sources: source("X — A24", "https://a24films.com/films/x") },
  { slug: "as-boas-maneiras", titleBr: "As Boas Maneiras", originalTitle: "As Boas Maneiras", year: 2017, durationMinutes: 135, countries: ["Brasil", "França"], directors: ["Juliana Rojas", "Marco Dutra"], genres: ["Terror", "Drama", "Musical"], subgenres: ["Fantástico", "Criatura"], themes: ["Classe", "Maternidade", "Desejo"], shortDescription: "Uma fábula paulistana combina trabalho doméstico, romance, maternidade e uma criatura clássica.", audienceProfile: "Para quem prefere fantasia sombria e melodrama a sustos constantes.", experience: "Contemplativo, fabuloso e afetivo", contentWarnings: ["Gravidez", "Sangue", "Crianças em perigo"], sources: source("As Boas Maneiras — ANCINE", "https://www.gov.br/ancine/pt-br/assuntos/noticias/ancine-apoia-presenca-de-18-filmes-em-14-eventos-internacionais-em-outubro") },
  { slug: "one-cut-of-the-dead", titleBr: "One Cut of the Dead", originalTitle: "Kamera o Tomeru na!", year: 2017, durationMinutes: 96, countries: ["Japão"], directors: ["Shinichiro Ueda"], genres: ["Terror", "Comédia"], subgenres: ["Zumbi", "Metalinguagem"], themes: ["Cinema", "Trabalho coletivo", "Improviso"], shortDescription: "Uma filmagem de zumbis aparentemente desastrada revela uma engenharia cômica sobre colaboração e improviso.", audienceProfile: "Para quem tolera uma abertura irregular em troca de uma grande mudança de perspectiva.", experience: "Inventivo, alegre e metalinguístico", contentWarnings: ["Violência caricatural"], sources: source("One Cut of the Dead — BFI", bfiModern) },
  { slug: "o-que-ficou-para-tras", titleBr: "O Que Ficou Para Trás", originalTitle: "His House", year: 2020, durationMinutes: 93, countries: ["Reino Unido"], directors: ["Remi Weekes"], genres: ["Terror", "Drama"], subgenres: ["Casa assombrada", "Sobrenatural"], themes: ["Refúgio", "Culpa", "Burocracia"], shortDescription: "Um casal refugiado enfrenta uma nova casa, a burocracia britânica e aquilo que trouxe consigo.", audienceProfile: "Para quem busca horror sobrenatural com conflito político e emocional concreto.", experience: "Sombrio, íntimo e moralmente difícil", contentWarnings: ["Guerra", "Morte de criança", "Luto"], sources: source("His House — BFI", "https://www.bfi.org.uk/lists/10-great-supernatural-horror-films-21st-century") },
  { slug: "jogos-mortais", titleBr: "Jogos Mortais", originalTitle: "Saw", year: 2004, durationMinutes: 103, countries: ["Estados Unidos"], directors: ["James Wan"], genres: ["Terror", "Suspense"], subgenres: ["Armadilhas"], themes: ["Sobrevivência", "Culpa", "Punição"], shortDescription: "Duas pessoas acordam presas em um banheiro e precisam compreender um jogo de punição construído ao redor delas.", audienceProfile: "Para fãs de mistério macabro que aceitam violência e estética marcada pelos anos 2000.", experience: "Nervoso, fechado e gráfico", contentWarnings: ["Tortura", "Automutilação", "Violência gráfica"], sources: source("Saw — Sundance Institute", sundanceHorror) },
  { slug: "sob-a-pele", titleBr: "Sob a Pele", originalTitle: "Under the Skin", year: 2013, durationMinutes: 108, countries: ["Reino Unido", "Estados Unidos", "Suíça"], directors: ["Jonathan Glazer"], genres: ["Terror", "Ficção científica"], subgenres: ["Experimental"], themes: ["Corpo", "Desejo", "Humanidade"], shortDescription: "Um olhar não humano percorre a Escócia e aprende a observar, atrair e habitar corpos.", audienceProfile: "Para quem aceita narrativa rarefeita, diálogos escassos e forte experimentação audiovisual.", experience: "Abstrato, lento e alienígena", contentWarnings: ["Nudez", "Violência sexual", "Afogamento"], sources: source("Under the Skin — BFI", "https://www.bfi.org.uk/film/155d7690-bc57-50ef-8d2f-eaf1e7102ae9/under-the-skin") },
  ...ghibliMovieSeeds,
  ...laikaMovieSeeds,
];

const rawMovies = seeds.map((movie) => ({
  ...movie,
  id: movie.id ?? movieIds[movie.slug],
  contentType: "movie" as const,
  schemaVersion: 1,
  aliases: movie.aliases ?? [],
  createdAt: "2026-08-10",
  updatedAt: "2026-08-11",
  relatedContentIds: [],
  format: "feature" as const,
  credits: movie.credits ?? [],
  organizationRelationships: movie.organizationRelationships ?? [],
  poster: movie.poster ?? posterCatalog[movie.slug as keyof typeof posterCatalog],
  status: "draft" as const,
  seo: {
    title: `${movie.titleBr}: ficha e análise do filme`,
    description: `${movie.titleBr} (${movie.year}): informações verificadas, estilo, temas, público provável e artigos em que o filme aparece.`,
  },
}));

export const movies = MovieBatchSchema.parse(rawMovies);

export const moviesBySlug = new Map(movies.map((movie) => [movie.slug, movie]));

export function getMovie(slug: string) {
  return moviesBySlug.get(slug);
}

export function getPublishedMovies() {
  return movies.filter((movie) => movie.status === "published");
}
