import type { Product, ProductOffer, ProductVariant } from "./productSchema";

const checked = "2026-09-05";
type Category = "Projetores" | "Fones Bluetooth" | "Webcams";
type Seed = { key:string; name:string; maker:string; line:string; category:Category; image:string; imageUrl:string; source:string; price:number; retailer:string; specs:Record<string,string>; strength:string; limit:string; profile:string };
const articles:Record<Category,string[]> = {Projetores:["melhores-projetores-2026"],"Fones Bluetooth":["melhores-fones-bluetooth-ate-300-2026"],Webcams:["melhores-webcams-2026"]};
const seeds:Seed[] = [
{key:"epson_co_w01",name:"Epson EpiqVision Flex CO-W01",maker:"epson",line:"EpiqVision Flex",category:"Projetores",image:"projectors/epson-co-w01.jpg",imageUrl:"https://mediaserver.goepson.com/adaptivemedia/rendition?id=9339938eadbd2005f9e7367b0c016577322d8ecf",source:"https://epson.com.br/Para-casa/Projetores/Entretenimento-em-casa/Projetor-Epson-EpiqVision-Flex-CO-W01/p/V11HA86020",price:3499,retailer:"Epson Brasil",specs:{Resolução:"WXGA nativa (1280 × 800)",Brilho:"3.000 lúmens ISO em branco e cores",Tecnologia:"3LCD",Áudio:"5 W"},strength:"Brilho alto e 3LCD atendem sala com algum controle de luz.",limit:"Não é Full HD nativo e exige fonte externa para streaming.",profile:"Apresentações, esportes e tela grande em sala."},
{key:"epson_fh02",name:"Epson EpiqVision Flex CO-FH02",maker:"epson",line:"EpiqVision Flex",category:"Projetores",image:"projectors/epson-fh02.jpg",imageUrl:"https://mediaserver.goepson.com/adaptivemedia/rendition?id=21b6a5a5cea27656b5c52ca305496f92fdef2a2f",source:"https://epson.com.br/Para-casa/Projetores/Entretenimento-em-casa/Projetor-Epson-EpiqVision-Flex-FH02/p/V11HA85020",price:4699,retailer:"Epson Brasil",specs:{Resolução:"Full HD nativa",Brilho:"3.000 lúmens ISO em branco e cores",Tecnologia:"3LCD",Sistema:"Android TV em módulo incluso"},strength:"Full HD nativo, brilho e streaming integrado formam um conjunto versátil.",limit:"Sem recursos gamer avançados ou zoom óptico amplo.",profile:"Filmes e séries em quarto ou sala."},
{key:"benq_th575",name:"BenQ TH575",maker:"benq",line:"Home Entertainment",category:"Projetores",image:"projectors/benq-th575.jpg",imageUrl:"https://image.benq.com/is/image/benqco/th575-right30-1",source:"https://www.benq.com/pt-br/projector/cinema/th575.html",price:4999,retailer:"Varejo brasileiro",specs:{Resolução:"Full HD nativa",Brilho:"3.800 ANSI lúmens declarados",Tecnologia:"DLP",Jogos:"16,7 ms declarados a 1080p/60"},strength:"Brilho e atraso documentado o tornam a opção mais coerente para consoles.",limit:"Não tem sistema inteligente completo e DLP pode gerar efeito arco-íris.",profile:"Console, esportes e sala com luz controlada."},
{key:"xiaomi_smart_projector_l1",name:"Xiaomi Smart Projector L1",maker:"xiaomi",line:"Smart Projector",category:"Projetores",image:"projectors/xiaomi-smart-projector-l1.jpg",imageUrl:"https://i02.appmifile.com/254_operatorx_operatorx_opx/29/11/2024/5f723cedd2d609518676a33cad29d216.png",source:"https://www.mi.com/global/product/xiaomi-smart-projector-l1/",price:2599,retailer:"Varejo brasileiro",specs:{Resolução:"Full HD nativa",Brilho:"200 lúmens ISO declarados",Sistema:"Google TV",Projeção:"40 a 120 polegadas declaradas"},strength:"É compacto e integra Google TV, foco e correção automática.",limit:"O brilho exige quarto escuro e a garantia varia por vendedor.",profile:"Quarto escuro e uso portátil dentro de casa."},
{key:"redmi_buds_6_play",name:"Redmi Buds 6 Play",maker:"xiaomi",line:"Redmi Buds",category:"Fones Bluetooth",image:"headphones/redmi-buds-6-play.jpg",imageUrl:"https://i02.appmifile.com/640_operatorx_operatorx_opx/02/09/2024/2e17e2f72632d75847bdb47d5cee20bc.png",source:"https://www.mi.com/br/product/redmi-buds-6-play/",price:129,retailer:"Varejo brasileiro",specs:{Formato:"TWS intra-auricular",Bateria:"Até 7,5 h; 36 h com estojo",Codec:"AAC e SBC",Proteção:"IPX4"},strength:"Aplicativo, autonomia e IPX4 formam uma entrada barata coerente.",limit:"Não possui cancelamento ativo de ruído.",profile:"Uso cotidiano e academia com orçamento mínimo."},
{key:"redmi_buds_6_lite",name:"Redmi Buds 6 Lite",maker:"xiaomi",line:"Redmi Buds",category:"Fones Bluetooth",image:"headphones/redmi-buds-6-lite.jpg",imageUrl:"https://i02.appmifile.com/103_operatorx_operatorx_opx/15/08/2024/dc0880f52cfb9fa67d1d000b54c9582e.png",source:"https://www.mi.com/br/product/redmi-buds-6-lite/",price:229,retailer:"Varejo brasileiro",specs:{Formato:"TWS intra-auricular",ANC:"Até 40 dB declarados",Bateria:"Até 7 h; 38 h com estojo",Codec:"AAC e SBC"},strength:"ANC e aplicativo criam o pacote mais equilibrado abaixo de R$ 250.",limit:"O ANC depende da vedação e não há codec de alta resolução.",profile:"Transporte, estudo e trabalho."},
{key:"qcy_melobuds_pro",name:"QCY MeloBuds Pro",maker:"qcy",line:"MeloBuds",category:"Fones Bluetooth",image:"headphones/qcy-melobuds-pro.jpg",imageUrl:"https://www.qcy.com/cdn/shop/files/HT08_-1_aca60518-7636-48a3-adf8-a2df012c997b.png",source:"https://www.qcy.com/products/qcy-melobuds-pro",price:299,retailer:"Varejo brasileiro",specs:{Formato:"TWS intra-auricular",ANC:"Adaptativo, até 46 dB declarados",Codec:"LDAC, AAC e SBC",Conexão:"Bluetooth 5.3 e multiponto"},strength:"LDAC, multiponto e ANC adaptativo são raros no teto de R$ 300.",limit:"Assistência e garantia dependem do importador ou revendedor.",profile:"Android, deslocamentos e quem prioriza recursos."},
{key:"edifier_w800bt_pro",name:"Edifier W800BT Pro",maker:"edifier",line:"W800BT",category:"Fones Bluetooth",image:"headphones/edifier-w800bt-pro.jpg",imageUrl:"https://new-edifier-us-oss.edifier.com/images/20240719/432bffb3d61f8a5a530972fa68282305.png",source:"https://www.edifier.com/global/p/over-ear-on-ear-headphones/w800bt-pro",price:299,retailer:"Varejo brasileiro",specs:{Formato:"Over-ear",ANC:"Cancelamento ativo",Bateria:"Até 45 h sem ANC; 26 h com ANC",Codec:"LDAC, AAC e SBC"},strength:"Conforto over-ear, bateria e LDAC atendem longas sessões.",limit:"É volumoso para academia e o microfone não substitui headset dedicado.",profile:"Trabalho, estudo e música em casa."},
{key:"samsung_galaxy_buds_core",name:"Samsung Galaxy Buds Core",maker:"samsung_electronics",line:"Galaxy Buds",category:"Fones Bluetooth",image:"headphones/samsung-galaxy-buds-core.jpg",imageUrl:"https://images.samsung.com/is/image/samsung/p6pim/br/sm-r410nzkazto/gallery/br-galaxy-buds-core-r410-sm-r410nzkazto-549069343",source:"https://www.samsung.com/br/audio-sound/galaxy-buds/galaxy-buds-core-black-sm-r410nzkazto/",price:299,retailer:"Samsung Brasil",specs:{Formato:"TWS intra-auricular",ANC:"Cancelamento ativo",Bateria:"Até 20 h totais com ANC; 35 h sem ANC",Proteção:"IP54"},strength:"Integração Galaxy, ANC e IP54 formam uma escolha segura em promoção.",limit:"Recursos e codecs favorecem aparelhos Samsung.",profile:"Usuário de celular Galaxy e chamadas cotidianas."},
{key:"logitech_c270",name:"Logitech C270",maker:"logitech",line:"C-Series",category:"Webcams",image:"webcams/logitech-c270.jpg",imageUrl:"https://resource.logitech.com/content/dam/logitech/en/products/webcams/c270/gallery/c270-gallery-1.png",source:"https://www.logitech.com/pt-br/products/webcams/c270-hd-webcam.960-000694.html",price:169,retailer:"Varejo brasileiro",specs:{Vídeo:"720p a 30 fps",Foco:"Fixo",Campo:"55°",Microfone:"Mono"},strength:"É barata e suficiente para chamadas em janela pequena.",limit:"720p, foco fixo e campo estreito limitam criação e pouca luz.",profile:"Aulas e reuniões ocasionais."},
{key:"logitech_brio_100",name:"Logitech Brio 100",maker:"logitech",line:"Brio",category:"Webcams",image:"webcams/logitech-brio-100.jpg",imageUrl:"https://resource.logitech.com/content/dam/logitech/en/products/webcams/brio-100/gallery/brio-100-gallery-offwhite-1.png",source:"https://www.logitech.com/pt-br/products/webcams/brio-100-webcam.960-001592.html",price:249,retailer:"Varejo brasileiro",specs:{Vídeo:"1080p a 30 fps",Foco:"Fixo",Campo:"58°",Privacidade:"Obturador integrado"},strength:"Full HD e obturador melhoram o básico sem encarecer muito.",limit:"Foco fixo e 30 fps não são ideais para objetos próximos ou movimento.",profile:"Home office e aulas."},
{key:"logitech_c920s",name:"Logitech C920s",maker:"logitech",line:"C-Series",category:"Webcams",image:"webcams/logitech-c920s.jpg",imageUrl:"https://resource.logitech.com/content/dam/logitech/en/products/webcams/c920s/gallery/c920s-gallery-1.png",source:"https://www.logitech.com/pt-br/products/webcams/c920s-pro-hd-webcam.960-001257.html",price:399,retailer:"Varejo brasileiro",specs:{Vídeo:"1080p a 30 fps",Foco:"Autofocus",Campo:"78°",Microfone:"Estéreo"},strength:"Autofocus e campo de 78° explicam sua longevidade.",limit:"Não entrega 60 fps nem USB-C.",profile:"Reuniões frequentes, aulas e streaming inicial."},
{key:"logitech_brio_500",name:"Logitech Brio 500",maker:"logitech",line:"Brio",category:"Webcams",image:"webcams/logitech-brio-500.jpg",imageUrl:"https://resource.logitech.com/content/dam/logitech/en/products/webcams/brio-500/gallery/brio-500-gallery-graphite-1.png",source:"https://www.logitech.com/pt-br/products/webcams/brio-500-webcam.960-001422.html",price:599,retailer:"Varejo brasileiro",specs:{Vídeo:"1080p30; 720p60",Foco:"Autofocus",Campo:"65°, 78° ou 90°",Conexão:"USB-C"},strength:"Campo ajustável, exposição e 720p60 atendem home office avançado.",limit:"Continua limitada a 1080p30 na resolução máxima.",profile:"Apresentações, equipes híbridas e criação casual."},
{key:"elgato_facecam_neo",name:"Elgato Facecam Neo",maker:"elgato",line:"Neo",category:"Webcams",image:"webcams/elgato-facecam-neo.jpg",imageUrl:"https://images.ctfassets.net/h50kqpe25yx1/46LfEQDMPjY6poywWOsERl/fd105594d5bcf8c5733466898dfab62b/social-graph-NEO-Facecam.jpg",source:"https://www.elgato.com/us/en/p/facecam-neo",price:699,retailer:"Varejo brasileiro",specs:{Vídeo:"1080p a 60 fps",Foco:"Fixo otimizado",Campo:"77°",Software:"Camera Hub"},strength:"1080p60 e controles no Camera Hub servem melhor ao streaming.",limit:"Não possui microfone e o foco fixo não favorece objetos muito próximos.",profile:"Streaming e criação com microfone separado."},
];
const image=(s:Seed)=>({src:`/images/products/${s.image}`,alt:`${s.name} em imagem oficial do fabricante`,sourceUrl:s.imageUrl,credit:s.maker.replaceAll("_"," "),rights:"official-promotional" as const,width:1000,height:1000});
export const audiovisualProducts:Product[]=seeds.map(s=>({id:`prod_${s.key}`,contentType:"product",schemaVersion:1,slug:s.key.replaceAll("_","-"),aliases:[],name:s.name,manufacturerId:`org_${s.maker}`,line:s.line,category:s.category,mainImage:image(s),gallery:[],shortDescription:`${s.name}: ${s.profile} Especificações e preço observados no mercado brasileiro.`,strengths:[s.strength],limitations:[s.limit],suitableFor:[s.profile],categories:[s.category,"Eletrônicos"],tags:Object.values(s.specs),relatedProductIds:[],relatedArticleSlugs:articles[s.category],editorialSummary:`${s.strength} Limitação: ${s.limit}`,seo:{title:`${s.name}: ficha, análise e ofertas`,description:`Ficha de ${s.name} com especificações, limitações e preço observado no Brasil.`},sources:[{title:`${s.name} — página oficial`,url:s.source,accessedAt:checked}],status:"published",createdAt:checked,publishedAt:checked,updatedAt:checked,reviewedAt:checked}));
export const audiovisualVariants:ProductVariant[]=seeds.map(s=>({id:`prod_variant_${s.key}_br`,productId:`prod_${s.key}`,name:"Versão pesquisada para o mercado brasileiro",market:"BR",distinguishingAttributes:{model:s.name},specifications:{type:"generic",groups:[{label:"Especificações verificadas",entries:Object.entries(s.specs).map(([label,value])=>({key:label.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-"),label,value}))}]},imageIds:[],sources:[{title:`${s.name} — página oficial`,url:s.source,accessedAt:checked}],status:"published",createdAt:checked,updatedAt:checked,reviewedAt:checked}));
export const audiovisualOffers:ProductOffer[]=seeds.map(s=>({id:`prod_offer_${s.key}_reference`,variantId:`prod_variant_${s.key}_br`,retailer:s.retailer,url:s.source,region:"BR",observedPrice:{amount:s.price,currency:"BRL"},availability:"available",checkedAt:checked}));
