import type { Product, ProductOffer, ProductVariant } from "./productSchema";

const reviewedAt = "2026-09-02";
const articleSlug = "melhores-liquidificadores-profissionais";
const source = (title: string, url: string) => ({ title, url, accessedAt: reviewedAt });
const image = (src: string, alt: string, sourceUrl: string): Product["mainImage"] => ({ src, alt, sourceUrl, credit: "Skymsen", rights: "official-promotional", width: 350, height: 350 });
const specs = (data: Omit<Extract<ProductVariant["specifications"], { type: "blender" }>, "type">): ProductVariant["specifications"] => ({ type: "blender", ...data });
const warranty = "6 meses para uso comercial intermitente em um turno, conforme condições da fabricante";

export const blenderProducts: Product[] = [
  {
    id: "prod_skymsen_li2", contentType: "product", schemaVersion: 1, slug: "skymsen-li2", aliases: ["skymsen-li-2-litros"], name: "Skymsen LI2", manufacturerId: "org_skymsen", line: "Alta rotação", category: "Liquidificadores profissionais",
    mainImage: image("/images/products/blenders/skymsen-li2-v1.jpg", "Liquidificador profissional Skymsen LI2 com copo de inox", "https://www.skymsen.com/index.php/produtos/detalhe/474428"), gallery: [], shortDescription: "Liquidificador comercial de alta rotação com copo de inox de 2 litros, 18.000 rpm e versões de 127 ou 220 V.",
    strengths: ["Copo, lâminas e gabinete de inox favorecem higienização e resistência no balcão", "Rotação de 18.000 rpm atende sucos, vitaminas, shakes e molhos líquidos com rapidez", "Desenho explodido e catálogo de componentes facilitam identificar peças de reposição"], limitations: ["Uma única velocidade oferece menos controle que o BM2", "Copo opaco impede acompanhar visualmente a textura durante o processamento"], suitableFor: ["Lanchonetes, cafeterias e pequenos restaurantes focados em bebidas e preparos líquidos", "Quem precisa de equipamento comercial simples sem pagar pelo desempenho do BM2"], categories: ["Liquidificadores profissionais", "Equipamentos comerciais"], tags: ["2 litros", "Copo inox", "Alta rotação", "18.000 rpm"], relatedProductIds: ["prod_skymsen_l2", "prod_skymsen_bm2"], relatedArticleSlugs: [articleSlug], editorialSummary: "É a escolha de entrada para bebidas e misturas fluidas: 18.000 rpm, conjunto inox e peças catalogadas sustentam o uso comercial melhor que um doméstico potente. Não é a indicação para massas pesadas ou pastas secas.", seo: { title: "Skymsen LI2: ficha, usos e ofertas", description: "Ficha do liquidificador profissional Skymsen LI2 de 2 litros, com potência nominal, rotação, copo inox, tensão, limitações e preço." }, sources: [source("Skymsen LI2 — especificações oficiais", "https://www.skymsen.com/index.php/produtos/detalhe/474428"), source("Termos de garantia Skymsen", "https://www.skymsen.com/index.php/institucional/termosecondicoes_garantia")], status: "published", createdAt: reviewedAt, publishedAt: reviewedAt, updatedAt: reviewedAt, reviewedAt,
  },
  {
    id: "prod_skymsen_l2", contentType: "product", schemaVersion: 1, slug: "skymsen-l2", aliases: ["skymsen-l2-comercial"], name: "Skymsen L2", manufacturerId: "org_skymsen", line: "Linha L", category: "Liquidificadores profissionais",
    mainImage: image("/images/products/blenders/skymsen-l2-v1.jpg", "Liquidificador comercial Skymsen L2 com copo monobloco de inox", "https://www.skymsen.com/index.php/produtos/detalhe/709786"), gallery: [], shortDescription: "Liquidificador comercial de baixa rotação com motor de indução, copo monobloco de inox de 2 litros e seleção 127/220 V.",
    strengths: ["Motor de indução de 3.500 rpm foi projetado para uso contínuo com menor ruído e desgaste", "Copo monobloco sem soldas ou frestas facilita higienização", "Construção de 9,1 kg oferece estabilidade superior aos modelos leves de alta rotação"], limitations: ["Baixa rotação não produz bebidas congeladas com a mesma rapidez ou textura do BM2", "Equipamento alto e pesado ocupa mais bancada e é menos fácil de transportar"], suitableFor: ["Restaurantes e cozinhas de produção que priorizam ciclos repetidos, cremes, molhos e sopas", "Operações que valorizam baixo ruído e limpeza do copo monobloco"], categories: ["Liquidificadores profissionais", "Equipamentos comerciais"], tags: ["2 litros", "Baixa rotação", "Motor de indução", "Copo monobloco inox"], relatedProductIds: ["prod_skymsen_li2", "prod_skymsen_bm2"], relatedArticleSlugs: [articleSlug], editorialSummary: "É o modelo para rotina contínua e misturas culinárias, não uma tentativa de vencer pela potência anunciada. O motor de indução, a baixa rotação e o corpo pesado priorizam torque, ruído e vida de serviço; bebidas com muito gelo pedem o BM2.", seo: { title: "Skymsen L2: ficha, usos e ofertas", description: "Ficha do liquidificador comercial Skymsen L2 com motor de indução, copo monobloco inox, baixa rotação, dimensões, garantia e preço." }, sources: [source("Skymsen L2 — especificações oficiais", "https://www.skymsen.com/index.php/produtos/detalhe/709786"), source("Termos de garantia Skymsen", "https://www.skymsen.com/index.php/institucional/termosecondicoes_garantia")], status: "published", createdAt: reviewedAt, publishedAt: reviewedAt, updatedAt: reviewedAt, reviewedAt,
  },
  {
    id: "prod_skymsen_bm2", contentType: "product", schemaVersion: 1, slug: "skymsen-bm2", aliases: ["skymsen-maxi-blender-bm2"], name: "Skymsen BM2 Maxi Blender", manufacturerId: "org_skymsen", line: "Maxi Blender", category: "Liquidificadores profissionais",
    mainImage: image("/images/products/blenders/skymsen-bm2-v1.jpg", "Liquidificador profissional Skymsen BM2 com copo transparente de Tritan", "https://www.skymsen.com/index.php/produto/bm2_127v"), gallery: [], shortDescription: "Maxi blender comercial de 2 litros com copo Tritan, velocidade variável, pulsar, seis lâminas e rotação máxima de 38.000 rpm.",
    strengths: ["Velocidade variável e pulsar permitem controlar textura e iniciar misturas difíceis gradualmente", "Seis lâminas e 38.000 rpm processam gelo, polpas congeladas, grãos, castanhas e receitas fluidas", "Copo Tritan transparente, livre de BPA, facilita acompanhar a consistência"], limitations: ["Custa aproximadamente o dobro de um LI2", "Alta rotação e motor mais forte produzem mais ruído que o L2 de indução"], suitableFor: ["Casas de suco, cafeterias e cozinhas que alternam gelo, polpas, sopas e moagem", "Negócios em que controle de textura e produtividade justificam o investimento"], categories: ["Liquidificadores profissionais", "Equipamentos comerciais"], tags: ["2 litros", "Tritan", "38.000 rpm", "Velocidade variável", "Seis lâminas"], relatedProductIds: ["prod_skymsen_li2", "prod_skymsen_l2"], relatedArticleSlugs: [articleSlug], editorialSummary: "É o modelo mais versátil e rápido da seleção. A vantagem não vem apenas dos watts: copo Tritan, seis lâminas, rolamentos blindados, pulsar e velocidade variável ampliam os preparos e o controle. Ainda assim, não substitui equipamento específico para massas pesadas.", seo: { title: "Skymsen BM2 Maxi Blender: ficha e ofertas", description: "Ficha do Skymsen BM2 profissional com copo Tritan de 2 litros, seis lâminas, velocidade variável, potência, rotação, garantia e preço." }, sources: [source("Skymsen BM2 — especificações oficiais", "https://www.skymsen.com/index.php/produto/bm2_127v"), source("Termos de garantia Skymsen", "https://www.skymsen.com/index.php/institucional/termosecondicoes_garantia")], status: "published", createdAt: reviewedAt, publishedAt: reviewedAt, updatedAt: reviewedAt, reviewedAt,
  },
];

export const blenderVariants: ProductVariant[] = [
  { id: "prod_variant_skymsen_li2_127v_br", productId: "prod_skymsen_li2", name: "LI2 código 47442.8 — 127 V", market: "BR", manufacturerModelNumber: "47442.8", gtin: "7895707474420", distinguishingAttributes: { voltage: "127 V", jar: "Inox", capacity: "2 L" }, specifications: specs({ powerNominalWatts: 350, motorPower: "900 W", totalCapacityLiters: 2, usefulCapacity: "Não informada; 2 L é o volume máximo do copo", jarMaterial: "Aço inox", bladeMaterial: "Aço inox", speeds: "Uma velocidade", pulse: false, rotationRpm: 18000, dimensionsMm: { width: 200, height: 420, depth: 190 }, weightKg: 2.05, voltage: "127 V", warranty, intendedUse: "Uso comercial intermitente em um turno", recommendedPreparations: ["Sucos", "Vitaminas", "Shakes", "Coquetéis", "Molhos líquidos", "Polpas congeladas com líquido"], restrictedPreparations: ["Massas pesadas", "Pastas espessas sem líquido", "Processamento contínuo sem pausas"], safetyFeatures: ["Conformidade informada com o Inmetro"] }), imageIds: [], sources: [source("Skymsen LI2 127 V — ficha oficial", "https://www.skymsen.com/index.php/produtos/detalhe/474428")], status: "published", createdAt: reviewedAt, updatedAt: reviewedAt, reviewedAt },
  { id: "prod_variant_skymsen_l2_127_220v_br", productId: "prod_skymsen_l2", name: "L2 código 70978.6 — seleção 127/220 V", market: "BR", manufacturerModelNumber: "70978.6", gtin: "7895707709782", distinguishingAttributes: { voltage: "127/220 V selecionável", jar: "Inox monobloco", capacity: "2 L" }, specifications: specs({ powerNominalWatts: 665, motorPower: "0,5 HP-CV", totalCapacityLiters: 2, usefulCapacity: "Não informada; 2 L é o volume máximo do copo", jarMaterial: "Aço inox monobloco", bladeMaterial: "Aço inox", speeds: "Uma velocidade", pulse: false, rotationRpm: 3500, dimensionsMm: { width: 240, height: 640, depth: 270 }, weightKg: 9.1, voltage: "127/220 V com seleção correta antes de ligar", noiseLevel: "Fabricante descreve operação de baixo ruído, sem valor em dB", warranty, intendedUse: "Uso comercial contínuo, respeitando carga e manual", recommendedPreparations: ["Molhos", "Cremes", "Sopas", "Recheios fluidos", "Preparos culinários com líquido"], restrictedPreparations: ["Grandes volumes de gelo", "Bebidas congeladas que exigem emulsão muito fina", "Massas que o manual não autorize"], safetyFeatures: ["Copo monobloco sem soldas e frestas", "Base pesada para estabilidade"] }), imageIds: [], sources: [source("Skymsen L2 — ficha oficial", "https://www.skymsen.com/index.php/produtos/detalhe/709786")], status: "published", createdAt: reviewedAt, updatedAt: reviewedAt, reviewedAt },
  { id: "prod_variant_skymsen_bm2_127v_br", productId: "prod_skymsen_bm2", name: "BM2 código 65335.7 — 127 V", market: "BR", manufacturerModelNumber: "65335.7", gtin: "7895707653351", distinguishingAttributes: { voltage: "127 V", jar: "Tritan", capacity: "2 L" }, specifications: specs({ powerNominalWatts: 1050, motorPower: "2.238 W / 3 HP informados pelo fabricante", totalCapacityLiters: 2, usefulCapacity: "Não informada; 2 L é o volume máximo do copo", jarMaterial: "Tritan transparente, livre de BPA", bladeMaterial: "Aço inox", bladeDescription: "Conjunto de seis pontas com eixo, bucha e rolamentos blindados", speeds: "Velocidade variável", pulse: true, rotationRpm: 38000, dimensionsMm: { width: 205, height: 505, depth: 230 }, weightKg: 4.05, voltage: "127 V", warranty, intendedUse: "Uso comercial intermitente em um turno", recommendedPreparations: ["Gelo", "Polpas congeladas", "Sucos", "Smoothies", "Shakes", "Sopas", "Papinhas", "Grãos e castanhas"], restrictedPreparations: ["Massas pesadas sem líquido", "Processamento contínuo além do regime do manual"], safetyFeatures: ["Tampa com sobretampa", "Controle variável para partida gradual"] }), imageIds: [], sources: [source("Skymsen BM2 127 V — ficha oficial", "https://www.skymsen.com/index.php/produto/bm2_127v")], status: "published", createdAt: reviewedAt, updatedAt: reviewedAt, reviewedAt },
];

export const blenderOffers: ProductOffer[] = [
  { id: "prod_offer_skymsen_li2_127v_magalu", variantId: "prod_variant_skymsen_li2_127v_br", retailer: "Magazine Luiza — marketplace", url: "https://www.magazineluiza.com.br/liquidificador-inox-alta-rotacao-li2-2litros-127v-skymsen/p/jh4h373711/pi/liqi/", region: "BR", observedPrice: { amount: 880.53, currency: "BRL" }, availability: "available", checkedAt: reviewedAt },
  { id: "prod_offer_skymsen_l2_leroy", variantId: "prod_variant_skymsen_l2_127_220v_br", retailer: "Leroy Merlin — marketplace", url: "https://www.leroymerlin.com.br/liquidificador-comercial-skymsen-inox-copo-monobloco-2-litros-l2-bivolt_1572658364", region: "BR", observedPrice: { amount: 872.10, currency: "BRL" }, availability: "available", checkedAt: reviewedAt },
  { id: "prod_offer_skymsen_bm2_acimaq", variantId: "prod_variant_skymsen_bm2_127v_br", retailer: "Acimaq", url: "https://www.acimaq.com.br/liquidificador-alta-rotacao-bm2-maxi-blender-3cv-2-litros-127v---skymsen/p", region: "BR", observedPrice: { amount: 1817.99, currency: "BRL" }, availability: "available", checkedAt: reviewedAt },
];
