import type { Product, ProductOffer, ProductVariant } from "./productSchema";

const reviewedAt = "2026-09-04";
const articleSlugs = ["melhores-cameras-2026", "melhores-cameras-para-iniciantes-2026", "melhores-cameras-para-video-2026"];
const source = (title: string, url: string) => ({ title, url, accessedAt: reviewedAt });

type CameraInput = {
  key: string; name: string; maker: "canon" | "sony" | "fujifilm"; line: string; year: number;
  image: { file: string; width: number; height: number; url: string; credit: string };
  sensor: string; technology: string; mp: number; af: string; stabilization: string; video: string;
  mount: string; lenses: string; battery: string; mic: boolean; phones: boolean; recording: string;
  codecs: string[]; connectivity: string[]; weight?: number; strengths: string[]; limits: string[];
  bestFor: string[]; summary: string; technicalUrl: string; offerUrl: string; retailer: string; price: number;
};

const entries: CameraInput[] = [
  { key:"canon_eos_r100",name:"Canon EOS R100",maker:"canon",line:"EOS R",year:2023,image:{file:"canon-eos-r100.jpg",width:1440,height:960,url:"https://www.canon.com.br/para-voce/cameras/eos-mirrorless/eos-r100",credit:"Canon"},sensor:"APS-C",technology:"CMOS",mp:24.1,af:"Dual Pixel CMOS AF em fotos e Full HD; AF por contraste no 4K",stabilization:"Sem IBIS; estabilização óptica depende da lente e digital no vídeo",video:"4K a 24p com recorte; Full HD a 60p",mount:"Canon RF",lenses:"RF e RF-S; EF/EF-S com adaptador, mas a linha RF-S ainda é menor que Sony E",battery:"LP-E17, cerca de 340 fotos pelo padrão CIPA",mic:true,phones:false,recording:"8-bit interno",codecs:["H.264"],connectivity:["Wi-Fi","Bluetooth","USB-C","micro-HDMI"],weight:356,strengths:["É a porta de entrada mais barata no sistema Canon RF com visor eletrônico","Sensor APS-C entrega latitude e controle de profundidade superiores aos de celulares em situações adequadas"],limits:["Tela fixa e sem toque torna a operação menos amigável que na EOS R50","4K recortado perde o Dual Pixel AF e não é uma boa base para vídeo frequente"],bestFor:["Quem prioriza fotografia e encontra o kit claramente abaixo da EOS R50"],summary:"A EOS R100 só lidera pelo preço. Para fotografia básica funciona; para vídeo, autorretrato ou aprendizado com tela tátil, a diferença para a R50 costuma justificar o gasto extra.",technicalUrl:"https://www.canon.com.br/para-voce/cameras/eos-mirrorless/eos-r100",offerUrl:"https://www.loja.canon.com.br/pt/canonbr/cameras-canon/cameras-canon/camera-eos-R100-com-rf-s-18-45mm",retailer:"Loja Canon",price:4299 },
  { key:"canon_eos_r50",name:"Canon EOS R50",maker:"canon",line:"EOS R",year:2023,image:{file:"canon-eos-r50.jpg",width:1750,height:1400,url:"https://www.canon.com.au/about-canon/news-and-press-releases/canon-unveils-the-ultimate-travel-companion-with-its-latest-eos-r-system-aps-c-mirrorless-camera",credit:"Canon Australia"},sensor:"APS-C",technology:"CMOS",mp:24.2,af:"Dual Pixel CMOS AF II com detecção de pessoas, animais e veículos",stabilization:"Sem IBIS; IS óptico da lente e Movie Digital IS",video:"4K 30p sobremostrado de 6K; 4K 60p com recorte",mount:"Canon RF",lenses:"RF e RF-S; EF/EF-S com adaptador",battery:"LP-E17, cerca de 370 fotos pelo padrão CIPA",mic:true,phones:false,recording:"4K 10-bit HDR PQ ou 8-bit convencional",codecs:["H.264","H.265"],connectivity:["Wi-Fi","Bluetooth","USB-C UVC/UAC","micro-HDMI"],weight:375,strengths:["Autofocus confiável e tela articulada reduzem a fricção para quem está começando","4K 30p sobremostrado preserva mais detalhe que o 4K recortado da R100"],limits:["Não possui estabilização no sensor nem saída para fones","O catálogo RF-S é funcional, porém menos amplo que Sony E e Fujifilm X"],bestFor:["Primeira câmera híbrida para família, viagem, fotografia e vídeo curto"],summary:"É a recomendação inicial mais equilibrada quando o kit custa perto de R$ 5.500: simples sem ser limitada demais, com AF muito melhor e vídeo mais útil que a R100.",technicalUrl:"https://www.canon.com.br/para-voce/cameras/eos-mirrorless/eos-r50",offerUrl:"https://www.loja.canon.com.br/pt/canonbr/promocoes-canon/cameras-canon/camera-eos-r50-rf18-45mm",retailer:"Loja Canon",price:5499 },
  { key:"canon_eos_r10",name:"Canon EOS R10",maker:"canon",line:"EOS R",year:2022,image:{file:"canon-eos-r10.jpg",width:3900,height:2600,url:"https://prtimes.jp/main/html/rd/p/000000775.000013980.html",credit:"Canon"},sensor:"APS-C",technology:"CMOS",mp:24.2,af:"Dual Pixel CMOS AF II com rastreamento de pessoas, animais e veículos",stabilization:"Sem IBIS; estabilização óptica da lente e digital no vídeo",video:"4K 30p sobremostrado de 6K; 4K 60p com recorte",mount:"Canon RF",lenses:"RF e RF-S; EF/EF-S com adaptador",battery:"LP-E17, cerca de 430 fotos no modo econômico",mic:true,phones:false,recording:"4K 10-bit HDR PQ; 8-bit nos modos convencionais",codecs:["H.264","H.265"],connectivity:["Wi-Fi","Bluetooth","USB-C","micro-HDMI"],weight:429,strengths:["Controles, rajada e buffer fazem mais sentido para aprender fotografia que corpos voltados só a vlog","Autofocus e 4K 30p sobremostrado sustentam uso híbrido"],limits:["Não possui IBIS e o 4K 60p aplica recorte","O preço do kit oficial se aproxima de câmeras estabilizadas em promoções"],bestFor:["Iniciantes comprometidos com fotografia, ação leve e evolução técnica"],summary:"A R10 é a Canon APS-C para quem já sabe que quer fotografar com frequência. Vale pelo corpo e controles, não por megapixels, e perde força quando custa perto de uma X-S20.",technicalUrl:"https://www.canon-europe.com/cameras/eos-r10/specifications/",offerUrl:"https://www.loja.canon.com.br/pt/canonbr/Camera-EOSR10-CORPO",retailer:"Loja Canon",price:7099 },
  { key:"canon_eos_r7",name:"Canon EOS R7",maker:"canon",line:"EOS R",year:2022,image:{file:"canon-eos-r7.jpg",width:1000,height:667,url:"https://www.loja.canon.com.br/pt/canonbr/cameras-canon/cameras-canon/Camera-EOS-R7-CORPO-BR",credit:"Canon Brasil"},sensor:"APS-C",technology:"CMOS",mp:32.5,af:"Dual Pixel CMOS AF II com detecção avançada de sujeitos",stabilization:"IBIS de 5 eixos, até 8 pontos com lentes compatíveis",video:"4K 60p; 4K Fine 30p sobremostrado de 7K",mount:"Canon RF",lenses:"RF e RF-S; boa oferta de teleobjetivas RF, EF/EF-S via adaptador",battery:"LP-E6NH, cerca de 500 fotos com visor ou 770 pela tela",mic:true,phones:true,recording:"4K 10-bit Canon Log 3 ou HDR PQ",codecs:["H.264","H.265"],connectivity:["Wi-Fi","Bluetooth","USB-C","micro-HDMI"],weight:612,strengths:["Sensor APS-C denso, rajada e AF favorecem esporte e vida selvagem","IBIS e dois cartões UHS-II aumentam a segurança do trabalho"],limits:["Rolling shutter do obturador eletrônico exige cautela em movimento rápido","O estoque oficial estava esgotado na verificação e o preço encosta em full frame de entrada"],bestFor:["Fotografia de esporte, aves e natureza com alcance de teleobjetiva"],summary:"É a escolha especializada para ação e vida selvagem. O recorte APS-C é parte da vantagem; para retrato e baixa luz, uma full frame pode entregar um sistema mais coerente.",technicalUrl:"https://www.canon-europe.com/cameras/eos-r7/specifications/",offerUrl:"https://www.loja.canon.com.br/pt/canonbr/cameras-canon/cameras-canon/Camera-EOS-R7-CORPO-BR",retailer:"Loja Canon",price:11299 },
  { key:"canon_eos_r6_mark_ii",name:"Canon EOS R6 Mark II",maker:"canon",line:"EOS R",year:2022,image:{file:"canon-eos-r6-mark-ii.jpg",width:1000,height:667,url:"https://www.loja.canon.com.br/pt/canonbr/cameras-canon/todas-cameras-canon/camera-eos-r6-mark-ii-corpo",credit:"Canon Brasil"},sensor:"Full frame",technology:"CMOS",mp:24.2,af:"Dual Pixel CMOS AF II com detecção de pessoas, animais e veículos",stabilization:"IBIS de 5 eixos, até 8 pontos com lentes compatíveis",video:"4K 60p sobremostrado de 6K; Full HD 180p",mount:"Canon RF",lenses:"Ampla linha RF full frame; EF com adaptador",battery:"LP-E6NH, cerca de 450 fotos com visor ou 760 pela tela",mic:true,phones:true,recording:"4K 10-bit Canon Log 3 ou HDR PQ",codecs:["H.264","H.265","RAW 6K externo"],connectivity:["Wi-Fi","Bluetooth","USB-C","micro-HDMI"],weight:670,strengths:["Combina AF, estabilização, baixa luz e vídeo sem sacrificar a fotografia","Dois slots SD UHS-II e controles completos atendem trabalho pago"],limits:["Lentes RF luminosas elevam bastante o custo total","Micro-HDMI é menos robusto que HDMI de tamanho completo em produção"],bestFor:["Profissionais híbridos de eventos, retrato, casamento e vídeo"],summary:"É a full frame mais equilibrada do grupo para quem realmente trabalha com foto e vídeo. O corpo é só o começo: lentes, cartões, áudio e baterias tornam o investimento muito maior.",technicalUrl:"https://www.canon-europe.com/cameras/eos-r6-mark-ii/specifications/",offerUrl:"https://www.loja.canon.com.br/pt/canonbr/cameras-canon/todas-cameras-canon/camera-eos-r6-mark-ii-corpo",retailer:"Loja Canon",price:15859 },
  { key:"sony_zv_e10",name:"Sony ZV-E10",maker:"sony",line:"ZV",year:2021,image:{file:"sony-zv-e10.jpg",width:6016,height:4000,url:"https://www.ephotozine.com/article/sony-zv-e10-mirrorless-camera---16-50mm-f-3-5-5-6-pz-oss-lens-review-35746",credit:"Sony via ePHOTOzine"},sensor:"APS-C",technology:"Exmor CMOS",mp:24.2,af:"Fast Hybrid AF com 425 pontos de fase e Eye AF",stabilization:"Sem IBIS; estabilização óptica da lente e modo Active digital",video:"4K 30p; Full HD 120p",mount:"Sony E",lenses:"Maior variedade APS-C nativa do grupo, incluindo Sony, Sigma, Tamron e Viltrox",battery:"NP-FW50, cerca de 440 fotos ou 80 minutos de vídeo real",mic:true,phones:true,recording:"4K 8-bit 4:2:0 interno",codecs:["XAVC S","H.264"],connectivity:["Wi-Fi","Bluetooth","USB-C streaming","micro-HDMI"],weight:343,strengths:["Preço e grande catálogo de lentes formam uma entrada racional para vídeo","Tem microfone direcional, tela articulada e saídas de microfone e fone"],limits:["4K 8-bit e rolling shutter limitam movimentos e correção de cor pesada","Não possui visor nem estabilização no sensor"],bestFor:["YouTube e vídeo em tripé com orçamento controlado"],summary:"Continua relevante quando custa muito menos que a ZV-E10 II. É uma câmera de vídeo barata com limitações conhecidas, não uma versão econômica da FX30.",technicalUrl:"https://www.sony.com.br/electronics/lentes-fotograficas-intercambiaveis/zv-e10/specifications",offerUrl:"https://www.fotocentro.com.br/cameras-e-filmadoras/camera-sony-zv-e10-mirrorless-kit-com-lente-16-50mm-preta",retailer:"Foto Centro",price:5589 },
  { key:"sony_zv_e10_ii",name:"Sony ZV-E10 II",maker:"sony",line:"ZV",year:2024,image:{file:"sony-zv-e10-ii.jpg",width:1500,height:1200,url:"https://www.foto-erhardt.com/cameras/system-cameras/sony-mirrorless-cameras/sony-alpha-zv-e10-ii-housing.html",credit:"Sony via Foto Erhardt"},sensor:"APS-C",technology:"Exmor R CMOS BSI",mp:26,af:"Fast Hybrid AF com 759 pontos de fase e rastreamento em tempo real",stabilization:"Sem IBIS; estabilização óptica da lente e modo Active digital",video:"4K 60p 10-bit; 4K 30p sobremostrado de 5,6K",mount:"Sony E",lenses:"Oferta APS-C ampla de Sony e terceiros",battery:"NP-FZ100, cerca de 610 fotos ou 130 minutos de vídeo real",mic:true,phones:true,recording:"4K 10-bit 4:2:2 interno",codecs:["XAVC HS","XAVC S","XAVC S-I","H.265","H.264"],connectivity:["Wi-Fi 5 GHz","Bluetooth","USB-C streaming","micro-HDMI"],weight:377,strengths:["4K 60p 10-bit, AF e bateria grande tornam o corpo adequado a criadores recorrentes","E-mount facilita começar com lente de kit e evoluir sem trocar o corpo"],limits:["Sem IBIS e sem visor, cobra estabilização da lente, tripé ou gimbal","Rolling shutter e aquecimento dependem de modo, ambiente e duração da tomada"],bestFor:["YouTube, Reels e produção solo que precisa de 10-bit"],summary:"É o ponto de equilíbrio para vídeo antes de partir a uma a6700 ou FX30. Para fotografia, a ausência de visor e IBIS torna R10, R50 e X-S20 mais agradáveis.",technicalUrl:"https://www.sony.com.br/electronics/lentes-fotograficas-intercambiaveis/zv-e10m2/specifications",offerUrl:"https://www.tapadoreletro.com.br/cameras/sony/zv-e10-ii",retailer:"Tapadoreletro",price:7616.70 },
  { key:"sony_a6700",name:"Sony Alpha 6700",maker:"sony",line:"Alpha",year:2023,image:{file:"sony-a6700.jpg",width:800,height:800,url:"https://fotosale.ua/ua/product_N65556.htm",credit:"Sony via FotoSale"},sensor:"APS-C",technology:"Exmor R CMOS BSI",mp:26,af:"759 pontos de fase com unidade de IA para reconhecimento de sujeitos",stabilization:"IBIS de 5 eixos com modo Active no vídeo",video:"4K 120p 10-bit; 4K 60p sobremostrado de 6K",mount:"Sony E",lenses:"Oferta APS-C ampla de Sony e terceiros",battery:"NP-FZ100, cerca de 570 fotos ou 100 minutos de vídeo real",mic:true,phones:true,recording:"4K 10-bit 4:2:2 interno",codecs:["XAVC HS","XAVC S","XAVC S-I","H.265","H.264"],connectivity:["Wi-Fi 5 GHz","Bluetooth","USB-C streaming","micro-HDMI"],weight:493,strengths:["Une o sensor de vídeo da FX30 a visor, IBIS e ergonomia de câmera híbrida","AF e ampla linha de lentes sustentam fotografia, vídeo e evolução do kit"],limits:["4K 120p aplica recorte e gera arquivos pesados","Um único slot de cartão e micro-HDMI limitam trabalhos que exigem redundância"],bestFor:["Criadores híbridos avançados que querem um único corpo APS-C"],summary:"É a melhor híbrida APS-C do recorte quando foto e vídeo têm peso semelhante. Quem só grava paga por visor e recursos fotográficos que a FX30 troca por refrigeração e conexões.",technicalUrl:"https://www.sony.com.br/electronics/cameras-lentes-intercambiaveis/ilce-6700/specifications",offerUrl:"https://www.zoom.com.br/busca/a6700",retailer:"Zoom",price:11262 },
  { key:"sony_a7_iv",name:"Sony Alpha 7 IV",maker:"sony",line:"Alpha",year:2021,image:{file:"sony-a7-iv.png",width:1000,height:1000,url:"https://ayoubcomputers.com/sony-alpha-a7-iv-mirrorless-camera/",credit:"Sony via Ayoub Computers"},sensor:"Full frame",technology:"Exmor R CMOS BSI",mp:33,af:"759 pontos de fase com Real-time Tracking e Eye AF",stabilization:"IBIS de 5 eixos, até 5,5 pontos",video:"4K 30p sobremostrado de 7K; 4K 60p com recorte Super 35",mount:"Sony E",lenses:"A oferta full frame mais ampla do grupo entre marca e terceiros",battery:"NP-FZ100, cerca de 520 fotos pelo visor ou 580 pela tela",mic:true,phones:true,recording:"4K 10-bit 4:2:2 interno",codecs:["XAVC HS","XAVC S","XAVC S-I","H.265","H.264"],connectivity:["Wi-Fi 5 GHz","Bluetooth","USB-C streaming","HDMI tamanho completo"],weight:658,strengths:["Sensor de 33 MP equilibra detalhe fotográfico e fluxo profissional","Ecossistema E-mount oferece muitas rotas de lente e dois slots trazem redundância"],limits:["4K 60p usa recorte APS-C e o rolling shutter é visível em movimentos rápidos","É um corpo de 2021 que só vale com preço significativamente abaixo dos sucessores"],bestFor:["Fotografia profissional híbrida com vídeo 4K moderado"],summary:"A Alpha 7 IV continua forte pelo conjunto e pelo sistema de lentes, não por ser a mais nova. Para vídeo de movimento, FX30 e a6700 leem o sensor mais rapidamente; para foto, 33 MP e full frame pesam.",technicalUrl:"https://www.sony.com.br/electronics/cameras-lentes-intercambiaveis/ilce-7m4/specifications",offerUrl:"https://achapromo.com.br/produto/sony-alpha-a7-iv-ilce-7m4-sem-espelho-cor-preto/555a7fa5-5d60-4068-98dd-e15f462021ce",retailer:"Mercado Livre via AchaPromo",price:13373 },
  { key:"sony_fx30",name:"Sony FX30",maker:"sony",line:"Cinema Line",year:2022,image:{file:"sony-fx30.jpg",width:800,height:800,url:"https://fotosale.ua/ua/product_N65029.htm",credit:"Sony via FotoSale"},sensor:"APS-C / Super 35",technology:"Exmor R CMOS BSI",mp:26.1,af:"Fast Hybrid AF com 495 pontos de fase no vídeo",stabilization:"IBIS de 5 eixos com modo Active e metadados giroscópicos",video:"4K 120p 10-bit; 4K 60p sobremostrado de 6K",mount:"Sony E",lenses:"Oferta APS-C ampla, com muitas opções de zoom luminoso e cinema",battery:"NP-FZ100, cerca de 115 minutos de gravação real",mic:true,phones:true,recording:"4K 10-bit 4:2:2; saída RAW 16-bit por HDMI",codecs:["XAVC HS","XAVC S","XAVC S-I","H.265","H.264","RAW externo"],connectivity:["Wi-Fi","USB-C","HDMI tamanho completo","timecode por adaptador"],weight:646,strengths:["Ventoinha, tally, HDMI completo e pontos de montagem favorecem tomadas longas e rigs","Grava 4K 120p, 10-bit e oferece workflow de LUT e Cine EI"],limits:["Não possui visor e é uma escolha ruim quando fotografia é parte importante do trabalho","XLR depende da versão com alça ou acessório, elevando o custo"],bestFor:["Produção profissional de vídeo, documentário, estúdio e equipes pequenas"],summary:"A FX30 é a recomendação profissional de vídeo porque prioriza operação contínua e conexões. A a6700 entrega imagem parecida em corpo híbrido; a FX30 ganha pelo trabalho ao redor da imagem.",technicalUrl:"https://www.sony.com.br/electronics/cameras-cinema-line/ilme-fx30/specifications",offerUrl:"https://megareview.com.br/produto/sony-camera-cinema-line-fx30-super-35/",retailer:"Amazon Brasil via MegaReview",price:10389 },
  { key:"fujifilm_x_m5",name:"Fujifilm X-M5",maker:"fujifilm",line:"X Series",year:2024,image:{file:"fujifilm-x-m5.jpg",width:480,height:480,url:"https://www.fujifilm-x.com/pt-br/products/cameras/x-m5/",credit:"Fujifilm"},sensor:"APS-C",technology:"X-Trans CMOS 4 BSI",mp:26.1,af:"AF híbrido por fase e contraste com detecção de sujeitos",stabilization:"Sem IBIS; estabilização digital e óptica conforme a lente",video:"6.2K 30p open gate; 4K 60p; Full HD 240p",mount:"Fujifilm X",lenses:"Linha APS-C madura da Fujifilm, Sigma, Tamron, Viltrox e outras",battery:"NP-W126S, cerca de 330 fotos no modo normal",mic:true,phones:true,recording:"6.2K/4K 10-bit 4:2:2 interno",codecs:["H.265","H.264"],connectivity:["Wi-Fi","Bluetooth","USB-C streaming","micro-HDMI"],weight:355,strengths:["6.2K open gate facilita recortes horizontal e vertical a partir da mesma tomada","Corpo pequeno e ampla linha APS-C ajudam quem quer viajar leve"],limits:["Não possui visor nem IBIS e a bateria é menor que na X-S20","O preço brasileiro alto reduz a vantagem frente à ZV-E10 II"],bestFor:["Reels, vlog de viagem e criação que aproveita open gate"],summary:"A X-M5 é interessante pelo 6.2K open gate e tamanho, mas não é automaticamente boa compra no Brasil. Sem visor e IBIS, precisa custar perto da ZV-E10 II, não da X-S20.",technicalUrl:"https://www.fujifilm-x.com/pt-br/products/cameras/x-m5/specifications/",offerUrl:"https://loja.fujifilm.com.br/collections/all/camera%20digital",retailer:"Loja Fujifilm",price:7999 },
  { key:"fujifilm_x_s20",name:"Fujifilm X-S20",maker:"fujifilm",line:"X Series",year:2023,image:{file:"fujifilm-x-s20.jpg",width:500,height:500,url:"https://vjshop.vn/may-anh-mirrorless/fujifilm-x-s20-lens-xc-15-45mm-f35-56",credit:"Fujifilm via VJShop"},sensor:"APS-C",technology:"X-Trans CMOS 4 BSI",mp:26.1,af:"AF híbrido por fase e contraste com detecção de sujeitos",stabilization:"IBIS de 5 eixos, até 7 pontos",video:"6.2K 30p open gate; 4K 60p; Full HD 240p",mount:"Fujifilm X",lenses:"Linha APS-C madura da Fujifilm e de fabricantes terceiros",battery:"NP-W235, cerca de 750 fotos no modo normal",mic:true,phones:true,recording:"6.2K/4K 10-bit 4:2:2 interno; RAW externo",codecs:["H.265","H.264","ProRes RAW externo","Blackmagic RAW externo"],connectivity:["Wi-Fi","Bluetooth","USB-C streaming","micro-HDMI"],weight:491,strengths:["IBIS, visor, bateria grande e 6.2K open gate formam o pacote híbrido mais completo da linha média","Simulações de filme entregam resultados utilizáveis sem pós-produção pesada"],limits:["O preço oficial brasileiro de corpo se aproxima de full frames em promoção","Slot único UHS-II e micro-HDMI limitam redundância e rig profissional"],bestFor:["Criadores híbridos, viagem e vídeo vertical/horizontal com um único corpo"],summary:"A X-S20 é uma excelente câmera híbrida, mas depende do preço. Até perto de R$ 10 mil compete com a a6700; muito acima disso, full frame e lentes entram na discussão.",technicalUrl:"https://www.fujifilm-x.com/pt-br/products/cameras/x-s20/specifications/",offerUrl:"https://loja.fujifilm.com.br/products/camera-digital-mirrorless-fujifilm-x-s20",retailer:"Loja Fujifilm",price:10799 },
];

const makerId = { canon: "org_canon", sony: "org_sony", fujifilm: "org_fujifilm" } as const;

export const cameraProducts: Product[] = entries.map((item) => ({
  id: `prod_${item.key}`, contentType:"product", schemaVersion:1, slug:item.key.replaceAll("_", "-"), aliases:[], name:item.name,
  manufacturerId:makerId[item.maker], line:item.line, category:"Câmeras", releaseYear:item.year,
  mainImage:{src:`/images/products/cameras/${item.image.file}`,alt:`${item.name}, câmera mirrorless vista em fotografia de produto`,sourceUrl:item.image.url,credit:item.image.credit,rights:"official-promotional",width:item.image.width,height:item.image.height}, gallery:[],
  shortDescription:`Câmera ${item.sensor} de ${item.mp} MP com mount ${item.mount}, ${item.af.toLowerCase()} e ${item.video}.`,
  strengths:item.strengths, limitations:item.limits, suitableFor:item.bestFor, categories:["Câmeras","Eletrônicos"],
  tags:[item.sensor,item.mount,"Mirrorless",item.video.split(";")[0]], relatedProductIds:[], relatedArticleSlugs:articleSlugs,
  editorialSummary:item.summary, seo:{title:`${item.name}: ficha, análise e preço`,description:`Ficha da ${item.name} com sensor, autofocus, estabilização, vídeo, mount, bateria, limitações e preço observado no Brasil.`},
  sources:[source(`${item.name} — especificações oficiais`,item.technicalUrl)], status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt,
}));

export const cameraVariants: ProductVariant[] = entries.map((item) => ({
  id:`prod_variant_${item.key}_body_br`,productId:`prod_${item.key}`,name:"Corpo ou kit brasileiro comparado",market:"BR",distinguishingAttributes:{mount:item.mount},
  specifications:{type:"camera",cameraType:item.key === "sony_fx30" ? "cinema-mirrorless" : "mirrorless",sensorFormat:item.sensor,sensorTechnology:item.technology,resolutionMegapixels:item.mp,autofocus:item.af,stabilization:item.stabilization,video:item.video,lensMount:item.mount,lensAvailability:item.lenses,battery:item.battery,microphoneInput:item.mic,headphoneOutput:item.phones,internalRecording:item.recording,codecs:item.codecs,connectivity:item.connectivity,weightGrams:item.weight},
  imageIds:[],sources:[source(`${item.name} — especificações oficiais`,item.technicalUrl)],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt,
}));

export const cameraOffers: ProductOffer[] = entries.map((item) => ({
  id:`prod_offer_${item.key}_br_20260904`,variantId:`prod_variant_${item.key}_body_br`,retailer:item.retailer,url:item.offerUrl,region:"BR",observedPrice:{amount:item.price,currency:"BRL"},availability:item.key === "canon_eos_r7" ? "temporarily-unavailable" : "available",checkedAt:reviewedAt,
}));

