import type { Product, ProductOffer, ProductVariant } from "./productSchema";

const reviewedAt = "2026-09-02";
const articleSlug = "kit-para-comecar-a-vender-bolos-e-doces";
const source = (title: string, url: string) => ({ title, url, accessedAt: reviewedAt });

export const confectioneryEssentialProducts: Product[] = [
  {id:"prod_fischer_premier_48l",contentType:"product",schemaVersion:1,slug:"fischer-premier-48-litros",aliases:["forno-fischer-premier-48l"],name:"Forno Fischer Premier 48 litros",manufacturerId:"org_fischer",line:"Premier",category:"Fornos elétricos",mainImage:{src:"/images/products/ovens/fischer-premier-48l-v1.png",alt:"Forno elétrico de bancada Fischer Premier 48 litros preto",sourceUrl:"https://www.fischer.com.br/forno-eletrico-fischer-premier-bancada-48l/p",credit:"Fischer",rights:"official-promotional",width:386,height:386},gallery:[],shortDescription:"Forno elétrico de bancada de 48 litros com resistências superior e inferior, dourador independente, porta de vidro duplo e timer de 120 minutos.",strengths:["Faixa de 50 °C a 300 °C e aquecimento superior independente ampliam o controle de acabamento","Porta de vidro duplo e estrutura de 13,7 kg oferecem retenção e estabilidade melhores que fornos muito leves","Cavidade de 39,2 × 26,7 × 44,5 cm permite verificar antecipadamente quais formas cabem"],limitations:["Não possui convecção, portanto forma e posição continuam influenciando a uniformidade","Um único forno de 48 litros ainda limita produção simultânea e não substitui teste de temperatura"],suitableFor:["Quem comprovou que o forno doméstico atual é inconsistente ou pequeno para suas formas","Produção caseira inicial que precisa de um forno dedicado sem obra de embutir"],categories:["Fornos elétricos","Equipamentos de confeitaria"],tags:["48 litros","Bancada","Vidro duplo","Dourador"],relatedProductIds:["prod_oster_bowl_inox_iii"],relatedArticleSlugs:[articleSlug],editorialSummary:"É uma opção de forno dedicado para quem já testou o forno de casa e encontrou um gargalo real. A recomendação depende das dimensões internas e da instalação elétrica; litros e temperatura no seletor não garantem uniformidade sem testes com a receita.",seo:{title:"Fischer Premier 48L: ficha e análise para bolos",description:"Ficha do forno Fischer Premier 48 litros com dimensões internas, potência, temperatura, tensão, limitações e oferta observada."},sources:[source("Fischer Premier 48 litros — página oficial","https://www.fischer.com.br/forno-eletrico-fischer-premier-bancada-48l/p"),source("Manual oficial Fischer Premier 48 litros","https://www.fischer.com.br/media/amasty/amfile/attach/RKSJxKdm6FPzef8QD8brRZeldwEhBYS1.pdf")],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_urano_udc_pop_6_1",contentType:"product",schemaVersion:1,slug:"urano-udc-pop-6kg-1g",aliases:["balanca-urano-udc-pop-6-1"],name:"Balança Urano UDC POP 6 kg / 1 g",manufacturerId:"org_urano",line:"UDC POP",category:"Balanças comerciais",mainImage:{src:"/images/products/scales/urano-udc-pop-6kg-v1.jpg",alt:"Balança comercial Urano UDC POP com plataforma de inox",sourceUrl:"https://b2b.nowak.com.br/balancas/balanca-comercial/balanca-pesadora-6kg-divisao-1g-urano-udc6-1pop-ref-20094",credit:"Urano, reprodução do varejista Nowak",rights:"official-promotional",width:800,height:800},gallery:[],shortDescription:"Balança comercial de bancada com capacidade de 6 kg, divisão de 1 g, tara, plataforma inox e fonte bivolt automática.",strengths:["Divisão de 1 g em toda a faixa de até 6 kg atende padronização de lotes e porções","Projeto comercial com plataforma inox, pés reguláveis e bateria interna","Homologação metrológica e construção apropriada para áreas de produção"],limitations:["É muito mais cara e volumosa que uma balança doméstica simples","Carga mínima e resolução de 1 g não substituem balança de precisão para aditivos em frações de grama"],suitableFor:["Produção crescente que exige pesagem diária, plataforma maior e equipamento comercial","Negócio que também precisa conferir porções e recebimento dentro de 6 kg"],categories:["Balanças comerciais","Equipamentos de confeitaria"],tags:["6 kg","Divisão de 1 g","Plataforma inox","Bivolt"],relatedProductIds:["prod_fischer_premier_48l"],relatedArticleSlugs:[articleSlug],editorialSummary:"É a alternativa de crescimento, não a compra inicial padrão. Uma balança doméstica de 5 kg com divisão de 1 g e tara basta para começar; a UDC POP passa a fazer sentido quando frequência, estabilidade, plataforma e uso comercial justificam o custo.",seo:{title:"Urano UDC POP 6 kg/1 g: ficha e usos",description:"Ficha da balança comercial Urano UDC POP de 6 kg com divisão de 1 g, plataforma inox, alimentação, limitações e aplicação em produção."},sources:[source("Catálogo comercial Urano — UDC POP","https://www.urano.com.br/wp-content/uploads/2020/06/cat_comercial_rev8_web.pdf"),source("Urano UDC POP 6 kg — ficha do varejista","https://b2b.nowak.com.br/balancas/balanca-comercial/balanca-pesadora-6kg-divisao-1g-urano-udc6-1pop-ref-20094")],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
];

export const confectioneryEssentialVariants: ProductVariant[] = [
  {id:"prod_variant_fischer_premier_48l_127_br",productId:"prod_fischer_premier_48l",name:"Premier 48 L preto 127 V",market:"BR",manufacturerModelNumber:"29420-70307",distinguishingAttributes:{voltage:"127 V",color:"Preto"},specifications:{type:"generic",groups:[{label:"Cocção",entries:[{key:"capacity",label:"Capacidade",value:"48 litros"},{key:"temperature",label:"Temperatura",value:"50 °C a 300 °C"},{key:"heating",label:"Aquecimento",value:"Resistências superior e inferior; dourador independente"},{key:"timer",label:"Timer",value:"Até 120 minutos com aviso sonoro"}]},{label:"Dimensões e instalação",entries:[{key:"external",label:"Dimensões externas",value:"575 × 370 × 524,5 mm"},{key:"internal",label:"Dimensões internas",value:"392 × 267 × 445 mm"},{key:"weight",label:"Peso",value:"13,7 kg"},{key:"power",label:"Potência e tensão",value:"1.775 W · 127 V · 13,8 A"}]},{label:"Construção",entries:[{key:"door",label:"Porta",value:"Vidro duplo"},{key:"interior",label:"Interior",value:"EasyClean, luz interna e bandeja esmaltada para resíduos"},{key:"warranty",label:"Garantia",value:"12 meses"}]}]},imageIds:[],sources:[source("Manual oficial Fischer Premier 48 litros","https://www.fischer.com.br/media/amasty/amfile/attach/RKSJxKdm6FPzef8QD8brRZeldwEhBYS1.pdf")],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_urano_udc_pop_6_1_br",productId:"prod_urano_udc_pop_6_1",name:"UDC POP 6 kg / 1 g",market:"BR",manufacturerModelNumber:"22.31.104.0247",distinguishingAttributes:{capacity:"6 kg",division:"1 g"},specifications:{type:"generic",groups:[{label:"Pesagem",entries:[{key:"capacity",label:"Capacidade",value:"6 kg"},{key:"division",label:"Divisão",value:"1 g em toda a faixa"},{key:"tare",label:"Tara",value:"Sim"},{key:"platform",label:"Plataforma",value:"Aço inox, 310 × 270 mm"}]},{label:"Construção e alimentação",entries:[{key:"dimensions",label:"Dimensões",value:"340 × 120 × 420 mm"},{key:"display",label:"Visor",value:"LCD frontal e traseiro com iluminação"},{key:"power",label:"Alimentação",value:"Fonte automática de 90 a 240 V e bateria interna"},{key:"warranty",label:"Garantia",value:"12 meses segundo o varejista consultado"}]}]},imageIds:[],sources:[source("Catálogo comercial Urano — UDC POP","https://www.urano.com.br/wp-content/uploads/2020/06/cat_comercial_rev8_web.pdf")],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
];

export const confectioneryEssentialOffers: ProductOffer[] = [
  {id:"prod_offer_fischer_premier_48l_127",variantId:"prod_variant_fischer_premier_48l_127_br",retailer:"Fischer",url:"https://www.fischer.com.br/forno-eletrico-fischer-premier-bancada-48l/p",region:"BR",observedPrice:{amount:899,currency:"BRL"},availability:"available",checkedAt:reviewedAt},
];
