import type { Product, ProductOffer, ProductVariant } from "./productSchema";

const checked="2026-09-05";
type Category="Air fryers"|"Robôs aspiradores"|"Cafeteiras espresso"|"Aspiradores verticais";
type Seed={key:string;name:string;maker:string;line:string;category:Category;image:string;imageUrl:string;source:string;price:number;retailer:string;voltage:string;specs:Record<string,string>;strength:string;limit:string;profile:string;availability?:"available"|"unavailable"};
const articleByCategory:Record<Category,string[]>={
  "Air fryers":["melhores-air-fryers-2026"],
  "Robôs aspiradores":["melhores-robos-aspiradores-2026"],
  "Cafeteiras espresso":["melhores-cafeteiras-espresso-custo-beneficio-2026"],
  "Aspiradores verticais":["melhores-aspiradores-verticais-sem-fio-2026"],
};
const seeds:Seed[]=[
  {key:"electrolux_eaf10",name:"Electrolux EAF10",maker:"electrolux",line:"Efficient",category:"Air fryers",image:"air-fryers/electrolux-eaf10.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/219291/AirFryer_EAF10_Front_Electrolux_portuguese-principal.jpg",source:"https://loja.electrolux.com.br/eletroportateis/air-fryer",price:399.90,retailer:"Electrolux",voltage:"127 V ou 220 V",specs:{Capacidade:"3,2 L total",Potência:"1.400 W",Controles:"Analógicos",Cesto:"Removível e antiaderente"},strength:"Ocupa pouco espaço e atende porções pequenas sem pagar por funções digitais.",limit:"A área útil é pequena para uma família e exige preparar em lotes.",profile:"Uma ou duas pessoas e cozinhas compactas."},
  {key:"electrolux_eaf40",name:"Electrolux EAF40",maker:"electrolux",line:"Efficient",category:"Air fryers",image:"air-fryers/electrolux-eaf40.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/164224/Airfryer_EAF40_Perspective_Electrolux_Portuguese.jpg",source:"https://loja.electrolux.com.br/eletroportateis/air-fryer",price:299.90,retailer:"Electrolux",voltage:"127 V ou 220 V",specs:{Capacidade:"5,6 L total; cesto útil menor",Potência:"1.400 W",Controles:"Analógicos",Cesto:"Antiaderente"},strength:"Entrega cesto familiar por preço de aparelho compacto.",limit:"O controle analógico é simples e o volume anunciado não equivale à área plana.",profile:"Casal ou família pequena que quer gastar pouco."},
  {key:"electrolux_eaf45",name:"Electrolux EAF45",maker:"electrolux",line:"Experience",category:"Air fryers",image:"air-fryers/electrolux-eaf45.jpg",imageUrl:"https://electroluxar.vtexassets.com/arquivos/ids/164230/Airfryer_EAF45_Perspective_Electrolux_Spanish.jpg",source:"https://loja.electrolux.com.br/eletroportateis/air-fryer",price:399.90,retailer:"Electrolux",voltage:"127 V ou 220 V",specs:{Capacidade:"5,6 L total; cesto de 4 L",Potência:"1.400 W",Controles:"Painel digital",Recursos:"Lembrete para virar"},strength:"O painel e o lembrete ajudam a repetir preparos sem encarecer demais.",limit:"Não aumenta a área útil em relação à EAF40.",profile:"Quem quer controles digitais em uma air fryer familiar."},
  {key:"electrolux_eaf50",name:"Electrolux EAF50",maker:"electrolux",line:"Family Efficient",category:"Air fryers",image:"air-fryers/electrolux-eaf50.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/294440/Airfryer_EAF50_FrontView_Electrolux_Portuguese.jpg",source:"https://loja.electrolux.com.br/eletroportateis/air-fryer",price:419.90,retailer:"Electrolux",voltage:"127 V ou 220 V",specs:{Capacidade:"5 L",Potência:"1.700 W",Controles:"Analógicos",Cesto:"Removível"},strength:"Potência e formato equilibrados para o uso familiar cotidiano.",limit:"Perde funções digitais para a EAF45 e espaço para a EAF71.",profile:"Famílias pequenas que preferem comandos simples."},
  {key:"electrolux_eaf71",name:"Electrolux EAF71",maker:"electrolux",line:"Efficient",category:"Air fryers",image:"air-fryers/electrolux-eaf71.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/296285/Airfryer_EAF71_Front_Electrolux_Portuguese-1000x1000.jpg",source:"https://loja.electrolux.com.br/eletroportateis/air-fryer",price:399.90,retailer:"Electrolux",voltage:"127 V ou 220 V",specs:{Capacidade:"7 L total",Potência:"1.700 W",Controles:"Analógicos",Cesto:"Familiar"},strength:"O cesto mais largo reduz a necessidade de empilhar alimentos.",limit:"É maior na bancada e não possui painel digital.",profile:"Família de três a cinco pessoas."},
  {key:"electrolux_eaf180",name:"Electrolux EAF180",maker:"electrolux",line:"Expert",category:"Air fryers",image:"air-fryers/electrolux-eaf180.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/296475/Airfryer_EAF180_Front_Electrolux_Portuguese.jpg",source:"https://loja.electrolux.com.br/eletroportateis/air-fryer",price:819.90,retailer:"Electrolux",voltage:"127 V ou 220 V",specs:{Capacidade:"7 L",Potência:"1.700 W",Controles:"Digitais",Recursos:"Vapor e autolimpeza"},strength:"Vapor amplia o repertório e ajuda em alimentos que ressecam facilmente.",limit:"Custa quase o dobro das opções convencionais de mesma capacidade.",profile:"Quem realmente usará vapor e limpeza assistida."},
  {key:"electrolux_eaf90",name:"Electrolux EAF90",maker:"electrolux",line:"Experience Oven",category:"Air fryers",image:"air-fryers/electrolux-eaf90.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/285870/EAF90_Front_Electrolux_Portuguese-1000x1000.raw.jpg",source:"https://loja.electrolux.com.br/air-fryer-oven-electrolux-rita-lobo-12l-digital-grafite-c--espeto-e-grelhas-antiaderente--eaf90-/p",price:799.90,retailer:"Electrolux",voltage:"127 V ou 220 V",specs:{Capacidade:"12 L de cavidade; cesto de 3,5 L",Potência:"1.700 W",Formato:"Forno com duas grades",Dimensões:"32,2 × 40,9 × 37,6 cm"},strength:"Grades, espeto e porta transparente permitem preparos que uma cuba não acomoda.",limit:"Os 12 L não representam um cesto de 12 L e a limpeza envolve mais peças.",profile:"Família que quer forno compacto e air fryer no mesmo aparelho."},
  {key:"oster_ofrt780",name:"Oster Oven Fryer OFRT780",maker:"oster",line:"Oven Fryer",category:"Air fryers",image:"air-fryers/oster-ofrt780.jpg",imageUrl:"https://www.oster.com.br/arquivos/ids/160920/OFRT780-1.jpg",source:"https://www.oster.com.br/fritadeira-oven-fryer-12l-oster-3-em-1/p",price:579.90,retailer:"Oster",voltage:"127 V ou 220 V",specs:{Capacidade:"12 L de cavidade",Potência:"1.800 W",Formato:"Forno, rotisserie e desidratador",Dimensões:"31 × 37,7 × 34,5 cm"},strength:"Entrega rotisserie e duas grades por preço menor que ovens equivalentes.",limit:"A oferta oficial estava marcada como esgotada e o cesto rotativo não substitui uma cuba larga.",profile:"Quem quer oven compacta e aceita procurar estoque em varejistas.",availability:"unavailable"},
  {key:"philips_hd9206",name:"Philips Walita Série 3000 HD9206",maker:"philips_walita",line:"Série 3000 Grill Edition",category:"Air fryers",image:"air-fryers/philips-hd9206.jpg",imageUrl:"https://www.documents.philips.com/assets/20240223/5dc20efed16c4deda342b11f00c91a07.jpg",source:"https://www.philips.com.br/c-p/HD9206_90/3000-series-airfryer",price:549.90,retailer:"Varejo brasileiro",voltage:"220 V no SKU HD9206/90; confira o SKU",specs:{Capacidade:"6,2 L",Potência:"2.000 W",Temperatura:"80 °C a 200 °C",Controles:"Analógicos"},strength:"A cuba XL e o fluxo Rapid Air são o diferencial prático, não apenas os watts.",limit:"O SKU e a tensão precisam ser conferidos; não há painel digital.",profile:"Família que prioriza uma cuba convencional ampla."},
  {key:"philips_ri9270",name:"Philips Walita Série 3000 XL RI9270",maker:"philips_walita",line:"Série 3000 XL",category:"Air fryers",image:"air-fryers/philips-ri9270.jpg",imageUrl:"https://www.documents.philips.com/assets/20210505/4c97e550e25e4b2ea125ad1f00d9e529.jpg",source:"https://www.philips.com.br/c-p/RI9270_91/-",price:463.15,retailer:"AchaPromo",voltage:"127 V ou 220 V conforme final do SKU",specs:{Capacidade:"6,2 L; até 1,2 kg declarado",Potência:"2.000 W",Controles:"Digitais",Recursos:"Manter aquecido"},strength:"É a única desta seleção com capacidade em peso publicada pela marca.",limit:"Pode custar muito mais que rivais de cuba semelhante fora de promoção.",profile:"Quem quer controles digitais e referência de carga mais clara."},

  {key:"wap_robot_w90",name:"WAP Robot W90",maker:"wap",line:"Robot",category:"Robôs aspiradores",image:"robot-vacuums/wap-w90.jpg",imageUrl:"https://wap.vtexassets.com/arquivos/ids/162294/robot-w90.jpg",source:"https://loja.wap.ind.br/robo-aspirador-de-po-wap-robot-w90-perola/p",price:549.90,retailer:"WAP",voltage:"Carregador bivolt",specs:{Navegação:"Aleatória, cantos e espiral",Autonomia:"Até 1h40",Reservatório:"250 ml",Mop:"Pano passivo; sem tanque"},strength:"É barato, baixo e simples de operar com um botão.",limit:"Não mapeia, não retorna à base e pode repetir áreas enquanto ignora outras.",profile:"Cômodo pequeno e desobstruído; manutenção entre limpezas manuais."},
  {key:"wap_robot_w310",name:"WAP Robot W310",maker:"wap",line:"Robot",category:"Robôs aspiradores",image:"robot-vacuums/wap-w310.jpg",imageUrl:"https://wap.vtexassets.com/arquivos/ids/162397/w310.jpg",source:"https://loja.wap.ind.br/robo-aspirador-de-po-wap-robot-w310/p",price:1208.91,retailer:"WAP",voltage:"Carregador bivolt",specs:{Navegação:"Sensores e controle remoto",Autonomia:"Até 2h10",Reservatório:"420 ml",Base:"Retorno automático"},strength:"Base, escova central e reservatório maior melhoram a rotina sobre os robôs aleatórios básicos.",limit:"Não oferece mapa por aplicativo nem limpeza sistemática por LiDAR.",profile:"Quem quer retorno à base sem depender de aplicativo."},
  {key:"wap_robot_w1000",name:"WAP Robot W1000",maker:"wap",line:"Robot",category:"Robôs aspiradores",image:"robot-vacuums/wap-w1000.jpg",imageUrl:"https://wap.vtexassets.com/arquivos/ids/163002/7899831332618-WAP-ROBOT-W1000-06-3.jpg",source:"https://loja.wap.ind.br/robo-aspirador-de-po-wap-robot-w1000/p",price:1376.33,retailer:"WAP",voltage:"Carregador bivolt",specs:{Navegação:"Mapeamento por giroscópio e app",Autonomia:"Até 2h40",Reservatórios:"260 ml pó + 350 ml água",Mop:"Controle de água"},strength:"Mapeamento e assistência nacional custam menos que um LiDAR importado.",limit:"O mapa por giroscópio é menos preciso e recuperável que LiDAR.",profile:"Apartamento que precisa de rotas e agenda sem estação."},
  {key:"xiaomi_robot_vacuum_s20",name:"Xiaomi Robot Vacuum S20",maker:"xiaomi",line:"Robot Vacuum",category:"Robôs aspiradores",image:"robot-vacuums/xiaomi-s20.jpg",imageUrl:"https://i02.appmifile.com/mi-com-product/fly-birds/xiaomi-robot-vacuum-s20/M/73573752de22f572dab895a27fb78223.png",source:"https://www.mi.com/br/product/xiaomi-robot-vacuum-s20/",price:1589.19,retailer:"Varejo brasileiro via Zoom",voltage:"Base/carregador conforme importador",specs:{Navegação:"LiDAR LDS",SucçãoDeclarada:"5.000 Pa",Reservatórios:"400 ml pó + 270 ml água",Mop:"Passivo com rota em Y"},strength:"LiDAR cria mapas e rotas previsíveis mesmo com pouca luz.",limit:"Mop só arrasta o pano e suporte/garantia dependem do vendedor.",profile:"Quem quer LiDAR e bom aplicativo sem pagar por estação."},
  {key:"wap_robot_w4000",name:"WAP Robot W4000",maker:"wap",line:"Robot",category:"Robôs aspiradores",image:"robot-vacuums/wap-w4000.jpg",imageUrl:"https://wap.vtexassets.com/arquivos/ids/162922/robot-w4000.jpg",source:"https://loja.wap.ind.br/robo-aspirador-w4000/p",price:2456.10,retailer:"Varejo brasileiro",voltage:"127 V ou 220 V conforme estação",specs:{Navegação:"LiDAR 360°",Autonomia:"Até 2 horas",Mop:"Dois discos giratórios",Estação:"Autoesvaziamento do pó; mops exigem limpeza"},strength:"Combina LiDAR, mop giratório e estação com suporte local.",limit:"A tensão da estação é fixa e consumíveis tornam a posse mais cara.",profile:"Quem quer reduzir o esvaziamento manual sem presumir que a base lave os mops."},
  {key:"samsung_jet_bot_combo",name:"Samsung Bespoke Jet Bot Combo AI",maker:"samsung_electronics",line:"Bespoke Jet Bot",category:"Robôs aspiradores",image:"robot-vacuums/samsung-jet-bot-combo.jpg",imageUrl:"https://images.samsung.com/is/image/samsung/p6pim/br/vr7md96514g-az/gallery/br-bespoke-jet-bot-combo-vr7md96514g-az-542891489?$684_547_PNG$",source:"https://www.samsung.com/br/vacuum-cleaners/robot/70w-jet-bot-combo-all-in-one-clean-station-steam-plus-with-steamwash-satin-greige-vr7md96514g-az/",price:6999,retailer:"Samsung Brasil",voltage:"Confira a tensão da estação",specs:{Navegação:"LiDAR e reconhecimento de objetos",Mop:"Discos giratórios",Estação:"Esvazia, lava e seca mops",App:"SmartThings"},strength:"A estação reduz várias tarefas e o desvio de objetos é mais sofisticado.",limit:"Preço, tamanho da estação e manutenção só fazem sentido em casas compatíveis.",profile:"Casa grande, pets e orçamento premium."},

  {key:"oster_ocaf900",name:"Oster Espresso Double Digital OCAF900",maker:"oster",line:"Double Digital",category:"Cafeteiras espresso",image:"espresso/oster-ocaf900.jpg",imageUrl:"https://www.oster.com.br/arquivos/ids/161255/ocaf900.jpg",source:"https://www.oster.com.br/cozinha/cafeteiras-espresso/220V/234",price:729.90,retailer:"Oster",voltage:"127 V ou 220 V",specs:{Tipo:"Manual com filtros pressurizados",Café:"Pó e cápsula compatível",Leite:"Vaporizador manual",Moedor:"Não incluso"},strength:"É a entrada mais barata sem abandonar café moído e vaporizador.",limit:"Para controlar moagem e extrair melhor, exige moedor separado.",profile:"Iniciante que alterna pó e cápsula."},
  {key:"oster_ocaf950",name:"Oster Compacta Perfect Moment OCAF950",maker:"oster",line:"Perfect Moment",category:"Cafeteiras espresso",image:"espresso/oster-ocaf950.jpg",imageUrl:"https://www.oster.com.br/arquivos/ids/161430/ocaf950.jpg",source:"https://www.oster.com.br/cozinha/cafeteiras-espresso/maquina",price:899.90,retailer:"Oster",voltage:"127 V ou 220 V",specs:{Tipo:"Manual compacta",Leite:"Vaporizador",Moedor:"Não incluso",Perfil:"Bancada pequena"},strength:"Ocupa menos bancada que máquinas com moedor e mantém vaporização manual.",limit:"O custo do moedor pode superar o da própria cafeteira.",profile:"Cozinha pequena e usuário disposto a aprender."},
  {key:"oster_primalatte_touch",name:"Oster PrimaLatte Touch",maker:"oster",line:"PrimaLatte",category:"Cafeteiras espresso",image:"espresso/oster-primalatte-touch.jpg",imageUrl:"https://www.oster.com.br/arquivos/ids/159754/primalatte-touch.jpg",source:"https://www.oster.com.br/cozinha/cafeteiras-espresso/maquina",price:1199,retailer:"Oster",voltage:"127 V ou 220 V",specs:{Tipo:"Semiautomática",Café:"Pó, sachê e cápsula compatível",Leite:"Reservatório automático",Moedor:"Não incluso"},strength:"Prepara bebidas com leite com menos técnica e limpeza imediata do bico.",limit:"A espuma automática oferece menos controle e acrescenta peças para higienizar.",profile:"Quem bebe cappuccino e latte com frequência."},
  {key:"oster_xpert_perfect_brew",name:"Oster Xpert Perfect Brew",maker:"oster",line:"Perfect Brew",category:"Cafeteiras espresso",image:"espresso/oster-xpert-perfect-brew.jpg",imageUrl:"https://www.oster.com.br/arquivos/ids/158851/xpert-perfect-brew.jpg",source:"https://www.oster.com.br/cafeteira-espresso-oster-xpert-perfect-brew/p",price:2399,retailer:"Oster",voltage:"127 V ou 220 V",specs:{Tipo:"Semiautomática",Moedor:"Cônico, 30 ajustes, 250 g",Bomba:"15 bar declarados",Reservatório:"2,8 L"},strength:"Integra moedor, controle térmico e acessórios em um kit coerente.",limit:"É grande, exige regulagem e a pressão anunciada não garante boa extração sozinha.",profile:"Entusiasta que quer aprender sem comprar moedor separado."},
  {key:"oster_ocaf980",name:"Oster Superautomática OCAF980",maker:"oster",line:"Superautomática",category:"Cafeteiras espresso",image:"espresso/oster-ocaf980.jpg",imageUrl:"https://www.oster.com.br/arquivos/ids/161621/ocaf980.jpg",source:"https://www.oster.com.br/cozinha/cafeteiras-espresso/maquina",price:2499,retailer:"Oster",voltage:"127 V ou 220 V",specs:{Tipo:"Superautomática",Moedor:"Cônico integrado",Bebidas:"Espresso e café a partir do grão",Manutenção:"Limpeza e descalcificação periódicas"},strength:"Entrega café do grão à xícara com menos operação manual.",limit:"O usuário perde controle e assume manutenção interna mais complexa.",profile:"Escritório ou casa que prioriza conveniência."},
  {key:"tramontina_breville_express",name:"Tramontina by Breville Express",maker:"tramontina",line:"Breville Express",category:"Cafeteiras espresso",image:"espresso/tramontina-breville-express.jpg",imageUrl:"https://assets.tramontina.com.br/upload/tramon/imagens/CUT/69065011PDM001G.jpg",source:"https://www.tramontina.com.br/cafeteira-eletrica-tramontina-by-breville-express-em-aco-inox-1-8-l-127-v/69065011.html",price:5034.14,retailer:"Tramontina",voltage:"127 V ou 220 V em SKUs separados",specs:{Tipo:"Semiautomática",Moedor:"Integrado",Reservatório:"1,8 L",Garantia:"1 ano"},strength:"Conjunto maduro para controlar moagem, dose e vaporização em uma só máquina.",limit:"O preço oficial está muito acima da Xpert e aproxima-se de equipamentos especializados.",profile:"Entusiasta que aceita pagar pelo ecossistema Breville."},

  {key:"wap_eco_rapido",name:"WAP Eco Rápido",maker:"wap",line:"Eco Rápido",category:"Aspiradores verticais",image:"stick-vacuums/wap-eco-rapido.jpg",imageUrl:"https://wap.vtexassets.com/arquivos/ids/161190/eco-rapido.jpg",source:"https://loja.wap.ind.br/aspirador-de-po-2-em-1-sem-fio-wap-eco-rapido/p",price:599.90,retailer:"Varejo brasileiro",voltage:"Carregador bivolt",specs:{Autonomia:"Mais de 40 min Eco; mais de 17 min Turbo",Bateria:"14,4 V, 2.000 mAh, integrada",Peso:"2,4 kg",Reservatório:"0,7 L"},strength:"É leve, bivolt e tem autonomia adequada à manutenção diária.",limit:"A bateria não é removível e o modo turbo reduz bastante o tempo útil.",profile:"Piso frio, apartamento e limpezas rápidas."},
  {key:"electrolux_erg019",name:"Electrolux Ergorápido ERG019",maker:"electrolux",line:"Ergorápido",category:"Aspiradores verticais",image:"stick-vacuums/electrolux-erg019.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/244070/Vacuum_Cleaner_ERG019_FrontView_Electrolux-1000x1000.jpg",source:"https://loja.electrolux.com.br/aspirador-de-po-vertical-sem-fio-electrolux-ergorapido-2-em-1-cyclonic-power-ate-30-min-azul-ERG019/p",price:699.90,retailer:"Electrolux",voltage:"Bivolt",specs:{Autonomia:"Até 30 minutos",Formato:"2 em 1 com unidade de mão",Filtro:"HEPA",Bateria:"Lítio integrada"},strength:"Fica em pé sozinho e a unidade destacável ajuda em móveis e carro.",limit:"Trinta minutos declarados podem não cobrir casa grande, sobretudo em potência alta.",profile:"Apartamento e manutenção entre faxinas."},
  {key:"electrolux_erg28",name:"Electrolux Ergorápido ERG28",maker:"electrolux",line:"Ergorápido",category:"Aspiradores verticais",image:"stick-vacuums/electrolux-erg28.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/244095/ERG28.jpg",source:"https://loja.electrolux.com.br/aspirador-de-po-vertical-18v-ergorapido-electrolux-sem-fio-2-em-1-luz-led-ate-35-min--erg28-/p",price:999.90,retailer:"Electrolux",voltage:"Bivolt",specs:{Autonomia:"Até 35 minutos",Bateria:"Lítio 18 V integrada",Peso:"3,6 kg",Acessórios:"Bocal de cantos e frestas"},strength:"18 V e escova iluminada formam um degrau acima do ERG019.",limit:"É pesado para escadas e a bateria não é trocada durante a limpeza.",profile:"Casa média com pisos e tapetes baixos."},
  {key:"electrolux_erg26",name:"Electrolux Ergorápido ERG26",maker:"electrolux",line:"Ergorápido Pet",category:"Aspiradores verticais",image:"stick-vacuums/electrolux-erg26.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/244088/ERG26.jpg",source:"https://loja.electrolux.com.br/eletroportateis/aspirador-de-po/aspirador-de-po-vertical-sem-fio",price:999.90,retailer:"Electrolux",voltage:"Bivolt",specs:{Autonomia:"Até 45 minutos",Formato:"2 em 1",Acessórios:"Bocal Pet",Filtro:"Sistema ciclônico"},strength:"Bocal específico e autonomia maior são diferenças úteis para pelos.",limit:"Pelos continuam exigindo remover fios da escova e limpar filtros.",profile:"Casa com animais e tapetes baixos."},
  {key:"electrolux_emc2500",name:"Electrolux EMC2500",maker:"electrolux",line:"Multifuncional",category:"Aspiradores verticais",image:"stick-vacuums/electrolux-emc2500.jpg",imageUrl:"https://electrolux.vtexassets.com/arquivos/ids/292040/EMC2500.jpg",source:"https://loja.electrolux.com.br/eletroportateis/aspirador-de-po/aspirador-de-po-vertical-sem-fio",price:2099.90,retailer:"Electrolux",voltage:"Bivolt",specs:{Autonomia:"Até 40 minutos",Formato:"3 em 1",Painel:"LED",Acessórios:"Pisos, móveis e áreas altas"},strength:"O corpo modular alcança piso, estofado e partes altas melhor que o 2 em 1 clássico.",limit:"O preço exige comparar potência, bateria e acessórios com modelos premium.",profile:"Quem precisa limpar várias superfícies com um aparelho."},
  {key:"samsung_bespoke_jet_ai",name:"Samsung Bespoke Jet AI",maker:"samsung_electronics",line:"Bespoke Jet",category:"Aspiradores verticais",image:"stick-vacuums/samsung-bespoke-jet-ai.jpg",imageUrl:"https://images.samsung.com/is/image/samsung/p6pim/br/vs28c9762uk-az/gallery/br-bespoke-jet-ai-vs28c9762uk-az-537124687?$684_547_PNG$",source:"https://www.samsung.com/br/vacuum-cleaners/stick/bespoke-jet-ai-black-vs28c9762uk-az/",price:5699,retailer:"Samsung Brasil",voltage:"Base conforme SKU brasileiro",specs:{SucçãoDeclarada:"Até 280 W",Autonomia:"Até 100 min no mínimo e sem escova motorizada",Reservatório:"0,5 L",Estação:"Esvaziamento automático"},strength:"Bateria removível, escovas e estação atendem uma limpeza principal mais completa.",limit:"A autonomia máxima não representa uso normal com escova e potência alta.",profile:"Casa grande, tapetes e orçamento premium."},
];

const image=(s:Seed)=>({src:`/images/products/${s.image}`,alt:`${s.name} visto em fotografia oficial de catálogo`,sourceUrl:s.imageUrl,credit:s.maker.replaceAll("_"," "),rights:"official-promotional" as const,width:1000,height:1000});
export const homeCleaningProducts:Product[]=seeds.map(s=>({id:`prod_${s.key}`,contentType:"product",schemaVersion:1,slug:s.key.replaceAll("_","-"),aliases:[],name:s.name,manufacturerId:`org_${s.maker}`,line:s.line,category:s.category,mainImage:image(s),gallery:[],shortDescription:`${s.name} para ${s.profile.toLowerCase()} Versão pesquisada: ${s.voltage}.`,strengths:[s.strength],limitations:[s.limit],suitableFor:[s.profile],categories:[s.category,"Casa"],tags:Object.values(s.specs).slice(0,4),relatedProductIds:[],relatedArticleSlugs:articleByCategory[s.category],editorialSummary:`${s.strength} Limitação principal: ${s.limit}`,seo:{title:`${s.name}: ficha, análise e ofertas`,description:`Ficha de ${s.name} com especificações, tensão, limitações e preço observado.`},sources:[{title:`${s.name} — fonte oficial`,url:s.source,accessedAt:checked}],status:"published",createdAt:checked,publishedAt:checked,updatedAt:checked,reviewedAt:checked}));
export const homeCleaningVariants:ProductVariant[]=seeds.map(s=>({id:`prod_variant_${s.key}_br`,productId:`prod_${s.key}`,name:`Versão brasileira — ${s.voltage}`,market:"BR",distinguishingAttributes:{voltage:s.voltage},specifications:{type:"generic",groups:[{label:"Especificações verificadas",entries:[...Object.entries(s.specs),["Voltagem",s.voltage]].map(([label,value])=>({key:label.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replaceAll(/[^a-z0-9]+/g,"-"),label,value}))}]},imageIds:[],sources:[{title:`${s.name} — fonte oficial`,url:s.source,accessedAt:checked}],status:"published",createdAt:checked,updatedAt:checked,reviewedAt:checked}));
export const homeCleaningOffers:ProductOffer[]=seeds.map(s=>({id:`prod_offer_${s.key}_reference`,variantId:`prod_variant_${s.key}_br`,retailer:s.retailer,url:s.source,region:"BR",observedPrice:{amount:s.price,currency:"BRL"},availability:s.availability ?? "available",checkedAt:checked}));
