import type { Product, ProductOffer, ProductVariant } from "./productSchema";

const reviewedAt = "2026-09-02";
const articleSlug = "melhores-notebooks-custo-beneficio";
const source = (title: string, url: string) => ({ title, url, accessedAt: reviewedAt });
const image = (src: string, alt: string, sourceUrl: string, credit: string, width: number, height: number, rights: "official-promotional" | "permission-pending" = "official-promotional"): Product["mainImage"] => ({
  src, alt, sourceUrl, credit, rights, width, height,
});
const notebook = (data: Omit<Extract<ProductVariant["specifications"], { type: "notebook" }>, "type">): ProductVariant["specifications"] => ({ type: "notebook", ...data });

export const notebookProducts: Product[] = [
  {
    id: "prod_acer_aspire_15_a15_51m", contentType: "product", schemaVersion: 1, slug: "acer-aspire-15-a15-51m", aliases: [], name: "Acer Aspire 15 A15-51M", manufacturerId: "org_acer", line: "Aspire 15", category: "Notebooks", releaseYear: 2024,
    mainImage: image("/images/products/notebooks/acer-aspire-15-a15-51m-v1.jpg", "Notebook Acer Aspire 15 A15-51M cinza visto de frente", "https://quenotebookcomprar.com.br/acer-aspire-15-a15-51m-56kr/", "Qual Notebook Comprar", 280, 240, "permission-pending"), gallery: [],
    shortDescription: "Notebook de 15,6 polegadas cuja variante A15-51M-56KR combina Core i5-13420H, 16 GB de RAM, SSD de 512 GB e Linux.",
    strengths: ["Core i5 série H e 16 GB sustentam multitarefa, programação leve e trabalho administrativo com folga", "SSD NVMe PCIe 4.0 de 512 GB e USB4 são diferenciais úteis na faixa", "Bateria de 53 Wh é maior que a de vários rivais de entrada"],
    limitations: ["Tela TN estreita os ângulos de visão e prejudica cores e contraste", "Memória soldada impede ampliar a RAM da variante A15-51M-56KR"], suitableFor: ["Quem prioriza desempenho de processador e multitarefa acima da qualidade da tela", "Estudantes e profissionais que aceitam Linux ou pretendem instalar outro sistema"], categories: ["Notebooks", "Eletrônicos"], tags: ["Core i5", "16 GB RAM", "512 GB SSD", "Linux", "USB4"], relatedProductIds: ["prod_asus_vivobook_15_m1502", "prod_positivo_vision_r15"], relatedArticleSlugs: [articleSlug],
    editorialSummary: "É a escolha de desempenho da seleção: o Core i5-13420H e os 16 GB oferecem mais margem para compilar projetos, manter muitas abas e usar aplicativos de escritório em paralelo. A tela TN é a concessão decisiva e impede tratá-lo como recomendação universal.", seo: { title: "Acer Aspire 15 A15-51M: ficha, análise e ofertas", description: "Ficha do Acer Aspire 15 A15-51M-56KR com especificações da variante brasileira, vantagens, limitações, preço observado e ofertas." },
    sources: [source("Acer Aspire 15 A15-51M-56KR — especificações oficiais", "https://www.acer.com/br-pt/laptops/aspire/aspire-intel/pdp/NX.J1RAL.004"), source("Acer A15-51M-56KR — variante e imagem", "https://quenotebookcomprar.com.br/acer-aspire-15-a15-51m-56kr/")], status: "published", createdAt: reviewedAt, publishedAt: reviewedAt, updatedAt: reviewedAt, reviewedAt,
  },
  {
    id: "prod_asus_vivobook_15_m1502", contentType: "product", schemaVersion: 1, slug: "asus-vivobook-15-m1502", aliases: [], name: "ASUS Vivobook 15 M1502", manufacturerId: "org_asus", line: "Vivobook 15", category: "Notebooks", releaseYear: 2023,
    mainImage: image("/images/products/notebooks/asus-vivobook-15-m1502-v1.jpg", "Notebook ASUS Vivobook 15 M1502 prateado aberto", "https://www.asus.com/br/laptops/for-home/vivobook/vivobook-15-m1502/", "ASUS Brasil", 800, 800), gallery: [],
    shortDescription: "Notebook de 15,6 polegadas cuja variante M1502YA-NJ612 traz Ryzen 7 5825U, 16 GB, SSD de 512 GB, tela IPS-level e KeepOS.", strengths: ["Tela IPS-level oferece ângulos de visão melhores que o painel TN do Acer", "Ryzen 7 de oito núcleos, 16 GB e SSD de 512 GB formam um conjunto equilibrado para estudo e trabalho", "Webcam com obturador físico e teclado numérico ajudam no uso cotidiano"], limitations: ["Processador é eficiente, mas pertence a uma arquitetura anterior às linhas Ryzen atuais", "RAM já está no limite de 16 GB informado para a configuração e Wi-Fi 5 é antigo"], suitableFor: ["Quem lê, escreve, participa de reuniões e quer uma tela mais confortável", "Quem precisa de bom equilíbrio entre multitarefa, peso e conectividade"], categories: ["Notebooks", "Eletrônicos"], tags: ["Ryzen 7", "16 GB RAM", "512 GB SSD", "IPS", "KeepOS"], relatedProductIds: ["prod_acer_aspire_15_a15_51m", "prod_positivo_vision_r15"], relatedArticleSlugs: [articleSlug],
    editorialSummary: "É a recomendação mais equilibrada para faculdade e trabalho porque evita a tela TN sem abrir mão de 16 GB e SSD de 512 GB. O Ryzen 7 5825U continua competente, mas sua idade e o teto de memória exigem preço inferior ao de notebooks mais novos.", seo: { title: "ASUS Vivobook 15 M1502: ficha, análise e ofertas", description: "Ficha do ASUS Vivobook 15 M1502YA-NJ612 com variante brasileira, tela, memória, armazenamento, limitações e preço observado." }, sources: [source("ASUS Vivobook 15 M1502 — especificações oficiais", "https://www.asus.com/br/laptops/for-home/vivobook/vivobook-15-m1502/techspec/"), source("Vivobook M1502YA-NJ612 — oferta Magazine Luiza", "https://www.magazineluiza.com.br/notebook-asus-vivobook-15-m1502ya-amd-ryzen-7-5825u-16gb-ram-512gb-ssd-linux-keepos-156-fhd-cool-silver-nj612/p/gkd48kae3c/in/note/")], status: "published", createdAt: reviewedAt, publishedAt: reviewedAt, updatedAt: reviewedAt, reviewedAt,
  },
  {
    id: "prod_positivo_vision_r15", contentType: "product", schemaVersion: 1, slug: "positivo-vision-r15", aliases: [], name: "Positivo Vision R15", manufacturerId: "org_positivo_tecnologia", line: "Vision R15", category: "Notebooks", releaseYear: 2024,
    mainImage: image("/images/products/notebooks/positivo-vision-r15-v1.jpg", "Notebook Positivo Vision R15 Linux aberto visto de frente", "https://loja.meupositivo.com.br/notebook-positivo-vision-r15-amd-ryzen-5-5500u-linux-16gb-ram-512gb-ssd-full-hd-15-6-preto-3002878/p", "Positivo", 1000, 1000), gallery: [], shortDescription: "Notebook brasileiro com Ryzen 5 5500U, 16 GB de RAM, SSD de 512 GB, tela IPS Full HD de 15,6 polegadas e Linux.", strengths: ["16 GB, SSD de 512 GB e tela IPS formam uma base adequada sem upgrade imediato", "Ryzen 5 de seis núcleos atende estudo, Office e multitarefa cotidiana", "Lumina Bar pode melhorar a imagem em reuniões realizadas em ambientes escuros"], limitations: ["Preço observado o aproxima de rivais com processadores ou construção superiores", "Expansão de RAM e armazenamento não foi confirmada para o SKU 3002878 nas fontes consultadas"], suitableFor: ["Quem encontra a variante de 16 GB em promoção substancial", "Quem quer tela IPS e memória suficiente gastando menos que nos modelos intermediários"], categories: ["Notebooks", "Eletrônicos"], tags: ["Ryzen 5", "16 GB RAM", "512 GB SSD", "IPS", "Linux"], relatedProductIds: ["prod_asus_vivobook_15_m1502", "prod_acer_aspire_15_a15_51m"], relatedArticleSlugs: [articleSlug], editorialSummary: "É uma opção barata condicional, não a melhor compra no preço cheio. O conjunto de 16 GB, 512 GB e IPS evita economias prejudiciais, mas só vence Acer e ASUS quando a diferença de preço é grande; perto de R$ 3.200, não vale.", seo: { title: "Positivo Vision R15: ficha, análise e ofertas", description: "Ficha do Positivo Vision R15 3002878 com Ryzen 5, 16 GB, SSD de 512 GB, tela IPS, limitações e preço observado." }, sources: [source("Positivo Vision R15 3002878 — página oficial", "https://loja.meupositivo.com.br/notebook-positivo-vision-r15-amd-ryzen-5-5500u-linux-16gb-ram-512gb-ssd-full-hd-15-6-preto-3002878/p")], status: "published", createdAt: reviewedAt, publishedAt: reviewedAt, updatedAt: reviewedAt, reviewedAt,
  },
];

export const notebookVariants: ProductVariant[] = [
  { id: "prod_variant_acer_aspire_15_a15_51m_56kr_br", productId: "prod_acer_aspire_15_a15_51m", name: "A15-51M-56KR, 16 GB + 512 GB, Linux", market: "BR", manufacturerModelNumber: "NX.J1RAL.004", distinguishingAttributes: { processor: "Core i5-13420H", ram: "16 GB", storage: "512 GB", operatingSystem: "Linux" }, specifications: notebook({ processor: "Intel Core i5-13420H, 8 núcleos e 12 threads", processorGeneration: "13ª geração", gpu: "Intel UHD integrada", ramGb: 16, ramType: "LPDDR5 soldada", ramUpgrade: "Sem expansão; memória soldada nesta variante", storageGb: 512, storageType: "SSD M.2 NVMe PCIe 4.0", storageUpgrade: "Um slot M.2 ocupado; substituição do SSD", display: { sizeInches: 15.6, resolution: "1920 × 1080", panelType: "TN antirreflexo", refreshRateHz: 60 }, batteryWh: 53, chargerWatts: 90, ports: ["2 × USB-A", "1 × USB4 Type-C", "1 × HDMI", "Conector de áudio"], usbC: "USB4 Type-C", videoOutput: "HDMI e vídeo por USB4", wifi: "Wi-Fi 6", bluetooth: "Bluetooth", webcam: "Webcam integrada", weightKg: 1.77, operatingSystem: "Linux 64 bits", warranty: "12 meses", keyboard: "ABNT2 com teclado numérico" }), imageIds: [], sources: [source("Acer Aspire 15 A15-51M-56KR — especificações oficiais", "https://www.acer.com/br-pt/laptops/aspire/aspire-intel/pdp/NX.J1RAL.004"), source("A15-51M-56KR — memória da variante", "https://quenotebookcomprar.com.br/acer-aspire-15-a15-51m-56kr/")], status: "published", createdAt: reviewedAt, updatedAt: reviewedAt, reviewedAt },
  { id: "prod_variant_asus_vivobook_15_m1502ya_nj612_br", productId: "prod_asus_vivobook_15_m1502", name: "M1502YA-NJ612, 16 GB + 512 GB, KeepOS", market: "BR", manufacturerModelNumber: "M1502YA-NJ612", distinguishingAttributes: { processor: "Ryzen 7 5825U", ram: "16 GB", storage: "512 GB", operatingSystem: "KeepOS" }, specifications: notebook({ processor: "AMD Ryzen 7 5825U, 8 núcleos e 16 threads", processorGeneration: "Ryzen 5000, arquitetura Zen 3", gpu: "AMD Radeon integrada", ramGb: 16, ramType: "DDR4, 8 GB integrados + 8 GB SO-DIMM", ramUpgrade: "Um módulo SO-DIMM; máximo de 16 GB informado para a configuração", storageGb: 512, storageType: "SSD M.2 NVMe PCIe 3.0", storageUpgrade: "Um slot M.2 ocupado; substituição do SSD", display: { sizeInches: 15.6, resolution: "1920 × 1080", panelType: "IPS-level antirreflexo, 45% NTSC", brightnessNits: 250, refreshRateHz: 60 }, chargerWatts: 45, ports: ["2 × USB 3.2 Gen 1 Type-A", "1 × USB 3.2 Gen 1 Type-C", "1 × USB 2.0 Type-A", "1 × HDMI 1.4", "Conector de áudio"], usbC: "USB 3.2 Gen 1 Type-C", videoOutput: "HDMI 1.4", wifi: "Wi-Fi 5", bluetooth: "Bluetooth 4.1", webcam: "720p com obturador de privacidade", weightKg: 1.7, operatingSystem: "KeepOS (Linux)", warranty: "12 meses", keyboard: "ABNT2 com teclado numérico" }), imageIds: [], sources: [source("ASUS Vivobook 15 M1502 — especificações oficiais", "https://www.asus.com/br/laptops/for-home/vivobook/vivobook-15-m1502/techspec/"), source("M1502YA-NJ612 — identificação da variante", "https://www.magazineluiza.com.br/notebook-asus-vivobook-15-m1502ya-amd-ryzen-7-5825u-16gb-ram-512gb-ssd-linux-keepos-156-fhd-cool-silver-nj612/p/gkd48kae3c/in/note/")], status: "published", createdAt: reviewedAt, updatedAt: reviewedAt, reviewedAt },
  { id: "prod_variant_positivo_vision_r15_3002878_br", productId: "prod_positivo_vision_r15", name: "3002878, 16 GB + 512 GB, Linux", market: "BR", manufacturerModelNumber: "3002878", distinguishingAttributes: { processor: "Ryzen 5 5500U", ram: "16 GB", storage: "512 GB", operatingSystem: "Linux" }, specifications: notebook({ processor: "AMD Ryzen 5 5500U, 6 núcleos e 12 threads", processorGeneration: "Ryzen 5000, arquitetura Zen 2", gpu: "AMD Radeon integrada", ramGb: 16, ramType: "DDR4", ramUpgrade: "Não confirmado para a variante 3002878", storageGb: 512, storageType: "SSD M.2 NVMe", storageUpgrade: "Não confirmado para a variante 3002878", display: { sizeInches: 15.6, resolution: "1920 × 1080", panelType: "IPS antirreflexo", refreshRateHz: 60 }, ports: ["USB-A", "USB-C", "HDMI", "Conector de áudio"], usbC: "USB-C; funções adicionais não informadas na fonte oficial consultada", videoOutput: "HDMI", wifi: "Wi-Fi", bluetooth: "Bluetooth", webcam: "Webcam HD com Lumina Bar", weightKg: 1.75, operatingSystem: "Linux", warranty: "12 meses", keyboard: "ABNT2 com teclado numérico" }), imageIds: [], sources: [source("Positivo Vision R15 3002878 — especificações oficiais", "https://loja.meupositivo.com.br/notebook-positivo-vision-r15-amd-ryzen-5-5500u-linux-16gb-ram-512gb-ssd-full-hd-15-6-preto-3002878/p"), source("Vision R15 3002878 — peso", "https://quenotebookcomprar.com.br/positivo-vision-r15-3002878/")], status: "published", createdAt: reviewedAt, updatedAt: reviewedAt, reviewedAt },
];

export const notebookOffers: ProductOffer[] = [
  { id: "prod_offer_acer_aspire_15_a15_51m_56kr", variantId: "prod_variant_acer_aspire_15_a15_51m_56kr_br", retailer: "Mercado Livre", url: "https://www.mercadolivre.com.br/notebook-acer-aspire-15-a15-51m-56kr-intel-core-i5-13420h-13-geracao-16-gb-512ssd-156-full-hd/p/MLB43513588", region: "BR", observedPrice: { amount: 3347.07, currency: "BRL" }, availability: "available", checkedAt: reviewedAt },
  { id: "prod_offer_magalu_asus_vivobook_15_m1502ya_nj612", variantId: "prod_variant_asus_vivobook_15_m1502ya_nj612_br", retailer: "Magazine Luiza", url: "https://www.magazineluiza.com.br/notebook-asus-vivobook-15-m1502ya-amd-ryzen-7-5825u-16gb-ram-512gb-ssd-linux-keepos-156-fhd-cool-silver-nj612/p/gkd48kae3c/in/note/", region: "BR", observedPrice: { amount: 3599.20, currency: "BRL" }, availability: "available", checkedAt: reviewedAt },
  { id: "prod_offer_positivo_vision_r15_3002878", variantId: "prod_variant_positivo_vision_r15_3002878_br", retailer: "Positivo", url: "https://loja.meupositivo.com.br/notebook-positivo-vision-r15-amd-ryzen-5-5500u-linux-16gb-ram-512gb-ssd-full-hd-15-6-preto-3002878/p", region: "BR", observedPrice: { amount: 3249, currency: "BRL" }, availability: "available", checkedAt: reviewedAt },
];
