import type { Product, ProductOffer, ProductVariant } from "./productSchema";

const reviewedAt = "2026-09-04";
const slugs = ["pc-gamer-ate-3000", "pc-gamer-ate-4000", "pc-gamer-ate-5000", "pc-gamer-ate-6000", "pc-gamer-sem-placa-de-video", "pc-gamer-pronto-ou-montar", "quanto-custa-montar-um-pc-gamer", "pc-para-estudar-trabalhar-e-jogar"];
const source = (title: string, url: string) => ({ title, url, accessedAt: reviewedAt });
const image = (src: string, alt: string, sourceUrl: string, credit: string): Product["mainImage"] => ({ src, alt, sourceUrl, credit, rights: "official-promotional", width: 600, height: 600 });
const generic = (entries: Array<[string,string,string]>): ProductVariant["specifications"] => ({ type: "generic", groups: [{ label: "Especificações", entries: entries.map(([key,label,value]) => ({ key,label,value })) }] });
const product = (id:string, slug:string, name:string, manufacturerId:string, category:string, img:string, alt:string, page:string, credit:string, description:string, strengths:string[], limitations:string[], suitableFor:string[], relatedProductIds:string[]):Product => ({
  id, contentType:"product", schemaVersion:1, slug, aliases:[], name, manufacturerId, category, mainImage:image(img,alt,page,credit), gallery:[], shortDescription:description,
  strengths, limitations, suitableFor, categories:[category,"Hardware"], tags:["PC gamer","Hardware"], relatedProductIds, relatedArticleSlugs:slugs,
  editorialSummary:`${description} A recomendação depende do preço da variante e da compatibilidade com o restante da configuração.`, seo:{title:`${name}: ficha, análise e ofertas`,description:`Ficha do ${name} com especificações verificadas, vantagens, limitações, preços observados e artigos relacionados.`},
  sources:[source(`${name} — especificações`,page)], status:"published", createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt
});

export const pcComponentProducts:Product[] = [
  product("prod_amd_ryzen_5_7600","amd-ryzen-5-7600","AMD Ryzen 5 7600","org_amd","Processadores","/images/products/pc-components/amd-ryzen-5-7600-v1.jpg","Processador AMD Ryzen 5 7600 em sua embalagem","https://www.amd.com/en/products/processors/desktops/ryzen/7000-series/amd-ryzen-5-7600.html","AMD","Processador AM5 Zen 4 de seis núcleos e doze threads, com cooler Wraith Stealth e vídeo integrado básico.",["Plataforma AM5 oferece caminho de atualização mais amplo","PCIe 5.0 e DDR5 modernizam a base da configuração"],["Custo de placa-mãe e DDR5 pode retirar dinheiro da placa de vídeo"],["Montagens modernas que priorizam futuras trocas de CPU"],["prod_gigabyte_b650m_gaming_wifi","prod_gigabyte_geforce_rtx_5060_windforce"]),
  product("prod_gigabyte_b650m_gaming_wifi","gigabyte-b650m-gaming-wifi","Gigabyte B650M Gaming WiFi","org_gigabyte","Placas-mãe","/images/products/pc-components/gigabyte-b650m-gaming-wifi-v1.jpg","Placa-mãe Gigabyte B650M Gaming WiFi","https://www.gigabyte.com/Motherboard/B650M-GAMING-WIFI-rev-10","Gigabyte","Placa-mãe micro-ATX AM5 com dois slots DDR5, Wi-Fi e atualização de BIOS por Q-Flash Plus.",["AM5 permite futuras CPUs compatíveis sem trocar memória e placa","Q-Flash Plus facilita atualizar a BIOS"],["Apenas dois slots de memória reduzem a flexibilidade de expansão"],["Build AM5 econômica com kit de memória definido desde o início"],["prod_amd_ryzen_5_7600","prod_gigabyte_geforce_rtx_5060_windforce"]),
  product("prod_gigabyte_geforce_rtx_5060_windforce","gigabyte-geforce-rtx-5060-windforce","Gigabyte GeForce RTX 5060 Windforce OC 8 GB","org_gigabyte","Placas de vídeo","/images/products/pc-components/gigabyte-rtx-5060-windforce-v1.jpg","Placa de vídeo Gigabyte GeForce RTX 5060 Windforce OC","https://www.gigabyte.com/Graphics-Card/GV-N5060WF2OC-8GD","Gigabyte","Placa de vídeo Blackwell com 8 GB GDDR7, encoder AV1 e recursos DLSS 4, voltada sobretudo a 1080p.",["Bom desempenho por real no mercado observado e recursos fortes de upscaling","Encoder AV1 e ecossistema CUDA ajudam em criação compatível"],["Oito gigabytes limitam presets de textura e alguns cenários em 1440p"],["Full HD de alta qualidade e 1440p com ajustes e upscaling"],["prod_amd_ryzen_5_7600","prod_msi_mag_a650bn"]),
  product("prod_amd_ryzen_5_5600gt","amd-ryzen-5-5600gt","AMD Ryzen 5 5600GT","org_amd","Processadores","/images/products/pc-components/amd-ryzen-5-5600gt-v1.jpg","Processador AMD Ryzen 5 5600GT em sua embalagem","https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-5-5600gt.html","AMD","APU AM4 de seis núcleos e doze threads com gráficos Radeon integrados e cooler Wraith Stealth.",["Vídeo integrado permite montar o computador sem GPU dedicada","Seis núcleos e doze threads dão boa margem para uso geral"],["Interface PCIe 3.0 e plataforma AM4 já não oferecem a rota mais longa de atualização"],["PC econômico para jogos leves e futura instalação de placa de vídeo"],["prod_msi_b550m_pro_vdh_wifi","prod_kingston_fury_beast_ddr4_16gb"]),
  product("prod_amd_ryzen_5_5500","amd-ryzen-5-5500","AMD Ryzen 5 5500","org_amd","Processadores","/images/products/pc-components/amd-ryzen-5-5500-v1.jpg","Processador AMD Ryzen 5 5500 em sua embalagem","https://www.amd.com/en/products/processors/desktops/ryzen/5000-series/amd-ryzen-5-5500.html","AMD","Processador AM4 de seis núcleos e doze threads, sem gráficos integrados, acompanhado do cooler Wraith Stealth.",["Preço libera orçamento para uma placa de vídeo dedicada melhor","Seis núcleos e doze threads atendem jogos e multitarefa cotidiana"],["Não produz vídeo sem GPU dedicada e trabalha em PCIe 3.0"],["Montagens AM4 com GPU dedicada e orçamento controlado"],["prod_asrock_radeon_rx_6600_challenger","prod_asrock_radeon_rx_7600_challenger"]),
  product("prod_asrock_radeon_rx_6600_challenger","asrock-radeon-rx-6600-challenger","ASRock Radeon RX 6600 Challenger 8 GB","org_asrock","Placas de vídeo","/images/products/pc-components/asrock-rx-6600-challenger-v1.jpg","Placa de vídeo ASRock Radeon RX 6600 Challenger branca","https://www.asrock.com/Graphics-Card/AMD/Radeon%20RX%206600%20Challenger%20D%208GB/","ASRock","Placa de vídeo RDNA 2 com 8 GB GDDR6, voltada principalmente a jogos em 1080p.",["Desempenho em 1080p muito superior ao de gráficos integrados","Consumo típico de 132 W facilita uma montagem equilibrada"],["Ray tracing é limitado e a geração é antiga"],["Quem quer jogar em Full HD sem consumir quase todo o orçamento na GPU"],["prod_amd_ryzen_5_5500","prod_msi_mag_a650bn"]),
  product("prod_asrock_radeon_rx_7600_challenger","asrock-radeon-rx-7600-challenger","ASRock Radeon RX 7600 Challenger 8 GB","org_asrock","Placas de vídeo","/images/products/pc-components/asrock-rx-7600-challenger-v1.jpg","Placa de vídeo ASRock Radeon RX 7600 Challenger","https://www.asrock.com/Graphics-Card/AMD/Radeon%20RX%207600%20Challenger%208GB%20OC/","ASRock","Placa de vídeo RDNA 3 de 8 GB para Full HD em qualidade alta e 1440p com ajustes.",["Entrega mais margem de desempenho que a RX 6600 em jogos atuais","Suporta codificação AV1 e recursos da arquitetura RDNA 3"],["Os 8 GB limitam texturas máximas em alguns jogos pesados e ray tracing não é seu ponto forte"],["Quem prioriza Full HD em alta qualidade e aceita ajustar jogos pesados em 1440p"],["prod_amd_ryzen_5_5500","prod_msi_mag_a650bn"]),
  product("prod_msi_b550m_pro_vdh_wifi","msi-b550m-pro-vdh-wifi","MSI B550M PRO-VDH WIFI","org_msi","Placas-mãe","/images/products/pc-components/msi-b550m-pro-vdh-wifi-v1.jpg","Placa-mãe MSI B550M PRO-VDH WIFI","https://www.msi.com/Motherboard/B550M-PRO-VDH-WIFI","MSI","Placa-mãe micro-ATX AM4 com quatro slots DDR4, dois M.2, Wi-Fi e recurso Flash BIOS Button.",["Quatro slots de memória e dois M.2 preservam expansão","Flash BIOS Button reduz o risco de incompatibilidade de BIOS"],["AM4 encerrou sua principal trajetória de novas gerações"],["Montagens Ryzen 5000 que precisam de expansão e rede sem fio"],["prod_amd_ryzen_5_5600gt","prod_amd_ryzen_5_5500"]),
  product("prod_kingston_fury_beast_ddr4_16gb","kingston-fury-beast-ddr4-16gb","Kingston Fury Beast DDR4 16 GB (2 × 8 GB)","org_kingston","Memória RAM","/images/products/pc-components/kingston-fury-beast-ddr4-16gb-v1.jpg","Módulo de memória Kingston Fury Beast DDR4 preto","https://www.kingston.com/en/memory/gaming/kingston-fury-beast-ddr4-memory","Kingston","Kit DDR4-3200 CL16 de 16 GB em dois módulos para operação em dois canais.",["Dois módulos ativam dual-channel quando instalados nos slots corretos","16 GB são a base coerente para os três orçamentos"],["Dois módulos ocupam metade dos quatro slots da placa indicada"],["Jogos e uso geral em plataforma AM4"],["prod_msi_b550m_pro_vdh_wifi"]),
  product("prod_kingston_nv3_1tb","kingston-nv3-1tb","Kingston NV3 1 TB","org_kingston","Armazenamento","/images/products/pc-components/kingston-nv3-1tb-v1.jpg","SSD Kingston NV3 NVMe de 1 TB","https://www.kingston.com/en/ssd/nv3-nvme-pcie-ssd","Kingston","SSD M.2 NVMe de 1 TB para sistema, aplicativos e uma biblioteca inicial de jogos.",["Um terabyte evita o aperto imediato de unidades de 256 GB ou 512 GB","Formato M.2 dispensa cabos de dados e energia"],["É uma unidade de entrada e o desempenho sustentado varia conforme capacidade e carga"],["Configurações de jogos que precisam equilibrar capacidade e preço"],["prod_msi_b550m_pro_vdh_wifi"]),
  product("prod_msi_mag_a650bn","msi-mag-a650bn","MSI MAG A650BN 650 W","org_msi","Fontes","/images/products/pc-components/msi-mag-a650bn-v1.jpg","Fonte MSI MAG A650BN de 650 watts","https://www.msi.com/Power-Supply/MAG-A650BN","MSI","Fonte ATX de 650 W com certificação 80 Plus Bronze, PFC ativo e proteções elétricas declaradas.",["Potência e conectores atendem as configurações propostas com folga","Modelo identificável evita a loteria de fontes genéricas"],["Cabos fixos dificultam um pouco a organização interna"],["PCs intermediários com RX 6600 ou RX 7600"],["prod_asrock_radeon_rx_6600_challenger","prod_asrock_radeon_rx_7600_challenger"]),
];

export const pcComponentVariants:ProductVariant[] = [
  ["prod_variant_amd_ryzen_5_7600_box_br","prod_amd_ryzen_5_7600","100-100001015BOX",generic([["cores","Núcleos e threads","6 / 12"],["socket","Soquete","AM5"],["memory","Memória","DDR5, dois canais"],["pcie","PCIe","5.0"],["tdp","TDP","65 W"],["cooler","Cooler","Wraith Stealth incluído"]])],
  ["prod_variant_gigabyte_b650m_gaming_wifi_rev1_br","prod_gigabyte_b650m_gaming_wifi","B650M GAMING WIFI rev. 1.0",generic([["socket","Soquete","AM5"],["memory","Memória","2 × DDR5"],["storage","Armazenamento","M.2 PCIe 4.0 e SATA"],["network","Rede","Gigabit Ethernet e Wi-Fi"]])],
  ["prod_variant_gigabyte_rtx_5060_windforce_8gb_br","prod_gigabyte_geforce_rtx_5060_windforce","GV-N5060WF2OC-8GD",generic([["gpu","GPU","GeForce RTX 5060"],["memory","Memória","8 GB GDDR7"],["interface","Interface","PCIe 5.0 x8"],["power","Potência gráfica total","145 W"],["connector","Energia","1 × 8 pinos"]])],
  ["prod_variant_amd_ryzen_5_5600gt_box_br","prod_amd_ryzen_5_5600gt","100-100001488BOX",generic([["cores","Núcleos e threads","6 / 12"],["socket","Soquete","AM4"],["graphics","Vídeo","Radeon integrada, 7 núcleos gráficos a 1.900 MHz"],["tdp","TDP","65 W"],["pcie","PCIe","3.0"],["cooler","Cooler","Wraith Stealth incluído"]])],
  ["prod_variant_amd_ryzen_5_5500_box_br","prod_amd_ryzen_5_5500","100-100000457BOX",generic([["cores","Núcleos e threads","6 / 12"],["socket","Soquete","AM4"],["graphics","Vídeo","Não possui"],["tdp","TDP","65 W"],["pcie","PCIe","3.0"],["cooler","Cooler","Wraith Stealth incluído"]])],
  ["prod_variant_asrock_rx_6600_challenger_8gb_br","prod_asrock_radeon_rx_6600_challenger","90-GA4UZZ-00UANF",generic([["gpu","GPU","Radeon RX 6600"],["memory","Memória","8 GB GDDR6"],["power","Consumo típico","132 W"],["connector","Energia","1 × 8 pinos"]])],
  ["prod_variant_asrock_rx_7600_challenger_8gb_br","prod_asrock_radeon_rx_7600_challenger","90-GA41ZZ-00UANF",generic([["gpu","GPU","Radeon RX 7600"],["memory","Memória","8 GB GDDR6"],["power","Consumo típico","165 W"],["connector","Energia","1 × 8 pinos"]])],
  ["prod_variant_msi_b550m_pro_vdh_wifi_br","prod_msi_b550m_pro_vdh_wifi","B550M-PRO-VDH-WIFI",generic([["socket","Soquete","AM4"],["memory","Memória","4 × DDR4"],["storage","Armazenamento","2 × M.2 e 4 × SATA"],["network","Rede","Gigabit Ethernet, Wi-Fi e Bluetooth"]])],
  ["prod_variant_kingston_fury_beast_2x8_3200_br","prod_kingston_fury_beast_ddr4_16gb","KF432C16BBK2/16",generic([["capacity","Capacidade","16 GB (2 × 8 GB)"],["speed","Velocidade","DDR4-3200 CL16"]])],
  ["prod_variant_kingston_nv3_1tb_br","prod_kingston_nv3_1tb","SNV3S/1000G",generic([["capacity","Capacidade","1 TB"],["interface","Interface","M.2 2280 NVMe PCIe 4.0 x4"]])],
  ["prod_variant_msi_mag_a650bn_br","prod_msi_mag_a650bn","306-7ZP2B22-CE0",generic([["power","Potência","650 W"],["efficiency","Eficiência","80 Plus Bronze"],["pcie","PCIe","2 × 6+2 pinos"]])],
].map(([id,productId,model,specifications]) => ({id:id as string,productId:productId as string,name:`${model} (Brasil)`,market:"BR",manufacturerModelNumber:model as string,distinguishingAttributes:{model:model as string},specifications:specifications as ProductVariant["specifications"],imageIds:[],sources:[source("Especificações do fabricante",pcComponentProducts.find(p=>p.id===productId)?.sources[0].url ?? "https://www.amd.com/")],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt}));

export const pcComponentOffers:ProductOffer[] = [
  ["prod_offer_kabum_ryzen_7600","prod_variant_amd_ryzen_5_7600_box_br","https://www.kabum.com.br/produto/405799",999.99],
  ["prod_offer_kabum_gigabyte_b650m_gaming_wifi","prod_variant_gigabyte_b650m_gaming_wifi_rev1_br","https://www.kabum.com.br/produto/513870",859.99],
  ["prod_offer_pichau_gigabyte_rtx_5060_windforce","prod_variant_gigabyte_rtx_5060_windforce_8gb_br","https://www.pichau.com.br/placa-de-video-gigabyte-geforce-rtx-5060-windforce-oc-8gb-gddr7-128-bit-gv-n5060wf2oc-8gd",2599.99],
  ["prod_offer_kabum_ryzen_5600gt","prod_variant_amd_ryzen_5_5600gt_box_br","https://www.kabum.com.br/produto/520368",879.99],
  ["prod_offer_kabum_ryzen_5500","prod_variant_amd_ryzen_5_5500_box_br","https://www.kabum.com.br/produto/356695",539],
  ["prod_offer_kabum_rx_6600","prod_variant_asrock_rx_6600_challenger_8gb_br","https://www.kabum.com.br/produto/695107",1499.99],
  ["prod_offer_kabum_rx_7600","prod_variant_asrock_rx_7600_challenger_8gb_br","https://www.kabum.com.br/produto/459144",1879.99],
  ["prod_offer_kabum_b550m_pro_vdh_wifi","prod_variant_msi_b550m_pro_vdh_wifi_br","https://www.kabum.com.br/produto/114338",749.99],
  ["prod_offer_kabum_fury_beast_16gb","prod_variant_kingston_fury_beast_2x8_3200_br","https://www.kabum.com.br/produto/172366",319.99],
  ["prod_offer_kabum_kingston_nv3_1tb","prod_variant_kingston_nv3_1tb_br","https://www.kabum.com.br/produto/621162",399.99],
  ["prod_offer_kabum_msi_a650bn","prod_variant_msi_mag_a650bn_br","https://www.kabum.com.br/produto/369658",319.99],
].map(([id,variantId,url,amount]) => ({id:id as string,variantId:variantId as string,retailer:"KaBuM!",url:url as string,region:"BR",observedPrice:{amount:amount as number,currency:"BRL"},availability:"available",checkedAt:reviewedAt}));
