import { ProductCatalogSchema, type Product, type ProductVariant } from "./productSchema";
import { notebookOffers, notebookProducts, notebookVariants } from "./notebooks";
import { washerDryerOffers, washerDryerProducts, washerDryerVariants } from "./washerDryers";
import { blenderOffers, blenderProducts, blenderVariants } from "./blenders";
import { standMixerOffers, standMixerProducts, standMixerVariants } from "./standMixers";
import { confectioneryEssentialOffers, confectioneryEssentialProducts, confectioneryEssentialVariants } from "./confectioneryEssentials";

const articleSlug = "melhores-celulares-ate-1500";
const motoG86ArticleSlug = "moto-g86-vale-a-pena";
const tvArticleSlug = "melhores-tvs-custo-beneficio";
const reviewedAt = "2026-09-02";
const motoG86ReviewedAt = "2026-09-04";
const image = (src:string,alt:string,sourceUrl:string,credit:string,width:number,height:number):Product["mainImage"] => ({src,alt,sourceUrl,credit,rights:"official-promotional",width,height});
const smartphone = (data: Omit<Extract<ProductVariant["specifications"],{type:"smartphone"}>,"type">):ProductVariant["specifications"] => ({type:"smartphone",...data});
const television = (data: Omit<Extract<ProductVariant["specifications"],{type:"television"}>,"type">):ProductVariant["specifications"] => ({type:"television",...data});

const products:Product[]=[
  ...confectioneryEssentialProducts,
  ...standMixerProducts,
  ...blenderProducts,
  ...washerDryerProducts,
  ...notebookProducts,
  {id:"prod_motorola_moto_g86_5g",contentType:"product",schemaVersion:1,slug:"motorola-moto-g86-5g",aliases:["moto-g86-5g"],name:"Motorola Moto G86 5G",manufacturerId:"org_motorola_mobility",line:"Moto G",category:"Celulares",releaseYear:2025,mainImage:image("/images/products/smartphones/motorola-moto-g86-5g-graphite-v1.png","Moto G86 5G grafite visto pela frente e por trás","https://www.motorola.com.br/smartphone-moto-g86-5g-256gb/p?idsku=1707","Motorola Brasil",1000,1000),gallery:[],shortDescription:"Intermediário 5G com 8 GB de RAM física, 256 GB, tela pOLED 1,5K de 120 Hz, câmera principal com OIS e proteção IP68/IP69.",strengths:["Tela pOLED de alta resolução, 120 Hz e brilho de pico elevado","Conjunto equilibrado com Dimensity 7300, 8 GB de RAM física e armazenamento expansível","Câmera principal com OIS, ultrawide e proteção IP68/IP69"],limitations:["Carregamento de 33 W é apenas mediano diante de rivais com 45 W ou mais","Política brasileira de grandes atualizações não estava detalhada na página oficial consultada","Desempenho atende jogos, mas não substitui um aparelho gamer ou topo de linha"],suitableFor:["Quem valoriza tela, resistência e um conjunto equilibrado para uso cotidiano","Quem quer 5G, NFC, eSIM, microSD, OIS e ultrawide no mesmo aparelho"],categories:["Celulares","Eletrônicos"],tags:["5G","NFC","256 GB","pOLED","IP68","Android"],relatedProductIds:["prod_samsung_galaxy_a26_5g","prod_motorola_moto_g56_5g","prod_xiaomi_redmi_note_14_4g"],relatedArticleSlugs:[motoG86ArticleSlug,articleSlug],editorialSummary:"O Moto G86 é forte quando custa perto de R$ 1.600: tela, resistência, memória e câmeras formam um pacote raro nessa faixa. Perto de R$ 1.800, a decisão exige comparar promoções de Galaxy A36 e Edge 60 Fusion.",seo:{title:"Motorola Moto G86 5G: ficha, análise e ofertas",description:"Ficha do Moto G86 5G com variante brasileira, especificações oficiais, vantagens, limitações, preços observados e artigos relacionados."},sources:[{title:"Moto G86 5G 256 GB — Motorola Brasil",url:"https://www.motorola.com.br/smartphone-moto-g86-5g-256gb/p?idsku=1707",accessedAt:motoG86ReviewedAt}],status:"published",createdAt:motoG86ReviewedAt,publishedAt:motoG86ReviewedAt,updatedAt:motoG86ReviewedAt,reviewedAt:motoG86ReviewedAt},
  {id:"prod_motorola_moto_g56_5g",contentType:"product",schemaVersion:1,slug:"motorola-moto-g56-5g",aliases:[],name:"Motorola Moto G56 5G",manufacturerId:"org_motorola_mobility",line:"Moto G",category:"Celulares",releaseYear:2025,mainImage:image("/images/products/smartphones/motorola-moto-g56-5g-green-v1.png","Moto G56 5G verde visto pela frente e por trás","https://empresas.motorola.com.br/smartphone-moto-g56-5g/p/","Motorola Empresas",1000,1000),gallery:[],shortDescription:"Intermediário 5G com 8 GB de RAM, 256 GB, tela LCD de 120 Hz, bateria de 5.200 mAh e proteção IP68/IP69.",strengths:["Conjunto de 8 GB de RAM e 256 GB sem depender da memória virtual anunciada","Proteção IP68/IP69 e vidro Gorilla Glass 7i acima do comum na faixa","Câmera principal Sony LYTIA 600 acompanhada de ultrawide"],limitations:["Tela LCD tem contraste inferior aos painéis AMOLED dos concorrentes","Política brasileira de grandes atualizações não estava detalhada na fonte consultada"],suitableFor:["Quem prioriza desempenho equilibrado, armazenamento e resistência","Quem quer 5G, NFC e câmera ultrawide sem ultrapassar muito o teto"],categories:["Celulares","Eletrônicos"],tags:["5G","NFC","256 GB","IP68","Android"],relatedProductIds:["prod_samsung_galaxy_a26_5g","prod_samsung_galaxy_a17_5g","prod_xiaomi_redmi_note_14_4g"],relatedArticleSlugs:[articleSlug],editorialSummary:"É a referência geral do recorte porque reúne memória física suficiente, 256 GB, 5G, NFC, câmera ultrawide e proteção forte. A concessão está na tela LCD: quem valoriza contraste e preto profundo encontra AMOLED nos Samsung e no Redmi.",seo:{title:"Motorola Moto G56 5G: ficha, análise e ofertas",description:"Ficha do Moto G56 5G com variante brasileira, especificações verificadas, vantagens, limitações, ofertas e artigos relacionados."},sources:[{title:"Moto G56 5G — Motorola Empresas",url:"https://empresas.motorola.com.br/smartphone-moto-g56-5g/p/",accessedAt:reviewedAt},{title:"Moto G56 5G — especificações Motorola",url:"https://en-us.support.motorola.com/app/answers/detail/a_id/186749",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_samsung_galaxy_a26_5g",contentType:"product",schemaVersion:1,slug:"samsung-galaxy-a26-5g",aliases:[],name:"Samsung Galaxy A26 5G",manufacturerId:"org_samsung_electronics",line:"Galaxy A",category:"Celulares",releaseYear:2025,mainImage:image("/images/products/smartphones/samsung-galaxy-a26-5g-white-v1.png","Galaxy A26 5G branco visto pela frente e por trás","https://www.samsung.com/br/smartphones/galaxy-a/galaxy-a26-5g-white-256gb-sm-a266mzwhzto/","Samsung Brasil",1164,776),gallery:[],shortDescription:"Intermediário Samsung com tela Super AMOLED de 120 Hz, câmera principal estabilizada, 5G, NFC, IP67 e suporte longo.",strengths:["Tela Super AMOLED de 120 Hz e câmera principal com estabilização óptica","Proteção IP67 e seis gerações de sistema e segurança","Variante de 256 GB oferece 8 GB de RAM e expansão por microSD"],limitations:["Carregamento de 25 W é mais lento que o de rivais diretos","Preço observado normalmente ultrapassa R$ 1.500 e exige esperar promoção"],suitableFor:["Quem prioriza tela, câmera principal, resistência e suporte de software","Quem aceita acompanhar promoções para comprar a variante de 256 GB no teto"],categories:["Celulares","Eletrônicos"],tags:["5G","NFC","256 GB","AMOLED","IP67","Android"],relatedProductIds:["prod_motorola_moto_g56_5g","prod_samsung_galaxy_a17_5g"],relatedArticleSlugs:[articleSlug],editorialSummary:"É o aparelho mais completo da seleção quando aparece por até R$ 1.500, especialmente por tela, OIS, IP67 e suporte longo. Fora de promoção, perde o sentido do recorte e deve ser comparado com aparelhos da faixa seguinte.",seo:{title:"Samsung Galaxy A26 5G: ficha, análise e ofertas",description:"Ficha do Galaxy A26 5G com variante de 256 GB, especificações, vantagens, limitações, ofertas verificadas e artigos relacionados."},sources:[{title:"Galaxy A26 5G 256 GB — Samsung Brasil",url:"https://www.samsung.com/br/smartphones/galaxy-a/galaxy-a26-5g-white-256gb-sm-a266mzwhzto/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_samsung_galaxy_a17_5g",contentType:"product",schemaVersion:1,slug:"samsung-galaxy-a17-5g",aliases:[],name:"Samsung Galaxy A17 5G",manufacturerId:"org_samsung_electronics",line:"Galaxy A",category:"Celulares",releaseYear:2025,mainImage:image("/images/products/smartphones/samsung-galaxy-a17-5g-blue-v1.png","Galaxy A17 5G azul visto pela frente e por trás","https://www.samsung.com/br/smartphones/galaxy-a/galaxy-a17-5g-blue-128gb-sm-a176bzbozto/","Samsung Brasil",1164,776),gallery:[],shortDescription:"Samsung de entrada com 5G, tela Super AMOLED de 90 Hz, câmera principal com OIS e seis anos de suporte.",strengths:["Tela Super AMOLED e estabilização óptica pouco comuns no segmento de entrada","Seis atualizações de sistema e seis anos de segurança","5G, NFC e expansão por microSD"],limitations:["A variante de 128 GB possui somente 4 GB de RAM física","Carregamento de 25 W e ausência de som estéreo reduzem o apelo multimídia"],suitableFor:["Quem quer Samsung barato, suporte longo e uso cotidiano sem jogos pesados","Quem valoriza tela AMOLED e câmera estabilizada mais que multitarefa intensa"],categories:["Celulares","Eletrônicos"],tags:["5G","NFC","128 GB","AMOLED","IP54","Android"],relatedProductIds:["prod_samsung_galaxy_a26_5g","prod_motorola_moto_g56_5g"],relatedArticleSlugs:[articleSlug],editorialSummary:"É a escolha Samsung econômica, não o aparelho mais rápido. Faz sentido para comunicação, bancos, vídeo e fotografia cotidiana, mas 4 GB de RAM impõem um limite real para multitarefa e longevidade de desempenho.",seo:{title:"Samsung Galaxy A17 5G: ficha, análise e ofertas",description:"Ficha do Galaxy A17 5G de 128 GB com especificações oficiais, vantagens, limites, ofertas verificadas e artigos relacionados."},sources:[{title:"Galaxy A17 5G 128 GB — Samsung Brasil",url:"https://www.samsung.com/br/smartphones/galaxy-a/galaxy-a17-5g-blue-128gb-sm-a176bzbozto/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_xiaomi_redmi_note_14_4g",contentType:"product",schemaVersion:1,slug:"xiaomi-redmi-note-14-4g",aliases:["redmi-note-14"],name:"Xiaomi Redmi Note 14 4G",manufacturerId:"org_xiaomi",line:"Redmi Note",category:"Celulares",releaseYear:2025,mainImage:image("/images/products/smartphones/xiaomi-redmi-note-14-v1.jpg","Redmi Note 14 nas cores verde, preta e azul visto por trás","https://www.mi.com/br/product/redmi-note-14/","Xiaomi Brasil",2560,1400),gallery:[],shortDescription:"Celular 4G com tela AMOLED de 120 Hz, 8 GB de RAM, 256 GB, bateria de 5.500 mAh e carregamento de 33 W.",strengths:["Tela AMOLED de 120 Hz, bateria de 5.500 mAh e 256 GB por preço inferior aos rivais 5G","Carregador de 33 W, capa e expansão por microSD reduzem gastos adicionais","Alto-falantes estéreo e entrada de 3,5 mm favorecem mídia"],limitations:["Não possui 5G nem câmera ultrawide na variante 4G","Política de atualizações é menos clara que a oferecida pela Samsung"],suitableFor:["Quem quer gastar perto de R$ 1.100 e prioriza tela, bateria e armazenamento","Quem não precisa de 5G durante a vida útil planejada"],categories:["Celulares","Eletrônicos"],tags:["4G","NFC","256 GB","AMOLED","bateria","Android"],relatedProductIds:["prod_motorola_moto_g56_5g","prod_samsung_galaxy_a17_5g"],relatedArticleSlugs:[articleSlug],editorialSummary:"É a opção econômica da lista porque entrega uma experiência visual e autonomia fortes sem cobrar por 5G. A economia só é racional para quem aceita explicitamente permanecer no 4G; acima de aproximadamente R$ 1.250, os modelos 5G ficam mais defensáveis.",seo:{title:"Xiaomi Redmi Note 14 4G: ficha, análise e ofertas",description:"Ficha do Redmi Note 14 4G de 256 GB com especificações oficiais, vantagens, limitações, ofertas e artigos relacionados."},sources:[{title:"Redmi Note 14 — especificações Xiaomi Brasil",url:"https://www.mi.com/br/product/redmi-note-14/specs/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_tcl_p7k",contentType:"product",schemaVersion:1,slug:"tcl-p7k",aliases:[],name:"TCL P7K",manufacturerId:"org_tcl_electronics",line:"P7K",category:"Televisores",releaseYear:2025,mainImage:image("/images/products/televisions/tcl-p7k-50-v1.jpg","TV TCL P7K de 50 polegadas vista de frente","https://www.tcl.com/br/pt/tvs/p7k","TCL Brasil",800,600),gallery:[],shortDescription:"TV QLED 4K de entrada com Google TV, Dolby Vision, HDR10+, painel nativo de 60 Hz, ALLM e eARC.",strengths:["QLED com Dolby Vision e HDR10+ por preço próximo ao de TVs LCD básicas","Google TV reúne ampla oferta de aplicativos e Chromecast integrado","ALLM, eARC e Game Bar atendem jogos casuais"],limitations:["Painel nativo de 60 Hz não entrega 4K a 120 Hz real","Brilho e controle de contraste ficam abaixo das Mini LED"],suitableFor:["Quem procura uma TV 4K de 50 polegadas acessível para streaming e uso geral","Quem prefere Google TV e ampla compatibilidade de HDR"],categories:["Televisores","Eletrônicos"],tags:["QLED","4K","Google TV","Dolby Vision","50 polegadas"],relatedProductIds:["prod_samsung_u8100f","prod_tcl_c6k"],relatedArticleSlugs:[tvArticleSlug],editorialSummary:"É a porta de entrada da seleção: melhora cores e compatibilidade HDR sem fingir ser uma TV gamer de 120 Hz. Faz sentido pelo preço, não como substituta da C6K em contraste, brilho ou movimento.",seo:{title:"TCL P7K: ficha, tamanhos, análise e ofertas",description:"Ficha da TCL P7K com variante brasileira de 50 polegadas, especificações verificadas, vantagens, limites e ofertas comerciais."},sources:[{title:"TCL P7K — página oficial",url:"https://www.tcl.com/br/pt/tvs/p7k",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_samsung_u8100f",contentType:"product",schemaVersion:1,slug:"samsung-u8100f",aliases:["samsung-crystal-uhd-u8100f"],name:"Samsung Crystal UHD U8100F",manufacturerId:"org_samsung_electronics",line:"Crystal UHD",category:"Televisores",releaseYear:2025,mainImage:image("/images/products/televisions/samsung-u8100f-55-v1.png","TV Samsung Crystal UHD U8100F de 55 polegadas vista de frente","https://www.samsung.com/br/tvs/uhd-4k-tv/u8000f-55-inch-crystal-uhd-4k-smart-tv-un55u8100fgxzd/","Samsung Brasil",1164,776),gallery:[],shortDescription:"TV LCD 4K de 60 Hz com Tizen, três HDMI, eARC, ALLM, VRR, Gaming Hub e sete anos de atualizações prometidas.",strengths:["Tizen com sete anos declarados de atualizações e boa cobertura de aplicativos","Gaming Hub, AirPlay e SmartThings ampliam o uso além do streaming","Processamento e upscaling consistentes para TV aberta e conteúdo comprimido"],limitations:["Painel LCD de 60 Hz sem local dimming tem contraste e HDR modestos","Não oferece Dolby Vision e possui apenas três HDMI"],suitableFor:["Quem valoriza sistema, suporte e integração com o ecossistema Samsung","Quem assiste TV aberta e streaming convencional mais que filmes em sala escura"],categories:["Televisores","Eletrônicos"],tags:["LCD","4K","Tizen","55 polegadas","Gaming Hub"],relatedProductIds:["prod_tcl_p7k","prod_tcl_c6k"],relatedArticleSlugs:[tvArticleSlug],editorialSummary:"É recomendada pelo conjunto de sistema, suporte e processamento, não por entregar a melhor imagem da faixa. Em promoção compete com a P7K; no preço cheio, a TCL oferece cores e HDR mais convincentes.",seo:{title:"Samsung U8100F: ficha, tamanhos, análise e ofertas",description:"Ficha da Samsung Crystal UHD U8100F de 55 polegadas com especificações oficiais, vantagens, limitações e links comerciais."},sources:[{title:"Samsung U8100F 55 — página oficial",url:"https://www.samsung.com/br/tvs/uhd-4k-tv/u8000f-55-inch-crystal-uhd-4k-smart-tv-un55u8100fgxzd/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_tcl_c6k",contentType:"product",schemaVersion:1,slug:"tcl-c6k",aliases:[],name:"TCL C6K",manufacturerId:"org_tcl_electronics",line:"C6K",category:"Televisores",releaseYear:2025,mainImage:image("/images/products/televisions/tcl-c6k-55-v1.png","TV TCL C6K de 55 polegadas vista de frente","https://www.tcl.com/br/pt/tvs/c6k","TCL Brasil",2560,2560),gallery:[],shortDescription:"TV QD-Mini LED 4K com painel HVA, 144 Hz nativos, Google TV, VRR, ALLM, eARC e áudio Onkyo 2.1.",strengths:["Mini LED e painel HVA entregam contraste e brilho muito acima das TVs de entrada","144 Hz nativos, VRR e ALLM formam o melhor pacote gamer da seleção pelo preço","Google TV, Dolby Vision IQ e áudio Onkyo 2.1 tornam o conjunto versátil"],limitations:["Escurecimento por zonas ainda pode produzir halos em cenas extremas","Upscaling e acabamento de movimento podem exigir ajustes conforme a fonte"],suitableFor:["Quem quer salto real de imagem sem pagar o preço de uma OLED","Quem joga em PS5, Xbox Series ou PC e também assiste filmes e esportes"],categories:["Televisores","Eletrônicos"],tags:["Mini LED","QLED","4K","144 Hz","Google TV","55 polegadas"],relatedProductIds:["prod_tcl_p7k","prod_lg_oled_c5","prod_samsung_u8100f"],relatedArticleSlugs:[tvArticleSlug],editorialSummary:"É o melhor equilíbrio geral porque traz controle local de iluminação, alto contraste e recursos completos de jogos por preço intermediário. Não alcança o preto por pixel da OLED C5, mas custa bem menos.",seo:{title:"TCL C6K: ficha, tamanhos, análise e ofertas",description:"Ficha da TCL C6K Mini LED com variante de 55 polegadas, especificações verificadas, vantagens, limitações e ofertas."},sources:[{title:"TCL C6K — página oficial",url:"https://www.tcl.com/br/pt/tvs/c6k",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_lg_oled_c5",contentType:"product",schemaVersion:1,slug:"lg-oled-c5",aliases:["lg-c5"],name:"LG OLED evo C5",manufacturerId:"org_lg_electronics",line:"OLED evo C",category:"Televisores",releaseYear:2025,mainImage:image("/images/products/televisions/lg-oled-c5-55-v1.jpg","TV LG OLED evo C5 de 55 polegadas com controle remoto","https://www.lg.com/br/tvs-e-soundbars/oled-evo/oled55c5psa/","LG Brasil",450,450),gallery:[],shortDescription:"TV OLED 4K de 120 Hz com VRR até 144 Hz, quatro HDMI 2.1, Dolby Vision, webOS 25 e áudio de 40 W.",strengths:["Pixels autoiluminados entregam preto perfeito e excelente contraste para cinema","Quatro HDMI 2.1, VRR até 144 Hz e resposta rápida atendem consoles e PC","Processador Alpha 9, Dolby Vision e Filmmaker Mode formam o pacote mais completo de imagem"],limitations:["Preço é substancialmente superior ao das TVs Mini LED intermediárias","OLED exige cuidado com conteúdo estático prolongado e não é a escolha mais econômica para uso despreocupado"],suitableFor:["Quem quer montar um cinema em casa e prioriza imagem em ambiente controlado","Quem quer uma TV premium também preparada para jogos"],categories:["Televisores","Eletrônicos"],tags:["OLED","4K","Dolby Vision","144 Hz","webOS","55 polegadas"],relatedProductIds:["prod_tcl_c6k","prod_samsung_u8100f"],relatedArticleSlugs:[tvArticleSlug],editorialSummary:"É a melhor imagem da seleção e a indicação para cinema em casa, desde que o orçamento comporte o salto. Preto por pixel, ângulo de visão e resposta superam as LCD; a C6K conserva melhor custo-benefício absoluto.",seo:{title:"LG OLED evo C5: ficha, tamanhos, análise e ofertas",description:"Ficha da LG OLED evo C5 de 55 polegadas com especificações oficiais, vantagens, limitações, dimensões e ofertas."},sources:[{title:"LG OLED evo C5 55 — página oficial",url:"https://www.lg.com/br/tvs-e-soundbars/oled-evo/oled55c5psa/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,publishedAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
];

const variants:ProductVariant[]=[
  ...confectioneryEssentialVariants,
  ...standMixerVariants,
  ...blenderVariants,
  ...washerDryerVariants,
  ...notebookVariants,
  {id:"prod_variant_motorola_moto_g86_5g_8_256_br",productId:"prod_motorola_moto_g86_5g",name:"8 GB + 256 GB (Brasil)",market:"BR",distinguishingAttributes:{ram:"8 GB físicos + 16 GB RAM Boost opcional",storage:"256 GB; expansível até 1 TB por microSD",gpu:"ARM Mali-G615 MC2",displayGlass:"Corning Gorilla Glass 7i",peakBrightness:"4.500 nits (pico declarado)",sim:"nano-SIM + eSIM; bandeja alternativa para microSD"},specifications:smartphone({processor:"MediaTek Dimensity 7300, octa-core até 2,5 GHz",ramGb:8,storageGb:256,display:{technology:"pOLED HDR10+",sizeInches:6.7,resolution:"2712 × 1220",refreshRateHz:120},batteryMah:5200,chargingWatts:33,rearCameras:{main:"50 MP Sony LYTIA 600 com OIS, f/1,88",ultrawide:"8 MP, 118,6°, com macro",additional:[]},frontCamera:"32 MP, f/2,2",video:"4K a 30 fps nas câmeras traseira e frontal; Full HD a 60 fps na traseira",connectivity:["5G","4G","Wi-Fi 6","Bluetooth 5.4","USB-C","eSIM"],nfc:true,fiveG:true,waterResistance:"IP68 e IP69; resistência testada segundo MIL-STD-810H",operatingSystemAtLaunch:"Android 15",dimensionsMm:{height:161.21,width:74.74,depth:7.87},weightGrams:185}),imageIds:[],sources:[{title:"Motorola Brasil — especificações do Moto G86 5G 256 GB",url:"https://www.motorola.com.br/smartphone-moto-g86-5g-256gb/p?idsku=1707",accessedAt:motoG86ReviewedAt}],status:"published",createdAt:motoG86ReviewedAt,updatedAt:motoG86ReviewedAt,reviewedAt:motoG86ReviewedAt},
  {id:"prod_variant_motorola_moto_g56_5g_8_256_br",productId:"prod_motorola_moto_g56_5g",name:"8 GB + 256 GB (Brasil)",market:"BR",manufacturerModelNumber:"XT2529-1",distinguishingAttributes:{ram:"8 GB",storage:"256 GB"},specifications:smartphone({processor:"MediaTek Dimensity 7060",ramGb:8,storageGb:256,display:{technology:"LCD",sizeInches:6.72,resolution:"2400 × 1080",refreshRateHz:120},batteryMah:5200,chargingWatts:30,rearCameras:{main:"50 MP Sony LYTIA 600 com OIS",ultrawide:"8 MP",additional:[]},frontCamera:"32 MP",video:"1080p a 60 fps na câmera traseira",connectivity:["5G","4G","Wi-Fi 5","Bluetooth 5.3","USB-C"],nfc:true,fiveG:true,waterResistance:"IP68 e IP69",operatingSystemAtLaunch:"Android 15",dimensionsMm:{height:165.75,width:76.26,depth:8.35},weightGrams:200}),imageIds:[],sources:[{title:"Motorola — especificações do Moto G56 5G",url:"https://en-us.support.motorola.com/app/answers/detail/a_id/186749",accessedAt:reviewedAt},{title:"Motorola Brasil — guia do Moto G56 5G",url:"https://pt-br.support.motorola.com/app/answers/detail/a_id/187897/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_samsung_galaxy_a26_5g_8_256_br",productId:"prod_samsung_galaxy_a26_5g",name:"8 GB + 256 GB (Brasil)",market:"BR",manufacturerModelNumber:"SM-A266M",distinguishingAttributes:{ram:"8 GB",storage:"256 GB",color:"Branco"},specifications:smartphone({processor:"Samsung Exynos 1380, octa-core até 2,4 GHz",ramGb:8,storageGb:256,display:{technology:"Super AMOLED",sizeInches:6.7,resolution:"2340 × 1080",refreshRateHz:120},batteryMah:5000,chargingWatts:25,rearCameras:{main:"50 MP com OIS",ultrawide:"8 MP",additional:["Macro de 2 MP"]},frontCamera:"13 MP",video:"4K a 30 fps",connectivity:["5G","4G","Wi-Fi 5","Bluetooth 5.3","USB-C"],nfc:true,fiveG:true,waterResistance:"IP67",operatingSystemAtLaunch:"Android 15 com One UI 7",updatePolicy:"Seis atualizações de sistema e seis anos de segurança",dimensionsMm:{height:164,width:77.5,depth:7.7},weightGrams:200}),imageIds:[],sources:[{title:"Samsung Brasil — Galaxy A26 5G 256 GB",url:"https://www.samsung.com/br/smartphones/galaxy-a/galaxy-a26-5g-white-256gb-sm-a266mzwhzto/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_samsung_galaxy_a17_5g_4_128_br",productId:"prod_samsung_galaxy_a17_5g",name:"4 GB + 128 GB (Brasil)",market:"BR",manufacturerModelNumber:"SM-A176B",distinguishingAttributes:{ram:"4 GB",storage:"128 GB",color:"Azul claro"},specifications:smartphone({processor:"Samsung Exynos 1330, octa-core até 2,4 GHz",ramGb:4,storageGb:128,display:{technology:"Super AMOLED",sizeInches:6.7,resolution:"2340 × 1080",refreshRateHz:90},batteryMah:5000,chargingWatts:25,rearCameras:{main:"50 MP com OIS",ultrawide:"5 MP",additional:["Macro de 2 MP"]},frontCamera:"13 MP",video:"1080p a 30 fps",connectivity:["5G","4G","Wi-Fi 5","Bluetooth 5.3","USB-C"],nfc:true,fiveG:true,waterResistance:"IP54",operatingSystemAtLaunch:"Android 15 com One UI 7",updatePolicy:"Seis atualizações de sistema e seis anos de segurança",dimensionsMm:{height:164.4,width:77.9,depth:7.5},weightGrams:192}),imageIds:[],sources:[{title:"Samsung Brasil — Galaxy A17 5G 128 GB",url:"https://www.samsung.com/br/smartphones/galaxy-a/galaxy-a17-5g-blue-128gb-sm-a176bzbozto/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_xiaomi_redmi_note_14_4g_8_256_br",productId:"prod_xiaomi_redmi_note_14_4g",name:"8 GB + 256 GB (Brasil)",market:"BR",manufacturerModelNumber:"24094RAD4G",distinguishingAttributes:{ram:"8 GB",storage:"256 GB"},specifications:smartphone({processor:"MediaTek Helio G99-Ultra",ramGb:8,storageGb:256,display:{technology:"AMOLED",sizeInches:6.67,resolution:"2400 × 1080",refreshRateHz:120},batteryMah:5500,chargingWatts:33,rearCameras:{main:"108 MP",additional:["Profundidade de 2 MP","Macro de 2 MP"]},frontCamera:"20 MP",video:"1080p a 60 fps na câmera traseira",connectivity:["4G","Wi-Fi 5","Bluetooth 5.3","USB-C","Conector de 3,5 mm"],nfc:true,fiveG:false,waterResistance:"IP54",operatingSystemAtLaunch:"Xiaomi HyperOS baseado em Android",dimensionsMm:{height:163.25,width:76.55,depth:8.16},weightGrams:196.5}),imageIds:[],sources:[{title:"Xiaomi Brasil — especificações do Redmi Note 14",url:"https://www.mi.com/br/product/redmi-note-14/specs/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_tcl_p7k_50_br",productId:"prod_tcl_p7k",name:"50 polegadas (50P7K)",market:"BR",manufacturerModelNumber:"50P7K",distinguishingAttributes:{screenSize:"50 polegadas"},specifications:television({screenSizeInches:50,availableSizesInches:[43,50,55,65,75,85],panelTechnology:"QLED LCD HVA com iluminação LED",resolution:"4K (3840 × 2160)",nativeRefreshRateHz:60,hdrFormats:["Dolby Vision","HDR10+","HDR10","HLG"],operatingSystem:"Google TV",hdmiPorts:3,earc:true,vrr:true,allm:true,wifi:"Wi-Fi",bluetooth:"Bluetooth",assistants:["Google Assistente"],gamingFeatures:["Game Master","Game Bar","Game Accelerator 120 Hz por software"],audio:"Dolby Atmos e DTS Virtual:X"}),imageIds:[],sources:[{title:"TCL P7K — página oficial",url:"https://www.tcl.com/br/pt/tvs/p7k",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_samsung_u8100f_55_br",productId:"prod_samsung_u8100f",name:"55 polegadas (UN55U8100FGXZD)",market:"BR",manufacturerModelNumber:"UN55U8100FGXZD",distinguishingAttributes:{screenSize:"55 polegadas"},specifications:television({screenSizeInches:55,availableSizesInches:[43,50,55,58,65,70,75,85],panelTechnology:"LCD LED Crystal UHD",resolution:"4K (3840 × 2160)",nativeRefreshRateHz:60,hdrFormats:["HDR10+","HDR10","HLG"],operatingSystem:"Tizen",hdmiPorts:3,hdmi21Ports:0,earc:true,vrr:true,allm:true,wifi:"Wi-Fi 5",bluetooth:"Bluetooth 5.2",assistants:["Bixby","Alexa por dispositivo separado"],gamingFeatures:["Gaming Hub","HGiG","Motion Xcelerator"],audio:"20 W, 2 canais, Som Adaptativo e Q-Symphony",dimensionsMm:{width:1234.1,height:758,depth:237,includesStand:true},weightKg:11.9}),imageIds:[],sources:[{title:"Samsung U8100F 55 — especificações oficiais",url:"https://www.samsung.com/br/tvs/uhd-4k-tv/u8000f-55-inch-crystal-uhd-4k-smart-tv-un55u8100fgxzd/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_tcl_c6k_55_br",productId:"prod_tcl_c6k",name:"55 polegadas (55C6K)",market:"BR",manufacturerModelNumber:"55C6K",distinguishingAttributes:{screenSize:"55 polegadas",panel:"HVA"},specifications:television({screenSizeInches:55,availableSizesInches:[55,65,75,85,98],panelTechnology:"QD-Mini LED com painel HVA",resolution:"4K (3840 × 2160)",nativeRefreshRateHz:144,hdrFormats:["Dolby Vision IQ","HDR10+","HDR10","HLG"],operatingSystem:"Google TV",hdmiPorts:4,earc:true,vrr:true,allm:true,wifi:"Wi-Fi",bluetooth:"Bluetooth",assistants:["Google Assistente"],gamingFeatures:["144 Hz VRR","FreeSync Premium Pro","Game Master","Game Bar"],audio:"Sistema Onkyo 2.1 com subwoofer integrado"}),imageIds:[],sources:[{title:"TCL C6K — página oficial",url:"https://www.tcl.com/br/pt/tvs/c6k",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
  {id:"prod_variant_lg_oled_c5_55_br",productId:"prod_lg_oled_c5",name:"55 polegadas (OLED55C5PSA)",market:"BR",manufacturerModelNumber:"OLED55C5PSA",gtin:"7893299959677",distinguishingAttributes:{screenSize:"55 polegadas"},specifications:television({screenSizeInches:55,availableSizesInches:[42,48,55,65,77,83],panelTechnology:"OLED evo com pixels autoiluminados",resolution:"4K (3840 × 2160)",nativeRefreshRateHz:120,hdrFormats:["Dolby Vision","HDR10","HLG"],operatingSystem:"webOS 25",hdmiPorts:4,hdmi21Ports:4,earc:true,vrr:true,allm:true,wifi:"Wi-Fi",bluetooth:"Bluetooth",assistants:["LG ThinQ","Google Home","Alexa"],gamingFeatures:["VRR até 144 Hz","G-Sync","FreeSync","HGiG","Dolby Vision Gaming 4K 120 Hz"],audio:"40 W, 2.2 canais, Dolby Atmos",dimensionsMm:{width:1222,height:757,depth:230,includesStand:true},weightKg:16,warranty:"12 meses"}),imageIds:[],sources:[{title:"LG OLED evo C5 55 — especificações oficiais",url:"https://www.lg.com/br/tvs-e-soundbars/oled-evo/oled55c5psa/",accessedAt:reviewedAt}],status:"published",createdAt:reviewedAt,updatedAt:reviewedAt,reviewedAt},
];

export const productCatalog=ProductCatalogSchema.parse({products,variants,offers:[
  ...confectioneryEssentialOffers,
  ...standMixerOffers,
  ...blenderOffers,
  ...washerDryerOffers,
  ...notebookOffers,
  {id:"prod_offer_amazon_motorola_moto_g86_5g_8_256",variantId:"prod_variant_motorola_moto_g86_5g_8_256_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/s?k=moto+g86&crid=339BS6XZ5PRN0&sprefix=Moto+%2Caps%2C278&linkCode=ll2&tag=riquehen-20&linkId=51b5bd00e21a5fbbfd0a8994cba6c6d9&ref_=as_li_ss_tl",region:"BR",availability:"unknown",affiliateProgram:"Amazon Associados",affiliateId:"riquehen-20",commissionDisclosure:"Este link pode gerar comissão sem custo adicional para quem compra.",checkedAt:motoG86ReviewedAt},
  {id:"prod_offer_motorola_moto_g86_5g_8_256",variantId:"prod_variant_motorola_moto_g86_5g_8_256_br",retailer:"Motorola Brasil",url:"https://www.motorola.com.br/smartphone-moto-g86-5g-256gb/p?idsku=1707",region:"BR",observedPrice:{amount:1599,currency:"BRL"},availability:"available",checkedAt:motoG86ReviewedAt},
  {id:"prod_offer_amazon_motorola_moto_g56_5g_8_256",variantId:"prod_variant_motorola_moto_g56_5g_8_256_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/dp/B0F9MT4TTZ",region:"BR",observedPrice:{amount:1377.40,currency:"BRL"},availability:"available",checkedAt:"2026-08-20"},
  {id:"prod_offer_amazon_samsung_galaxy_a26_5g_8_256",variantId:"prod_variant_samsung_galaxy_a26_5g_8_256_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/dp/B0F29YZ3MF",region:"BR",observedPrice:{amount:1614.05,currency:"BRL"},availability:"available",checkedAt:"2026-09-01"},
  {id:"prod_offer_amazon_samsung_galaxy_a17_5g_4_128",variantId:"prod_variant_samsung_galaxy_a17_5g_4_128_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/dp/B0FPPQ5T37",region:"BR",observedPrice:{amount:1259.10,currency:"BRL"},availability:"available",checkedAt:"2026-08-08"},
  {id:"prod_offer_amazon_xiaomi_redmi_note_14_4g_8_256",variantId:"prod_variant_xiaomi_redmi_note_14_4g_8_256_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/dp/B0DT5LHPMX",region:"BR",observedPrice:{amount:1178,currency:"BRL"},availability:"available",checkedAt:reviewedAt},
  {id:"prod_offer_amazon_tcl_p7k_50",variantId:"prod_variant_tcl_p7k_50_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/dp/B0F1H26GFQ",region:"BR",observedPrice:{amount:2099,currency:"BRL"},availability:"available",checkedAt:reviewedAt},
  {id:"prod_offer_amazon_samsung_u8100f_55",variantId:"prod_variant_samsung_u8100f_55_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/dp/B0FSX4WVCD",region:"BR",availability:"unknown",checkedAt:reviewedAt},
  {id:"prod_offer_amazon_tcl_c6k_55",variantId:"prod_variant_tcl_c6k_55_br",retailer:"Amazon Brasil",url:"https://www.amazon.com.br/dp/B0F7JZMVKF",region:"BR",observedPrice:{amount:3499,currency:"BRL"},availability:"available",checkedAt:reviewedAt},
  {id:"prod_offer_lg_oled_c5_55",variantId:"prod_variant_lg_oled_c5_55_br",retailer:"LG Brasil",url:"https://www.lg.com/br/tvs-e-soundbars/oled-evo/oled55c5psa/",region:"BR",observedPrice:{amount:5490,currency:"BRL"},availability:"unknown",checkedAt:"2026-08-11"},
]});

export const productsById=new Map(productCatalog.products.map((product)=>[product.id,product]));
export const productsBySlug=new Map(productCatalog.products.flatMap((product)=>[product.slug,...product.aliases].map((slug)=>[slug,product] as const)));
