import { IdeaBatchSchema } from "./ideaSchema";

export const ideas = IdeaBatchSchema.parse([{
  id: "idea_public_ideas_archive",
  contentType: "idea",
  schemaVersion: 1,
  slug: "arquivo-publico-de-ideias",
  aliases: [],
  title: "Arquivo público de ideias",
  description: "Criar um espaço no meu site para registrar ideias, acompanhar como elas mudam e manter um histórico público do processo de desenvolvimento.",
  createdAt: "2026-08-19",
  updatedAt: "2026-08-19",
  status: "em-desenvolvimento",
  visibility: "public",
  publicationStatus: "published",
  type: "idea",
  categories: ["Site"],
  tags: ["Arquivo pessoal", "Processo", "Conhecimento"],
  idea: [
    "Construir uma área permanente para ideias que ainda estão sendo testadas, sem exigir que elas pareçam projetos concluídos ou promessas de execução.",
    "Cada registro deve preservar a formulação atual e uma linha do tempo das mudanças, permitindo consultar mais tarde como o pensamento evoluiu.",
  ],
  motivation: [
    "Artigos normalmente mostram uma conclusão organizada. Projetos mostram algo que já ganhou forma. Faltava um lugar para registrar o intervalo entre uma intuição inicial e aquilo que ela talvez se torne.",
  ],
  currentState: [
    "A estrutura inicial usa arquivos locais validados, páginas públicas e um histórico cronológico. A primeira ideia é a própria criação desta área.",
  ],
  nextSteps: [
    "Usar a área com ideias reais e observar quais campos continuam úteis.",
    "Relacionar ideias a artigos e projetos quando essas derivações existirem.",
    "Reavaliar a modelagem antes de qualquer migração para uma fonte remota.",
  ],
  updates: [{
    date: "2026-08-19",
    title: "Decisão de criar a área",
    content: ["Decidi criar uma página pública para registrar ideias e suas mudanças. O sistema deve funcionar como arquivo de processo, não como gerenciador de tarefas."],
    links: [],
  }],
  relatedIdeaIds: [],
  relatedArticleSlugs: [],
  relatedProjectSlugs: [],
  seo: {
    title: "Arquivo público de ideias",
    description: "A ideia de criar uma área pública para registrar pensamentos em desenvolvimento e preservar como decisões e caminhos mudam ao longo do tempo.",
  },
}, {
  id: "idea_henrique_dog_editorial_sustentavel",
  contentType: "idea",
  schemaVersion: 1,
  slug: "henrique-dog-projeto-editorial-sustentavel",
  aliases: [],
  title: "Transformar o henrique.dog em um projeto editorial sustentável",
  description: "Transformar meu site pessoal em um projeto editorial capaz de reunir meus interesses, registrar minhas ideias e, no longo prazo, gerar uma fonte relevante de renda orgânica.",
  createdAt: "2026-08-16",
  updatedAt: "2026-08-20",
  status: "explorando",
  visibility: "public",
  publicationStatus: "published",
  type: "project",
  categories: ["Site", "Projeto editorial"],
  tags: ["SEO", "Entretenimento", "Marketing", "Monetização", "Arquivo pessoal"],
  idea: [
    "O henrique.dog começou como meu site pessoal, mas estou passando a tratá-lo também como um projeto editorial.",
    "Quero reunir interesses, estudos e experiências sem perder o caráter de arquivo pessoal, enquanto testo se esse trabalho pode se tornar uma fonte sustentável de renda orgânica.",
    "Em 16 de agosto de 2026, o período analisado no Google Search Console mostrava aproximadamente 8,25 mil impressões, 7 cliques, CTR média de 0,1% e posição média de 11,9. O tráfego ainda é pequeno, mas este é o primeiro sinal mensurável de distribuição orgânica que quero preservar como marco inicial.",
  ],
  motivation: [
    "Quero poder comparar decisões e resultados ao longo do tempo, entendendo não apenas o que cresceu, mas quais assuntos, formatos e formas de monetização fizeram sentido para o projeto.",
  ],
  currentState: [
    "Estou explorando frentes editoriais diferentes e ainda não sei qual delas terá maior importância. As avaliações abaixo são hipóteses atuais, abertas a revisão conforme novos dados aparecerem.",
  ],
  sections: [
    {
      id: "objetivo-de-longo-prazo",
      title: "Objetivo de longo prazo",
      tone: "goal",
      content: ["Minha expectativa para aproximadamente dois anos é construir um arquivo editorial consistente, com diferentes formas de monetização e renda orgânica razoável."],
      items: ["Alcançar pelo menos 100 mil cliques orgânicos mensais. Isso é uma meta de trabalho, não uma projeção nem uma promessa.", "Registrar de forma consistente os assuntos que estudo, penso e crio."],
    },
    {
      id: "entretenimento",
      title: "Frente 1 — Entretenimento",
      tone: "hypothesis",
      content: ["Hipótese atual: dificuldade média. A concorrência e os portais estabelecidos tornam a disputa difícil, e tráfego puramente informacional pode ser complicado de monetizar.", "Ao mesmo tempo, existe uma audiência ampla, procura contínua por novas obras e espaço para curadoria, obras menos conhecidas, listas, recomendações e conteúdos evergreen."],
      items: [],
    },
    {
      id: "marketing-e-produtos-digitais",
      title: "Frente 2 — Marketing e produtos digitais",
      tone: "hypothesis",
      content: ["Quero transformar aprendizados sobre marketing, social media, SEO, produtos digitais e experiências profissionais em conteúdo que consolide meu aprendizado, ajude outras pessoas e demonstre conhecimento.", "Hipótese atual: essa frente pode alcançar uma audiência menor que entretenimento, mas ter maior potencial comercial por visitante, inclusive para clientes, produtos ou serviços digitais. Isso ainda precisa ser testado."],
      items: [],
    },
    {
      id: "arquivo-pessoal",
      title: "Frente 3 — Arquivo pessoal",
      content: ["O site também deve centralizar pensamentos, ideias, estudos, experimentos, projetos, descobertas e mudanças de opinião. A própria área de ideias nasce dessa intenção de preservar não apenas o que produzi, mas como meu pensamento evoluiu."],
      items: [],
    },
    {
      id: "monetizacao",
      title: "Monetização",
      tone: "hypothesis",
      content: ["Ainda estou explorando possibilidades como afiliados, produtos digitais, serviços, conteúdos comerciais e projetos próprios. Nenhuma delas é o modelo definitivo."],
      items: ["Descobrir o que realmente funciona.", "Entender o que combina com o conteúdo e é sustentável.", "Priorizar formatos que eu me sinta confortável produzindo."],
    },
  ],
  nextSteps: [
    "Continuar produzindo e testando conteúdos para descobrir quais assuntos consigo sustentar.",
    "Acompanhar impressões, cliques e conteúdos que começam a receber tráfego recorrente.",
    "Testar formas de monetização sem assumir antecipadamente um modelo definitivo.",
    "Comparar esforço, audiência e retorno dos formatos e documentar os resultados nesta página.",
  ],
  updates: [
    { date: "2026-08-16", title: "Primeiros sinais de tráfego orgânico", content: ["O Google Search Console registrou aproximadamente 8,25 mil impressões e 7 cliques no período analisado. Este passa a ser o primeiro marco quantitativo documentado."], links: [] },
    { date: "2026-08-18", title: "Definição das primeiras frentes editoriais", content: ["Comecei experimentando principalmente entretenimento, pela escala potencial e pelo interesse pessoal, e marketing e produtos digitais, pelo potencial de transformar experiência profissional em conteúdo útil e comercialmente sustentável."], links: [] },
    { date: "2026-08-19", title: "O site passa a funcionar também como arquivo de ideias", content: ["Decidi registrar publicamente projetos, hipóteses e pensamentos em desenvolvimento, preservando ideias incompletas e mudanças de direção."], links: [] },
  ],
  relatedIdeaIds: ["idea_public_ideas_archive", "idea_achadinhos_curadoria"],
  relatedArticleSlugs: [],
  relatedProjectSlugs: [],
  seo: {
    title: "henrique.dog como projeto editorial sustentável",
    description: "O marco inicial, as frentes editoriais e as hipóteses para transformar o henrique.dog em um arquivo consistente e sustentável.",
  },
}, {
  id: "idea_biohazard_brand",
  contentType: "idea",
  schemaVersion: 1,
  slug: "biohazard-identidade-possivel-marca",
  aliases: [],
  title: "Biohazard — exploração de uma identidade para uma possível marca",
  description: "Explorar uma identidade visual e conceitual chamada Biohazard que futuramente pode se transformar em uma loja ou marca.",
  createdAt: "2026-08-20",
  updatedAt: "2026-08-20",
  status: "explorando",
  visibility: "public",
  publicationStatus: "published",
  type: "business",
  categories: ["Marca", "Negócio"],
  tags: ["Branding", "E-commerce", "Produtos", "Kitsune"],
  idea: [
    "Biohazard é uma identidade visual e conceitual ainda sem definição completa. Ela pode futuramente se tornar uma loja, uma marca de roupas ou algo mais amplo.",
    "Quero usar este registro para desenvolver identidade, testar referências, explorar produtos, experimentar linguagem visual e avaliar possibilidades comerciais.",
  ],
  motivation: [
    "A ideia se relaciona a experiências anteriores da época em que administrei a Kitsune. Algumas coisas precisaram ser pausadas, e quero descobrir quais aprendizados ainda têm valor sem simplesmente recriar o projeto antigo.",
  ],
  currentState: ["A identidade e o modelo continuam em exploração. Biohazard precisa encontrar uma linguagem própria antes de se transformar em uma definição comercial fechada."],
  sections: [{
    id: "questoes-em-aberto",
    title: "Questões em aberto",
    tone: "hypothesis",
    content: ["Estas perguntas fazem parte da exploração e devem ser respondidas conforme referências, conceitos e experimentos ganharem forma."],
    items: ["O que exatamente é Biohazard?", "É uma loja, uma marca de roupas ou algo mais amplo?", "Qual público pretende atingir?", "Quais elementos da experiência da Kitsune ainda fazem sentido?", "O que deve ser completamente diferente?", "Qual será sua linguagem visual?", "Existe um modelo comercial sustentável para ela?"],
  }],
  nextSteps: ["Organizar referências visuais e definir um conceito central.", "Recuperar materiais relevantes da Kitsune e separar os aprendizados que ainda fazem sentido.", "Experimentar identidades e possibilidades de produtos.", "Documentar os experimentos sem antecipar uma definição comercial."],
  updates: [
    { date: "2026-08-20", title: "Registro da ideia", content: ["Decidi documentar Biohazard como uma possibilidade de marca futura. Sua identidade e seu modelo ainda estão em exploração."], links: [] },
    { date: "2026-08-20", title: "Recuperando aprendizados da Kitsune", content: ["Parte do processo será revisitar o que desenvolvi quando administrava a Kitsune e identificar aprendizados que possam servir de base para algo novo, sem apenas recuperar projetos antigos."], links: [] },
  ],
  relatedIdeaIds: [],
  relatedArticleSlugs: [],
  relatedProjectSlugs: [],
  seo: {
    title: "Biohazard — identidade para uma possível marca",
    description: "Registro público da exploração de Biohazard: identidade, aprendizados da Kitsune, questões em aberto e possibilidades para uma futura marca.",
  },
}, {
  id: "idea_small_software_lab",
  contentType: "idea", schemaVersion: 1,
  slug: "pequenos-softwares-renda-recorrente", aliases: [],
  title: "Criar pequenos softwares que possam gerar renda recorrente",
  description: "Experimentar pequenos softwares, ferramentas e produtos digitais que resolvam problemas específicos e possam gerar receita sem exigir uma operação pesada.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20",
  status: "em-desenvolvimento", visibility: "public", publicationStatus: "published", type: "business",
  categories: ["Software", "Negócio"], tags: ["Micro-SaaS", "Renda recorrente", "Produtos digitais"],
  idea: ["Tenho criado sistemas pequenos para aprender, testar mercados e atender necessidades específicas. A intenção não é necessariamente construir uma grande startup.", "Quero testar se vários produtos baratos de operar e com manutenção reduzida podem formar uma fonte de renda interessante ao longo do tempo."],
  motivation: ["Já consegui o primeiro cliente fixo, pagando R$ 200 por mês por um software de baixa manutenção. Este é um primeiro marco comercial, não evidência de receita recorrente consolidada."],
  currentState: ["Existem experimentos e um primeiro cliente recorrente. Ainda preciso medir custos, tempo de suporte e repetibilidade antes de concluir se a estratégia funciona."],
  sections: [{ id: "hipotese", title: "Hipótese", tone: "hypothesis", content: ["Um produto simples que resolva um problema real, tenha baixo custo de infraestrutura, exija pouca manutenção e mantenha clientes recorrentes pode ser mais interessante para mim do que começar por um SaaS grande e complexo."], items: [] }],
  nextSteps: ["Continuar criando produtos pequenos e acompanhar seu custo real de manutenção.", "Medir tempo gasto por cliente e receita recorrente por produto.", "Descobrir quais produtos conseguem clientes organicamente.", "Evitar produtos com carga operacional desproporcional e documentar sucessos e fracassos."],
  updates: [{ date: "2026", title: "Primeiros experimentos", content: ["Comecei a desenvolver sistemas pequenos para testar ideias e necessidades específicas."], links: [] }, { date: "2026", title: "Primeiro cliente recorrente", content: ["Consegui meu primeiro cliente fixo pagando R$ 200 por mês por um software de baixa manutenção. Este passa a ser o primeiro marco financeiro registrado da estratégia."], links: [] }],
  relatedIdeaIds: ["idea_wedding_invitation_system", "idea_cruz_das_almas_marketplace", "idea_simple_resume_builder", "idea_live_command_card_game"], relatedArticleSlugs: [], relatedProjectSlugs: [],
  seo: { title: "Pequenos softwares e renda recorrente", description: "Experimentos com pequenos softwares, o primeiro cliente de R$ 200 por mês e a hipótese de uma operação simples e sustentável." },
}, {
  id: "idea_wedding_invitation_system", contentType: "idea", schemaVersion: 1,
  slug: "sistema-digital-convites-casamento", aliases: [], title: "Sistema digital para convites de casamento",
  description: "Sistema para criação de uma experiência digital de casamento, incluindo convite, informações para convidados, confirmação de presença e lista de presentes.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "em-desenvolvimento", visibility: "public", publicationStatus: "published", type: "project",
  categories: ["Software", "Casamentos"], tags: ["Convite digital", "Lista de presentes", "Micro-SaaS"],
  idea: ["Criei um sistema que pode reunir convite digital, informações da cerimônia e da festa, confirmação de presença, lista de presentes e links importantes para convidados.", "A lista de presentes é uma das funcionalidades centrais que quero explorar."],
  motivation: [], currentState: ["O sistema já foi desenvolvido, mas o formato comercial e o grau de padronização ainda estão em aberto."],
  sections: [{ id: "hipotese-comercial", title: "Hipótese comercial", tone: "hypothesis", content: ["O sistema pode funcionar como serviço personalizado, produto digital, micro-SaaS, solução vendida por casamento ou parceria com profissionais do setor. Ainda não existe um modelo definitivo."], items: [] }, { id: "questoes-em-aberto", title: "Questões em aberto", content: ["As próximas decisões dependem de entender disposição a pagar, configuração e suporte."], items: ["Produto personalizado ou padronizado?", "Como simplificar a configuração de cada casamento?", "Lista de presentes própria ou integrada?", "Qual é o custo de suporte por casal?", "Existe potencial de indicação entre clientes?"] }],
  nextSteps: [], updates: [{ date: "2026", title: "Primeira implementação", content: ["Desenvolvi a base de uma experiência digital para casamentos. O produto e seu modelo comercial continuam em desenvolvimento."], links: [] }],
  relatedIdeaIds: ["idea_small_software_lab"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Sistema digital para convites de casamento", description: "Projeto de convite digital com informações para convidados, confirmação de presença e lista de presentes, ainda sem modelo comercial definitivo." },
}, {
  id: "idea_cruz_das_almas_marketplace", contentType: "idea", schemaVersion: 1,
  slug: "marketplace-local-cruz-das-almas", aliases: [], title: "Marketplace local para Cruz das Almas",
  description: "Criar um pequeno marketplace voltado para estabelecimentos, serviços e comércio de Cruz das Almas, começando por uma versão experimental em PWA.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "em-desenvolvimento", visibility: "public", publicationStatus: "published", type: "business",
  categories: ["Software", "Negócio local"], tags: ["Marketplace", "PWA", "Cruz das Almas", "Hiperlocal"],
  idea: ["O produto reúne estabelecimentos, serviços e comércio de Cruz das Almas em uma experiência hiperlocal."], motivation: [],
  currentState: ["Uma versão em PWA já está disponível e continua experimental. Ainda não comprei domínio próprio: quero observar uso, interesse comercial e sinais de receita antes de ampliar o investimento."],
  sections: [{ id: "hipotese-e-risco", title: "Hipótese e principal risco", tone: "hypothesis", content: ["Um produto hiperlocal pode conhecer melhor o comércio, as necessidades, os eventos e o comportamento da cidade do que plataformas generalistas.", "O principal risco é o problema de dois lados: o marketplace depende simultaneamente de oferta suficiente e de demanda recorrente."], items: [] }, { id: "metricas-futuras", title: "Métricas futuras", content: ["Quando houver dados reais, quero acompanhar os indicadores abaixo sem preencher a página com painéis vazios."], items: ["Estabelecimentos cadastrados", "Usuários e acessos", "Contatos gerados", "Clientes pagantes e receita", "Custo de infraestrutura"] }],
  nextSteps: ["Observar uso e interesse comercial antes de investir em domínio próprio.", "Registrar sinais reais de oferta, demanda e receita."], updates: [{ date: "2026", title: "Versão experimental em PWA", content: ["Disponibilizei uma primeira versão do marketplace como PWA para observar utilização e interesse antes de ampliar o investimento."], links: [] }],
  relatedIdeaIds: ["idea_small_software_lab"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Marketplace local para Cruz das Almas", description: "Experimento hiperlocal em PWA para reunir comércio e serviços de Cruz das Almas, com oferta e demanda como principal risco." },
}, {
  id: "idea_simple_resume_builder", contentType: "idea", schemaVersion: 1,
  slug: "criador-simples-curriculos", aliases: [], title: "Criador simples de currículos",
  description: "Criar uma ferramenta simples para montar currículos organizados e exportáveis sem exigir que as pessoas lidem com editores de texto complexos.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "rascunho", visibility: "public", publicationStatus: "published", type: "idea",
  categories: ["Software", "Produto digital"], tags: ["Currículo", "PDF", "Empregabilidade"],
  idea: ["A proposta não é criar mais um editor cheio de opções. O usuário fornece suas informações e o sistema ajuda a transformá-las em um currículo visualmente adequado."], motivation: [], currentState: ["A direção do produto está registrada, mas as funcionalidades ainda não serão implementadas."],
  sections: [{ id: "possibilidades-futuras", title: "Possibilidades futuras", content: ["Estas são direções possíveis, não um escopo comprometido."], items: ["Diferentes modelos e exportação em PDF", "Sugestões e revisão de escrita", "Versões adequadas para vagas diferentes", "Armazenamento opcional", "Geração assistida por IA"] }],
  nextSteps: [], updates: [{ date: "2026-08-20", title: "Registro da direção", content: ["Registrei o princípio de simplicidade antes de decidir se a ferramenta deve ser desenvolvida."], links: [] }], relatedIdeaIds: ["idea_small_software_lab"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Ideia de um criador simples de currículos", description: "Uma ferramenta ainda no papel para transformar informações em currículos organizados e exportáveis sem um editor complexo." },
}, {
  id: "idea_shareable_messages_site", contentType: "idea", schemaVersion: 1,
  slug: "site-mensagens-bom-dia-compartilhar", aliases: [], title: "Site de mensagens de bom dia e conteúdos para compartilhar",
  description: "Criar um site simples de mensagens, imagens e pequenos conteúdos que pessoas possam encontrar e enviar para familiares e amigos.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "rascunho", visibility: "public", publicationStatus: "published", type: "idea",
  categories: ["Conteúdo", "Experimento editorial"], tags: ["SEO", "Compartilhamento", "Conteúdo programático"],
  idea: ["A ideia, internamente lembrada com humor como o site de mensagens de bom dia para tias, é atender com simplicidade buscas e hábitos de compartilhamento que produtos mais sofisticados costumam ignorar."], motivation: [], currentState: ["É uma hipótese de conteúdo ainda no papel, sem páginas geradas nem produção em massa."],
  sections: [{ id: "hipotese", title: "Hipótese", tone: "hypothesis", content: ["Mensagens de bom dia, boa noite, aniversário, religião, amizade, família, datas comemorativas e motivação podem sustentar um experimento de SEO, recorrência e compartilhamento."], items: ["Qualidade e utilidade continuam sendo critérios.", "Não criar páginas em massa apenas para manipular mecanismos de busca.", "Observar se monetização por volume é compatível com uma experiência útil."] }],
  nextSteps: [], updates: [{ date: "2026-08-20", title: "Registro do experimento", content: ["Preservei a hipótese antes de produzir conteúdo ou automatizar páginas."], links: [] }], relatedIdeaIds: ["idea_henrique_dog_editorial_sustentavel"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Site de mensagens e conteúdos para compartilhar", description: "Ideia de um site simples de mensagens compartilháveis como experimento responsável de SEO, recorrência e conteúdo programático." },
}, {
  id: "idea_achadinhos_curadoria", contentType: "idea", schemaVersion: 1,
  slug: "curadoria-achadinhos-produtos-interessantes", aliases: [], title: "Curadoria de achadinhos e produtos interessantes",
  description: "Criar dentro do henrique.dog uma área de curadoria de produtos, ofertas e coisas interessantes, integrada ao projeto editorial existente.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "explorando", visibility: "public", publicationStatus: "published", type: "business",
  categories: ["Projeto editorial", "Curadoria"], tags: ["Achadinhos", "Produtos", "Ofertas", "Afiliados"],
  idea: ["A curadoria será desenvolvida dentro do henrique.dog, não como site independente neste momento.", "O objetivo não é transformar o blog inteiro em um site de ofertas, mas incorporar produtos e descobertas coerentes com o ecossistema editorial."], motivation: ["A área pode futuramente contribuir para monetização por afiliados e outras parcerias, sem assumir antecipadamente um modelo definitivo."], currentState: ["A integração editorial e os critérios de curadoria ainda estão sendo explorados."], sections: [],
  nextSteps: ["Definir critérios editoriais para produtos e ofertas.", "Testar a integração sem descaracterizar o restante do site."], updates: [{ date: "2026-08-20", title: "Definição do lugar do projeto", content: ["Decidi que Achadinhos deve nascer dentro do henrique.dog e permanecer subordinado à proposta editorial do site."], links: [] }],
  relatedIdeaIds: ["idea_henrique_dog_editorial_sustentavel", "idea_offer_discovery_community"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Curadoria de achadinhos no henrique.dog", description: "Exploração de uma área editorial de produtos e ofertas dentro do henrique.dog, sem transformar todo o site em um catálogo comercial." },
}, {
  id: "idea_offer_discovery_community", contentType: "idea", schemaVersion: 1,
  slug: "comunidade-descoberta-avaliacao-ofertas", aliases: [], title: "Comunidade para descoberta e avaliação de ofertas",
  description: "Explorar no longo prazo uma plataforma para descoberta, compartilhamento e avaliação comunitária de ofertas sem simplesmente copiar produtos existentes.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "rascunho", visibility: "public", publicationStatus: "published", type: "idea",
  categories: ["Software", "Comunidade"], tags: ["Ofertas", "Marketplace", "Confiança", "Afiliados"],
  idea: ["O Pelando é uma referência de categoria e comportamento, mas a intenção não é copiá-lo. Quero investigar como uma comunidade pode descobrir, avaliar e contextualizar promoções reais."], motivation: [], currentState: ["É um projeto de longo prazo, ainda no papel."],
  sections: [{ id: "questoes-em-aberto", title: "Questões em aberto", content: ["O produto depende de confiança e participação; começar sem comunidade grande é parte central do problema."], items: ["Como as pessoas descobrem boas ofertas?", "Como diferenciar promoção real de desconto artificial?", "Votos ajudam a ordenar ofertas?", "Como evitar spam?", "Como lojas e afiliados entram no modelo?", "Como construir confiança e começar sem uma comunidade grande?"] }],
  nextSteps: [], updates: [{ date: "2026-08-20", title: "Registro como possibilidade de longo prazo", content: ["Registrei a categoria de produto e suas dúvidas centrais sem definir regras ou modelo comercial."], links: [] }], relatedIdeaIds: ["idea_achadinhos_curadoria", "idea_henrique_dog_editorial_sustentavel", "idea_small_software_lab"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Comunidade para descoberta de ofertas", description: "Ideia de longo prazo para descobrir e avaliar ofertas em comunidade, investigando confiança, spam e o problema de começar sem audiência." },
}, {
  id: "idea_live_command_card_game", contentType: "idea", schemaVersion: 1,
  slug: "jogo-online-comandos-cartas-poderes", aliases: [], title: "Jogo online baseado em comandos ao vivo e cartas de poderes",
  description: "Criar por diversão um jogo online em que jogadores interagem por comandos textuais em tempo real e usam cartas de poderes, ações ou modificadores.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "explorando", visibility: "public", publicationStatus: "published", type: "experiment",
  categories: ["Jogos", "Software"], tags: ["Multiplayer", "Tempo real", "Game design", "Cartas"],
  idea: ["A interface não precisa depender de animações complexas. Comandos, respostas textuais, cartas, decisões e acontecimentos em tempo real formam o centro da experiência.", "Uma ação como atacar outro jogador poderia produzir respostas e modificadores textuais, mas qualquer regra descrita agora é apenas referência conceitual."],
  motivation: ["Este projeto não precisa de modelo de monetização. Quero experimentar multiplayer, sistemas de regras e comunicação em tempo real, além de criar algo simplesmente porque parece divertido."], currentState: ["O conceito está em exploração e não possui design de regras consolidado."], sections: [],
  nextSteps: ["Experimentar um ciclo mínimo de comandos e respostas.", "Testar como cartas podem modificar ações sem tornar as regras opacas."], updates: [{ date: "2026-08-20", title: "Conceito inicial", content: ["Registrei a combinação de comandos ao vivo, cartas e interação multiplayer como experimento de game design."], links: [] }], relatedIdeaIds: ["idea_small_software_lab"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Jogo online de comandos e cartas", description: "Experimento de um jogo multiplayer baseado em comandos textuais, cartas de poderes e acontecimentos em tempo real, criado também por diversão." },
}, {
  id: "idea_legal_manga_platform", contentType: "idea", schemaVersion: 1,
  slug: "plataforma-legal-leitura-distribuicao-mangas", aliases: [], title: "Explorar uma plataforma legal para leitura e distribuição de mangás",
  description: "Investigar como uma implementação já existente de leitura de mangás poderia operar com conteúdo autorizado e um modelo juridicamente sustentável.",
  createdAt: "2026-08-20", updatedAt: "2026-08-20", status: "explorando", visibility: "public", publicationStatus: "published", type: "research",
  categories: ["Pesquisa", "Entretenimento"], tags: ["Mangás", "Direitos autorais", "Distribuição", "Autores independentes"],
  idea: ["Já desenvolvi um site de leitura de mangás. A tecnologia existe, mas o principal desafio deixou de ser apenas o leitor: preciso descobrir um ecossistema legítimo de conteúdo e monetização.", "Não quero que o projeto dependa da distribuição não autorizada de obras protegidas. A autorização de um grupo de tradução, isoladamente, não substitui os direitos dos titulares da obra original."],
  motivation: ["Sites de mangás e scanlations enfrentam restrições de direitos autorais, distribuição, hospedagem, remoção, pagamento, publicidade e monetização."], currentState: ["A implementação técnica deve ser separada do catálogo. A pesquisa jurídica e os possíveis fornecedores de conteúdo precisam vir antes de uma estratégia comercial."],
  sections: [{ id: "direcoes-de-pesquisa", title: "Direções de pesquisa", tone: "hypothesis", content: ["A parte difícil talvez seja construir um ecossistema legítimo de conteúdo, não o leitor em si."], items: ["Obras autorizadas ou licenciadas", "Autores e publicações independentes", "Conteúdo oferecido legalmente pelos criadores", "Parcerias que possuam autorização apropriada", "Publicação direta e apoio juridicamente possível a criadores e tradutores", "Produtos relacionados e outras receitas que não dependam de conteúdo não autorizado"] }, { id: "questoes-em-aberto", title: "Questões em aberto", content: ["As respostas devem considerar os direitos da obra original e não apenas a capacidade técnica de hospedar arquivos."], items: ["Que conteúdo posso distribuir legalmente?", "Existe espaço para autores independentes?", "Posso criar ferramentas para traduções autorizadas?", "Existe um modelo de publicação direta?", "É possível gerar valor sem conteúdo não autorizado?"] }],
  nextSteps: ["Pesquisar modelos legais de distribuição e fontes de conteúdo autorizado.", "Separar o leitor tecnológico do catálogo.", "Investigar autores independentes e custos de armazenamento e distribuição.", "Somente depois definir uma estratégia de monetização."], updates: [{ date: "2026", title: "Implementação técnica existente", content: ["Desenvolvi uma experiência de leitura; o projeto passa agora a ser tratado como pesquisa de conteúdo autorizado e sustentabilidade jurídica."], links: [] }],
  relatedIdeaIds: ["idea_henrique_dog_editorial_sustentavel"], relatedArticleSlugs: [], relatedProjectSlugs: [], seo: { title: "Plataforma legal para leitura de mangás", description: "Pesquisa para separar a tecnologia de leitura do desafio de obter conteúdo autorizado e construir distribuição juridicamente sustentável." },
}]);
