export type SeriesListItem={seriesId:string;context:string};
export type SeriesList={id:string;slug:string;title:string;href:string;mode:"editorial";items:SeriesListItem[]};
export const seriesCurations:SeriesList[]=[{id:"series_vampire_br",slug:"melhores-series-de-vampiro",title:"Melhores séries de vampiro e onde assistir no Brasil",href:"/blog/melhores-series-de-vampiro",mode:"editorial",items:[
 ["ser_buffy","O ponto de partida histórico: fez horror, comédia e amadurecimento sustentarem uma linguagem televisiva própria."],["ser_angel","Expande a pergunta sobre redenção e transforma o vampiro em investigador noir e adulto."],["ser_interview","A reinvenção contemporânea mais rica de Anne Rice, interessada em memória, desejo, raça e poder."],["ser_true_blood","Assume sexo, política e sátira para imaginar vampiros vivendo publicamente entre humanos."],["ser_midnight_mass","Usa o vampiro com parcimônia para pensar fé, milagre, dependência e contágio comunitário."],["ser_what_shadows","A melhor comédia do recorte porque conhece profundamente as regras que ridiculariza."],["ser_castlevania","Dá escala trágica e ação extraordinária a Drácula sem tratar animação como gênero infantil."],["ser_castlevania_nocturne","Leva a guerra vampírica à Revolução Francesa e confronta aristocracia e colonialismo."],["ser_vampire_diaries","O melodrama juvenil mais influente do ciclo recente, mesmo com sua propensão ao excesso."],["ser_originals","Troca o colégio pela disputa de uma família imortal pelo poder em Nova Orleans."],["ser_dracula_2020","Uma adaptação compacta e divisiva que prefere testar o mito a reverenciá-lo."],["ser_strain","Faz do vampiro uma infestação biológica repulsiva e recupera o medo físico da criatura."],["ser_being_human_uk","Encontra drama e humor no esforço cotidiano de um vampiro para não repetir seus impulsos."],["ser_carmilla","Mostra como poucos recursos, episódios curtos e perspectiva queer podem renovar um texto gótico."],["ser_vampire_garden","Uma tragédia animada curta sobre convivência, música e fuga num mundo dividido."],["ser_sirius","Oferece uma rota japonesa mais pulp, com caçadores e vampiros na Tóquio dos anos 1930."],["ser_first_kill","Romance queer juvenil de premissa forte, recomendado com o aviso de cancelamento precoce."],["ser_immortals_tr","Desloca a guerra vampírica para Istambul e amplia a geografia predominantemente anglófona da lista."],["ser_discovery_witches","Representa o romance fantástico adulto, com vampiros ligados a ciência, linhagem e história."],
 ].map(([seriesId,context])=>({seriesId,context}))}];
seriesCurations.push({id:"series_horror_essentials",slug:"melhores-series-de-terror",title:"Melhores séries de terror para assistir",href:"/blog/melhores-series-de-terror",mode:"editorial",items:[
 ["ser_twilight_zone","A matriz da antologia moderna: usa fantasia e horror para comprimir dilemas morais em imagens duradouras."],["ser_twin_peaks","Transformou o mal doméstico, o melodrama e o surrealismo em uma linguagem televisiva ainda difícil de domesticar."],["ser_buffy","Fez o horror acompanhar personagens por anos sem perder humor, risco ou capacidade de experimentar."],["ser_hannibal","Converte crime procedural em romance macabro, horror corporal e composição visual de precisão incomum."],["ser_penny_dreadful","Reúne o gótico literário em torno de personagens feridos, especialmente a extraordinária Vanessa Ives."],["ser_channel_zero","Mostra como creepypastas podem sustentar temporadas autorais sem virar apenas referências de internet."],["ser_the_terror","A primeira temporada transforma frio, fome, hierarquia e isolamento em um horror histórico quase tátil."],["ser_hill_house","Equilibra casa assombrada, luto familiar e invenção formal numa minissérie acessível sem ser rasa."],["ser_marianne","Entrega bruxaria e imagens agressivas com uma malícia física que diferencia o terror francês recente."],["ser_kingdom","Faz zumbis, fome e disputa sucessória participarem do mesmo mecanismo político."],["ser_midnight_mass","Constrói terror religioso por conversa, comunidade e escolhas, não apenas por revelações sobrenaturais."],["ser_yellowjackets","Mantém o sobrenatural em disputa enquanto trauma, fome e versões do passado corroem o grupo."],["ser_from","Usa regras de sobrevivência claras para sustentar uma mitologia serializada deliberadamente labiríntica."],["ser_interview","Reformula o gótico de Anne Rice por memória, desejo queer e narradores que disputam a própria história."],["ser_it_derry","Uma produção contemporânea ambiciosa que torna a história social de Derry parte do ciclo de horror de Pennywise."],["ser_chucky","Prova que um slasher pode acumular continuidade, humor e personagens adolescentes sem perder violência."],["ser_30_coins","Representa o terror religioso espanhol em chave barroca, monstruosa e assumidamente excessiva."],["ser_joko_nightmares","Leva antologia e ficção científica sobrenatural a conflitos sociais da Indonésia contemporânea."],["ser_juon_origins","Reduz a ornamentação para encontrar uma crueldade doméstica severa dentro da franquia japonesa."],["ser_gannibal","Faz o isolamento rural e uma família dominante sustentarem folk horror japonês de combustão lenta."],["ser_cabinet","Funciona como porta de entrada para oito autores e várias tradições do conto macabro."],["ser_last_of_us","Usa o apocalipse fúngico para perguntar o que vínculo e proteção autorizam alguém a destruir."],["ser_desalma","Coloca ritual, imigração e paisagem do sul do Brasil no centro de um folk horror próprio."],
].map(([seriesId,context])=>({seriesId,context}))});
seriesCurations.push({id:"series_after_derry",slug:"series-para-quem-gostou-de-it-bem-vindos-a-derry",title:"Melhores séries para quem gostou de It: Bem-Vindos a Derry",href:"/blog/series-para-quem-gostou-de-it-bem-vindos-a-derry",mode:"editorial",items:[
 ["ser_castle_rock","A recomendação mais diretamente ligada a Stephen King: uma cidade que acumula histórias violentas e parece participar delas."],
 ["ser_twin_peaks","Outra comunidade em que o crime contra uma jovem rompe a fachada cordial e revela um mal simultaneamente humano e sobrenatural."],
 ["ser_stranger_things","Compartilha o grupo juvenil, o desaparecimento e a cidade contaminada, mas troca a crueldade histórica de Derry por aventura e amizade."],
 ["ser_dark","Leva desaparecimentos, famílias e repetição histórica a um extremo temporal: Winden também não consegue escapar do próprio passado."],
 ["ser_from","Transforma a cidade em armadilha literal, com regras noturnas, crianças enigmáticas e monstros que se alimentam da desorientação coletiva."],
 ["ser_marianne","Uma criadora retorna à cidade natal e encontra a bruxa, os amigos e os pactos que julgava ter deixado na adolescência."],
 ["ser_hill_house","A ameaça está concentrada numa casa, mas o movimento é semelhante: crianças sobrevivem e adultos descobrem que sobreviver não encerrou o trauma."],
 ["ser_yellowjackets","O passado adolescente continua sendo reescrito por adultas que não concordam sobre o que viveram, esconderam ou invocaram."],
 ["ser_equinox","Um desaparecimento coletivo de estudantes retorna décadas depois como ferida familiar, segredo comunitário e possível ciclo ritual."],
 ["ser_archive_81","Investiga um lugar apagado por meio de registros incompletos e encontra uma história de culto, repetição e pessoas desaparecidas."],
 ["ser_the_outsider","Parte da violência contra uma criança para observar como uma entidade explora descrença, luto e suspeita numa comunidade."],
 ["ser_channel_zero","A primeira temporada, Candle Cove, aproxima programa infantil, memória falha, desaparecimentos e o retorno de um adulto à cidade natal."],
 ["ser_chucky","Usa adolescentes e uma pequena cidade para um slasher mais irreverente, mas atento a bullying, família e adultos que não enxergam o perigo."],
 ["ser_locke_key","Oferece uma versão mais leve do amadurecimento sobrenatural: irmãos herdam uma casa, segredos e consequências esquecidas pelos adultos."],
 ["ser_midnight_mass","Substitui o grupo de crianças por uma ilha inteira e pergunta por que uma comunidade prefere chamar o perigo de milagre."],
].map(([seriesId,context])=>({seriesId,context}))});
