import { z } from "zod";

export const SeriesOfferSchema = z.object({ id:z.string().regex(/^ser_offer_[a-z0-9_]+$/), seriesId:z.string(), provider:z.string(), offerType:z.enum(["stream","free"]), url:z.string().url(), region:z.literal("BR"), seasonFrom:z.number().int().positive(), seasonTo:z.number().int().positive(), checkedAt:z.string().regex(/^\d{4}-\d{2}-\d{2}$/), note:z.string().optional() });
export type SeriesOffer = z.infer<typeof SeriesOfferSchema>;
const date="2026-08-13";
const offer=(id:string,seriesId:string,provider:string,url:string,from:number,to:number,note?:string,offerType:SeriesOffer["offerType"]="stream"):SeriesOffer=>SeriesOfferSchema.parse({id:`ser_offer_${id}`,seriesId,provider,url,seasonFrom:from,seasonTo:to,region:"BR",checkedAt:date,note,offerType});
export const seriesOffers:SeriesOffer[]=[
 offer("disney_buffy","ser_buffy","Disney+","https://www.disneyplus.com/pt-br/browse/entity-f2c277c5-62b4-417c-b277-8435b70176dd",1,7), offer("disney_angel","ser_angel","Disney+","https://www.disneyplus.com/pt-br/browse/entity-8034c900-f242-4cea-96ba-1c6f61f812af",1,5),
 offer("max_trueblood","ser_true_blood","HBO Max","https://www.justwatch.com/br/serie/sangue-fresco",1,7), offer("netflix_tvd","ser_vampire_diaries","Netflix","https://www.justwatch.com/br/serie/diarios-de-um-vampiro",1,8), offer("prime_tvd","ser_vampire_diaries","Prime Video","https://www.justwatch.com/br/serie/diarios-de-um-vampiro",1,8), offer("max_tvd","ser_vampire_diaries","HBO Max","https://www.justwatch.com/br/serie/diarios-de-um-vampiro",1,8),
 offer("prime_originals","ser_originals","Prime Video","https://www.justwatch.com/br/serie/the-originals",1,5), offer("max_originals","ser_originals","HBO Max","https://www.justwatch.com/br/serie/the-originals",1,5),
 offer("netflix_interview","ser_interview","Netflix","https://www.netflix.com/br/title/81663145",1,1,"Apenas a 1ª temporada confirmada."), offer("prime_interview","ser_interview","AMC+ via Prime Video","https://www.primevideo.com/-/pt/detail/0TS257OBLLNSZJ9UK4Q2MLXYLE",1,2,"Temporadas 1 e 2; a 3ª não foi confirmada em streaming no Brasil."),
 offer("netflix_mass","ser_midnight_mass","Netflix","https://www.netflix.com/br/title/81083626",1,1), offer("disney_shadows","ser_what_shadows","Disney+","https://www.disneyplus.com/pt-br/browse/entity-0b10c46a-12f0-4357-8a00-547057b49bac",1,6),
 offer("netflix_castlevania","ser_castlevania","Netflix","https://www.netflix.com/br/title/80095241",1,4), offer("netflix_nocturne","ser_castlevania_nocturne","Netflix","https://www.netflix.com/br/title/81436901",1,2), offer("netflix_garden","ser_vampire_garden","Netflix","https://www.netflix.com/br/title/80996247",1,1), offer("netflix_sirius","ser_sirius","Netflix","https://www.netflix.com/br/title/80997339",1,1), offer("netflix_dracula","ser_dracula_2020","Netflix","https://www.netflix.com/br/title/80997687",1,1), offer("disney_strain","ser_strain","Disney+","https://www.disneyplus.com/pt-br/browse/entity-d424ff74-760e-4070-a490-73b89d180fc4",1,4),
 offer("youtube_carmilla","ser_carmilla","YouTube (KindaTV)","https://www.youtube.com/watch?v=3uPd3g5wi1A",1,3,"Compilações oficiais gratuitas.","free"), offer("netflix_firstkill","ser_first_kill","Netflix","https://www.netflix.com/title/81213653",1,1), offer("netflix_immortals","ser_immortals_tr","Netflix","https://www.netflix.com/title/81026095",1,1), offer("prime_discovery","ser_discovery_witches","AMC+ via Prime Video","https://www.primevideo.com/-/pt/detail/0MC2YPA38DSTPZJUSP5H4IC7TE",1,3), offer("netflix_vwars","ser_vwars","Netflix","https://www.netflix.com/br/title/80236118",1,1),
 offer("paramount_penny","ser_penny_dreadful","Paramount+","https://www.justwatch.com/br/serie/penny-dreadful",1,3), offer("claro_terror","ser_the_terror","Claro video","https://www.justwatch.com/br/serie/the-terror",1,2,"A 3ª temporada não estava incluída na assinatura verificada."),
 offer("netflix_hill","ser_hill_house","Netflix","https://www.netflix.com/br/title/80189221",1,1), offer("netflix_marianne","ser_marianne","Netflix","https://www.netflix.com/br/title/80217779",1,1), offer("netflix_kingdom","ser_kingdom","Netflix","https://www.netflix.com/br/title/80180171",1,2),
 offer("paramount_yellow","ser_yellowjackets","Paramount+","https://www.justwatch.com/br/serie/yellowjackets",1,3,"A 4ª temporada estava anunciada para 2026, mas ainda não constava no catálogo verificado."), offer("globoplay_from","ser_from","Globoplay","https://www.justwatch.com/br/serie/from",1,4), offer("max_derry","ser_it_derry","HBO Max","https://www.justwatch.com/br/serie/welcome-to-derry",1,1),
 offer("disney_chucky","ser_chucky","Disney+","https://www.justwatch.com/br/serie/chucky",1,3), offer("max_30coins","ser_30_coins","HBO Max","https://www.justwatch.com/br/serie/30-monedas",1,2), offer("netflix_joko","ser_joko_nightmares","Netflix","https://www.netflix.com/br/title/81582069",1,1), offer("netflix_juon","ser_juon_origins","Netflix","https://www.netflix.com/title/81059942",1,1),
 offer("disney_gannibal","ser_gannibal","Disney+","https://www.justwatch.com/br/serie/gannibal",1,2), offer("netflix_cabinet","ser_cabinet","Netflix","https://www.netflix.com/br/title/80209229",1,1), offer("max_lastofus","ser_last_of_us","HBO Max","https://www.justwatch.com/br/serie/the-last-of-us",1,2), offer("globoplay_desalma","ser_desalma","Globoplay","https://globoplay.globo.com/desalma/t/9KrqC8HqTp/",1,2),
 offer("netflix_strangerthings","ser_stranger_things","Netflix","https://www.netflix.com/br/title/80057281",1,5), offer("netflix_dark","ser_dark","Netflix","https://www.netflix.com/br/title/80100172",1,3),
 offer("netflix_archive81","ser_archive_81","Netflix","https://www.netflix.com/br/title/80222802",1,1), offer("netflix_equinox","ser_equinox","Netflix","https://www.netflix.com/br/title/81075958",1,1), offer("netflix_lockekey","ser_locke_key","Netflix","https://www.netflix.com/br/title/80241239",1,3),
 offer("max_outsider","ser_the_outsider","HBO Max","https://www.justwatch.com/br/serie/the-outsider",1,1), offer("claro_outsider","ser_the_outsider","Claro tv+","https://www.justwatch.com/br/serie/the-outsider",1,1),
];
export const getSeriesOffers=(seriesId:string)=>seriesOffers.filter((item)=>item.seriesId===seriesId);
