import { SeriesBatchSchema, type Series } from "./seriesSchema";

const checked = "2026-08-13";
const source = (title:string, url:string) => [{ title, url }];
const make = (id:string, slug:string, titleBr:string, originalTitle:string, startYear:number, endYear:number|undefined, seasons:number, format:Series["format"], countries:string[], languages:string[], creators:string[], genres:string[], description:string, audience:string, experience:string, sources:Series["sources"], extra:Partial<Series> = {}):Series => ({
  id, contentType:"series", schemaVersion:1, slug, aliases:[], titleBr, originalTitle, startYear, endYear, seasons, format, countries, originalLanguages:languages, creators, genres, themes:[], shortDescription:description, audienceProfile:audience, experience, contentWarnings:[], sources, status:endYear ? "ended" : "returning", editorialStatus:"review", createdAt:checked, updatedAt:checked, ...extra,
});

export const seriesCatalog: Series[] = SeriesBatchSchema.parse([
  make("ser_buffy","buffy-a-caca-vampiros","Buffy: A Caça-Vampiros","Buffy the Vampire Slayer",1997,2003,7,"live-action",["Estados Unidos"],["Inglês"],["Joss Whedon"],["Terror","Drama","Comédia"],"Uma adolescente escolhida para caçar vampiros atravessa escola, amadurecimento e apocalipses sem separar monstros de problemas cotidianos.","Para quem aceita efeitos datados em troca de personagens, humor e uma série decisiva para a TV de gênero.","Ágil, afetiva e progressivamente sombria",source("Buffy: A Caça-Vampiros — Disney+ Brasil","https://www.disneyplus.com/pt-br/browse/entity-f2c277c5-62b4-417c-b277-8435b70176dd"),{contentWarnings:["Violência","Morte","Relacionamentos abusivos"]}),
  make("ser_angel","angel","Angel","Angel",1999,2004,5,"live-action",["Estados Unidos"],["Inglês"],["David Greenwalt","Joss Whedon"],["Terror","Drama","Ação"],"Um vampiro com consciência tenta construir uma prática de redenção em Los Angeles enquanto casos sobrenaturais se tornam dilemas morais.","Para quem quer um drama urbano mais adulto e serializado depois de Buffy.","Noir sobrenatural com humor amargo",source("Angel — Disney+ Brasil","https://www.disneyplus.com/pt-br/browse/entity-8034c900-f242-4cea-96ba-1c6f61f812af")),
  make("ser_true_blood","true-blood","True Blood","True Blood",2008,2014,7,"live-action",["Estados Unidos"],["Inglês"],["Alan Ball"],["Drama","Terror","Romance"],"A existência pública dos vampiros transforma uma cidade da Louisiana em campo de disputa por desejo, direitos, religião e poder.","Para adultos que gostam de melodrama, sexo, política e excesso deliberado.","Erótica, sangrenta e satírica",source("True Blood — JustWatch Brasil","https://www.justwatch.com/br/serie/sangue-fresco"),{aliases:["sangue-fresco"],contentWarnings:["Sexo explícito","Violência gráfica","Discriminação"]}),
  make("ser_vampire_diaries","diarios-do-vampiro","Diários do Vampiro","The Vampire Diaries",2009,2017,8,"live-action",["Estados Unidos"],["Inglês"],["Kevin Williamson","Julie Plec"],["Drama","Romance","Fantasia"],"Dois irmãos vampiros entram na vida de uma adolescente e ampliam um romance escolar até uma mitologia familiar de séculos.","Para quem procura romance sobrenatural viciante e aceita muitas reviravoltas.","Novelesca, romântica e veloz",source("Diários do Vampiro — JustWatch Brasil","https://www.justwatch.com/br/serie/diarios-de-um-vampiro")),
  make("ser_originals","os-originais","Os Originais","The Originals",2013,2018,5,"live-action",["Estados Unidos"],["Inglês"],["Julie Plec"],["Drama","Fantasia","Terror"],"A família dos vampiros originais retorna a Nova Orleans e converte imortalidade em guerra dinástica, paternidade e disputa territorial.","Para quem prefere intriga familiar e política sobrenatural ao triângulo adolescente.","Barroca, familiar e conflituosa",source("Os Originais — JustWatch Brasil","https://www.justwatch.com/br/serie/the-originals")),
  make("ser_interview","entrevista-com-o-vampiro-serie","Entrevista com o Vampiro","Interview with the Vampire",2022,undefined,3,"live-action",["Estados Unidos"],["Inglês"],["Rolin Jones"],["Drama","Terror gótico","Romance"],"Louis narra sua vida com Lestat e expõe como memória, desejo e abuso alteram uma história contada mais de uma vez.","Para adultos interessados em drama queer, performances intensas e reinvenção literária.","Luxuosa, trágica e emocionalmente feroz",source("Entrevista com o Vampiro — Prime Video Brasil","https://www.primevideo.com/-/pt/detail/0TS257OBLLNSZJ9UK4Q2MLXYLE"),{contentWarnings:["Relacionamento abusivo","Violência gráfica","Suicídio"]}),
  make("ser_midnight_mass","missa-da-meia-noite","Missa da Meia-Noite","Midnight Mass",2021,2021,1,"live-action",["Estados Unidos"],["Inglês"],["Mike Flanagan"],["Terror","Drama"],"Milagres numa ilha isolada aproximam fé, dependência e vampirismo sem transformar religião em resposta simples.","Para quem gosta de terror lento, diálogos longos e conflito espiritual.","Contemplativa, trágica e crescente",source("Missa da Meia-Noite — Netflix Brasil","https://www.netflix.com/br/title/81083626"),{status:"limited",contentWarnings:["Fanatismo religioso","Alcoolismo","Suicídio","Violência"]}),
  make("ser_what_shadows","o-que-fazemos-nas-sombras-serie","O Que Fazemos nas Sombras","What We Do in the Shadows",2019,2024,6,"live-action",["Estados Unidos"],["Inglês"],["Jemaine Clement"],["Comédia","Terror"],"Um documentário acompanha vampiros centenários que dividem casa e fracassam repetidamente nas tarefas mais banais da vida noturna.","Para quem quer começar com comédia e conhecer as regras do gênero pela paródia.","Absurda, calorosa e muito engraçada",source("What We Do in the Shadows — Disney+ Brasil","https://www.disneyplus.com/pt-br/browse/entity-0b10c46a-12f0-4357-8a00-547057b49bac")),
  make("ser_castlevania","castlevania","Castlevania","Castlevania",2017,2021,4,"animation",["Estados Unidos"],["Inglês"],["Warren Ellis"],["Animação","Terror","Ação"],"A vingança de Drácula contra a humanidade reúne um caçador, uma maga e o filho do próprio vampiro numa guerra de grande escala.","Para adultos que procuram animação violenta, fantasia sombria e personagens fortes.","Sangrenta, dinâmica e melancólica",source("Castlevania — Netflix Brasil","https://www.netflix.com/br/title/80095241"),{contentWarnings:["Violência gráfica","Abuso religioso"]}),
  make("ser_castlevania_nocturne","castlevania-noturno","Castlevania: Noturno","Castlevania: Nocturne",2023,2025,2,"animation",["Estados Unidos"],["Inglês"],["Clive Bradley"],["Animação","Terror","Ação"],"A Revolução Francesa vira cenário para uma nova geração de caçadores enfrentar aristocratas vampiros e colonialismo.","Para quem já gosta do universo ou quer ação animada com conflito histórico.","Operística, política e violenta",source("Castlevania: Noturno — Netflix Brasil","https://www.netflix.com/br/title/81436901"),{contentWarnings:["Violência gráfica","Escravidão"]}),
  make("ser_vampire_garden","vampire-in-the-garden","Vampire in the Garden","Vampire in the Garden",2022,2022,1,"anime",["Japão"],["Japonês"],["Ryotaro Makihara"],["Anime","Drama","Fantasia"],"Uma garota humana e uma rainha vampira fogem de sociedades em guerra procurando um lugar onde música e convivência ainda sejam possíveis.","Para quem quer uma minissérie animada curta, melancólica e centrada em afeto.","Íntima, pós-apocalíptica e triste",source("Vampire in the Garden — Netflix Brasil","https://www.netflix.com/br/title/80996247"),{status:"limited",episodes:5}),
  make("ser_sirius","sirius-the-jaeger","Sirius the Jaeger","Tenrō: Sirius the Jaeger",2018,2018,1,"anime",["Japão"],["Japonês"],["Masahiro Ando"],["Anime","Ação","Fantasia"],"Caçadores perseguem vampiros na Tóquio imperial enquanto um jovem lobisomem enfrenta o passado de sua família.","Para quem prefere ação compacta, monstros clássicos e animação japonesa.","Rápida, elegante e pulp",source("Sirius the Jaeger — Netflix Brasil","https://www.netflix.com/br/title/80997339"),{status:"limited"}),
  make("ser_dracula_2020","dracula-2020","Drácula","Dracula",2020,2020,1,"live-action",["Reino Unido"],["Inglês"],["Mark Gatiss","Steven Moffat"],["Terror","Drama","Gótico"],"Três episódios longos reconfiguram encontros clássicos com Drácula e mudam radicalmente tempo, espaço e adversários.","Para quem aceita uma adaptação irregular, espirituosa e cheia de desvios.","Gótica, autoconsciente e provocadora",source("Drácula — Netflix Brasil","https://www.netflix.com/br/title/80997687"),{status:"limited",episodes:3,contentWarnings:["Violência","Sangue"]}),
  make("ser_strain","the-strain","The Strain","The Strain",2014,2017,4,"live-action",["Estados Unidos"],["Inglês"],["Guillermo del Toro","Chuck Hogan"],["Terror","Suspense","Ficção científica"],"Uma investigação epidemiológica trata vampirismo como parasita e transforma Nova York em zona de contágio e cerco.","Para quem quer monstros repulsivos, ritmo de thriller e horror corporal.","Urgente, grotesca e apocalíptica",source("The Strain — Disney+ Brasil","https://www.disneyplus.com/pt-br/browse/entity-d424ff74-760e-4070-a490-73b89d180fc4"),{contentWarnings:["Horror corporal","Violência gráfica","Epidemia"]}),
  make("ser_being_human_uk","being-human-uk","Being Human","Being Human",2008,2013,5,"live-action",["Reino Unido"],["Inglês"],["Toby Whithouse"],["Drama","Terror","Comédia"],"Um vampiro, um lobisomem e uma fantasma dividem casa e tentam praticar humanidade apesar dos impulsos e sistemas que os cercam.","Para quem valoriza convivência, humor britânico e consequências emocionais.","Doméstica, espirituosa e dolorosa",source("Being Human — BBC","https://www.bbc.co.uk/programmes/b00hqlc4")),
  make("ser_carmilla","carmilla-webserie","Carmilla","Carmilla",2014,2016,3,"web-series",["Canadá"],["Inglês"],["Jordan Hall"],["Comédia","Romance","Mistério"],"Uma estudante investiga desaparecimentos no campus enquanto sua enigmática colega de quarto aproxima a novela de Sheridan Le Fanu da cultura de vlog.","Para quem quer romance queer, episódios curtos e produção independente assumidamente modesta.","Leve, inventiva e íntima",source("Carmilla — temporada 1 oficial, KindaTV","https://www.youtube.com/watch?v=3uPd3g5wi1A")),
  make("ser_first_kill","first-kill","First Kill","First Kill",2022,2022,1,"live-action",["Estados Unidos"],["Inglês"],["V. E. Schwab"],["Romance","Drama","Fantasia"],"Uma vampira e uma caçadora adolescentes se apaixonam enquanto as famílias exigem que cada uma cumpra o papel herdado.","Para quem quer romance queer juvenil e aceita uma história cancelada sem conclusão.","Novelesca, romântica e incompleta",source("First Kill — Netflix","https://www.netflix.com/title/81213653"),{episodes:8,contentWarnings:["Violência","Cancelada após uma temporada"]}),
  make("ser_immortals_tr","imortais-serie-turca","Imortais","Yaşamayanlar",2018,2018,1,"live-action",["Turquia"],["Turco"],["Alphan Eşeli"],["Drama","Terror","Fantasia"],"Transformada contra a vontade, Mia retorna a Istambul para matar o vampiro que roubou sua humanidade e disputar um artefato de poder.","Para quem busca uma variação turca compacta e aceita acabamento irregular.","Sombria, urbana e movida por vingança",source("Immortals — Netflix","https://www.netflix.com/title/81026095"),{episodes:8}),
  make("ser_discovery_witches","a-noite-de-todas-as-almas","A Noite de Todas as Almas","A Discovery of Witches",2018,2022,3,"live-action",["Reino Unido"],["Inglês"],["Kate Brooke"],["Drama","Romance","Fantasia"],"Uma historiadora bruxa e um vampiro geneticista formam uma aliança que atravessa bibliotecas, linhagens e conflitos entre espécies.","Para quem quer romance adulto, fantasia histórica e ritmo deliberado.","Romântica, elegante e expositiva",source("A Discovery of Witches — Prime Video Brasil","https://www.primevideo.com/-/pt/detail/0MC2YPA38DSTPZJUSP5H4IC7TE"),{aliases:["a-descoberta-das-bruxas"]}),
  make("ser_vwars","v-wars","V Wars","V Wars",2019,2019,1,"live-action",["Canadá"],["Inglês"],["William Laurin","Glenn Davis"],["Ficção científica","Terror","Suspense"],"Uma doença transforma parte da população e rompe a amizade entre um cientista e o líder emergente dos chamados Bloods.","Para quem gosta de conspiração e epidemia, sabendo que a história foi cancelada cedo.","Distópica, direta e incompleta",source("V Wars — Netflix Brasil","https://www.netflix.com/br/title/80236118"),{episodes:10,contentWarnings:["Epidemia","Violência","Cancelada após uma temporada"]}),
  make("ser_twilight_zone","alem-da-imaginacao-1959","Além da Imaginação","The Twilight Zone",1959,1964,5,"live-action",["Estados Unidos"],["Inglês"],["Rod Serling"],["Antologia","Terror","Ficção científica"],"Histórias independentes usam o fantástico, a paranoia e a ironia para deslocar medos sociais e escolhas morais para uma zona sem regras estáveis.","Para quem aceita televisão clássica e quer conhecer a gramática da antologia moderna.","Concisa, imaginativa e moralmente inquieta",source("The Twilight Zone — Britannica","https://www.britannica.com/topic/The-Twilight-Zone-American-television-program"),{aliases:["alem-da-imaginacao"]}),
  make("ser_twin_peaks","twin-peaks","Twin Peaks","Twin Peaks",1990,2017,3,"live-action",["Estados Unidos"],["Inglês"],["David Lynch","Mark Frost"],["Mistério","Terror","Drama"],"A investigação da morte de Laura Palmer revela uma cidade em que melodrama, violência doméstica, sonho e forças sobrenaturais ocupam a mesma paisagem.","Para quem aceita desvios, humor excêntrico e uma terceira temporada radicalmente experimental.","Onírica, engraçada e profundamente perturbadora",source("Twin Peaks — JustWatch Brasil","https://www.justwatch.com/br/serie/twin-peaks"),{contentWarnings:["Violência sexual","Abuso doméstico","Assassinato"]}),
  make("ser_hannibal","hannibal-serie","Hannibal","Hannibal",2013,2015,3,"live-action",["Estados Unidos"],["Inglês"],["Bryan Fuller"],["Terror psicológico","Crime","Drama"],"A relação entre o profiler Will Graham e Hannibal Lecter transforma investigação criminal em sedução, manipulação e horror corporal de composição minuciosa.","Para adultos interessados em linguagem visual extrema e relações obsessivas.","Elegante, operística e grotesca",source("Hannibal — JustWatch Brasil","https://www.justwatch.com/br/serie/hannibal"),{contentWarnings:["Canibalismo","Violência gráfica","Manipulação psicológica"]}),
  make("ser_penny_dreadful","penny-dreadful","Penny Dreadful","Penny Dreadful",2014,2016,3,"live-action",["Estados Unidos","Reino Unido"],["Inglês"],["John Logan"],["Terror gótico","Drama","Fantasia"],"Vanessa Ives cruza a Londres vitoriana de Frankenstein, Drácula, Dorian Gray e outras figuras literárias sem reduzir o encontro a catálogo de referências.","Para quem quer gótico adulto, atuações intensas e horror literário.","Suntuosa, trágica e teatral",source("Penny Dreadful — JustWatch Brasil","https://www.justwatch.com/br/serie/penny-dreadful"),{contentWarnings:["Sexo","Violência","Possessão"]}),
  make("ser_channel_zero","channel-zero","Channel Zero","Channel Zero",2016,2018,4,"live-action",["Estados Unidos","Canadá"],["Inglês"],["Nick Antosca"],["Antologia","Terror sobrenatural","Surrealismo"],"Cada temporada transforma uma creepypasta em seis episódios, usando imagens da internet como ponto de partida para traumas e mundos próprios.","Para quem procura conceitos estranhos, temporadas curtas e horror menos domesticado.","Inventiva, desconfortável e irregular",source("Channel Zero — JustWatch Brasil","https://www.justwatch.com/br/serie/channel-zero"),{contentWarnings:["Violência","Horror corporal","Crianças em perigo"]}),
  make("ser_the_terror","the-terror","The Terror","The Terror",2018,undefined,3,"live-action",["Estados Unidos"],["Inglês","Japonês"],["David Kajganich","Alexander Woo"],["Antologia","Terror histórico","Sobrevivência"],"Temporadas independentes aproximam acontecimentos históricos de presenças sobrenaturais, isolamento e instituições que ampliam o medo.","Para quem gosta de ritmo lento, ambientes hostis e horror histórico.","Gélida, paciente e opressiva",source("The Terror — JustWatch Brasil","https://www.justwatch.com/br/serie/the-terror"),{contentWarnings:["Canibalismo","Violência","Racismo","Confinamento"]}),
  make("ser_hill_house","a-maldicao-da-residencia-hill","A Maldição da Residência Hill","The Haunting of Hill House",2018,2018,1,"live-action",["Estados Unidos"],["Inglês"],["Mike Flanagan"],["Terror sobrenatural","Drama","Casa assombrada"],"Uma família revive a casa que desorganizou infância, memória e vínculos, enquanto fantasmas visíveis e ocultos ocupam passado e presente.","Para quem quer terror emocional, estrutura temporal e episódios de grande elaboração formal.","Melancólica, assustadora e familiar",source("A Maldição da Residência Hill — Netflix Brasil","https://www.netflix.com/br/title/80189221"),{status:"limited",episodes:10,contentWarnings:["Suicídio","Dependência química","Luto"]}),
  make("ser_marianne","marianne","Marianne","Marianne",2019,2019,1,"live-action",["França"],["Francês"],["Samuel Bodin"],["Terror sobrenatural","Bruxaria","Drama"],"Uma escritora retorna à cidade natal quando a bruxa de seus livros começa a invadir corpos, casas e lembranças que ela tentou abandonar.","Para quem procura uma temporada direta, imagens agressivas e terror francês.","Maliciosa, física e sombria",source("Marianne — Netflix Brasil","https://www.netflix.com/br/title/80217779"),{episodes:8,contentWarnings:["Suicídio","Violência","Morte de animais"]}),
  make("ser_kingdom","kingdom-serie-coreana","Kingdom","Kingdom",2019,2020,2,"live-action",["Coreia do Sul"],["Coreano"],["Kim Eun-hee"],["Terror","Zumbis","Drama histórico"],"Uma epidemia de mortos famintos atravessa a Coreia Joseon enquanto sucessão real, fome e corrupção impedem respostas simples à catástrofe.","Para quem quer zumbis rápidos, intriga política e ação histórica muito clara.","Urgente, política e visualmente precisa",source("Kingdom — Netflix Brasil","https://www.netflix.com/br/title/80180171"),{contentWarnings:["Violência gráfica","Epidemia","Fome"]}),
  make("ser_yellowjackets","yellowjackets","Yellowjackets","Yellowjackets",2021,undefined,4,"live-action",["Estados Unidos"],["Inglês"],["Ashley Lyle","Bart Nickerson"],["Terror psicológico","Sobrevivência","Drama"],"Sobreviventes de um acidente aéreo carregam para a vida adulta versões incompatíveis do que aconteceu na floresta e do que escolheram acreditar.","Para quem gosta de mistério prolongado, personagens falhas e ambiguidade sobrenatural.","Febril, fragmentada e canibal",source("Yellowjackets — JustWatch Brasil","https://www.justwatch.com/br/serie/yellowjackets"),{contentWarnings:["Canibalismo","Automutilação","Violência"]}),
  make("ser_from","from-a-origem-do-mal","From: A Origem do Mal","From",2022,undefined,4,"live-action",["Estados Unidos"],["Inglês"],["John Griffin"],["Terror sobrenatural","Mistério","Sobrevivência"],"Uma cidade sem saída obriga moradores a criar regras contra criaturas noturnas enquanto cada tentativa de fuga abre um novo nível do enigma.","Para quem gosta de mitologia serializada e aceita respostas graduais.","Tensa, viciante e cheia de perguntas",source("From — JustWatch Brasil","https://www.justwatch.com/br/serie/from"),{aliases:["from"]}),
  make("ser_it_derry","it-bem-vindos-a-derry","It: Bem-Vindos a Derry","It: Welcome to Derry",2025,undefined,1,"live-action",["Estados Unidos"],["Inglês"],["Andy Muschietti","Barbara Muschietti","Jason Fuchs"],["Terror sobrenatural","Horror cósmico","Drama histórico"],"Derry em 1962 revela como violência racial, silêncio comunitário e ciclos de desaparecimento preparam terreno para o retorno da entidade conhecida como Pennywise.","Para quem quer horror contemporâneo de grande escala e aceita efeitos digitais e ritmos desiguais.","Ambiciosa, histórica e visualmente macabra",source("It: Bem-Vindos a Derry — HBO Max Brasil","https://www.youtube.com/watch?v=hdCIZK2zcYw"),{episodes:8,contentWarnings:["Violência contra crianças","Racismo","Violência gráfica"]}),
  make("ser_chucky","chucky-serie","Chucky","Chucky",2021,2024,3,"live-action",["Estados Unidos"],["Inglês"],["Don Mancini"],["Slasher","Comédia de terror","Drama adolescente"],"O boneco assassino chega a uma cidade pequena e conecta novos adolescentes à continuidade acumulada da franquia sem abandonar humor e gore.","Para quem quer slasher autoconsciente, personagens queer e continuidade de longa duração.","Sangrenta, irreverente e surpreendentemente afetiva",source("Chucky — JustWatch Brasil","https://www.justwatch.com/br/serie/chucky"),{contentWarnings:["Violência gráfica","Bullying"]}),
  make("ser_30_coins","30-moedas","30 Moedas","30 monedas",2020,2023,2,"live-action",["Espanha"],["Espanhol"],["Álex de la Iglesia"],["Terror religioso","Fantasia","Mistério"],"Uma moeda de Judas leva um padre, uma veterinária e um prefeito a uma conspiração católica que cresce do horror rural ao apocalipse delirante.","Para quem gosta de monstros, conspiração e excesso espanhol sem sobriedade obrigatória.","Barroca, blasfema e descontrolada",source("30 Moedas — JustWatch Brasil","https://www.justwatch.com/br/serie/30-monedas"),{contentWarnings:["Violência gráfica","Temas religiosos","Horror corporal"]}),
  make("ser_joko_nightmares","pesadelos-e-devaneios-de-joko-anwar","Pesadelos e Devaneios de Joko Anwar","Joko Anwar's Nightmares and Daydreams",2024,2024,1,"live-action",["Indonésia"],["Indonésio"],["Joko Anwar"],["Antologia","Terror","Ficção científica"],"Sete histórias conectam exploração econômica, fenômenos sobrenaturais e ficção científica por bairros e comunidades da Indonésia contemporânea.","Para quem quer ampliar a geografia do gênero e aceita conexões mais ambiciosas que conclusivas.","Social, surreal e expansiva",source("Pesadelos e Devaneios — Netflix Brasil","https://www.netflix.com/br/title/81582069"),{episodes:7}),
  make("ser_juon_origins","ju-on-origens","Ju-On: Origens","Ju-On: Origins",2020,2020,1,"live-action",["Japão"],["Japonês"],["Hiroshi Takahashi"],["Terror sobrenatural","Drama","Maldição"],"Casos separados convergem numa casa marcada por violência, deslocando a franquia para uma crueldade humana mais seca e serializada.","Para adultos que querem horror japonês severo e não dependem dos fantasmas mais conhecidos da franquia.","Sombria, fragmentada e cruel",source("Ju-On: Origins — Netflix","https://www.netflix.com/title/81059942"),{status:"limited",episodes:6,contentWarnings:["Violência sexual","Violência doméstica","Morte infantil"]}),
  make("ser_gannibal","gannibal","Canibal","Gannibal",2022,2025,2,"live-action",["Japão"],["Japonês"],["Takamasa Oe"],["Folk horror","Mistério","Crime"],"Um policial deslocado para uma vila montanhosa suspeita que a família dominante protege uma prática de canibalismo e uma ordem social própria.","Para quem procura horror rural japonês, investigação e violência contida até explodir.","Paranoica, rural e brutal",source("Gannibal — JustWatch Brasil","https://www.justwatch.com/br/serie/gannibal"),{aliases:["canibal-serie-japonesa"],contentWarnings:["Canibalismo","Violência gráfica","Crianças em perigo"]}),
  make("ser_cabinet","gabinete-de-curiosidades-guillermo-del-toro","O Gabinete de Curiosidades de Guillermo del Toro","Guillermo del Toro's Cabinet of Curiosities",2022,2022,1,"live-action",["Estados Unidos"],["Inglês"],["Guillermo del Toro"],["Antologia","Terror sobrenatural","Horror corporal"],"Oito diretores recebem espaço para explorar criaturas, ocultismo, adaptação literária e estranheza sem buscar uma identidade visual única.","Para quem quer experimentar vertentes e cineastas diferentes em episódios independentes.","Variada, artesanal e grotesca",source("Gabinete de Curiosidades — Netflix Brasil","https://www.netflix.com/br/title/80209229"),{status:"limited",episodes:8,contentWarnings:["Violência gráfica","Horror corporal"]}),
  make("ser_last_of_us","the-last-of-us-serie","The Last of Us","The Last of Us",2023,undefined,2,"live-action",["Estados Unidos"],["Inglês"],["Craig Mazin","Neil Druckmann"],["Terror pós-apocalíptico","Drama","Ficção científica"],"Uma travessia por uma sociedade destruída por fungos infectantes coloca vínculo, violência e escolhas morais acima da simples sobrevivência.","Para quem aceita que o drama humano frequentemente ocupe mais espaço que as criaturas.","Dolorosa, íntima e brutal",source("The Last of Us — JustWatch Brasil","https://www.justwatch.com/br/serie/the-last-of-us"),{contentWarnings:["Violência gráfica","Suicídio","Luto"]}),
  make("ser_desalma","desalma","Desalma","Desalma",2020,2022,2,"live-action",["Brasil"],["Português"],["Ana Paula Maia"],["Folk horror","Drama","Terror sobrenatural"],"Numa colônia ucraniana do sul do Brasil, o retorno de uma festa tradicional reabre desaparecimentos, rituais e memórias familiares.","Para quem quer folk horror brasileiro, atmosfera fria e ritmo contemplativo.","Rural, melancólica e ritualística",source("Desalma — Globoplay","https://globoplay.globo.com/desalma/t/9KrqC8HqTp/"),{contentWarnings:["Violência","Luto","Rituais"]}),
  make("ser_stranger_things","stranger-things","Stranger Things","Stranger Things",2016,2025,5,"live-action",["Estados Unidos"],["Inglês"],["Matt Duffer","Ross Duffer"],["Terror sobrenatural","Ficção científica","Drama adolescente"],"O desaparecimento de um garoto expõe experiências secretas, uma dimensão hostil e a vulnerabilidade de Hawkins a invasões que atravessam gerações.","Para quem quer amizade juvenil, aventura e monstros em escala crescente.","Nostálgica, afetiva e espetacular",source("Stranger Things — Netflix Brasil","https://www.netflix.com/br/title/80057281"),{episodes:42,themes:["Amadurecimento","Desaparecimentos","Cidade pequena"],contentWarnings:["Violência contra crianças e adolescentes","Luto","Horror corporal"]}),
  make("ser_dark","dark","Dark","Dark",2017,2020,3,"live-action",["Alemanha"],["Alemão"],["Baran bo Odar","Jantje Friese"],["Mistério","Ficção científica","Terror psicológico"],"O desaparecimento de uma criança revela como quatro famílias de Winden estão presas a uma história que atravessa gerações e desafia a ordem do tempo.","Para quem gosta de enigmas densos, árvores familiares e narrativas que exigem atenção.","Sombria, cerebral e fatalista",source("Dark — Netflix Brasil","https://www.netflix.com/br/title/80100172"),{episodes:26,themes:["Horror cíclico","Desaparecimentos","Segredos familiares"],contentWarnings:["Suicídio","Morte de crianças","Violência"]}),
  make("ser_castle_rock","castle-rock","Castle Rock","Castle Rock",2018,2019,2,"live-action",["Estados Unidos"],["Inglês"],["Sam Shaw","Dustin Thomason"],["Terror psicológico","Mistério","Drama"],"Histórias autônomas usam a cidade fictícia de Stephen King como um organismo de memórias violentas, famílias marcadas e instituições que enterram seus crimes.","Para quem conhece King, mas aceita uma mitologia nova em vez de adaptação direta.","Labiríntica, sombria e literária",source("Castle Rock — JustWatch Brasil","https://www.justwatch.com/br/serie/castle-rock"),{episodes:20,themes:["Cidade pequena","Trauma coletivo","Segredos históricos"],contentWarnings:["Violência","Abuso infantil","Demência"]}),
  make("ser_archive_81","arquivo-81","Arquivo 81","Archive 81",2022,2022,1,"live-action",["Estados Unidos"],["Inglês"],["Rebecca Sonnenshine"],["Terror sobrenatural","Mistério","Found footage"],"A restauração de fitas gravadas num edifício desaparecido aproxima um arquivista de uma investigação antiga, um culto e camadas incompatíveis do tempo.","Para quem gosta de arquivos, mídia analógica e mistérios que avançam por fragmentos.","Hipnótica, conspiratória e incompleta",source("Arquivo 81 — Netflix Brasil","https://www.netflix.com/br/title/80222802"),{episodes:8,themes:["Segredos históricos","Desaparecimentos","Ocultismo"],contentWarnings:["Suicídio","Incêndio","Cancelada após uma temporada"]}),
  make("ser_equinox","equinox","Equinox","Equinox",2020,2020,1,"live-action",["Dinamarca"],["Dinamarquês"],["Tea Lindeburg"],["Mistério","Terror sobrenatural","Folk horror"],"Décadas depois do desaparecimento de uma turma inteira, uma radialista retorna às visões da infância e ao ritual que a comunidade preferiu não compreender.","Para quem procura um mistério nórdico curto, folclórico e deliberadamente ambíguo.","Fria, ritualística e melancólica",source("Equinox — Netflix Brasil","https://www.netflix.com/br/title/81075958"),{status:"limited",episodes:6,themes:["Desaparecimentos","Trauma coletivo","Horror cíclico"],contentWarnings:["Suicídio","Adolescentes em perigo","Luto"]}),
  make("ser_locke_key","locke-e-key","Locke & Key","Locke & Key",2020,2022,3,"live-action",["Estados Unidos","Canadá"],["Inglês"],["Carlton Cuse","Meredith Averill","Aron Eli Coleite"],["Fantasia sombria","Drama adolescente","Mistério"],"Três irmãos encontram chaves mágicas na casa ancestral da família e descobrem que os adultos apagaram da memória uma guerra sobrenatural iniciada na juventude.","Para quem prefere fantasia juvenil, mistério familiar e terror menos intenso.","Inventiva, acessível e aventuresca",source("Locke & Key — Netflix Brasil","https://www.netflix.com/br/title/80241239"),{episodes:28,themes:["Amadurecimento","Segredos familiares","Casa ancestral"],contentWarnings:["Luto","Violência contra adolescentes"]}),
  make("ser_the_outsider","the-outsider-serie","The Outsider","The Outsider",2020,2020,1,"live-action",["Estados Unidos"],["Inglês"],["Richard Price"],["Terror sobrenatural","Crime","Mistério"],"Um crime contra uma criança parece ter provas incompatíveis até que a investigação admite uma entidade capaz de explorar luto, descrença e suspeita comunitária.","Para quem gosta de investigação paciente e sobrenatural tratado com sobriedade.","Austera, dolorosa e inquietante",source("The Outsider — JustWatch Brasil","https://www.justwatch.com/br/serie/the-outsider"),{status:"limited",episodes:10,themes:["Trauma coletivo","Monstros","Violência comunitária"],contentWarnings:["Assassinato de criança","Luto","Violência"]}),
]);

export const seriesBySlug = new Map<string, Series>(seriesCatalog.flatMap((item) => [
  [item.slug, item] as [string, Series],
  ...item.aliases.map((alias): [string, Series] => [alias, item]),
]));
