import type{Metadata}from"next";import Link from"next/link";import{BreadcrumbJsonLd}from"@/components/seo/BreadcrumbJsonLd";import{animationWorks}from"@/content/animationWorks/animationWorks";import{cartoonSaloon}from"@/content/organizations/organizations";import{baseURL}from"@/resources";import styles from"./cartoon-saloon.module.scss";
const path="/estudios/cartoon-saloon",title="Cartoon Saloon: desenho, memória e filmografia",description="Perfil editorial do Cartoon Saloon: história em Kilkenny, animação 2D, folclore irlandês, coproduções, pessoas e filmografia.";export const metadata:Metadata={title,description,alternates:{canonical:`${baseURL}${path}`},openGraph:{title,description,url:`${baseURL}${path}`,type:"profile"},twitter:{card:"summary",title,description},other:{commentsEnabled:"true"}};
const labels={feature:"Longa",short:"Curta",series:"Série"},roles={"primary-production":"Produção principal","co-production":"Coprodução","animation-service":"Serviço de animação",development:"Desenvolvimento"};
export default function Page(){const works=animationWorks.filter(w=>w.relationships.some(r=>r.organizationId===cartoonSaloon.id));const jsonLd={"@context":"https://schema.org","@type":"Organization","@id":`${baseURL}${path}#organization`,name:cartoonSaloon.name,foundingDate:"1999",location:{"@type":"Place",name:"Kilkenny, Ireland"},url:`${baseURL}${path}`,sameAs:"https://www.cartoonsaloon.ie/",member:["Tomm Moore","Nora Twomey","Paul Young"].map(name=>({"@type":"Person",name}))};return <main className={styles.page}><BreadcrumbJsonLd items={[{name:"Início",url:baseURL},{name:"Estúdios",url:`${baseURL}/estudios`},{name:"Cartoon Saloon",url:`${baseURL}${path}`}]} /><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/>
<header className={styles.hero}><div className={styles.print} aria-hidden="true"><i/><i/><i/><i/></div><div><span style={{color:"#d8e5dc"}}>Estúdio de animação · Kilkenny</span><h1>Cartoon<br/>Saloon</h1><p>Desenho, movimento e memória cultural tratados como partes da mesma narrativa — sem uma única fórmula visual.</p><dl><div><dt>Fundação</dt><dd>1999</dd></div><div><dt>Fundadores</dt><dd>Tomm Moore · Nora Twomey · Paul Young</dd></div></dl></div><small>Composição abstrata original em CSS; nenhuma arte dos filmes foi reproduzida.</small></header>
<nav className={styles.index}><a href="#historia">História</a><a href="#linguagem">Linguagem</a><a href="#folclore">Lugar</a><a href="#obras">Filmografia</a><a href="#fontes">Fontes</a></nav>
<section id="historia"><header><span>Formação e continuidade</span><h2>Um estúdio situado em Kilkenny, mas construído por colaboração internacional.</h2></header><div><p>Cartoon Saloon foi estabelecido em 1999 por Paul Young, Tomm Moore e Nora Twomey. Os primeiros anos combinaram curtas, séries, trabalho de serviço e o desenvolvimento demorado de <em>The Secret of Kells</em>. O longa abriu reconhecimento internacional, sem eliminar a dependência de coproduções europeias.</p><p>A continuidade veio da alternância entre projetos autorais, adaptações literárias, televisão e colaboração. Prêmios ajudam a medir circulação; não explicam sozinhos como o estúdio permaneceu ativo por mais de duas décadas.</p></div></section>
<section className={styles.ink} id="linguagem"><header><span>Ilustração em movimento</span><h2>A imagem plana não precisa ser emocionalmente rasa.</h2></header><div><p>Contorno, campos de cor e perspectiva estilizada organizam atenção antes de simular profundidade. A animação preserva a decisão gráfica: movimento, textura e composição respondem ao mundo específico de cada filme.</p><p>Essa recorrência não cria uma estética única. Tomm Moore trabalha folclore e paisagem por geometrias próprias; Nora Twomey adapta material literário e contextos culturais distintos. <em>The Breadwinner</em> não é uma extensão decorativa da Irlanda.</p></div></section>
<section id="folclore"><header><span>Folclore, história e lugar</span><h2>Irlanda aparece como memória disputada, não como ornamento.</h2></header><div><p><em>The Secret of Kells</em>, <em>Song of the Sea</em> e <em>WolfWalkers</em> formam o conjunto documentado como trilogia do folclore irlandês. São obras independentes, não capítulos de uma franquia formal.</p><p>Manuscritos, oralidade, paisagem, colonização e relação entre humanos e natureza mudam de função em cada filme. O conjunto preserva cultura ao colocá-la em conflito e transformação, não ao reduzi-la a símbolos “celtas” genéricos.</p></div></section>
<section className={styles.beyond}><span>Além da trilogia</span><h2>Afeganistão, literatura infantil, memória e televisão.</h2><p><em>The Breadwinner</em>, <em>My Father’s Dragon</em>, <em>Late Afternoon</em> e <em>Puffin Rock</em> impedem uma leitura uniforme do estúdio. Mudam os contextos, públicos, direções e relações produtivas — inclusive o peso de distribuidoras e coprodutores.</p></section>
<section className={styles.works} id="obras"><header><span>Filmografia estruturada</span><h2>Obras e vínculos, não apenas uma coleção de títulos.</h2><p>{works.length} registros centrais, organizados por formato. Nenhuma página individual insuficiente foi publicada.</p></header>{["feature","short","series"].map(format=><div key={format}><h3>{format==="feature"?"Longas":format==="short"?"Curtas":"Séries"}</h3>{works.filter(w=>w.format===format).map((work,index)=><article key={work.id}><b>{String(index+1).padStart(2,"0")}</b><div><span>{work.year} · {labels[work.format]}</span><h4>{work.title}</h4><p>{work.summary}</p><small>{work.directors.length?`Direção: ${work.directors.join(" e ")} · `:""}{roles[work.relationships.find(r=>r.organizationId===cartoonSaloon.id)!.role]}</small></div></article>)}</div>)}</section>
<section className={styles.people}><span>Pessoas</span><h2>O estúdio não substitui seus autores.</h2><p><strong>Tomm Moore</strong>, <strong>Nora Twomey</strong> e <strong>Paul Young</strong> fundaram a organização, mas exercem funções diferentes em direção, criação e produção. Ross Stewart, Louise Bagnall e outros profissionais aparecem vinculados às obras em que há crédito confirmado. Os registros pessoais permanecem como rascunhos, sem biografias públicas artificiais.</p></section>
<section className={styles.start}><span>Por onde começar</span><h2>Escolha uma relação, não uma nota.</h2><div><p><strong>Primeiro contato:</strong> <em>Song of the Sea</em>, pelo equilíbrio entre família, paisagem e tradição oral.</p><p><strong>História e conflito:</strong> <em>The Breadwinner</em>, para conhecer Nora Twomey e outra geografia cultural.</p><p><strong>Forma mais condensada:</strong> <em>Late Afternoon</em>, um curta em que memória organiza cor e tempo.</p><p><strong>Em família:</strong> <em>Puffin Rock</em>, que revela o lado serial e pré-escolar do estúdio.</p></div></section>
<section className={styles.related}><span>Continue</span><h2>Perfis e curadorias existentes.</h2><div><Link href="/blog/studio-ghibli">Perfil do Studio Ghibli</Link><Link href="/estudios/laika">Perfil da LAIKA</Link><Link href="/filmes">Biblioteca de filmes</Link></div></section>
<footer id="fontes"><span>Fontes e imagens</span><h2>Base documental</h2><ul><li><a href="https://www.cartoonsaloon.ie/irish-animation-studio/about/">Página institucional oficial</a>.</li><li><a href="https://www.cartoonsaloon.ie/irish-animation-studio/feature-films/">Longas oficiais</a>.</li><li><a href="https://www.cartoonsaloon.ie/irish-animation-studio/short-films/">Curtas oficiais</a>.</li><li><a href="https://www.dcci.ie/events/cartoon-saloon-the-irish-folklore-trilogy/">Design & Crafts Council Ireland: trilogia</a>.</li></ul><p>Nenhuma imagem, pôster ou frame foi usado. Todos permanecem pendentes de autorização específica; placeholders abstratos preservam a página sem imitar filmes ou artistas.</p></footer></main>}
