"use client";
import {useMemo,useState} from "react";
import {CatalogControls,CatalogEmpty,CatalogLoadMore} from "@/components/entertainment/CatalogControls";
import {normalizeCatalogText,uniqueCatalogValues,useProgressiveCatalog} from "@/components/entertainment/catalog";
import type {Creator} from "@/content/creators/creatorSchema";
import {PersonCard} from "./PersonCard";
import styles from "./EntityLibrary.module.scss";

function birthYear(person:Creator){return Number(person.birthDate?.slice(0,4)??person.birthYear)||undefined}function period(person:Creator){const year=birthYear(person);return year?String(Math.floor(year/100)*100):undefined}
export function PersonLibrary({people}:{people:readonly Creator[]}){const[query,setQuery]=useState("");const[occupation,setOccupation]=useState("all");const[country,setCountry]=useState("all");const[selectedPeriod,setSelectedPeriod]=useState("all");const facets=useMemo(()=>({occupations:uniqueCatalogValues(people.flatMap((person)=>person.occupations)),countries:uniqueCatalogValues(people.map((person)=>person.countryOrRegion).filter((value):value is string=>Boolean(value))),periods:uniqueCatalogValues(people.map(period).filter((value):value is string=>Boolean(value)))}),[people]);const filtered=useMemo(()=>people.filter((person)=>normalizeCatalogText([person.name,person.fullName,person.originalName].filter(Boolean).join(" ")).includes(normalizeCatalogText(query))&&(occupation==="all"||person.occupations.includes(occupation))&&(country==="all"||person.countryOrRegion===country)&&(selectedPeriod==="all"||period(person)===selectedPeriod)).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")),[country,occupation,people,query,selectedPeriod]);const resetKey=[query,occupation,country,selectedPeriod].join("|");const progressive=useProgressiveCatalog(resetKey,filtered.length,12);const clear=()=>{setQuery("");setOccupation("all");setCountry("all");setSelectedPeriod("all")};return <><CatalogControls query={query} onQueryChange={setQuery} placeholder="Nome ou nome completo" filters={[{id:"occupation",label:"Ocupação",value:occupation,allLabel:"Todas",options:facets.occupations.map((value)=>({value,label:value})),onChange:setOccupation},{id:"country",label:"País ou região",value:country,allLabel:"Todos",options:facets.countries.map((value)=>({value,label:value})),onChange:setCountry},{id:"period",label:"Período",value:selectedPeriod,allLabel:"Todos",options:facets.periods.map((value)=>({value,label:`Século ${Number(value)/100+1}`})),onChange:setSelectedPeriod}]} sort="alphabetical" sortOptions={[{value:"alphabetical",label:"Nome A–Z"}]} onSortChange={()=>undefined} resultCount={filtered.length} singular="personalidade encontrada" plural="personalidades encontradas" hasFilters={Boolean(query||occupation!=="all"||country!=="all"||selectedPeriod!=="all")} onClear={clear}/>{filtered.length?<div className={styles.grid}>{filtered.slice(0,progressive.visibleCount).map((person)=><PersonCard key={person.id} personId={person.id}/>)}</div>:<CatalogEmpty noun="personalidade" onClear={clear}/>} {progressive.hasMore?<CatalogLoadMore onLoadMore={progressive.loadMore}/>:null}</>}
