"use client";
import {useMemo,useState} from "react";
import {CatalogControls,CatalogEmpty,CatalogLoadMore} from "@/components/entertainment/CatalogControls";
import {normalizeCatalogText,uniqueCatalogValues,useProgressiveCatalog} from "@/components/entertainment/catalog";
import type {Organization} from "@/content/organizations/organizations";
import {StudioCard} from "./StudioCard";
import styles from "./EntityLibrary.module.scss";
const kindLabels:Record<string,string>={studio:"Estúdio",collective:"Coletivo",broadcaster:"Emissora",company:"Empresa",publisher:"Editora",imprint:"Selo",magazine:"Revista",platform:"Plataforma"};function period(org:Organization){return org.founded?String(Math.floor(org.founded/10)*10):undefined}
export function StudioLibrary({studios}:{studios:readonly Organization[]}){const[query,setQuery]=useState("");const[country,setCountry]=useState("all");const[specialty,setSpecialty]=useState("all");const[kind,setKind]=useState("all");const[selectedPeriod,setSelectedPeriod]=useState("all");const facets=useMemo(()=>({countries:uniqueCatalogValues(studios.map((studio)=>studio.location?.country).filter((value):value is string=>Boolean(value))),specialties:uniqueCatalogValues(studios.flatMap((studio)=>studio.specialties)),kinds:uniqueCatalogValues(studios.map((studio)=>studio.kind)),periods:uniqueCatalogValues(studios.map(period).filter((value):value is string=>Boolean(value)))}),[studios]);const filtered=useMemo(()=>studios.filter((studio)=>normalizeCatalogText([studio.name,studio.legalName,...studio.aliases].filter(Boolean).join(" ")).includes(normalizeCatalogText(query))&&(country==="all"||studio.location?.country===country)&&(specialty==="all"||studio.specialties.includes(specialty))&&(kind==="all"||studio.kind===kind)&&(selectedPeriod==="all"||period(studio)===selectedPeriod)).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")),[country,kind,query,selectedPeriod,specialty,studios]);const resetKey=[query,country,specialty,kind,selectedPeriod].join("|");const progressive=useProgressiveCatalog(resetKey,filtered.length,12);const clear=()=>{setQuery("");setCountry("all");setSpecialty("all");setKind("all");setSelectedPeriod("all")};return <><CatalogControls query={query} onQueryChange={setQuery} placeholder="Nome do estúdio" filters={[{id:"country",label:"País",value:country,allLabel:"Todos",options:facets.countries.map((value)=>({value,label:value})),onChange:setCountry},{id:"specialty",label:"Especialidade",value:specialty,allLabel:"Todas",options:facets.specialties.map((value)=>({value,label:value})),onChange:setSpecialty},{id:"kind",label:"Tipo",value:kind,allLabel:"Todos",options:facets.kinds.map((value)=>({value,label:kindLabels[value]??value})),onChange:setKind},{id:"period",label:"Início de atividade",value:selectedPeriod,allLabel:"Todos",options:facets.periods.map((value)=>({value,label:`Anos ${value}`})),onChange:setSelectedPeriod}]} sort="alphabetical" sortOptions={[{value:"alphabetical",label:"Nome A–Z"}]} onSortChange={()=>undefined} resultCount={filtered.length} singular="estúdio encontrado" plural="estúdios encontrados" hasFilters={Boolean(query||country!=="all"||specialty!=="all"||kind!=="all"||selectedPeriod!=="all")} onClear={clear}/>{filtered.length?<div className={styles.grid}>{filtered.slice(0,progressive.visibleCount).map((studio)=><StudioCard key={studio.id} organizationId={studio.id}/>)}</div>:<CatalogEmpty noun="estúdio" onClear={clear}/>} {progressive.hasMore?<CatalogLoadMore onLoadMore={progressive.loadMore}/>:null}</>}
