import type { Metadata } from "next";
import { ConsentVideo } from "@/components/media/ConsentVideo";
import { BreadcrumbJsonLd } from "@/components/seo/BreadcrumbJsonLd";
import { ghostAnimation } from "@/content/organizations/organizations";
import { wade } from "@/content/works/works";
import { baseURL } from "@/resources";
import styles from "./wade.module.scss";

const path = "/obras/wade";
const title = "Wade: Kolkata inundada e o horror climático";
const description = "Uma leitura editorial de Wade, curta indiano de Upamanyu Bhattacharyya e Kalp Sanghvi sobre crise climática, deslocamento e sobrevivência.";
export const metadata: Metadata = { title, description, alternates:{canonical:`${baseURL}${path}`}, openGraph:{title,description,url:`${baseURL}${path}`,type:"video.movie"}, twitter:{card:"summary",title,description} };

export default function WadePage(){
  const directors=[{name:"Upamanyu Bhattacharyya",id:"person_upamanyu_bhattacharyya"},{name:"Kalp Sanghvi",id:"person_kalp_sanghvi"}];
  const jsonLd={"@context":"https://schema.org","@type":"Movie","@id":`${baseURL}${path}#work`,name:"Wade",description:wade.summary,dateCreated:"2019",duration:"PT10M38S",countryOfOrigin:{"@type":"Country",name:"India"},director:directors.map(person=>({"@type":"Person","@id":`${baseURL}${path}#${person.id}`,name:person.name})),productionCompany:{"@type":"Organization","@id":`${baseURL}${path}#${ghostAnimation.id}`,name:ghostAnimation.name},sameAs:wade.officialUrl,url:`${baseURL}${path}`};
  return <main className={styles.page}><BreadcrumbJsonLd items={[{name:"Início",url:baseURL},{name:"Obras",url:`${baseURL}/obras`},{name:"Wade",url:`${baseURL}${path}`}]} /><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
    <header className={styles.hero} data-hero-mode="abstract"><div className={styles.water} aria-hidden="true"><i/><i/><i/><i/></div><div className={styles.heroCopy}><span>Curta de animação independente · Índia</span><h1>WADE</h1><p style={{ color: "#f2eee5" }}>Kolkata submersa. Pessoas e animais disputando o pouco espaço que ainda pode sustentar uma vida.</p><dl><div><dt>Direção</dt><dd>Upamanyu Bhattacharyya<br/>Kalp Sanghvi</dd></div><div><dt>Produção</dt><dd>2019 · 10 min 38 s</dd></div><div><dt>Forma</dt><dd>Animação 2D · sem diálogos</dd></div></dl></div><small>Hero abstrato original em CSS. Nenhum frame ou material promocional foi reproduzido.</small></header>

    <section className={styles.premise}><span>Uma cidade depois da margem</span><h2>O futuro de <em>Wade</em> começa onde a água já tomou o cotidiano.</h2><p>O curta imagina refugiados climáticos atravessando uma Kolkata inundada. Marcos urbanos sobrevivem como referências instáveis; fome, abandono e deslocamento reorganizam a convivência. Quando tigres-de-bengala também expulsos de seu habitat entram nesse espaço, o encontro não opõe humanidade e natureza de maneira simples. Todos chegam vulneráveis — mas não igualmente capazes de sobreviver.</p><aside>Esta apresentação evita a progressão final. As seções seguintes discutem acontecimentos decisivos e contêm spoilers.</aside></section>

    <section className={styles.city}><header><span>Kolkata inundada</span><h2>A água transforma geografia em pressão.</h2></header><div><p>A cidade não é um cenário genérico. A equipe pesquisou Kolkata a pé e por fotografias, deslocando para a inundação lugares reconhecíveis como a Howrah Bridge, Victoria Memorial e Park Street. Familiaridade e ruína coexistem: aquilo que orientava a vida urbana agora mede a profundidade da perda.</p><p>Os Sundarbans, delta de manguezais ao sul de Kolkata e habitat do tigre-de-bengala, ligam o deslocamento humano ao animal. Elevação do mar, salinização, ciclones e inundações compõem riscos documentados para a região. O filme radicaliza esses elementos numa ficção; não prevê literalmente quando nem de que forma Kolkata ficará submersa.</p></div></section>

    <section className={styles.conflict}><div><span>Humanos e tigres</span><h2>Não há território intacto para nenhum dos lados.</h2></div><div><p>O suspense nasce antes do ataque: superfícies opacas escondem movimento, a água reduz a velocidade humana e a ausência de fala torna cada ruído um sinal. Os tigres são ameaça física, mas não vilões externos ao desastre. Também foram empurrados para a cidade.</p><p>A violência expõe desigualdades dentro do próprio grupo humano: idade, mobilidade, acesso a alimento e poder de decisão determinam quem recebe proteção. Em condições extremas, solidariedade e cálculo de sobrevivência deixam de caber em categorias morais confortáveis.</p><p>A leitura editorial aqui é que o curta recusa uma inocência coletiva. Isso não equivale a dizer que distribui responsabilidade climática igualmente entre os personagens — a precariedade mostrada é também social e urbana.</p></div></section>

    <section className={styles.form}><header><span>Linguagem visual e sonora</span><h2>O quadro se fecha enquanto o perigo cresce.</h2></header><div className={styles.formFlow}><article><b>Confinamento</b><p>Enquadramentos largos estabelecem a escala da cidade; corpos comprimidos e obstáculos passam a dominar quando o espaço seguro diminui.</p></article><article><b>Movimento</b><p>A animação 2D dá aos tigres peso, elasticidade e direção. Listras animadas quadro a quadro tornam o deslocamento especialmente trabalhoso e legível.</p></article><article><b>Superfície</b><p>A paleta abandona o cinza inicial do terror e procura calor, umidade e matéria em decomposição. Água parada costura quase todos os planos.</p></article><article><b>Escuta</b><p>Sem diálogos ou comentário, montagem, música e desenho de som conduzem informação, ameaça e pausa sem converter o filme em discurso ilustrado.</p></article></div></section>

    <section className={styles.making}><header><span>Bastidores documentados</span><h2>Uma produção independente feita por muitas mãos.</h2></header><div><p>O projeto começou a ganhar forma em 2016, foi financiado coletivamente e ficou pronto em novembro de 2019. O relato da equipe descreve uma base apertada em Kolkata, colaboradores vivendo e trabalhando próximos e uma produção que cresceu além do plano inicial.</p><p>Foram 151 planos. A equipe estudou uma tigresa no zoológico de Alipore, percorreu a cidade, desenvolveu fundos detalhados e dividiu a animação entre diferentes fluxos de trabalho. Photoshop, Krita, Blender e After Effects aparecem no processo, mas a decisão decisiva foi formal: integrar linha, pintura, água e câmera simulada para que a cidade parecesse um espaço contínuo.</p><p>A Ghost Animation é registrada aqui como produtora e coletivo. O cadastro não gera uma página pública até existir conteúdo editorial suficiente.</p></div></section>

    <section className={styles.reception}><span>Circulação e reconhecimento</span><h2>Produzido em 2019, premiado em 2020.</h2><p>O arquivo oficial do Festival de Annecy registra <em>Wade</em> como produção de 2019 e vencedor do <strong>City of Annecy Award</strong> em 2020. O reconhecimento ajuda a documentar sua circulação, mas não funciona aqui como substituto para análise.</p></section>

    <section className={styles.watch}><header><span>Assista ao curta</span><h2>A publicação indicada pela equipe.</h2><p>O player só se conecta ao YouTube depois da sua escolha. O conteúdo principal desta página continua disponível sem JavaScript.</p></header><ConsentVideo youtubeId={wade.youtubeId} title="Wade, curta de Upamanyu Bhattacharyya e Kalp Sanghvi" sourceUrl={wade.officialUrl}/></section>

    <footer className={styles.credits}><span>Ficha, fontes e direitos</span><h2>Créditos confirmados</h2><dl><div><dt>Direção e roteiro</dt><dd>Upamanyu Bhattacharyya, Kalp Sanghvi</dd></div><div><dt>Produção</dt><dd>Ghost Animation, Kalp Sanghvi</dd></div><div><dt>Animação</dt><dd>Anwaar Alam, Shaheen Sheriff, Gaurav Wakankar, Nikunj Patel, Upamanyu Bhattacharyya, Kalp Sanghvi</dd></div><div><dt>Composição</dt><dd>Kalp Sanghvi</dd></div><div><dt>Música e som</dt><dd>Troy Vasanth</dd></div></dl><ul><li><a href={wade.officialUrl}>Publicação do curta no Short of the Week</a>.</li><li><a href="https://medium.com/@wadethefilm/making-wade-946162912faf">Making Wade</a>, relato assinado pela equipe.</li><li><a href="https://www.annecyfestival.com/about/archives/2020/award-winners/film-index%3Afilm-20200770">Ficha e prêmio no Festival de Annecy</a>.</li><li><a href="https://www.ipcc.ch/report/ar6/wg2/chapter/technical-summary/">IPCC AR6, síntese técnica</a>, e <a href="https://documents.worldbank.org/en/publication/documents-reports/documentdetail/834561468041134833">Banco Mundial: vulnerabilidade climática de Kolkata</a>.</li></ul><p>Nenhuma imagem foi utilizada: pôsteres, frames e materiais de produção permanecem pendentes de autorização explícita. O vídeo fica hospedado na fonte externa.</p></footer>
  </main>;
}
