"use client";

import { useMemo, useState } from "react";
import { CatalogControls, CatalogEmpty, CatalogLoadMore } from "@/components/entertainment/CatalogControls";
import { normalizeCatalogText, uniqueCatalogValues, useProgressiveCatalog } from "@/components/entertainment/catalog";
import { creators } from "@/content/creators/creators";
import { readingEditions, readingVolumes } from "@/content/reading/reading";
import type { ReadingWork } from "@/content/reading/readingSchema";
import { BookCard } from "./BookCard";
import { MangaCard } from "./MangaCard";
import styles from "./ReadingCatalogLibrary.module.scss";

type Mode = "books" | "comics";
type SortMode = "title" | "release" | "created";
const people = new Map(creators.map((person) => [person.id, person.name]));
const traditionLabels: Record<string,string> = { manga:"Mangá",manhwa:"Manhwa",manhua:"Manhua","western-comics":"HQ","brazilian-comics":"HQ brasileira",other:"Quadrinhos" };
const demographicLabels: Record<string,string> = { children:"Infantil","middle-grade":"Leitor jovem","young-adult":"Jovem adulto",adult:"Adulto",shonen:"Shōnen",shojo:"Shōjo",seinen:"Seinen",josei:"Josei",general:"Geral" };
const statusLabels: Record<string,string> = { announced:"Anunciada",ongoing:"Em publicação",completed:"Concluída",hiatus:"Em hiato",cancelled:"Cancelada","out-of-print":"Fora de catálogo" };
const formatLabels: Record<string,string> = { book:"Livro","light-novel":"Light novel" };

function authorNames(work:ReadingWork){return work.credits.map((credit)=>people.get(credit.personId)??credit.personId);}
function workEditions(work:ReadingWork){const volumeIds=new Set(readingVolumes.filter((volume)=>volume.workId===work.id).map((volume)=>volume.id));return readingEditions.filter((edition)=>edition.status==="published"&&(edition.workId===work.id||Boolean(edition.volumeId&&volumeIds.has(edition.volumeId))));}

export function ReadingCatalogLibrary({works,mode}:{works:readonly ReadingWork[];mode:Mode}){
  const [query,setQuery]=useState("");const [genre,setGenre]=useState("all");const [author,setAuthor]=useState("all");const [country,setCountry]=useState("all");const [format,setFormat]=useState("all");const [year,setYear]=useState("all");const [availability,setAvailability]=useState("all");
  const [tradition,setTradition]=useState("all");const [demographic,setDemographic]=useState("all");const [publicationStatus,setPublicationStatus]=useState("all");const [sort,setSort]=useState<SortMode>("title");
  const facets=useMemo(()=>({genres:uniqueCatalogValues(works.flatMap((work)=>work.genres)),authors:uniqueCatalogValues(works.flatMap(authorNames)),countries:uniqueCatalogValues(works.flatMap((work)=>work.originCountries)),formats:uniqueCatalogValues(works.map((work)=>work.format)),years:uniqueCatalogValues(works.map((work)=>work.publicationStart?.slice(0,4)).filter((value):value is string=>Boolean(value))).reverse(),traditions:uniqueCatalogValues(works.map((work)=>work.comicTradition).filter((value):value is NonNullable<ReadingWork["comicTradition"]>=>Boolean(value))),demographics:uniqueCatalogValues(works.flatMap((work)=>work.demographics)),statuses:uniqueCatalogValues(works.map((work)=>work.publicationStatus))}),[works]);
  const filtered=useMemo(()=>works.filter((work)=>{const editions=workEditions(work);const available=editions.some((edition)=>edition.availabilityStatus==="available"||edition.availabilityStatus==="preorder");const searchable=normalizeCatalogText([work.titleBr,work.originalTitle,work.romanizedTitle,...authorNames(work),...work.genres,...work.themes,...work.originCountries,work.shortDescription].filter(Boolean).join(" "));const tokens=normalizeCatalogText(query).split(/\s+/).filter(Boolean);return tokens.every((token)=>searchable.includes(token))&&(genre==="all"||work.genres.includes(genre))&&(author==="all"||authorNames(work).includes(author))&&(country==="all"||work.originCountries.includes(country))&&(format==="all"||work.format===format)&&(year==="all"||work.publicationStart?.slice(0,4)===year)&&(tradition==="all"||work.comicTradition===tradition)&&(demographic==="all"||work.demographics.includes(demographic as never))&&(publicationStatus==="all"||work.publicationStatus===publicationStatus)&&(availability==="all"||(availability==="available"&&available)||(availability==="unavailable"&&!available));}).sort((a,b)=>sort==="release"?(b.publicationStart??"").localeCompare(a.publicationStart??"")||a.originalTitle.localeCompare(b.originalTitle,"pt-BR"):sort==="created"?b.createdAt.localeCompare(a.createdAt)||a.originalTitle.localeCompare(b.originalTitle,"pt-BR"):(a.titleBr??a.originalTitle).localeCompare(b.titleBr??b.originalTitle,"pt-BR")),[author,availability,country,demographic,format,genre,publicationStatus,query,sort,tradition,works,year]);
  const resetKey=[query,genre,author,country,format,year,availability,tradition,demographic,publicationStatus,sort].join("|");const progressive=useProgressiveCatalog(resetKey,filtered.length);const hasFilters=resetKey!==["","all","all","all","all","all","all","all","all","all","title"].join("|");
  const clear=()=>{setQuery("");setGenre("all");setAuthor("all");setCountry("all");setFormat("all");setYear("all");setAvailability("all");setTradition("all");setDemographic("all");setPublicationStatus("all");setSort("title");};
  const common=[{id:"genre",label:"Gênero",value:genre,allLabel:"Todos",options:facets.genres.map((value)=>({value,label:value})),onChange:setGenre},{id:"author",label:"Autoria",value:author,allLabel:"Todas",options:facets.authors.map((value)=>({value,label:value})),onChange:setAuthor}];
  const filters=mode==="books"?[...common,{id:"country",label:"País",value:country,allLabel:"Todos",options:facets.countries.map((value)=>({value,label:value})),onChange:setCountry},{id:"format",label:"Formato",value:format,allLabel:"Todos",options:facets.formats.map((value)=>({value,label:formatLabels[value]??value})),onChange:setFormat},{id:"year",label:"Ano",value:year,allLabel:"Todos",options:facets.years.map((value)=>({value,label:value})),onChange:setYear},{id:"availability",label:"Disponibilidade",value:availability,allLabel:"Todas",options:[{value:"available",label:"Com edição disponível"},{value:"unavailable",label:"Sem edição disponível"}],onChange:setAvailability}]:[...common,{id:"tradition",label:"Tradição",value:tradition,allLabel:"Todas",options:facets.traditions.map((value)=>({value,label:traditionLabels[value]??value})),onChange:setTradition},{id:"demographic",label:"Demografia",value:demographic,allLabel:"Todas",options:facets.demographics.map((value)=>({value,label:demographicLabels[value]??value})),onChange:setDemographic},{id:"publication",label:"Situação",value:publicationStatus,allLabel:"Todas",options:facets.statuses.map((value)=>({value,label:statusLabels[value]??value})),onChange:setPublicationStatus},{id:"country",label:"País",value:country,allLabel:"Todos",options:facets.countries.map((value)=>({value,label:value})),onChange:setCountry},{id:"availability",label:"Disponibilidade",value:availability,allLabel:"Todas",options:[{value:"available",label:"Com edição disponível"},{value:"unavailable",label:"Sem edição disponível"}],onChange:setAvailability}];
  const noun=mode==="books"?"livro":"quadrinho";
  return <><CatalogControls query={query} onQueryChange={setQuery} placeholder="Título, autoria, tema ou país" filters={filters} sort={sort} sortOptions={[{value:"title",label:"Título A–Z"},{value:"release",label:"Publicação mais recente"},{value:"created",label:"Cadastro mais recente"}]} onSortChange={(value)=>setSort(value as SortMode)} resultCount={filtered.length} singular={`${noun} encontrado`} plural={`${noun}s encontrados`} hasFilters={hasFilters} onClear={clear}/>{filtered.length?<div className={styles.grid}>{filtered.slice(0,progressive.visibleCount).map((work,index)=>mode==="books"?<BookCard key={work.id} workId={work.id} variant="library" priority={index<2}/>:<MangaCard key={work.id} workId={work.id} variant="library"/>)}</div>:<CatalogEmpty noun={noun} onClear={clear}/>} {progressive.hasMore?<CatalogLoadMore onLoadMore={progressive.loadMore}/>:null}</>;
}
