import type {Metadata} from "next";
import {StudioLibrary} from "@/components/entities/StudioLibrary";
import {BreadcrumbJsonLd} from "@/components/seo/BreadcrumbJsonLd";
import {getPublishedStudios} from "@/data/organizations";
import {baseURL} from "@/resources";
import styles from "../filmes/movies.module.scss";
const path="/estudios",title="Acervo de estúdios",description="Estúdios criativos organizados por país, especialidade, tipo e período de atividade.";
export const metadata:Metadata={title,description,alternates:{canonical:`${baseURL}${path}`},openGraph:{title,description,url:`${baseURL}${path}`,type:"website"}};
export default function StudiosPage(){const studios=getPublishedStudios();const jsonLd={"@context":"https://schema.org","@type":"CollectionPage",name:title,url:`${baseURL}${path}`,mainEntity:{"@type":"ItemList",numberOfItems:studios.length,itemListElement:studios.map((studio,index)=>({"@type":"ListItem",position:index+1,item:{"@type":"Organization",name:studio.name,url:`${baseURL}${studio.profilePath}`}}))}};return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><BreadcrumbJsonLd items={[{name:"Início",url:baseURL},{name:"Estúdios",url:`${baseURL}${path}`}]}/><header className={styles.hero}><div className={styles.heroMain}><span className={styles.kicker}>Biblioteca cultural · organizações</span><h1>Estúdios são estruturas, processos e escolhas coletivas.</h1><p>Perfis institucionais ligados às obras do acervo, com papéis produtivos preservados e sem confundir distribuição com autoria.</p></div><div className={styles.heroAside}><span>Perfis públicos</span><strong>{studios.length}</strong><p>estúdios com identidade, fontes e página editorial própria.</p></div></header><section className={styles.library}><div className={styles.sectionHeader}><h2>Estúdios</h2><p>Busque pelo nome ou combine país, especialidade, tipo e início de atividade.</p></div><StudioLibrary studios={studios}/></section></main>}
