import type { MDXComponents } from "mdx/types";
import {
  // básicos
  Callout,
  Quote,
  Highlight,
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  Gallery,
  Figure,
  HoverNote,
  ChartContainer,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  Legend,
  LineChart,
  Line,
  AreaChart,
  Area,
  PieChart,
  Pie,
  Cell,
} from "@/components/mdx";

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return {
    // básicos
    Callout,
    Quote,
    Highlight,
    Collapsible,
    CollapsibleTrigger,
    CollapsibleContent,
    Gallery,
    Figure,
    HoverNote,
    ChartContainer,
    ResponsiveContainer,
    BarChart,
    Bar,
    XAxis,
    YAxis,
    Tooltip,
    CartesianGrid,
    Legend,
    LineChart,
    Line,
    AreaChart,
    Area,
    PieChart,
    Pie,
    Cell,
    ...components,
  };
}
